---
modelFingerprint: "9175796D10145A40C084D75B9B3574D9"
methods:
- method:
    name: "initialize"
    signature: "initialize(org.springframework.context.ConfigurableApplicationContext)\
      \ : void"
    instructionFingerprint: "4BCCB791C88FBB7F258D7D1B261E2CB3"
  paths:
  - pathId: "path1"
    testPathName: "initializeTest"
    constructorSignature: "<init>() : void"
    filledByUser: false
    modelFingerprint: "24B658A3FBE225EE5CFE4CB07D289F07"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "applicationContext"
      modelFingerprint: "44628A3A30040CD84FB8401A8314293B"
      index: 2
      ignored: false
      valueUuid: "initialize_configurableApplicationContext1"
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "applicationContext"
      modelFingerprint: "39559553F9FC67D873F37D531ACEFD3B"
      index: 3
      ignored: false
      valueUuid: "initialize_configurableApplicationContext1"
      methodExercised:
        target: "applicationContext"
        name: "addApplicationListener"
        parameters:
        - name: "listener"
          valueUuid: "initialize_applicationListener1"
        signature: "addApplicationListener(ApplicationListener): void"
        returnValueUuid: "initialize_void1"
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 4
      ignored: false
      valueUuid: "uuid1"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "6900b201-d101-33a9-a69b-7a761e98aa93"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "LLM"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.rsocket.context.RSocketPortInfoApplicationContextInitializer"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.rsocket.context.RSocketPortInfoApplicationContextInitializer"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.rsocket.context.RSocketPortInfoApplicationContextInitializer"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "initialize_configurableApplicationContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "initialize_configurableApplicationContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "initialize_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "PRIVATE_INNER_CLASS_OR_LAMBDA"
      valueType: "org.springframework.context.ApplicationListener"
      uuid: "initialize_applicationListener1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      uuid: "uuid1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
