---
modelFingerprint: "B8B60957864465D40D6104A335B82CBD"
methods:
- method:
    name: "initialize"
    returnType: "void"
    signature: "initialize(org.springframework.context.ConfigurableApplicationContext)\
      \ : void"
    instructionFingerprint: "C9FBD46365573E84045889965FD2410C"
    parametersTypes:
    - "org.springframework.context.ConfigurableApplicationContext"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "initializeTest"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "E41CD0F1585464331DA5AB706B25A645"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.rsocket.context.RSocketPortInfoApplicationContextInitializer"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.rsocket.context.RSocketPortInfoApplicationContextInitializer"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.rsocket.context.RSocketPortInfoApplicationContextInitializer"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "applicationContext"
      modelFingerprint: "CB0A34DE1FBB843890680E449AF3C9F0"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.context.ConfigurableApplicationContext"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.context.ConfigurableApplicationContext"
        uuid: "initialize_configurableApplicationContext1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "applicationContext"
      modelFingerprint: "F13735CDC2DECFEE747B46C932ABB7F4"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.context.ConfigurableApplicationContext"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.context.ConfigurableApplicationContext"
        uuid: "initialize_configurableApplicationContext1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "applicationContext"
        name: "addApplicationListener"
        parameters:
        - name: "arg0"
          value:
            sapientType: "PRIVATE_INNER_CLASS_OR_LAMBDA"
            valueType: "org.springframework.context.ApplicationListener"
            uuid: "initialize_applicationListener1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "addApplicationListener(ApplicationListener): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "initialize_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "VOID"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "6900b201-d101-33a9-a69b-7a761e98aa93"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "LLM"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
