---
modelFingerprint: "4BF06094C994CF7AF69B50A8612F7A1D"
targetClass:
  fullClassName: "org.springframework.boot.rsocket.context.RSocketPortInfoApplicationContextInitializer"
methods:
- method:
    name: "initialize"
    sourceCodeSignature: "void initialize(ConfigurableApplicationContext applicationContext)"
    returnType: "void"
    parameters:
    - name: "applicationContext"
      type: "org.springframework.context.ConfigurableApplicationContext"
    instructionFingerprint: "4BCCB791C88FBB7F258D7D1B261E2CB3"
  paths:
  - pathId: "path1"
    testPathName: "initializeTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "EAFEAF158679C012188A31C013D4F17F"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "applicationContext"
      modelFingerprint: "DF659A8AABEBC6871FFB4901FD8A4D44"
      valueUuid: "applicationContext"
    - type: "LOCAL_VARIABLE"
      name: "applicationContext"
      modelFingerprint: "B6081B04FDDE57D69C757EB14BD30CA3"
      valueUuid: "applicationContext"
      methodExercised:
        expression: "addApplicationListener(listener:applicationListener):void"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    failureReason:
      reason: "METHOD_CALL_INSTRUCTION_CONSTRUCTION_UNFILLED_PARAMS"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.rsocket.context.RSocketPortInfoApplicationContextInitializer"
        parameters: []
      valueType: "org.springframework.boot.rsocket.context.RSocketPortInfoApplicationContextInitializer"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "applicationContext"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "applicationContext"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "ANY"
      valueType: "org.springframework.context.ApplicationListener"
      uuid: "applicationListener"
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
