---
modelFingerprint: "6249F14CC4A4BFD8E997D49B7105BE25"
methods:
- method:
    name: "errorPageFilter"
    signature: "errorPageFilter() : org.springframework.boot.web.servlet.support.ErrorPageFilter"
    sourceCodeSignature: "ErrorPageFilter errorPageFilter()"
    instructionFingerprint: "5904BFA9986BA714EB8494E5D6E15673"
  paths:
  - pathId: "path1"
    testPathName: "errorPageFilterTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "100FED9BAE2D4E656355047D82A37D1B"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "5774883E3DDAC439610D9BA6183716FF"
      index: 2
      valueUuid: "errorPageFilter_errorPageFilter1"
    uuid: "6a20f687-81b0-3ecc-a9e8-96164dc3e36d"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.support.ErrorPageFilterConfiguration"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.web.servlet.support.ErrorPageFilterConfiguration"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.support.ErrorPageFilter"
        parameters: []
        privateConstructor: false
        createdByTargetCode: true
      valueType: "org.springframework.boot.web.servlet.support.ErrorPageFilter"
      uuid: "errorPageFilter_errorPageFilter1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
- method:
    name: "errorPageFilterRegistration"
    signature: "errorPageFilterRegistration(org.springframework.boot.web.servlet.support.ErrorPageFilter)\
      \ : org.springframework.boot.web.servlet.FilterRegistrationBean<org.springframework.boot.web.servlet.support.ErrorPageFilter>"
    sourceCodeSignature: "FilterRegistrationBean<ErrorPageFilter> errorPageFilterRegistration(ErrorPageFilter\
      \ filter)"
    instructionFingerprint: "0C1EC776021D47B871C70AA230C1A9EA"
  paths:
  - pathId: "path1"
    testPathName: "errorPageFilterRegistrationTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "115BF39CB8AA8CF611DF4341B4B7C87C"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "filter"
      modelFingerprint: "900CB6ABE722D6CDBE74E58847C24155"
      index: 2
      valueUuid: "errorPageFilterRegistration_errorPageFilter1"
    - type: "LOCAL_VARIABLE"
      name: "filter"
      modelFingerprint: "D3CB62044A7757A06DCD6FFF267FE06A"
      index: 3
      valueUuid: "errorPageFilterRegistration_errorPageFilter1"
      methodExercised:
        target: "filter"
        name: "getOrder"
        parameters: []
        signature: "getOrder(): int"
        returnValueUuid: "errorPageFilterRegistration_int1"
        access: 1
    - type: "RESULT"
      name: "result"
      modelFingerprint: "29C52D489BD62819CBC87B8477EE1F6C"
      index: 4
      valueUuid: "errorPageFilterRegistration_filterRegistrationBean1"
    uuid: "56f5c141-02c8-30fd-ad49-c46b94a751c2"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.support.ErrorPageFilterConfiguration"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.web.servlet.support.ErrorPageFilterConfiguration"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.servlet.support.ErrorPageFilter"
      uuid: "errorPageFilterRegistration_errorPageFilter1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.servlet.support.ErrorPageFilter"
      uuid: "errorPageFilterRegistration_errorPageFilter1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: 0
      valueType: "int"
      uuid: "errorPageFilterRegistration_int1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.FilterRegistrationBean"
        parameters:
        - name: "filter"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.web.servlet.support.ErrorPageFilter"
            uuid: "errorPageFilterRegistration_errorPageFilter1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "servletRegistrationBeans"
          value:
            sapientType: "ARRAY"
            content: !<array>
              values: {}
            valueType: "org.springframework.boot.web.servlet.ServletRegistrationBean[]"
            uuid: "errorPageFilterRegistration_servletRegistrationBean[]1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: true
        propertiesMap:
          dispatcherTypes:
            sapientType: "ENUM"
            content: !<regular>
              value: "REQUEST"
            valueType: "jakarta.servlet.DispatcherType"
            uuid: "Enum-jakarta.servlet.DispatcherType-REQUEST"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
          order:
            sapientType: "BASIC"
            content: !<regular>
              value: 0
            valueType: "int"
            uuid: "errorPageFilterRegistration_int1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
      valueType: "org.springframework.boot.web.servlet.FilterRegistrationBean"
      genericValueType: "org.springframework.boot.web.servlet.support.ErrorPageFilter"
      uuid: "errorPageFilterRegistration_filterRegistrationBean1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
