---
modelFingerprint: "40C2F5B744F6292C597B0A3938663774"
targetClass:
  fullClassName: "org.springframework.boot.web.servlet.support.ErrorPageFilterConfiguration"
methods:
- method:
    name: "errorPageFilter"
    sourceCodeSignature: "ErrorPageFilter errorPageFilter()"
    returnType: "org.springframework.boot.web.servlet.support.ErrorPageFilter"
    instructionFingerprint: "5904BFA9986BA714EB8494E5D6E15673"
  paths:
  - pathId: "path1"
    testPathName: "errorPageFilterTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "7E8758FD6B0613C9490BCA76F309CB42"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "FE54E08897E13C2D1E59EB07FF591815"
      valueUuid: "errorPageFilter"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.support.ErrorPageFilterConfiguration"
        parameters: []
      valueType: "org.springframework.boot.web.servlet.support.ErrorPageFilterConfiguration"
      uuid: "target"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.support.ErrorPageFilter"
        parameters: []
      valueType: "org.springframework.boot.web.servlet.support.ErrorPageFilter"
      uuid: "errorPageFilter"
      fixed: true
- method:
    name: "errorPageFilterRegistration"
    sourceCodeSignature: "FilterRegistrationBean<ErrorPageFilter> errorPageFilterRegistration(ErrorPageFilter\
      \ filter)"
    returnType: "org.springframework.boot.web.servlet.FilterRegistrationBean"
    genericReturnType: "org.springframework.boot.web.servlet.support.ErrorPageFilter"
    parameters:
    - name: "filter"
      type: "org.springframework.boot.web.servlet.support.ErrorPageFilter"
    instructionFingerprint: "0C1EC776021D47B871C70AA230C1A9EA"
  paths:
  - pathId: "path1"
    testPathName: "errorPageFilterRegistrationTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "2B6A2F1FD74423806BD87ACD32C4D425"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "filter"
      modelFingerprint: "67D91B7945332F1F42D83AA5D8C4CEB3"
      valueUuid: "filter"
    - type: "LOCAL_VARIABLE"
      name: "filter"
      modelFingerprint: "9E2DDEFF705E392224853232A1BB0747"
      valueUuid: "filter"
      methodExercised:
        expression: "getOrder():int1"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "FEB90C3D22CB61ACBC1A3B73C46CFB24"
      valueUuid: "filterRegistrationBean"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.support.ErrorPageFilterConfiguration"
        parameters: []
      valueType: "org.springframework.boot.web.servlet.support.ErrorPageFilterConfiguration"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.servlet.support.ErrorPageFilter"
      uuid: "filter"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.servlet.support.ErrorPageFilter"
      uuid: "filter"
    - sapientType: "BASIC"
      content: !<regular>
        value: 0
      valueType: "int"
      uuid: "int1"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.FilterRegistrationBean"
        parameters:
        - name: "filter"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.web.servlet.support.ErrorPageFilter"
            uuid: "filter"
        - name: "servletRegistrationBeans"
          value:
            sapientType: "ARRAY"
            content: !<array>
              values: {}
            valueType: "org.springframework.boot.web.servlet.ServletRegistrationBean[]"
            uuid: "servletRegistrationBeanArray"
        propertiesMap:
          dispatcherTypes:
            sapientType: "ENUM"
            content: !<regular>
              value: "REQUEST"
            valueType: "jakarta.servlet.DispatcherType"
            uuid: "Enum-jakarta.servlet.DispatcherType-REQUEST"
            fixed: true
          order:
            sapientType: "BASIC"
            content: !<regular>
              value: 0
            valueType: "int"
            uuid: "int1"
      valueType: "org.springframework.boot.web.servlet.FilterRegistrationBean"
      genericValueType: "org.springframework.boot.web.servlet.support.ErrorPageFilter"
      uuid: "filterRegistrationBean"
      fixed: true
