---
modelFingerprint: "88D8732D00CB98C1B039E41A045FE37B"
targetClass:
  fullClassName: "org.springframework.boot.web.servlet.support.ServletContextApplicationContextInitializer"
methods:
- method:
    name: "setOrder"
    sourceCodeSignature: "void setOrder(int order)"
    returnType: "void"
    parameters:
    - name: "order"
      type: "int"
    instructionFingerprint: "F88C98C2D7593841680C2CA0FECB4028"
  paths:
  - pathId: "path1"
    testPathName: "setOrderTest"
    constructorSignature: "<init>(jakarta.servlet.ServletContext,boolean) : void"
    modelFingerprint: "27E5BAAC8F1D5D4AB5A7B8A0BBF5B480"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
- method:
    name: "getOrder"
    sourceCodeSignature: "int getOrder()"
    returnType: "int"
    instructionFingerprint: "342D4E4F854A43E567A525BCBCDEA20C"
  paths:
  - pathId: "path1"
    testPathName: "getOrderTest"
    constructorSignature: "<init>(jakarta.servlet.ServletContext,boolean) : void"
    modelFingerprint: "6B5C572BE5A43014D0DAB227F3B3ACFE"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
- method:
    name: "initialize"
    sourceCodeSignature: "void initialize(ConfigurableWebApplicationContext applicationContext)"
    returnType: "void"
    parameters:
    - name: "applicationContext"
      type: "org.springframework.web.context.ConfigurableWebApplicationContext"
    instructionFingerprint: "851337B760726B4B9B59DC7599F20F51"
  paths:
  - pathId: "path1"
    testPathName: "initializeWhenThisAddApplicationContextAttribute"
    constructorSignature: "<init>(jakarta.servlet.ServletContext,boolean) : void"
    modelFingerprint: "2F13607603944CAE00C3E3A7B01F13FE"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "EEFE595E664EEC19B521E5E4AB07E5FD"
      valueUuid: "target"
    - type: "INPUT"
      name: "applicationContext"
      modelFingerprint: "832CAF0FA6A11F1C66B1FE031FC5A6EE"
      valueUuid: "applicationContext"
    - type: "LOCAL_VARIABLE"
      name: "applicationContext"
      modelFingerprint: "51F16D902F05BCCB379F0B49ECE59157"
      valueUuid: "applicationContext"
      methodExercised:
        expression: "setServletContext(servletContext:servletContext):void"
    - type: "FIELD"
      name: "servletContext"
      modelFingerprint: "D55DF90C3A7DA0D9A279FFA856B073A5"
      valueUuid: "servletContext"
      methodExercised:
        expression: "setAttribute(arg0:string,arg1:applicationContext):void2"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.support.ServletContextApplicationContextInitializer"
        parameters:
        - name: "servletContext"
          value:
            sapientType: "MOCK"
            valueType: "jakarta.servlet.ServletContext"
            uuid: "servletContext"
        - name: "addApplicationContextAttribute"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: true
            valueType: "boolean"
            uuid: "addApplicationContextAttribute"
      valueType: "org.springframework.boot.web.servlet.support.ServletContextApplicationContextInitializer"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.web.context.ConfigurableWebApplicationContext"
      uuid: "applicationContext"
    - sapientType: "MOCK"
      valueType: "org.springframework.web.context.ConfigurableWebApplicationContext"
      uuid: "applicationContext"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "MOCK"
      valueType: "jakarta.servlet.ServletContext"
      uuid: "servletContext"
    - sapientType: "MOCK"
      valueType: "jakarta.servlet.ServletContext"
      uuid: "servletContext"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void2"
      fixed: true
    - sapientType: "BASIC"
      content: !<regular>
        value: "org.springframework.web.context.WebApplicationContext.ROOT"
      valueType: "java.lang.String"
      uuid: "string"
    - sapientType: "MOCK"
      valueType: "org.springframework.web.context.ConfigurableWebApplicationContext"
      uuid: "applicationContext"
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
    branches:
    - lineNumber: 76
      expression: "this.addApplicationContextAttribute"
      range: "(76,7)-(76,41)"
      evaluatedAs: true
