---
modelFingerprint: "F58122B44FD3B5B6C0E8F6062F412B0D"
methods:
- method:
    name: "setOrder"
    returnType: "void"
    signature: "setOrder(int) : void"
    instructionFingerprint: "F88C98C2D7593841680C2CA0FECB4028"
    parametersTypes:
    - "int"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "setOrderTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(jakarta.servlet.ServletContext,boolean) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "8D07511E9DA71CBF5E9FC19BA7BD754A"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "27a24730-befc-337f-a149-f3be3dcb76b7"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "getOrder"
    returnType: "int"
    signature: "getOrder() : int"
    instructionFingerprint: "342D4E4F854A43E567A525BCBCDEA20C"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getOrderTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(jakarta.servlet.ServletContext,boolean) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "C12FEA5D526F12DA68624D3B96734569"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "c0bb632e-c120-35d3-9fe3-7fc42c801bce"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "initialize"
    returnType: "void"
    signature: "initialize(org.springframework.web.context.ConfigurableWebApplicationContext)\
      \ : void"
    instructionFingerprint: "0189C06416029BC4AFD45CA7FD6EAD81"
    parametersTypes:
    - "org.springframework.web.context.ConfigurableWebApplicationContext"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "initializeWhenThisAddApplicationContextAttribute"
    nameDefinedByUser: false
    constructorSignature: "<init>(jakarta.servlet.ServletContext,boolean) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "57B02613E78A85A5ADF71383FAFD44FD"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "FF60DBCE82100BED6DF36A119E2DA3C1"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.web.servlet.support.ServletContextApplicationContextInitializer"
          parameters:
          - name: "servletContext"
            value:
              sapientType: "MOCK"
              suggestedContent: !<unknown_object>
                target: "jakarta.servlet.ServletContext"
                onlyPojoFunctions: false
                builderPattern: false
              valueType: "jakarta.servlet.ServletContext"
              uuid: "<init>_servletContext1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          - name: "addApplicationContextAttribute"
            value:
              sapientType: "BASIC"
              content: !<regular>
                value: true
              suggestedContent: !<regular>
                value: true
              valueType: "boolean"
              uuid: "<init>_boolean1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.web.servlet.support.ServletContextApplicationContextInitializer"
          parameters:
          - name: "servletContext"
            value:
              sapientType: "UNKNOWN"
              suggestedContent: !<unknown_object>
                target: "jakarta.servlet.ServletContext"
                onlyPojoFunctions: false
                builderPattern: false
              valueType: "jakarta.servlet.ServletContext"
              uuid: "<init>_servletContext1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          - name: "addApplicationContextAttribute"
            value:
              sapientType: "BASIC"
              suggestedContent: !<regular>
                value: true
              valueType: "boolean"
              uuid: "<init>_boolean1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.web.servlet.support.ServletContextApplicationContextInitializer"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "applicationContext"
      modelFingerprint: "D12D22DD4085EC6E562083E7D4D20E79"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.web.context.ConfigurableWebApplicationContext"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.web.context.ConfigurableWebApplicationContext"
        uuid: "initialize_configurableWebApplicationContext1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "applicationContext"
      modelFingerprint: "1A33EF01631C86A78129EA484C593A7F"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.web.context.ConfigurableWebApplicationContext"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.web.context.ConfigurableWebApplicationContext"
        uuid: "initialize_configurableWebApplicationContext1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "applicationContext"
        name: "setServletContext"
        parameters:
        - name: "arg0"
          value:
            sapientType: "MOCK"
            suggestedContent: !<unknown_object>
              target: "jakarta.servlet.ServletContext"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "jakarta.servlet.ServletContext"
            uuid: "<init>_servletContext1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "setServletContext(ServletContext): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "initialize_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "FIELD"
      name: "servletContext"
      modelFingerprint: "CE0C87F088F91E96E2F9CFC7D4095D9E"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "jakarta.servlet.ServletContext"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "jakarta.servlet.ServletContext"
        uuid: "<init>_servletContext1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "this.servletContext"
        name: "setAttribute"
        parameters:
        - name: "arg0"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "org.springframework.web.context.WebApplicationContext.ROOT"
            valueType: "java.lang.String"
            uuid: "initialize_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "arg1"
          value:
            sapientType: "MOCK"
            suggestedContent: !<unknown_object>
              target: "org.springframework.web.context.ConfigurableWebApplicationContext"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "org.springframework.web.context.ConfigurableWebApplicationContext"
            uuid: "initialize_configurableWebApplicationContext1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "setAttribute(String,ConfigurableWebApplicationContext): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "initialize_void2"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "VOID"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "4031da61-0337-3527-b36c-3a8b9e8308de"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path2"
    pathIdForUser: "path2"
    testPathName: "initializeWhenThisNotAddApplicationContextAttribute"
    nameDefinedByUser: false
    constructorSignature: "<init>(jakarta.servlet.ServletContext,boolean) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "041792CC2C8EA7D6BBB6787158DFE645"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "dd891447-06f9-33f5-9b08-66125321bbd1"
    deleted: true
    disabled: false
    ignoredBySystem: true
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
