---
modelFingerprint: "F0725305C3ECF09BA8DFB4DAFE8C99ED"
methods:
- method:
    name: "setOrder"
    signature: "setOrder(int) : void"
    instructionFingerprint: "F88C98C2D7593841680C2CA0FECB4028"
  paths:
  - pathId: "path1"
    testPathName: "setOrderTest"
    constructorSignature: "<init>(jakarta.servlet.ServletContext,boolean) : void"
    filledByUser: false
    modelFingerprint: "8D07511E9DA71CBF5E9FC19BA7BD754A"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "27a24730-befc-337f-a149-f3be3dcb76b7"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "getOrder"
    signature: "getOrder() : int"
    instructionFingerprint: "342D4E4F854A43E567A525BCBCDEA20C"
  paths:
  - pathId: "path1"
    testPathName: "getOrderTest"
    constructorSignature: "<init>(jakarta.servlet.ServletContext,boolean) : void"
    filledByUser: false
    modelFingerprint: "C12FEA5D526F12DA68624D3B96734569"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "c0bb632e-c120-35d3-9fe3-7fc42c801bce"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "initialize"
    signature: "initialize(org.springframework.web.context.ConfigurableWebApplicationContext)\
      \ : void"
    instructionFingerprint: "851337B760726B4B9B59DC7599F20F51"
  paths:
  - pathId: "path1"
    testPathName: "initializeWhenThisAddApplicationContextAttribute"
    constructorSignature: "<init>(jakarta.servlet.ServletContext,boolean) : void"
    filledByUser: false
    modelFingerprint: "EFE06C5E0B387FE6271C003A954F6FCE"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "FF60DBCE82100BED6DF36A119E2DA3C1"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "applicationContext"
      modelFingerprint: "D12D22DD4085EC6E562083E7D4D20E79"
      index: 2
      ignored: false
      valueUuid: "initialize_configurableWebApplicationContext1"
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "applicationContext"
      modelFingerprint: "D9CAC03F4B97BAE8C2FE07BBB8BF47EB"
      index: 3
      ignored: false
      valueUuid: "initialize_configurableWebApplicationContext1"
      methodExercised:
        target: "applicationContext"
        name: "setServletContext"
        parameters:
        - name: "servletContext"
          valueUuid: "<init>_servletContext1"
        signature: "setServletContext(ServletContext): void"
        returnValueUuid: "initialize_void1"
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "FIELD"
      name: "servletContext"
      modelFingerprint: "CE0C87F088F91E96E2F9CFC7D4095D9E"
      index: 4
      ignored: false
      valueUuid: "<init>_servletContext1"
      methodExercised:
        target: "this.servletContext"
        name: "setAttribute"
        parameters:
        - name: "arg0"
          valueUuid: "initialize_string1"
        - name: "arg1"
          valueUuid: "initialize_configurableWebApplicationContext1"
        signature: "setAttribute(String,ConfigurableWebApplicationContext): void"
        returnValueUuid: "initialize_void2"
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 5
      ignored: false
      valueUuid: "uuid2"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "4031da61-0337-3527-b36c-3a8b9e8308de"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.support.ServletContextApplicationContextInitializer"
        parameters:
        - name: "servletContext"
          value:
            sapientType: "MOCK"
            valueType: "jakarta.servlet.ServletContext"
            uuid: "<init>_servletContext1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "addApplicationContextAttribute"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: true
            suggestedContent: !<regular>
              value: true
            valueType: "boolean"
            uuid: "<init>_boolean1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.web.servlet.support.ServletContextApplicationContextInitializer"
        parameters:
        - name: "servletContext"
          value:
            sapientType: "UNKNOWN"
            suggestedContent: !<unknown_object>
              target: "jakarta.servlet.ServletContext"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "jakarta.servlet.ServletContext"
            uuid: "<init>_servletContext1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "addApplicationContextAttribute"
          value:
            sapientType: "BASIC"
            suggestedContent: !<regular>
              value: true
            valueType: "boolean"
            uuid: "<init>_boolean1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.web.servlet.support.ServletContextApplicationContextInitializer"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.web.context.ConfigurableWebApplicationContext"
      uuid: "initialize_configurableWebApplicationContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.web.context.ConfigurableWebApplicationContext"
      uuid: "initialize_configurableWebApplicationContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "initialize_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "jakarta.servlet.ServletContext"
      uuid: "<init>_servletContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "jakarta.servlet.ServletContext"
      uuid: "<init>_servletContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "initialize_void2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "org.springframework.web.context.WebApplicationContext.ROOT"
      valueType: "java.lang.String"
      uuid: "initialize_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.web.context.ConfigurableWebApplicationContext"
      uuid: "initialize_configurableWebApplicationContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      uuid: "uuid2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "initializeWhenThisNotAddApplicationContextAttribute"
    constructorSignature: "<init>(jakarta.servlet.ServletContext,boolean) : void"
    filledByUser: false
    modelFingerprint: "B03D1853D06DCA538A881C9BA60E0567"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "dd891447-06f9-33f5-9b08-66125321bbd1"
    deleted: true
    disabled: false
    ignoredBySystem: true
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
