---
modelFingerprint: "B99158B1AF8F31EF22EF84E24282DADE"
methods:
- method:
    name: "analyze"
    signature: "analyze(java.lang.Throwable,org.springframework.boot.context.properties.source.InvalidConfigurationPropertyNameException)\
      \ : org.springframework.boot.diagnostics.FailureAnalysis"
    sourceCodeSignature: "FailureAnalysis analyze(Throwable rootFailure, InvalidConfigurationPropertyNameException\
      \ cause)"
    instructionFingerprint: "13D804682C8CCFE88F7062F66A615625"
  paths:
  - pathId: "path3"
    testPathName: "analyze2WhenExceptionIsNull"
    constructorSignature: "<init>() : void"
    modelFingerprint: "A9D2A9D3AD1358133D2EE9C12B359420"
    problemWasSolvedByProver: false
    truncated: true
    inputParameters: []
    uuid: "2ae77513-a856-39e1-80b9-845213371223"
    deleted: true
    disabled: false
    ignoredBySystem: true
    failureReason:
      reason: "CLASS_TYPE_COULD_NOT_BE_MOCKED_AND_NEEDS_TO_STRING"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
  - pathId: "path1"
    testPathName: "analyze2WhenExceptionIsNotNull"
    constructorSignature: "<init>() : void"
    modelFingerprint: "747DEE9C621E76E221A792B1AE628F14"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "rootFailure"
      modelFingerprint: "0E0876255B44377EA3AAA876ACEFB2FD"
      index: 2
      valueUuid: "analyze_throwable1"
    - type: "INPUT"
      name: "cause"
      modelFingerprint: "C053EDED2BEAC063F27A9A99B875F4A2"
      index: 3
      valueUuid: "analyze_invalidConfigurationPropertyNameException1"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "091B27DD3BB01EAAD5D157AE70DDC517"
      index: 4
      valueUuid: "analyze_failureAnalysis1"
    uuid: "823198b3-778e-3602-9dc4-71ad6b9428ea"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.diagnostics.analyzer.InvalidConfigurationPropertyNameFailureAnalyzer"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.diagnostics.analyzer.InvalidConfigurationPropertyNameFailureAnalyzer"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.beans.factory.BeanCreationException"
        parameters:
        - name: "beanName"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "A"
            valueType: "java.lang.String"
            uuid: "buildDescription_string3"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "msg"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "msg1"
            valueType: "java.lang.String"
            uuid: "analyze_throwable1-msg"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.beans.factory.BeanCreationException"
      uuid: "analyze_throwable1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: true
      explicitCastForOverloadedMethods: "java.lang.Throwable"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.InvalidConfigurationPropertyNameException"
        parameters:
        - name: "name"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "analyze_charSequence1"
            valueType: "java.lang.String"
            uuid: "analyze_charSequence1"
            fixed: false
            nameForMock: "analyze_charSequence1"
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "invalidCharacters"
          value:
            sapientType: "COLLECTION"
            content: !<collection>
              collectionClass: "java.util.ArrayList"
              parameters: []
              values:
              - sapientType: "BASIC"
                content: !<regular>
                  value: "D"
                valueType: "java.lang.Character"
                uuid: "buildDescription_character1"
                fixed: false
                collectionUuid: "buildDescription_list1"
                equalsMethodPresent: false
                explicitCastNeeded: false
            valueType: "java.util.List"
            genericValueType: "java.lang.Character"
            uuid: "buildDescription_list1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.source.InvalidConfigurationPropertyNameException"
      uuid: "analyze_invalidConfigurationPropertyNameException1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.diagnostics.FailureAnalysis"
        parameters:
        - name: "description"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Configuration property name 'analyze_charSequence1' is not valid:\\\
                n\\n    Invalid characters: 'D'\\n    Bean: A\\n    Reason: Canonical\
                \ names should be kebab-case ('-' separated), lowercase alpha-numeric\
                \ characters and must start with a letter"
            valueType: "java.lang.String"
            uuid: "buildDescription_string6"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "action"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Modify 'analyze_charSequence1' so that it conforms to the canonical\
                \ names requirements."
            valueType: "java.lang.String"
            uuid: "analyze_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "cause"
          value:
            sapientType: "OBJECT"
            content: !<new>
              target: "org.springframework.boot.context.properties.source.InvalidConfigurationPropertyNameException"
              parameters:
              - name: "name"
                value:
                  sapientType: "BASIC"
                  content: !<regular>
                    value: "analyze_charSequence1"
                  valueType: "java.lang.String"
                  uuid: "analyze_charSequence1"
                  fixed: false
                  nameForMock: "analyze_charSequence1"
                  equalsMethodPresent: false
                  explicitCastNeeded: false
              - name: "invalidCharacters"
                value:
                  sapientType: "COLLECTION"
                  content: !<collection>
                    collectionClass: "java.util.ArrayList"
                    parameters: []
                    values:
                    - sapientType: "BASIC"
                      content: !<regular>
                        value: "D"
                      valueType: "java.lang.Character"
                      uuid: "buildDescription_character1"
                      fixed: false
                      collectionUuid: "buildDescription_list1"
                      equalsMethodPresent: false
                      explicitCastNeeded: false
                  valueType: "java.util.List"
                  genericValueType: "java.lang.Character"
                  uuid: "buildDescription_list1"
                  fixed: false
                  equalsMethodPresent: false
                  explicitCastNeeded: false
              privateConstructor: false
              createdByTargetCode: false
            valueType: "org.springframework.boot.context.properties.source.InvalidConfigurationPropertyNameException"
            uuid: "analyze_invalidConfigurationPropertyNameException1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: true
      valueType: "org.springframework.boot.diagnostics.FailureAnalysis"
      uuid: "analyze_failureAnalysis1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "analyze2WhenTypeNotIsInstanceFailureAndExceptionIsNull"
    constructorSignature: "<init>() : void"
    modelFingerprint: "612780E9F389FDD8AB5EF7A2354CFF5A"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "rootFailure"
      modelFingerprint: "DA839D4559B0DC7B2B0CF20E53AC8DBA"
      index: 2
      valueUuid: "analyze_throwable1"
    - type: "INPUT"
      name: "cause"
      modelFingerprint: "037AB0E199460A412A7AD4EA546E13E7"
      index: 3
      valueUuid: "analyze_invalidConfigurationPropertyNameException1"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "6F529F21F6E9C5D28FA8B1AF47E2880C"
      index: 4
      valueUuid: "analyze_failureAnalysis1"
    uuid: "203e0dbb-c2ab-38d5-aad7-9d320b830a8f"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.diagnostics.analyzer.InvalidConfigurationPropertyNameFailureAnalyzer"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.diagnostics.analyzer.InvalidConfigurationPropertyNameFailureAnalyzer"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "java.lang.Throwable"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "java.lang.Throwable"
      uuid: "analyze_throwable1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.InvalidConfigurationPropertyNameException"
        parameters:
        - name: "name"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "analyze_charSequence1"
            valueType: "java.lang.String"
            uuid: "analyze_charSequence1"
            fixed: false
            nameForMock: "analyze_charSequence1"
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "invalidCharacters"
          value:
            sapientType: "COLLECTION"
            content: !<collection>
              collectionClass: "java.util.ArrayList"
              parameters: []
              values:
              - sapientType: "BASIC"
                content: !<regular>
                  value: "A"
                valueType: "java.lang.Character"
                uuid: "buildDescription_character1"
                fixed: false
                collectionUuid: "buildDescription_list1"
                equalsMethodPresent: false
                explicitCastNeeded: false
            valueType: "java.util.List"
            genericValueType: "java.lang.Character"
            uuid: "buildDescription_list1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.source.InvalidConfigurationPropertyNameException"
      uuid: "analyze_invalidConfigurationPropertyNameException1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.diagnostics.FailureAnalysis"
        parameters:
        - name: "description"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Configuration property name 'analyze_charSequence1' is not valid:\\\
                n\\n    Invalid characters: 'A'\\n    Reason: Canonical names should\
                \ be kebab-case ('-' separated), lowercase alpha-numeric characters\
                \ and must start with a letter"
            valueType: "java.lang.String"
            uuid: "buildDescription_string4"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "action"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Modify 'analyze_charSequence1' so that it conforms to the canonical\
                \ names requirements."
            valueType: "java.lang.String"
            uuid: "analyze_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "cause"
          value:
            sapientType: "OBJECT"
            content: !<new>
              target: "org.springframework.boot.context.properties.source.InvalidConfigurationPropertyNameException"
              parameters:
              - name: "name"
                value:
                  sapientType: "BASIC"
                  content: !<regular>
                    value: "analyze_charSequence1"
                  valueType: "java.lang.String"
                  uuid: "analyze_charSequence1"
                  fixed: false
                  nameForMock: "analyze_charSequence1"
                  equalsMethodPresent: false
                  explicitCastNeeded: false
              - name: "invalidCharacters"
                value:
                  sapientType: "COLLECTION"
                  content: !<collection>
                    collectionClass: "java.util.ArrayList"
                    parameters: []
                    values:
                    - sapientType: "BASIC"
                      content: !<regular>
                        value: "A"
                      valueType: "java.lang.Character"
                      uuid: "buildDescription_character1"
                      fixed: false
                      collectionUuid: "buildDescription_list1"
                      equalsMethodPresent: false
                      explicitCastNeeded: false
                  valueType: "java.util.List"
                  genericValueType: "java.lang.Character"
                  uuid: "buildDescription_list1"
                  fixed: false
                  equalsMethodPresent: false
                  explicitCastNeeded: false
              privateConstructor: false
              createdByTargetCode: false
            valueType: "org.springframework.boot.context.properties.source.InvalidConfigurationPropertyNameException"
            uuid: "analyze_invalidConfigurationPropertyNameException1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: true
      valueType: "org.springframework.boot.diagnostics.FailureAnalysis"
      uuid: "analyze_failureAnalysis1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
