---
modelFingerprint: "56DFAC581B1A5B7B09A2F186F6D48AA3"
methods:
- method:
    name: "analyze"
    signature: "analyze(java.lang.Throwable,org.springframework.boot.context.properties.source.InvalidConfigurationPropertyValueException)\
      \ : org.springframework.boot.diagnostics.FailureAnalysis"
    sourceCodeSignature: "FailureAnalysis analyze(Throwable rootFailure, InvalidConfigurationPropertyValueException\
      \ cause)"
    instructionFingerprint: "0F0C25C0D4869EA5EBC07CAC132793FA"
  paths:
  - pathId: "path1"
    testPathName: "analyze2WhenDescriptorsIsEmpty"
    constructorSignature: "<init>(org.springframework.core.env.Environment) : void"
    modelFingerprint: "1BB428077110A102251B5757E6633D2A"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "5CA313E3F20F1AD46AD30C1967927587"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "rootFailure"
      modelFingerprint: "74AFC98C2E3A647A785F57191E4F7E6A"
      index: 2
      valueUuid: "analyze_throwable1"
    - type: "INPUT"
      name: "cause"
      modelFingerprint: "80833696C0E84D2261B348D445317A8D"
      index: 3
      valueUuid: "analyze_invalidConfigurationPropertyValueException1"
    - type: "LOCAL_VARIABLE"
      name: "cause"
      modelFingerprint: "73F392329EF572D0B8FBC95900C703A7"
      index: 4
      valueUuid: "analyze_invalidConfigurationPropertyValueException1"
      methodExercised:
        target: "cause"
        name: "getName"
        parameters: []
        signature: "getName(): String"
        returnValueUuid: "analyze_string1"
        access: 1
    - type: "RESULT"
      name: "result"
      modelFingerprint: "ED764FD4D57CC4D021211739049E5920"
      index: 5
      valueUuid: "analyze_failureAnalysis1"
    uuid: "2038f990-6689-3648-a6db-1df0ea26b860"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.diagnostics.analyzer.InvalidConfigurationPropertyValueFailureAnalyzer"
        parameters:
        - name: "environment"
          value:
            sapientType: "NULL"
            valueType: "org.springframework.core.env.ConfigurableEnvironment"
            uuid: "<init>_environment1"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: true
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.diagnostics.analyzer.InvalidConfigurationPropertyValueFailureAnalyzer"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "java.lang.Throwable"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "java.lang.Throwable"
      uuid: "analyze_throwable1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.InvalidConfigurationPropertyValueException"
        parameters:
        - name: "name"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "name1"
            valueType: "java.lang.String"
            uuid: "analyze_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "value"
          value:
            sapientType: "OBJECT"
            content: !<new>
              target: "java.lang.Object"
              parameters: []
              privateConstructor: false
              createdByTargetCode: false
            valueType: "java.lang.Object"
            uuid: "analyze_invalidConfigurationPropertyValueException1-value"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "reason"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "reason1"
            valueType: "java.lang.String"
            uuid: "analyze_invalidConfigurationPropertyValueException1-reason"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.source.InvalidConfigurationPropertyValueException"
      uuid: "analyze_invalidConfigurationPropertyValueException1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.InvalidConfigurationPropertyValueException"
        parameters:
        - name: "name"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "name1"
            valueType: "java.lang.String"
            uuid: "analyze_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "value"
          value:
            sapientType: "OBJECT"
            content: !<new>
              target: "java.lang.Object"
              parameters: []
              privateConstructor: false
              createdByTargetCode: false
            valueType: "java.lang.Object"
            uuid: "analyze_invalidConfigurationPropertyValueException1-value"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "reason"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "reason1"
            valueType: "java.lang.String"
            uuid: "analyze_invalidConfigurationPropertyValueException1-reason"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.source.InvalidConfigurationPropertyValueException"
      uuid: "analyze_invalidConfigurationPropertyValueException1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "name1"
      valueType: "java.lang.String"
      uuid: "analyze_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "NULL"
      valueType: "org.springframework.boot.diagnostics.FailureAnalysis"
      uuid: "analyze_failureAnalysis1"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "analyze2WhenThisEnvironmentIsNotNullAndDescriptorsIsEmpty"
    constructorSignature: "<init>(org.springframework.core.env.Environment) : void"
    modelFingerprint: "593D57EEEF9E212B648D2AE6A9E1F800"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4296CFF735F01FD9D120CF0417F19894"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "rootFailure"
      modelFingerprint: "DA839D4559B0DC7B2B0CF20E53AC8DBA"
      index: 2
      valueUuid: "analyze_throwable1"
    - type: "INPUT"
      name: "cause"
      modelFingerprint: "01829FAA5988A24F15080ADC65A00FD2"
      index: 3
      valueUuid: "analyze_invalidConfigurationPropertyValueException1"
    - type: "FIELD"
      name: "environment"
      modelFingerprint: "0EBC05823698F9EA4B241C515D4EE9A8"
      index: 4
      valueUuid: "<init>_environment1"
      methodExercised:
        target: "this.environment"
        name: "getPropertySources"
        parameters: []
        signature: "getPropertySources(): MutablePropertySources"
        returnValueUuid: "getPropertySources_mutablePropertySources1"
        access: 1025
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "7871CCCD3FBE0D77ADDF86ABEBADC2C9"
      index: 5
      valueUuid: "getPropertySources_mutablePropertySources1"
      methodExercised:
        target: "org.springframework.core.env.MutablePropertySources"
        name: "stream"
        parameters: []
        signature: "stream(): Stream"
        returnValueUuid: "getPropertySources_stream1"
        access: 1
    - type: "RESULT"
      name: "result"
      modelFingerprint: "ED764FD4D57CC4D021211739049E5920"
      index: 6
      valueUuid: "analyze_failureAnalysis1"
    uuid: "13bcba2b-7d92-3efe-820b-8d6faa31878d"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "VARIABLE_THAT_COULD_NOT_BE_ISOLATED_MOCKED"
      source: ".filter((source) -> !ConfigurationPropertySources.isAttachedConfigurationPropertySource(source));"
      lineNumber: 75
      details: "A variable could not be isolated or mocked when calling a method -\
        \ Variable name: object of type Stream - Method: filter"
    prover: "LLM"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.diagnostics.analyzer.InvalidConfigurationPropertyValueFailureAnalyzer"
        parameters:
        - name: "environment"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.core.env.ConfigurableEnvironment"
            uuid: "<init>_environment1"
            fixed: false
            nameForMock: "null"
            equalsMethodPresent: false
            explicitCastNeeded: true
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.diagnostics.analyzer.InvalidConfigurationPropertyValueFailureAnalyzer"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "java.lang.Throwable"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "java.lang.Throwable"
      uuid: "analyze_throwable1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.InvalidConfigurationPropertyValueException"
        parameters:
        - name: "name"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "name1"
            valueType: "java.lang.String"
            uuid: "analyze_invalidConfigurationPropertyValueException1-name"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "value"
          value:
            sapientType: "OBJECT"
            content: !<new>
              target: "java.lang.Object"
              parameters: []
              privateConstructor: false
              createdByTargetCode: false
            valueType: "java.lang.Object"
            uuid: "analyze_invalidConfigurationPropertyValueException1-value"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "reason"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "reason1"
            valueType: "java.lang.String"
            uuid: "analyze_invalidConfigurationPropertyValueException1-reason"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.source.InvalidConfigurationPropertyValueException"
      uuid: "analyze_invalidConfigurationPropertyValueException1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "<init>_environment1"
      fixed: false
      nameForMock: "null"
      equalsMethodPresent: false
      explicitCastNeeded: true
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.MutablePropertySources"
      uuid: "getPropertySources_mutablePropertySources1"
      fixed: false
      nameForMock: "MutablePropertySources"
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.MutablePropertySources"
      uuid: "getPropertySources_mutablePropertySources1"
      fixed: false
      nameForMock: "MutablePropertySources"
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.util.stream.Stream"
        method: "empty"
        methodParameters: []
      valueType: "java.util.stream.Stream"
      uuid: "getPropertySources_stream1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "NULL"
      valueType: "org.springframework.boot.diagnostics.FailureAnalysis"
      uuid: "analyze_failureAnalysis1"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
