---
modelFingerprint: "CC005E4D8527F3F6B0CD56DE002A23AA"
methods:
- method:
    name: "analyze"
    signature: "analyze(java.lang.Throwable,org.springframework.boot.context.properties.bind.UnboundConfigurationPropertiesException)\
      \ : org.springframework.boot.diagnostics.FailureAnalysis"
    sourceCodeSignature: "FailureAnalysis analyze(Throwable rootFailure, UnboundConfigurationPropertiesException\
      \ cause)"
    instructionFingerprint: "5A4B3255D5F6656C675C87E8E17516E2"
  paths:
  - pathId: "path5"
    testPathName: "analyze2WhenFailureIsNullThrowsNullPointerException"
    constructorSignature: "<init>() : void"
    modelFingerprint: "0F2AFCA5C382232B045BA8F463441F29"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "3158be00-0748-322d-a8eb-4f9914eaf2c9"
    deleted: true
    disabled: false
    ignoredBySystem: true
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
  - pathId: "path4"
    testPathName: "analyze2WhenTypeNotIsInstanceFailureThrowsNullPointerException"
    constructorSignature: "<init>() : void"
    modelFingerprint: "9C3B27AC80424204B3B952A05A5367C8"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "rootFailure"
      modelFingerprint: "DA839D4559B0DC7B2B0CF20E53AC8DBA"
      index: 2
      valueUuid: "analyze_throwable1"
    - type: "INPUT"
      name: "cause"
      modelFingerprint: "771C85ADAF743D07B8FD06C9B4A818CC"
      index: 3
      valueUuid: "analyze_unboundConfigurationPropertiesException1"
    - type: "LOCAL_VARIABLE"
      name: "cause"
      modelFingerprint: "5DF3AD2FD83D0F4D8963E0B16269B662"
      index: 4
      valueUuid: "findCause_throwable2"
      methodExercised:
        target: "cause"
        name: "getTarget"
        parameters: []
        signature: "getTarget(): Bindable"
        returnValueUuid: "uuid1"
        access: 1
    - type: "RESULT"
      name: "result"
      modelFingerprint: "1544C3243427A58A5AE91A88CC628F77"
      index: 5
      valueUuid: "uuid2"
    uuid: "4a365458-5fe0-3a89-afee-917b3977ac44"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.diagnostics.analyzer.UnboundConfigurationPropertyFailureAnalyzer"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.diagnostics.analyzer.UnboundConfigurationPropertyFailureAnalyzer"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "java.lang.Throwable"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "java.lang.Throwable"
      uuid: "analyze_throwable1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.bind.UnboundConfigurationPropertiesException"
      uuid: "analyze_unboundConfigurationPropertiesException1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "NULL"
      valueType: "org.springframework.boot.context.properties.bind.BindException"
      uuid: "findCause_throwable2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: true
    - sapientType: "EXCEPTION"
      content: !<new>
        target: "java.lang.NullPointerException"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "java.lang.NullPointerException"
      uuid: "uuid1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "EXCEPTION"
      content: !<new>
        target: "java.lang.NullPointerException"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "java.lang.NullPointerException"
      uuid: "uuid2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
  - pathId: "path3"
    testPathName: "analyze2WhenExceptionGetUnboundPropertiesIsEmpty"
    constructorSignature: "<init>() : void"
    modelFingerprint: "AAF361B7E5E3A3EDEF8FDFE2E4CB9725"
    problemWasSolvedByProver: false
    truncated: true
    inputParameters: []
    uuid: "2a70c39a-34e4-3d81-a2de-d5f891bf260f"
    deleted: true
    disabled: false
    ignoredBySystem: true
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.lang.Class.isInstance(java.lang.Throwable)\
        \ : boolean"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
  - pathId: "path1"
    testPathName: "analyze2WhenPropertyIsNotNull"
    constructorSignature: "<init>() : void"
    modelFingerprint: "918A41DA2FA676F9011939566D5C7FFA"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "rootFailure"
      modelFingerprint: "BF86D91B8E1CE4FFAD3BA46C22581B57"
      index: 2
      valueUuid: "analyze_throwable1"
    - type: "INPUT"
      name: "cause"
      modelFingerprint: "3447EDBCBC56E88B087804EB87E3933D"
      index: 3
      valueUuid: "analyze_unboundConfigurationPropertiesException1"
    - type: "LOCAL_VARIABLE"
      name: "cause"
      modelFingerprint: "70FF1E4853A61D92F5F31D36CE18F196"
      index: 4
      valueUuid: "analyze_throwable1"
      methodExercised:
        target: "cause"
        name: "getTarget"
        parameters: []
        signature: "getTarget(): Bindable"
        returnValueUuid: "analyzeUnboundConfigurationPropertiesException_bindable1"
        access: 1
    - type: "LOCAL_VARIABLE"
      name: "property"
      modelFingerprint: "0D9AEABB90AD5F1EB79A57E8A24FE328"
      index: 5
      valueUuid: "analyzeUnboundConfigurationPropertiesException_object1"
      methodExercised:
        target: "property"
        name: "getName"
        parameters: []
        signature: "getName(): ConfigurationPropertyName"
        returnValueUuid: "buildDescription_configurationPropertyName1"
        access: 1
    - type: "LOCAL_VARIABLE"
      name: "property"
      modelFingerprint: "FE81151352054DEB548A176C0167A942"
      index: 6
      valueUuid: "analyzeUnboundConfigurationPropertiesException_object1"
      methodExercised:
        target: "property"
        name: "getValue"
        parameters: []
        signature: "getValue(): Object"
        returnValueUuid: "buildDescription_object1"
        access: 1
    - type: "LOCAL_VARIABLE"
      name: "property"
      modelFingerprint: "50571524F1F452CCAC826DD0E4B321E5"
      index: 7
      valueUuid: "analyzeUnboundConfigurationPropertiesException_object1"
      methodExercised:
        target: "property"
        name: "getOrigin"
        parameters: []
        signature: "getOrigin(): Origin"
        returnValueUuid: "buildDescription_origin1"
        access: 1
    - type: "LOCAL_VARIABLE"
      name: "exception"
      modelFingerprint: "C90FB87D915DF26BAD38B96CF1DB7516"
      index: 8
      valueUuid: "analyze_unboundConfigurationPropertiesException1"
      methodExercised:
        target: "exception"
        name: "getMessage"
        parameters: []
        signature: "getMessage(): String"
        returnValueUuid: "analyzeUnboundConfigurationPropertiesException_string2"
        access: 1
    - type: "RESULT"
      name: "result"
      modelFingerprint: "2A8A12A7710CE30EB35270E9AFEC4819"
      index: 9
      valueUuid: "getFailureAnalysis_failureAnalysis1"
    uuid: "7f6bbcb3-974f-343f-9bb9-8f49d6ecf1d0"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "LLM"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.diagnostics.analyzer.UnboundConfigurationPropertyFailureAnalyzer"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.diagnostics.analyzer.UnboundConfigurationPropertyFailureAnalyzer"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.bind.BindException"
      uuid: "analyze_throwable1"
      fixed: false
      nameForMock: "BindException"
      equalsMethodPresent: false
      explicitCastNeeded: true
      explicitCastForOverloadedMethods: "java.lang.Throwable"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.bind.UnboundConfigurationPropertiesException"
        parameters:
        - name: "unboundProperties"
          value:
            sapientType: "COLLECTION"
            content: !<collection>
              parameters: []
              values: []
            valueType: "java.util.Set"
            uuid: "analyze_unboundConfigurationPropertiesException1-unboundProperties"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.bind.UnboundConfigurationPropertiesException"
      uuid: "analyze_unboundConfigurationPropertiesException1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.bind.BindException"
      uuid: "analyze_throwable1"
      fixed: false
      nameForMock: "BindException"
      equalsMethodPresent: false
      explicitCastNeeded: true
      explicitCastForOverloadedMethods: "java.lang.Throwable"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.bind.Bindable"
      genericValueType: "?"
      uuid: "analyzeUnboundConfigurationPropertiesException_bindable1"
      fixed: false
      nameForMock: "analyzeUnboundConfigurationPropertiesException_bindable1"
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.ConfigurationProperty"
        parameters:
        - name: "name"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyName"
            uuid: "buildDescription_configurationPropertyName1"
            fixed: false
            nameForMock: "ConfigurationPropertyName"
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "value"
          value:
            sapientType: "MOCK"
            valueType: "java.lang.Object"
            uuid: "buildDescription_object1"
            fixed: false
            nameForMock: "Object"
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "origin"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.origin.Origin"
            uuid: "buildDescription_origin1"
            fixed: false
            nameForMock: "Origin"
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.source.ConfigurationProperty"
      uuid: "analyzeUnboundConfigurationPropertiesException_object1"
      fixed: false
      collectionUuid: "analyze_unboundConfigurationPropertiesException1-unboundProperties"
      equalsMethodPresent: false
      explicitCastNeeded: true
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyName"
      uuid: "buildDescription_configurationPropertyName1"
      fixed: false
      nameForMock: "ConfigurationPropertyName"
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.ConfigurationProperty"
        parameters:
        - name: "name"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyName"
            uuid: "buildDescription_configurationPropertyName1"
            fixed: false
            nameForMock: "ConfigurationPropertyName"
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "value"
          value:
            sapientType: "MOCK"
            valueType: "java.lang.Object"
            uuid: "buildDescription_object1"
            fixed: false
            nameForMock: "Object"
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "origin"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.origin.Origin"
            uuid: "buildDescription_origin1"
            fixed: false
            nameForMock: "Origin"
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.source.ConfigurationProperty"
      uuid: "analyzeUnboundConfigurationPropertiesException_object1"
      fixed: false
      collectionUuid: "analyze_unboundConfigurationPropertiesException1-unboundProperties"
      equalsMethodPresent: false
      explicitCastNeeded: true
    - sapientType: "MOCK"
      valueType: "java.lang.Object"
      uuid: "buildDescription_object1"
      fixed: false
      nameForMock: "Object"
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.ConfigurationProperty"
        parameters:
        - name: "name"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyName"
            uuid: "buildDescription_configurationPropertyName1"
            fixed: false
            nameForMock: "ConfigurationPropertyName"
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "value"
          value:
            sapientType: "MOCK"
            valueType: "java.lang.Object"
            uuid: "buildDescription_object1"
            fixed: false
            nameForMock: "Object"
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "origin"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.origin.Origin"
            uuid: "buildDescription_origin1"
            fixed: false
            nameForMock: "Origin"
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.source.ConfigurationProperty"
      uuid: "analyzeUnboundConfigurationPropertiesException_object1"
      fixed: false
      collectionUuid: "analyze_unboundConfigurationPropertiesException1-unboundProperties"
      equalsMethodPresent: false
      explicitCastNeeded: true
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.origin.Origin"
      uuid: "buildDescription_origin1"
      fixed: false
      nameForMock: "Origin"
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.bind.UnboundConfigurationPropertiesException"
        parameters:
        - name: "unboundProperties"
          value:
            sapientType: "COLLECTION"
            content: !<collection>
              parameters: []
              values: []
            valueType: "java.util.Set"
            uuid: "analyze_unboundConfigurationPropertiesException1-unboundProperties"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.bind.UnboundConfigurationPropertiesException"
      uuid: "analyze_unboundConfigurationPropertiesException1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "String"
      valueType: "java.lang.String"
      uuid: "analyzeUnboundConfigurationPropertiesException_string2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.diagnostics.FailureAnalysis"
        parameters:
        - name: "description"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "\\\"Binding to target null failed:\\\\n\\\"\\\"\\\\n    Property:\
                \ null\\\",\\\"\\\\n    Value: \\\\\\\"null\\\\\\\"\\\",\\\"\\\\n\
                \    Origin: null\\\",\\\"\\\\n    Reason: String\\\""
            valueType: "java.lang.String"
            uuid: "getFailureAnalysis_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "action"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Update your application's configuration"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "cause"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.bind.BindException"
            uuid: "analyze_throwable1"
            fixed: false
            nameForMock: "BindException"
            equalsMethodPresent: false
            explicitCastNeeded: true
            explicitCastForOverloadedMethods: "java.lang.Throwable"
        privateConstructor: false
        createdByTargetCode: true
      valueType: "org.springframework.boot.diagnostics.FailureAnalysis"
      uuid: "getFailureAnalysis_failureAnalysis1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "analyze2WhenPropertyIsNull"
    constructorSignature: "<init>() : void"
    modelFingerprint: "C9CCAE8D5DA68839FE7459CF182D4AE7"
    problemWasSolvedByProver: false
    truncated: true
    inputParameters: []
    uuid: "8a7afb8c-7ad9-3290-8a42-b5014dcad535"
    deleted: true
    disabled: false
    ignoredBySystem: true
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.lang.Class.isInstance(java.lang.Throwable)\
        \ : boolean"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
