---
modelFingerprint: "42B55E75B59B118002D2FEFF792EDEDF"
methods:
- method:
    name: "getOrder"
    returnType: "int"
    signature: "getOrder() : int"
    instructionFingerprint: "D097CF84226A0A5BDFC73B598FC0E93C"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getOrderTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(org.springframework.boot.logging.DeferredLogFactory)\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "414992C646F613A9539A5575355BBD69"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "c0bb632e-c120-35d3-9fe3-7fc42c801bce"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "postProcessEnvironment"
    returnType: "void"
    signature: "postProcessEnvironment(org.springframework.core.env.ConfigurableEnvironment,org.springframework.boot.SpringApplication)\
      \ : void"
    instructionFingerprint: "0055449D8D5F9D959624F30635C93AC8"
    parametersTypes:
    - "org.springframework.core.env.ConfigurableEnvironment"
    - "org.springframework.boot.SpringApplication"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "postProcessEnvironmentTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(org.springframework.boot.logging.DeferredLogFactory)\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "FEC56ADD4F99F3B62A838E7E90C608DA"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "912D8EBDF2F9CBAC6B2F41E23564579A"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.env.RandomValuePropertySourceEnvironmentPostProcessor"
          parameters:
          - name: "logFactory"
            value:
              sapientType: "MOCK"
              suggestedContent: !<unknown_object>
                target: "org.springframework.boot.logging.DeferredLogFactory"
                onlyPojoFunctions: false
                builderPattern: false
              valueType: "org.springframework.boot.logging.DeferredLogFactory"
              uuid: "<init>_deferredLogFactory1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.env.RandomValuePropertySourceEnvironmentPostProcessor"
          parameters:
          - name: "logFactory"
            value:
              sapientType: "UNKNOWN"
              suggestedContent: !<unknown_object>
                target: "org.springframework.boot.logging.DeferredLogFactory"
                onlyPojoFunctions: false
                builderPattern: false
              valueType: "org.springframework.boot.logging.DeferredLogFactory"
              uuid: "<init>_deferredLogFactory1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.env.RandomValuePropertySourceEnvironmentPostProcessor"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "environment"
      modelFingerprint: "962B65C2F1EA756AFD656B8B0436E5E4"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.core.env.ConfigurableEnvironment"
        uuid: "postProcessEnvironment_configurableEnvironment1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "application"
      modelFingerprint: "D435F136F62C059C52F9B1D570510B03"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.boot.SpringApplication"
        uuid: "postProcessEnvironment_springApplication1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "logFactory"
      modelFingerprint: "ECE6F417BFD8D7DFB994FB5FC2034CB3"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.boot.logging.DeferredLogFactory"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.boot.logging.DeferredLogFactory"
        uuid: "<init>_deferredLogFactory1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "logFactory"
        name: "getLog"
        parameters:
        - name: "destination"
          value:
            sapientType: "CLASS"
            content: !<regular>
              value: "org.springframework.boot.env.RandomValuePropertySourceEnvironmentPostProcessor"
            valueType: "java.lang.Class"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "getLog(Class): Log"
        returnValue:
          sapientType: "NULL"
          suggestedContent: !<unknown_object>
            target: "org.apache.commons.logging.Log"
            onlyPojoFunctions: false
            builderPattern: false
          valueType: "org.apache.commons.logging.Log"
          uuid: "<init>_log1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "RandomValuePropertySource"
      modelFingerprint: "8C3211EB7A84413CF9A57BC7529440F0"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.boot.env.RandomValuePropertySource"
        uuid: "org.springframework.boot.env.RandomValuePropertySource"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.boot.env.RandomValuePropertySource"
        name: "addToEnvironment"
        parameters:
        - name: "environment"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.core.env.ConfigurableEnvironment"
            uuid: "postProcessEnvironment_configurableEnvironment1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "logger"
          value:
            sapientType: "NULL"
            suggestedContent: !<unknown_object>
              target: "org.apache.commons.logging.Log"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "org.apache.commons.logging.Log"
            uuid: "<init>_log1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "addToEnvironment(ConfigurableEnvironment,Log): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "postProcessEnvironment_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 8
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 6
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "VOID"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "2bf0d88c-87ae-32ff-8715-263d7bb08637"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "REAL_RETURN_TODO_COMMENT"
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
