---
modelFingerprint: "EBB82A39AADE427ED278D092847961AB"
methods:
- method:
    name: "getOrder"
    signature: "getOrder() : int"
    sourceCodeSignature: "int getOrder()"
    instructionFingerprint: "D097CF84226A0A5BDFC73B598FC0E93C"
  paths:
  - pathId: "path1"
    testPathName: "getOrderTest"
    constructorSignature: "<init>(org.springframework.boot.logging.DeferredLogFactory)\
      \ : void"
    modelFingerprint: "C0641C043DDBD98F7AB9166138B80EA3"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "c0bb632e-c120-35d3-9fe3-7fc42c801bce"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "postProcessEnvironment"
    signature: "postProcessEnvironment(org.springframework.core.env.ConfigurableEnvironment,org.springframework.boot.SpringApplication)\
      \ : void"
    sourceCodeSignature: "void postProcessEnvironment(ConfigurableEnvironment environment,\
      \ SpringApplication application)"
    instructionFingerprint: "0055449D8D5F9D959624F30635C93AC8"
  paths:
  - pathId: "path1"
    testPathName: "postProcessEnvironmentTest"
    constructorSignature: "<init>(org.springframework.boot.logging.DeferredLogFactory)\
      \ : void"
    modelFingerprint: "82ECF50F54C9AC1D354A65D169AB3E9C"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "912D8EBDF2F9CBAC6B2F41E23564579A"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "environment"
      modelFingerprint: "962B65C2F1EA756AFD656B8B0436E5E4"
      index: 2
      valueUuid: "postProcessEnvironment_configurableEnvironment1"
    - type: "INPUT"
      name: "application"
      modelFingerprint: "D435F136F62C059C52F9B1D570510B03"
      index: 3
      valueUuid: "postProcessEnvironment_springApplication1"
    - type: "LOCAL_VARIABLE"
      name: "logFactory"
      modelFingerprint: "BE861B082D11D0C3F76976F2532CB864"
      index: 4
      valueUuid: "<init>_deferredLogFactory1"
      methodExercised:
        target: "logFactory"
        name: "getLog"
        parameters:
        - name: "destination"
          valueUuid: "uuid3"
        signature: "getLog(Class): Log"
        returnValueUuid: "<init>_log1"
        access: 1
    - type: "STATIC"
      name: "RandomValuePropertySource"
      modelFingerprint: "4681F683D13433941AEC96038E133D37"
      index: 5
      valueUuid: "uuid4"
      methodExercised:
        target: "org.springframework.boot.env.RandomValuePropertySource"
        name: "addToEnvironment"
        parameters:
        - name: "environment"
          valueUuid: "postProcessEnvironment_configurableEnvironment1"
        - name: "logger"
          valueUuid: "<init>_log1"
        signature: "addToEnvironment(ConfigurableEnvironment,NoOpLog): void"
        returnValueUuid: "postProcessEnvironment_void1"
        access: 8
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 6
      valueUuid: "uuid5"
    uuid: "2bf0d88c-87ae-32ff-8715-263d7bb08637"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.env.RandomValuePropertySourceEnvironmentPostProcessor"
        parameters:
        - name: "logFactory"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.logging.DeferredLogFactory"
            uuid: "<init>_deferredLogFactory1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.env.RandomValuePropertySourceEnvironmentPostProcessor"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "postProcessEnvironment_configurableEnvironment1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.SpringApplication"
      uuid: "postProcessEnvironment_springApplication1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.logging.DeferredLogFactory"
      uuid: "<init>_deferredLogFactory1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.apache.commons.logging.impl.NoOpLog"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.apache.commons.logging.impl.NoOpLog"
      uuid: "<init>_log1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.env.RandomValuePropertySourceEnvironmentPostProcessor"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.env.RandomValuePropertySourceEnvironmentPostProcessor"
      uuid: "uuid3"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.env.RandomValuePropertySource"
      uuid: "uuid4"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "postProcessEnvironment_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "postProcessEnvironment_configurableEnvironment1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.apache.commons.logging.impl.NoOpLog"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.apache.commons.logging.impl.NoOpLog"
      uuid: "<init>_log1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      uuid: "uuid5"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
