---
modelFingerprint: "AD9CA121D552D9CB131966D48DF06315"
targetClass:
  fullClassName: "org.springframework.boot.env.ReflectionEnvironmentPostProcessorsFactory"
methods:
- method:
    name: "getEnvironmentPostProcessors"
    sourceCodeSignature: "List<EnvironmentPostProcessor> getEnvironmentPostProcessors(DeferredLogFactory\
      \ logFactory, ConfigurableBootstrapContext bootstrapContext)"
    returnType: "java.util.List"
    genericReturnType: "org.springframework.boot.env.EnvironmentPostProcessor"
    parameters:
    - name: "logFactory"
      type: "org.springframework.boot.logging.DeferredLogFactory"
    - name: "bootstrapContext"
      type: "org.springframework.boot.ConfigurableBootstrapContext"
    instructionFingerprint: "0E5FABDAC266DCD8E17229CEDD2147A9"
  paths:
  - pathId: "path1"
    testPathName: "getEnvironmentPostProcessorsWhenThisClassesIsNull"
    constructorSignature: "<init>(java.lang.ClassLoader,java.lang.String[]) : void"
    modelFingerprint: "E8BF11441763B1DD8B613C2C7DED1072"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "1B388523B2FAE56FF8FBDC91DDFFA1F6"
      valueUuid: "target"
    - type: "INPUT"
      name: "logFactory"
      modelFingerprint: "65D08C167BC71AA4EEC7AF424F5632E8"
      valueUuid: "logFactory"
    - type: "INPUT"
      name: "bootstrapContext"
      modelFingerprint: "10B4C5E8932B1B51CBD0F88CC11CB35F"
      valueUuid: "bootstrapContext"
    - type: "LOCAL_VARIABLE"
      name: "instantiator"
      modelFingerprint: "E9E85723643B4CCC20D5A5C9BC8ECDE9"
      valueUuid: "instantiator"
      methodExercised:
        expression: "instantiate(classLoader:classLoader,names:list):list2"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "47F13FEBA14FC1FFDB2EC077DCF24619"
      valueUuid: "list2"
    disabled: false
    failureReason:
      reason: "VARIABLE_THAT_COULD_NOT_BE_ISOLATED_MOCKED"
      source: ": instantiator.instantiate(this.classLoader, this.classNames);"
      lineNumber: 72
      details: "A variable could not be isolated/mocked when calling a method - Variable\
        \ name: instantiator - Method: instantiate"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.env.ReflectionEnvironmentPostProcessorsFactory"
        parameters:
        - name: "classLoader"
          value:
            sapientType: "OBJECT"
            content: !<static_method_return>
              target: "java.lang.ClassLoader"
              method: "getPlatformClassLoader"
              methodParameters: []
            valueType: "java.lang.ClassLoader"
            uuid: "classLoader"
        - name: "classNames"
          value:
            sapientType: "ARRAY"
            content: !<array>
              values: {}
            valueType: "java.lang.String[]"
            uuid: "classNames"
      valueType: "org.springframework.boot.env.ReflectionEnvironmentPostProcessorsFactory"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.logging.DeferredLogFactory"
      uuid: "logFactory"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.ConfigurableBootstrapContext"
      uuid: "bootstrapContext"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.util.Instantiator"
        parameters:
        - name: "type"
          value:
            sapientType: "CLASS"
            content: !<regular>
              value: "org.springframework.boot.env.EnvironmentPostProcessor"
            valueType: "java.lang.Class"
            genericValueType: "org.springframework.boot.env.EnvironmentPostProcessor"
            uuid: "uniqueUuid1"
            fixed: true
        - name: "availableParameters"
          value:
            sapientType: "PRIVATE_INNER_CLASS_OR_LAMBDA"
            valueType: "java.util.function.Consumer"
            uuid: "uniqueUuid2"
      valueType: "org.springframework.boot.util.Instantiator"
      genericValueType: "org.springframework.boot.env.EnvironmentPostProcessor"
      uuid: "instantiator"
      fixed: true
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.List"
      genericValueType: "org.springframework.boot.env.EnvironmentPostProcessor"
      uuid: "list2"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.lang.ClassLoader"
        method: "getPlatformClassLoader"
        methodParameters: []
      valueType: "java.lang.ClassLoader"
      uuid: "classLoader"
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.List"
      genericValueType: "java.lang.String"
      uuid: "list"
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.List"
      genericValueType: "org.springframework.boot.env.EnvironmentPostProcessor"
      uuid: "list2"
    branches:
    - lineNumber: 71
      expression: "this.classes != null"
      range: "(71,11)-(71,30)"
      evaluatedAs: false
