---
modelFingerprint: "55BF916AF6825B40CC4A35BF946A1789"
methods:
- method:
    name: "getEnvironmentPostProcessors"
    signature: "getEnvironmentPostProcessors(org.springframework.boot.logging.DeferredLogFactory,org.springframework.boot.ConfigurableBootstrapContext)\
      \ : java.util.List<org.springframework.boot.env.EnvironmentPostProcessor>"
    sourceCodeSignature: "List<EnvironmentPostProcessor> getEnvironmentPostProcessors(DeferredLogFactory\
      \ logFactory, ConfigurableBootstrapContext bootstrapContext)"
    instructionFingerprint: "0E5FABDAC266DCD8E17229CEDD2147A9"
  paths:
  - pathId: "path1"
    testPathName: "getEnvironmentPostProcessorsWhenThisClassesIsNull"
    constructorSignature: "<init>(java.lang.ClassLoader,java.lang.String[]) : void"
    modelFingerprint: "58CE9555EF18BA45A48675C49B5541D4"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "57AAD5CD253E877B8958709BEE99C392"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "logFactory"
      modelFingerprint: "9AE295A1EF00BD72CA60AC12F5AEB78D"
      index: 2
      valueUuid: "getEnvironmentPostProcessors_deferredLogFactory1"
    - type: "INPUT"
      name: "bootstrapContext"
      modelFingerprint: "446184A4A4343527F66F98FE23F7274E"
      index: 3
      valueUuid: "getEnvironmentPostProcessors_configurableBootstrapContext1"
    - type: "LOCAL_VARIABLE"
      name: "instantiator"
      modelFingerprint: "DD410E6F236ACAB4CEF726D919CA542B"
      index: 4
      valueUuid: "getEnvironmentPostProcessors_instantiator1"
      methodExercised:
        target: "instantiator"
        name: "instantiate"
        parameters:
        - name: "classLoader"
          valueUuid: "<init>_classLoader1"
        - name: "names"
          valueUuid: "<init>_list1"
        signature: "instantiate(ClassLoader,List): List"
        returnValueUuid: "getEnvironmentPostProcessors_list1"
        access: 1
    - type: "RESULT"
      name: "result"
      modelFingerprint: "B1500B6143E4C3AD74A922264839D076"
      index: 5
      valueUuid: "getEnvironmentPostProcessors_list1"
    uuid: "13700995-cb06-3995-a07e-88c400f68ae3"
    deleted: false
    disabled: false
    ignoredBySystem: false
    variablesCouldNotBeIsolated: "instantiator"
    failureReason:
      reason: "VARIABLE_THAT_COULD_NOT_BE_ISOLATED_MOCKED"
      source: ": instantiator.instantiate(this.classLoader, this.classNames);"
      lineNumber: 72
      details: "A variable could not be isolated or mocked when calling a method -\
        \ Variable name: instantiator - Method: instantiate"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.env.ReflectionEnvironmentPostProcessorsFactory"
        parameters:
        - name: "classLoader"
          value:
            sapientType: "OBJECT"
            content: !<static_method_return>
              target: "java.lang.ClassLoader"
              method: "getPlatformClassLoader"
              methodParameters: []
            valueType: "java.lang.ClassLoader"
            uuid: "<init>_classLoader1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "classNames"
          value:
            sapientType: "ARRAY"
            content: !<array>
              values: {}
            valueType: "java.lang.String[]"
            uuid: "<init>_string[]1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.env.ReflectionEnvironmentPostProcessorsFactory"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.logging.DeferredLogFactory"
      uuid: "getEnvironmentPostProcessors_deferredLogFactory1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.ConfigurableBootstrapContext"
      uuid: "getEnvironmentPostProcessors_configurableBootstrapContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.util.Instantiator"
        parameters:
        - name: "type"
          value:
            sapientType: "CLASS"
            content: !<regular>
              value: "org.springframework.boot.env.EnvironmentPostProcessor"
            valueType: "java.lang.Class"
            genericValueType: "org.springframework.boot.env.EnvironmentPostProcessor"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "availableParameters"
          value:
            sapientType: "PRIVATE_INNER_CLASS_OR_LAMBDA"
            valueType: "java.util.function.Consumer"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: true
      valueType: "org.springframework.boot.util.Instantiator"
      genericValueType: "org.springframework.boot.env.EnvironmentPostProcessor"
      uuid: "getEnvironmentPostProcessors_instantiator1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.List"
      genericValueType: "org.springframework.boot.env.EnvironmentPostProcessor"
      uuid: "getEnvironmentPostProcessors_list1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.lang.ClassLoader"
        method: "getPlatformClassLoader"
        methodParameters: []
      valueType: "java.lang.ClassLoader"
      uuid: "<init>_classLoader1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.List"
      genericValueType: "java.lang.String"
      uuid: "<init>_list1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.List"
      genericValueType: "org.springframework.boot.env.EnvironmentPostProcessor"
      uuid: "getEnvironmentPostProcessors_list1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
