---
modelFingerprint: "175F4D9FB2F7D9819BAC82D7EA193C0C"
methods:
- method:
    name: "getEnvironmentPostProcessors"
    returnType: "java.util.List"
    signature: "getEnvironmentPostProcessors(org.springframework.boot.logging.DeferredLogFactory,org.springframework.boot.ConfigurableBootstrapContext)\
      \ : java.util.List<org.springframework.boot.env.EnvironmentPostProcessor>"
    instructionFingerprint: "9F4CA45EDA29D35835E9BEEB3F07BF1B"
    parametersTypes:
    - "org.springframework.boot.logging.DeferredLogFactory"
    - "org.springframework.boot.ConfigurableBootstrapContext"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getEnvironmentPostProcessorsTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(org.springframework.core.io.support.SpringFactoriesLoader)\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "C5FEA9C22ABF3A70A831762A8F30D38A"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "E2B9DD63AC1502D9045BD2E8F37A188F"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.env.SpringFactoriesEnvironmentPostProcessorsFactory"
          parameters:
          - name: "loader"
            value:
              sapientType: "MOCK"
              suggestedContent: !<unknown_object>
                target: "org.springframework.core.io.support.SpringFactoriesLoader"
                onlyPojoFunctions: false
                builderPattern: false
              valueType: "org.springframework.core.io.support.SpringFactoriesLoader"
              uuid: "<init>_springFactoriesLoader1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.env.SpringFactoriesEnvironmentPostProcessorsFactory"
          parameters:
          - name: "loader"
            value:
              sapientType: "UNKNOWN"
              suggestedContent: !<unknown_object>
                target: "org.springframework.core.io.support.SpringFactoriesLoader"
                onlyPojoFunctions: false
                builderPattern: false
              valueType: "org.springframework.core.io.support.SpringFactoriesLoader"
              uuid: "<init>_springFactoriesLoader1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.env.SpringFactoriesEnvironmentPostProcessorsFactory"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "logFactory"
      modelFingerprint: "9AE295A1EF00BD72CA60AC12F5AEB78D"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.boot.logging.DeferredLogFactory"
        uuid: "getEnvironmentPostProcessors_deferredLogFactory1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "bootstrapContext"
      modelFingerprint: "446184A4A4343527F66F98FE23F7274E"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.boot.ConfigurableBootstrapContext"
        uuid: "getEnvironmentPostProcessors_configurableBootstrapContext1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "SpringFactoriesLoader.ArgumentResolver"
      modelFingerprint: "58C4AB02BD35B4619157D5EC104A7B64"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
        uuid: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
        name: "of"
        parameters:
        - name: "type"
          value:
            sapientType: "CLASS"
            content: !<regular>
              value: "org.springframework.boot.logging.DeferredLogFactory"
            valueType: "java.lang.Class"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "value"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.logging.DeferredLogFactory"
            uuid: "getEnvironmentPostProcessors_deferredLogFactory1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "of(Class,DeferredLogFactory): SpringFactoriesLoader$ArgumentResolver"
        returnValue:
          sapientType: "MOCK"
          suggestedContent: !<unknown_object>
            target: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
            onlyPojoFunctions: false
            builderPattern: false
          valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
          uuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "argumentResolver"
      modelFingerprint: "5C2B113CDDDAA60E2B9A2D7D58D206A8"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
        uuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "argumentResolver"
        name: "and"
        parameters:
        - name: "type"
          value:
            sapientType: "CLASS"
            content: !<regular>
              value: "org.springframework.boot.ConfigurableBootstrapContext"
            valueType: "java.lang.Class"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "value"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.ConfigurableBootstrapContext"
            uuid: "getEnvironmentPostProcessors_configurableBootstrapContext1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "and(Class,ConfigurableBootstrapContext): SpringFactoriesLoader$ArgumentResolver"
        returnValue:
          sapientType: "MOCK"
          suggestedContent: !<unknown_object>
            target: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
            onlyPojoFunctions: false
            builderPattern: false
          valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
          uuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver2"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "argumentResolver"
      modelFingerprint: "EC751EE6DCD33294897F400891EC4FC3"
      index: 6
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
        uuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver2"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "argumentResolver"
        name: "and"
        parameters:
        - name: "type"
          value:
            sapientType: "CLASS"
            content: !<regular>
              value: "org.springframework.boot.BootstrapContext"
            valueType: "java.lang.Class"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "value"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.ConfigurableBootstrapContext"
            uuid: "getEnvironmentPostProcessors_configurableBootstrapContext1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "and(Class,ConfigurableBootstrapContext): SpringFactoriesLoader$ArgumentResolver"
        returnValue:
          sapientType: "MOCK"
          suggestedContent: !<unknown_object>
            target: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
            onlyPojoFunctions: false
            builderPattern: false
          valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
          uuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver3"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "argumentResolver"
      modelFingerprint: "E43E46CBFACB794D69E86E77E47E2616"
      index: 7
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
        uuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver3"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "argumentResolver"
        name: "and"
        parameters:
        - name: "type"
          value:
            sapientType: "CLASS"
            content: !<regular>
              value: "org.springframework.boot.BootstrapRegistry"
            valueType: "java.lang.Class"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "value"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.ConfigurableBootstrapContext"
            uuid: "getEnvironmentPostProcessors_configurableBootstrapContext1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "and(Class,ConfigurableBootstrapContext): SpringFactoriesLoader$ArgumentResolver"
        returnValue:
          sapientType: "MOCK"
          valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
          uuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver4"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1
      staticReadMethodForField: false
      filledByUser: false
    - type: "FIELD"
      name: "loader"
      modelFingerprint: "8E6F5BCBE15BB551606966154FFE1E03"
      index: 8
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.core.io.support.SpringFactoriesLoader"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.core.io.support.SpringFactoriesLoader"
        uuid: "<init>_springFactoriesLoader1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "this.loader"
        name: "load"
        parameters:
        - name: "factoryType"
          value:
            sapientType: "CLASS"
            content: !<regular>
              value: "org.springframework.boot.env.EnvironmentPostProcessor"
            valueType: "java.lang.Class"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "argumentResolver"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
            uuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver4"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "load(Class,SpringFactoriesLoader$ArgumentResolver): List"
        returnValue:
          sapientType: "COLLECTION"
          content: !<collection>
            parameters: []
            values: []
          suggestedContent: !<collection>
            parameters: []
            values: []
          valueType: "java.util.List"
          genericValueType: "org.springframework.boot.env.EnvironmentPostProcessor"
          uuid: "getEnvironmentPostProcessors_list1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "B1500B6143E4C3AD74A922264839D076"
      index: 9
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "COLLECTION"
        content: !<collection>
          parameters: []
          values: []
        suggestedContent: !<collection>
          parameters: []
          values: []
        valueType: "java.util.List"
        genericValueType: "org.springframework.boot.env.EnvironmentPostProcessor"
        uuid: "getEnvironmentPostProcessors_list1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "12688756-c3ba-301b-928b-5d81f13420fd"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
