---
modelFingerprint: "D9E4CBC207FF09F9C2381418DBAB4064"
methods:
- method:
    name: "getEnvironmentPostProcessors"
    signature: "getEnvironmentPostProcessors(org.springframework.boot.logging.DeferredLogFactory,org.springframework.boot.ConfigurableBootstrapContext)\
      \ : java.util.List<org.springframework.boot.env.EnvironmentPostProcessor>"
    sourceCodeSignature: "List<EnvironmentPostProcessor> getEnvironmentPostProcessors(DeferredLogFactory\
      \ logFactory, ConfigurableBootstrapContext bootstrapContext)"
    instructionFingerprint: "9F4CA45EDA29D35835E9BEEB3F07BF1B"
  paths:
  - pathId: "path1"
    testPathName: "getEnvironmentPostProcessorsTest"
    constructorSignature: "<init>(org.springframework.core.io.support.SpringFactoriesLoader)\
      \ : void"
    modelFingerprint: "20E8B13D1DE687A82FAE70D5E67E4A2C"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "E2B9DD63AC1502D9045BD2E8F37A188F"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "logFactory"
      modelFingerprint: "9AE295A1EF00BD72CA60AC12F5AEB78D"
      index: 2
      valueUuid: "getEnvironmentPostProcessors_deferredLogFactory1"
    - type: "INPUT"
      name: "bootstrapContext"
      modelFingerprint: "446184A4A4343527F66F98FE23F7274E"
      index: 3
      valueUuid: "getEnvironmentPostProcessors_configurableBootstrapContext1"
    - type: "STATIC"
      name: "SpringFactoriesLoader.ArgumentResolver"
      modelFingerprint: "C62A0B28F966AEA9BDAD2567A3FEA3A9"
      index: 4
      valueUuid: "uuid2"
      methodExercised:
        target: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
        name: "of"
        parameters:
        - name: "type"
          valueUuid: "uuid1"
        - name: "value"
          valueUuid: "getEnvironmentPostProcessors_deferredLogFactory1"
        signature: "of(Class,DeferredLogFactory): SpringFactoriesLoader$ArgumentResolver"
        returnValueUuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver1"
        access: 9
    - type: "LOCAL_VARIABLE"
      name: "argumentResolver"
      modelFingerprint: "CFBA0DDF1633F041BAE1F40904DBD6A4"
      index: 5
      valueUuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver1"
      methodExercised:
        target: "argumentResolver"
        name: "and"
        parameters:
        - name: "type"
          valueUuid: "uuid3"
        - name: "value"
          valueUuid: "getEnvironmentPostProcessors_configurableBootstrapContext1"
        signature: "and(Class,ConfigurableBootstrapContext): SpringFactoriesLoader$ArgumentResolver"
        returnValueUuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver2"
        access: 1
    - type: "LOCAL_VARIABLE"
      name: "argumentResolver"
      modelFingerprint: "4EC0601AE60F487119618B017F8BB208"
      index: 6
      valueUuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver2"
      methodExercised:
        target: "argumentResolver"
        name: "and"
        parameters:
        - name: "type"
          valueUuid: "uuid4"
        - name: "value"
          valueUuid: "getEnvironmentPostProcessors_configurableBootstrapContext1"
        signature: "and(Class,ConfigurableBootstrapContext): SpringFactoriesLoader$ArgumentResolver"
        returnValueUuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver3"
        access: 1
    - type: "LOCAL_VARIABLE"
      name: "argumentResolver"
      modelFingerprint: "1E5B767EDE0D82F704BB8E4FC6F8C28E"
      index: 7
      valueUuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver3"
      methodExercised:
        target: "argumentResolver"
        name: "and"
        parameters:
        - name: "type"
          valueUuid: "uuid5"
        - name: "value"
          valueUuid: "getEnvironmentPostProcessors_configurableBootstrapContext1"
        signature: "and(Class,ConfigurableBootstrapContext): SpringFactoriesLoader$ArgumentResolver"
        returnValueUuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver4"
        access: 1
    - type: "FIELD"
      name: "loader"
      modelFingerprint: "060A0CA9EBD07C5EF781F05B5D7782E4"
      index: 8
      valueUuid: "<init>_springFactoriesLoader1"
      methodExercised:
        target: "this.loader"
        name: "load"
        parameters:
        - name: "factoryType"
          valueUuid: "uuid6"
        - name: "argumentResolver"
          valueUuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver4"
        signature: "load(Class,SpringFactoriesLoader$ArgumentResolver): List"
        returnValueUuid: "getEnvironmentPostProcessors_list1"
        access: 1
    - type: "RESULT"
      name: "result"
      modelFingerprint: "B1500B6143E4C3AD74A922264839D076"
      index: 9
      valueUuid: "getEnvironmentPostProcessors_list1"
    uuid: "12688756-c3ba-301b-928b-5d81f13420fd"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.env.SpringFactoriesEnvironmentPostProcessorsFactory"
        parameters:
        - name: "loader"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.core.io.support.SpringFactoriesLoader"
            uuid: "<init>_springFactoriesLoader1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.env.SpringFactoriesEnvironmentPostProcessorsFactory"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.logging.DeferredLogFactory"
      uuid: "getEnvironmentPostProcessors_deferredLogFactory1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.ConfigurableBootstrapContext"
      uuid: "getEnvironmentPostProcessors_configurableBootstrapContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "uuid2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.logging.DeferredLogFactory"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.logging.DeferredLogFactory"
      uuid: "uuid1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.logging.DeferredLogFactory"
      uuid: "getEnvironmentPostProcessors_deferredLogFactory1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.ConfigurableBootstrapContext"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.ConfigurableBootstrapContext"
      uuid: "uuid3"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.ConfigurableBootstrapContext"
      uuid: "getEnvironmentPostProcessors_configurableBootstrapContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver3"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.BootstrapContext"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.BootstrapContext"
      uuid: "uuid4"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.ConfigurableBootstrapContext"
      uuid: "getEnvironmentPostProcessors_configurableBootstrapContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver3"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver4"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.BootstrapRegistry"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.BootstrapRegistry"
      uuid: "uuid5"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.ConfigurableBootstrapContext"
      uuid: "getEnvironmentPostProcessors_configurableBootstrapContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader"
      uuid: "<init>_springFactoriesLoader1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.List"
      genericValueType: "org.springframework.boot.env.EnvironmentPostProcessor"
      uuid: "getEnvironmentPostProcessors_list1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.env.EnvironmentPostProcessor"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.env.EnvironmentPostProcessor"
      uuid: "uuid6"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "getEnvironmentPostProcessors_springFactoriesLoader.ArgumentResolver4"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.List"
      genericValueType: "org.springframework.boot.env.EnvironmentPostProcessor"
      uuid: "getEnvironmentPostProcessors_list1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
