---
modelFingerprint: "80A53D4A56087068CAFE5527A4EC7A11"
targetClass:
  fullClassName: "org.springframework.boot.env.SpringFactoriesEnvironmentPostProcessorsFactory"
methods:
- method:
    name: "getEnvironmentPostProcessors"
    sourceCodeSignature: "List<EnvironmentPostProcessor> getEnvironmentPostProcessors(DeferredLogFactory\
      \ logFactory, ConfigurableBootstrapContext bootstrapContext)"
    returnType: "java.util.List"
    genericReturnType: "org.springframework.boot.env.EnvironmentPostProcessor"
    parameters:
    - name: "logFactory"
      type: "org.springframework.boot.logging.DeferredLogFactory"
    - name: "bootstrapContext"
      type: "org.springframework.boot.ConfigurableBootstrapContext"
    instructionFingerprint: "9F4CA45EDA29D35835E9BEEB3F07BF1B"
  paths:
  - pathId: "path1"
    testPathName: "getEnvironmentPostProcessorsTest"
    constructorSignature: "<init>(org.springframework.core.io.support.SpringFactoriesLoader)\
      \ : void"
    modelFingerprint: "4C062C61D9797D1AE805F9CBDCCC857D"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "3FB0B27A655625D1F1AAC4989E0ECDAD"
      valueUuid: "target"
    - type: "INPUT"
      name: "logFactory"
      modelFingerprint: "65D08C167BC71AA4EEC7AF424F5632E8"
      valueUuid: "logFactory"
    - type: "INPUT"
      name: "bootstrapContext"
      modelFingerprint: "10B4C5E8932B1B51CBD0F88CC11CB35F"
      valueUuid: "bootstrapContext"
    - type: "STATIC"
      name: "SpringFactoriesLoader.ArgumentResolver.class"
      modelFingerprint: "D37C2BEA47E3A2185DCF1F39CA6D6D38"
      valueUuid: "SpringFactoriesLoader.ArgumentResolver.class"
      methodExercised:
        expression: "of(type:uniqueUuid1,value:logFactory):springFactoriesLoader.ArgumentResolver"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      name: "argumentResolver"
      modelFingerprint: "8814639EF3A863A40BE3EFDF97223994"
      valueUuid: "springFactoriesLoader.ArgumentResolver"
      methodExercised:
        expression: "and(type:uniqueUuid2,value:bootstrapContext):springFactoriesLoader.ArgumentResolver2"
    - type: "LOCAL_VARIABLE"
      name: "argumentResolver"
      modelFingerprint: "62F1225961CFBA0EEE5B836D3B094278"
      valueUuid: "springFactoriesLoader.ArgumentResolver2"
      methodExercised:
        expression: "and(type:uniqueUuid3,value:bootstrapContext):springFactoriesLoader.ArgumentResolver3"
    - type: "LOCAL_VARIABLE"
      name: "argumentResolver"
      modelFingerprint: "A32233505EFC762835A33AB8578BBADA"
      valueUuid: "springFactoriesLoader.ArgumentResolver3"
      methodExercised:
        expression: "and(type:uniqueUuid4,value:bootstrapContext):springFactoriesLoader.ArgumentResolver4"
    - type: "FIELD"
      name: "loader"
      modelFingerprint: "833D52D89A21C4A2C8ED501DA0BD180B"
      valueUuid: "loader"
      methodExercised:
        expression: "load(factoryType:uniqueUuid5,argumentResolver:springFactoriesLoader.ArgumentResolver4):list"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "47F13FEBA14FC1FFDB2EC077DCF24619"
      valueUuid: "list"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.env.SpringFactoriesEnvironmentPostProcessorsFactory"
        parameters:
        - name: "loader"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.core.io.support.SpringFactoriesLoader"
            uuid: "loader"
      valueType: "org.springframework.boot.env.SpringFactoriesEnvironmentPostProcessorsFactory"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.logging.DeferredLogFactory"
      uuid: "logFactory"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.ConfigurableBootstrapContext"
      uuid: "bootstrapContext"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "SpringFactoriesLoader.ArgumentResolver.class"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "springFactoriesLoader.ArgumentResolver"
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.logging.DeferredLogFactory"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.logging.DeferredLogFactory"
      uuid: "uniqueUuid1"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.logging.DeferredLogFactory"
      uuid: "logFactory"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "springFactoriesLoader.ArgumentResolver"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "springFactoriesLoader.ArgumentResolver2"
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.ConfigurableBootstrapContext"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.ConfigurableBootstrapContext"
      uuid: "uniqueUuid2"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.ConfigurableBootstrapContext"
      uuid: "bootstrapContext"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "springFactoriesLoader.ArgumentResolver2"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "springFactoriesLoader.ArgumentResolver3"
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.BootstrapContext"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.BootstrapContext"
      uuid: "uniqueUuid3"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.ConfigurableBootstrapContext"
      uuid: "bootstrapContext"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "springFactoriesLoader.ArgumentResolver3"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "springFactoriesLoader.ArgumentResolver4"
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.BootstrapRegistry"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.BootstrapRegistry"
      uuid: "uniqueUuid4"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.ConfigurableBootstrapContext"
      uuid: "bootstrapContext"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader"
      uuid: "loader"
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.List"
      genericValueType: "org.springframework.boot.env.EnvironmentPostProcessor"
      uuid: "list"
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.env.EnvironmentPostProcessor"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.env.EnvironmentPostProcessor"
      uuid: "uniqueUuid5"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader$ArgumentResolver"
      uuid: "springFactoriesLoader.ArgumentResolver4"
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.List"
      genericValueType: "org.springframework.boot.env.EnvironmentPostProcessor"
      uuid: "list"
