---
modelFingerprint: "B785E5B82B0B7D085E7046B57C8A1A63"
methods:
- method:
    name: "postProcessEnvironment"
    signature: "postProcessEnvironment(org.springframework.core.env.ConfigurableEnvironment,org.springframework.boot.SpringApplication)\
      \ : void"
    sourceCodeSignature: "void postProcessEnvironment(ConfigurableEnvironment environment,\
      \ SpringApplication application)"
    instructionFingerprint: "5B0CCC3B48189B4E21A6D9F0DC3BB763"
  paths:
  - pathId: "path1"
    testPathName: "postProcessEnvironmentWhenPropertySourceIsNotNull"
    constructorSignature: "<init>() : void"
    modelFingerprint: "7B14D582767C2D14E1979DFDAEF43044"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "environment"
      modelFingerprint: "81E728D1D9282AF5B8509F27D0207EB4"
      index: 2
      valueUuid: "postProcessEnvironment_configurableEnvironment1"
    - type: "INPUT"
      name: "application"
      modelFingerprint: "6D7313C5BD9DA075BE90338421637223"
      index: 3
      valueUuid: "postProcessEnvironment_springApplication1"
    - type: "LOCAL_VARIABLE"
      name: "environment"
      modelFingerprint: "A1BC4CE198708953BDAB55E146058919"
      index: 4
      valueUuid: "postProcessEnvironment_configurableEnvironment1"
      methodExercised:
        target: "environment"
        name: "getPropertySources"
        parameters: []
        signature: "getPropertySources(): MutablePropertySources"
        returnValueUuid: "postProcessEnvironment_mutablePropertySources1"
        access: 1025
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "7B9177A4C356BD3649F7DEB458C263F7"
      index: 5
      valueUuid: "postProcessEnvironment_mutablePropertySources1"
      methodExercised:
        target: "org.springframework.core.env.MutablePropertySources"
        name: "get"
        parameters:
        - name: "name"
          valueUuid: "postProcessEnvironment_string1"
        signature: "get(String): PropertySource"
        returnValueUuid: "postProcessEnvironment_propertySource1"
        access: 1
    - type: "LOCAL_VARIABLE"
      name: "application"
      modelFingerprint: "0BEF43F215EDBC6A329E83F472A30A61"
      index: 6
      valueUuid: "postProcessEnvironment_springApplication1"
      methodExercised:
        target: "application"
        name: "getEnvironmentPrefix"
        parameters: []
        signature: "getEnvironmentPrefix(): String"
        returnValueUuid: "postProcessEnvironment_string2"
        access: 1
    - type: "LOCAL_VARIABLE"
      name: "propertySource"
      modelFingerprint: "D1610BDC0185B086586C1B6548473E06"
      index: 7
      valueUuid: "postProcessEnvironment_propertySource1"
      methodExercised:
        target: "propertySource"
        name: "getSource"
        parameters: []
        signature: "getSource(): Object"
        returnValueUuid: "replacePropertySource_object1"
        access: 1
    - type: "LOCAL_VARIABLE"
      name: "environment"
      modelFingerprint: "A1BC4CE198708953BDAB55E146058919"
      index: 8
      valueUuid: "postProcessEnvironment_configurableEnvironment1"
      methodExercised:
        target: "environment"
        name: "getPropertySources"
        parameters: []
        signature: "getPropertySources(): MutablePropertySources"
        returnValueUuid: "replacePropertySource_mutablePropertySources1"
        access: 1025
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "CCCC700E862FAECB118C3281682E21B4"
      index: 9
      valueUuid: "replacePropertySource_mutablePropertySources1"
      methodExercised:
        target: "org.springframework.core.env.MutablePropertySources"
        name: "replace"
        parameters:
        - name: "name"
          valueUuid: "postProcessEnvironment_string1"
        - name: "propertySource"
          valueUuid: "replacePropertySource_systemEnvironmentPropertySourceEnvironmentPostProcessor.OriginAwareSystemEnvironmentPropertySource1"
        signature: "replace(String,SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource):\
          \ void"
        returnValueUuid: "replacePropertySource_void1"
        access: 1
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 10
      valueUuid: "uuid1"
    uuid: "c38a95fc-a6cb-397a-a3de-fea67cb0dbba"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "postProcessEnvironment_configurableEnvironment1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.SpringApplication"
        parameters:
        - name: "primarySources"
          value:
            sapientType: "ARRAY"
            content: !<array>
              values: {}
            valueType: "java.lang.Class[]"
            uuid: "postProcessEnvironment_springApplication1-primarySources"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
        propertiesMap:
          environmentPrefix:
            sapientType: "BASIC"
            content: !<regular>
              value: "environmentPrefix1"
            valueType: "java.lang.String"
            uuid: "postProcessEnvironment_string2"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
      valueType: "org.springframework.boot.SpringApplication"
      uuid: "postProcessEnvironment_springApplication1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "postProcessEnvironment_configurableEnvironment1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.MutablePropertySources"
      uuid: "postProcessEnvironment_mutablePropertySources1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.MutablePropertySources"
      uuid: "postProcessEnvironment_mutablePropertySources1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.PropertySource"
      genericValueType: "?"
      uuid: "postProcessEnvironment_propertySource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "systemEnvironment"
      valueType: "java.lang.String"
      uuid: "postProcessEnvironment_string1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.SpringApplication"
        parameters:
        - name: "primarySources"
          value:
            sapientType: "ARRAY"
            content: !<array>
              values: {}
            valueType: "java.lang.Class[]"
            uuid: "postProcessEnvironment_springApplication1-primarySources"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
        propertiesMap:
          environmentPrefix:
            sapientType: "BASIC"
            content: !<regular>
              value: "environmentPrefix1"
            valueType: "java.lang.String"
            uuid: "postProcessEnvironment_string2"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
      valueType: "org.springframework.boot.SpringApplication"
      uuid: "postProcessEnvironment_springApplication1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "environmentPrefix1"
      valueType: "java.lang.String"
      uuid: "postProcessEnvironment_string2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.PropertySource"
      genericValueType: "?"
      uuid: "postProcessEnvironment_propertySource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.Map"
      uuid: "replacePropertySource_object1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: true
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "postProcessEnvironment_configurableEnvironment1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.MutablePropertySources"
      uuid: "replacePropertySource_mutablePropertySources1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.MutablePropertySources"
      uuid: "replacePropertySource_mutablePropertySources1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "replacePropertySource_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "systemEnvironment"
      valueType: "java.lang.String"
      uuid: "postProcessEnvironment_string1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource"
        parameters:
        - name: "name"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "systemEnvironment"
            valueType: "java.lang.String"
            uuid: "postProcessEnvironment_string1"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "source"
          value:
            sapientType: "COLLECTION"
            content: !<collection>
              parameters: []
              values: []
            valueType: "java.util.Map"
            uuid: "replacePropertySource_object1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: true
        - name: "environmentPrefix"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "environmentPrefix1"
            valueType: "java.lang.String"
            uuid: "postProcessEnvironment_string2"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: true
      valueType: "org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource"
      uuid: "replacePropertySource_systemEnvironmentPropertySourceEnvironmentPostProcessor.OriginAwareSystemEnvironmentPropertySource1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      uuid: "uuid1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "postProcessEnvironmentWhenPropertySourceIsNull"
    constructorSignature: "<init>() : void"
    modelFingerprint: "AB6533BF702555D48364DEB5C758EA4B"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "631cd72a-a711-3032-bbbe-5973b675904b"
    deleted: true
    disabled: false
    ignoredBySystem: true
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "getOrder"
    signature: "getOrder() : int"
    sourceCodeSignature: "int getOrder()"
    instructionFingerprint: "342D4E4F854A43E567A525BCBCDEA20C"
  paths:
  - pathId: "path1"
    testPathName: "getOrderTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "207CE3F4610F0021B089B3A69B1BD423"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "c0bb632e-c120-35d3-9fe3-7fc42c801bce"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "setOrder"
    signature: "setOrder(int) : void"
    sourceCodeSignature: "void setOrder(int order)"
    instructionFingerprint: "F88C98C2D7593841680C2CA0FECB4028"
  paths:
  - pathId: "path1"
    testPathName: "setOrderTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "A7D75C8F70F798AFD3A35CDB1E6AD09C"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "27a24730-befc-337f-a149-f3be3dcb76b7"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
