---
modelFingerprint: "D6B9C5C931F405E6B46835BB1FE5BACC"
targetClass:
  fullClassName: "org.springframework.boot.logging.logback.RootLogLevelConfigurator"
methods:
- method:
    name: "configure"
    sourceCodeSignature: "ExecutionStatus configure(LoggerContext loggerContext)"
    returnType: "ch.qos.logback.classic.spi.Configurator$ExecutionStatus"
    parameters:
    - name: "loggerContext"
      type: "ch.qos.logback.classic.LoggerContext"
    instructionFingerprint: "64BCFA790A090E2079C4C24EC92FF2B8"
  paths:
  - pathId: "path1"
    testPathName: "configureTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "A947C3FA7BDA502C1DF5EA188438B669"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "loggerContext"
      modelFingerprint: "96067B6F3C2FA20EC47A42DCB5F1B3E5"
      valueUuid: "loggerContext"
    - type: "LOCAL_VARIABLE"
      name: "loggerContext"
      modelFingerprint: "154341AF2CD40EAEE11F6FD9EAC2C68E"
      valueUuid: "loggerContext"
      methodExercised:
        expression: "getLogger(name:uniqueUuid1):logger"
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "C279713C7FF989F81FCBFD9C348657D6"
      valueUuid: "logger"
      methodExercised:
        expression: "setLevel(newLevel:level):void"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "2469BEF37D7B6B9156CF6D799E3A5AFE"
      valueUuid: "Enum-ch.qos.logback.classic.spi.Configurator$ExecutionStatus-INVOKE_NEXT_IF_ANY"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.logging.logback.RootLogLevelConfigurator"
        parameters: []
      valueType: "org.springframework.boot.logging.logback.RootLogLevelConfigurator"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "ch.qos.logback.classic.LoggerContext"
      uuid: "loggerContext"
    - sapientType: "MOCK"
      valueType: "ch.qos.logback.classic.LoggerContext"
      uuid: "loggerContext"
    - sapientType: "MOCK"
      valueType: "ch.qos.logback.classic.Logger"
      uuid: "logger"
    - sapientType: "BASIC"
      content: !<regular>
        value: "ROOT"
      valueType: "java.lang.String"
      uuid: "uniqueUuid1"
      fixed: true
    - sapientType: "MOCK"
      valueType: "ch.qos.logback.classic.Logger"
      uuid: "logger"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "OBJECT"
      content: !<static_field_return>
        target: "ch.qos.logback.classic.Level"
        fieldName: "INFO"
      valueType: "ch.qos.logback.classic.Level"
      uuid: "level"
    - sapientType: "ENUM"
      content: !<regular>
        value: "INVOKE_NEXT_IF_ANY"
      valueType: "ch.qos.logback.classic.spi.Configurator$ExecutionStatus"
      uuid: "Enum-ch.qos.logback.classic.spi.Configurator$ExecutionStatus-INVOKE_NEXT_IF_ANY"
      fixed: true
