---
modelFingerprint: "60F1CA594B0849A9B464237DCC63A763"
methods:
- method:
    name: "configure"
    returnType: "ch.qos.logback.classic.spi.Configurator$ExecutionStatus"
    signature: "configure(ch.qos.logback.classic.LoggerContext) : ch.qos.logback.classic.spi.Configurator$ExecutionStatus"
    instructionFingerprint: "35CC2D697C7DA1C5812FB4046F53BB96"
    parametersTypes:
    - "ch.qos.logback.classic.LoggerContext"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "configureTest"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "432D4E88E5F251624CD40B86505F1E80"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.logging.logback.RootLogLevelConfigurator"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.logging.logback.RootLogLevelConfigurator"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.logging.logback.RootLogLevelConfigurator"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "loggerContext"
      modelFingerprint: "C3767917E25814C3932E2E2F4A31587C"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "ch.qos.logback.classic.LoggerContext"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "ch.qos.logback.classic.LoggerContext"
        uuid: "configure_loggerContext1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "loggerContext"
      modelFingerprint: "50FF0579CD1FBF00BD95B2D046BCA65F"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "ch.qos.logback.classic.LoggerContext"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "ch.qos.logback.classic.LoggerContext"
        uuid: "configure_loggerContext1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "loggerContext"
        name: "getLogger"
        parameters:
        - name: "childName"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "ROOT"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "getLogger(String): Logger"
        returnValue:
          sapientType: "MOCK"
          suggestedContent: !<unknown_object>
            target: "ch.qos.logback.classic.Logger"
            onlyPojoFunctions: false
            builderPattern: false
          valueType: "ch.qos.logback.classic.Logger"
          uuid: "configure_logger1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "DA303E748E9D8CF2D56F00DE17475126"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "ch.qos.logback.classic.Logger"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "ch.qos.logback.classic.Logger"
        uuid: "configure_logger1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "ch.qos.logback.classic.Logger"
        name: "setLevel"
        parameters:
        - name: "child"
          value:
            sapientType: "OBJECT"
            content: !<static_field_return>
              target: "ch.qos.logback.classic.Level"
              fieldName: "INFO"
            suggestedContent: !<static_field_return>
              target: "ch.qos.logback.classic.Level"
              fieldName: "INFO"
            valueType: "ch.qos.logback.classic.Level"
            uuid: "configure_level1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "setLevel(Level): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "configure_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 33
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "0441C44ADB055A68A7AA602DBA4165A1"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "ENUM"
        content: !<regular>
          value: "INVOKE_NEXT_IF_ANY"
        valueType: "ch.qos.logback.classic.spi.Configurator$ExecutionStatus"
        uuid: "Enum-ch.qos.logback.classic.spi.Configurator$ExecutionStatus-INVOKE_NEXT_IF_ANY"
        fixed: true
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "f56d41b4-cf00-3592-bb68-9a89456c3c5f"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
