---
modelFingerprint: "E4901C50E14B14F8E0A26788B1239F98"
methods:
- method:
    name: "getEnvironmentType"
    signature: "getEnvironmentType(org.springframework.boot.WebApplicationType) :\
      \ java.lang.Class<? extends org.springframework.core.env.ConfigurableEnvironment>"
    sourceCodeSignature: "Class<? extends ConfigurableEnvironment> getEnvironmentType(WebApplicationType\
      \ webApplicationType)"
    instructionFingerprint: "F10095CBEE585E044D84D931BC6AE810"
  paths:
  - pathId: "path1"
    testPathName: "getEnvironmentTypeWhenWebApplicationTypeNotEqualsWebApplicationTypeSERVLET"
    constructorSignature: "<init>() : void"
    modelFingerprint: "7C0E615C9D85042572BF46EFC245A184"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "29A1D15945F5B8C38A3E4C0E9B2E9E09"
      index: 2
      valueUuid: "getEnvironmentType_webApplicationType1"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "EA143E57F20F67410D2C6371C343A7A7"
      index: 3
      valueUuid: "getEnvironmentType_class1"
    uuid: "d16221f6-bb15-3ca5-bd13-03fe3c352231"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "ENUM"
      content: !<regular>
        value: "NONE"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "getEnvironmentType_webApplicationType1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "NULL"
      valueType: "java.lang.Class"
      genericValueType: "? extends org.springframework.core.env.ConfigurableEnvironment"
      uuid: "getEnvironmentType_class1"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "getEnvironmentTypeWhenWebApplicationTypeEqualsWebApplicationTypeSERVLET"
    constructorSignature: "<init>() : void"
    modelFingerprint: "A627D83260F08084739DC4FC52571860"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "37070A464B015891A0762A6502331DBA"
      index: 2
      valueUuid: "getEnvironmentType_webApplicationType1"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "759399C784AE5B21355DCB8C1841A208"
      index: 3
      valueUuid: "uuid1"
    uuid: "29490cb3-9210-3eff-8f97-46db0d720dd3"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "ENUM"
      content: !<regular>
        value: "SERVLET"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "getEnvironmentType_webApplicationType1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.web.servlet.context.ApplicationServletEnvironment"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.web.servlet.context.ApplicationServletEnvironment"
      uuid: "uuid1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
- method:
    name: "createEnvironment"
    signature: "createEnvironment(org.springframework.boot.WebApplicationType) : org.springframework.core.env.ConfigurableEnvironment"
    sourceCodeSignature: "ConfigurableEnvironment createEnvironment(WebApplicationType\
      \ webApplicationType)"
    instructionFingerprint: "A20B370949E5DC07398640EBA49DF126"
  paths:
  - pathId: "path1"
    testPathName: "createEnvironmentWhenWebApplicationTypeNotEqualsWebApplicationTypeSERVLET"
    constructorSignature: "<init>() : void"
    modelFingerprint: "32D7B1F935E1A55F7A4988900CA224E1"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "29A1D15945F5B8C38A3E4C0E9B2E9E09"
      index: 2
      valueUuid: "createEnvironment_webApplicationType1"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "56A1F4572BC3FF40BAB492DA126A3FF1"
      index: 3
      valueUuid: "createEnvironment_configurableEnvironment1"
    uuid: "92d4b71f-e8a9-37f2-9242-7c7e5d2b6994"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "ENUM"
      content: !<regular>
        value: "NONE"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "createEnvironment_webApplicationType1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "NULL"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "createEnvironment_configurableEnvironment1"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "createEnvironmentWhenWebApplicationTypeEqualsWebApplicationTypeSERVLET"
    constructorSignature: "<init>() : void"
    modelFingerprint: "4069EB206A3C8BDA619FEF53387BFB82"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "37070A464B015891A0762A6502331DBA"
      index: 2
      valueUuid: "createEnvironment_webApplicationType1"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "BB459B1FCF5CED04F251B26E8F1250CC"
      index: 3
      valueUuid: "createEnvironment_applicationServletEnvironment1"
    uuid: "cad05148-c22e-3fee-b24b-203b63c28a9b"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "ENUM"
      content: !<regular>
        value: "SERVLET"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "createEnvironment_webApplicationType1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.context.ApplicationServletEnvironment"
        parameters: []
        privateConstructor: false
        createdByTargetCode: true
      valueType: "org.springframework.boot.web.servlet.context.ApplicationServletEnvironment"
      uuid: "createEnvironment_applicationServletEnvironment1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
- method:
    name: "create"
    signature: "create(org.springframework.boot.WebApplicationType) : org.springframework.context.ConfigurableApplicationContext"
    sourceCodeSignature: "ConfigurableApplicationContext create(WebApplicationType\
      \ webApplicationType)"
    instructionFingerprint: "872AB29C5F1D1D4ADA7AA7B9C6D41109"
  paths:
  - pathId: "path1"
    testPathName: "createWhenWebApplicationTypeNotEqualsWebApplicationTypeSERVLET"
    constructorSignature: "<init>() : void"
    modelFingerprint: "041515D304ED4BE9CE0825FB10F6DD1C"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "29A1D15945F5B8C38A3E4C0E9B2E9E09"
      index: 2
      valueUuid: "create_webApplicationType1"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "34AD2A495F2D236EFD1D4C994C1E2626"
      index: 3
      valueUuid: "create_configurableApplicationContext1"
    uuid: "753c1c10-04e6-32a5-9fd6-a521de7f1671"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "ENUM"
      content: !<regular>
        value: "NONE"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "create_webApplicationType1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "NULL"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "create_configurableApplicationContext1"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "createWhenAotDetectorNotUseGeneratedArtifacts"
    constructorSignature: "<init>() : void"
    modelFingerprint: "F9ADA07F149E284A4ADBC39526D85B99"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "37070A464B015891A0762A6502331DBA"
      index: 2
      valueUuid: "create_webApplicationType1"
    - type: "STATIC"
      name: "AotDetector"
      modelFingerprint: "55755DDCD5FC917CDCF2F0B5D903F136"
      index: 3
      valueUuid: "uuid2"
      methodExercised:
        target: "org.springframework.aot.AotDetector"
        name: "useGeneratedArtifacts"
        parameters: []
        signature: "useGeneratedArtifacts(): boolean"
        returnValueUuid: "createContext_boolean1"
        access: 9
    - type: "RESULT"
      name: "result"
      modelFingerprint: "53B2913612BE7793A3FA9586DA9360FF"
      index: 4
      valueUuid: "createContext_annotationConfigServletWebServerApplicationContext1"
    uuid: "04d448bd-0d6b-3748-bb5b-1365c42e01b2"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "ENUM"
      content: !<regular>
        value: "SERVLET"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "create_webApplicationType1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "REAL"
      valueType: "org.springframework.aot.AotDetector"
      uuid: "uuid2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "createContext_boolean1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext"
        parameters: []
        privateConstructor: false
        createdByTargetCode: true
      valueType: "org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext"
      uuid: "createContext_annotationConfigServletWebServerApplicationContext1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
