---
modelFingerprint: "D918CC680D1EA41B5C0A4F125C3D14FE"
targetClass:
  fullClassName: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
methods:
- method:
    name: "getEnvironmentType"
    sourceCodeSignature: "Class<? extends ConfigurableEnvironment> getEnvironmentType(WebApplicationType\
      \ webApplicationType)"
    returnType: "java.lang.Class"
    genericReturnType: "? extends org.springframework.core.env.ConfigurableEnvironment"
    parameters:
    - name: "webApplicationType"
      type: "org.springframework.boot.WebApplicationType"
    instructionFingerprint: "F10095CBEE585E044D84D931BC6AE810"
  paths:
  - pathId: "path1"
    testPathName: "getEnvironmentTypeWhenWebApplicationTypeNotEqualsWebApplicationTypeSERVLET"
    constructorSignature: "<init>() : void"
    modelFingerprint: "DD5E1016B47186305D0B6A3AEB1BF6A9"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "830F43FA9F3CF78152E96597C66C0CA7"
      valueUuid: "webApplicationType"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "6E032A22C09FD07D5F1F19718D09D592"
      valueUuid: "class"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
        parameters: []
      valueType: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
      uuid: "target"
    - sapientType: "ENUM"
      content: !<regular>
        value: "NONE"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "webApplicationType"
    - sapientType: "NULL"
      valueType: "java.lang.Class"
      genericValueType: "? extends org.springframework.core.env.ConfigurableEnvironment"
      uuid: "class"
      fixed: true
    branches:
    - lineNumber: 37
      expression: "webApplicationType != WebApplicationType.SERVLET"
      range: "(37,11)-(37,58)"
      evaluatedAs: true
  - pathId: "path2"
    testPathName: "getEnvironmentTypeWhenWebApplicationTypeEqualsWebApplicationTypeSERVLET"
    constructorSignature: "<init>() : void"
    modelFingerprint: "DCDB35771F97FCA9FB3AA68100849D3B"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "164831593CDD369484F37909C8EF7621"
      valueUuid: "webApplicationType"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "401FA378CD3AAC2F89FD5A8048BACF20"
      valueUuid: "expectedResult"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
        parameters: []
      valueType: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
      uuid: "target"
    - sapientType: "ENUM"
      content: !<regular>
        value: "SERVLET"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "webApplicationType"
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.web.servlet.context.ApplicationServletEnvironment"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.web.servlet.context.ApplicationServletEnvironment"
      uuid: "expectedResult"
      fixed: true
    branches:
    - lineNumber: 37
      expression: "webApplicationType != WebApplicationType.SERVLET"
      range: "(37,11)-(37,58)"
      evaluatedAs: false
- method:
    name: "createEnvironment"
    sourceCodeSignature: "ConfigurableEnvironment createEnvironment(WebApplicationType\
      \ webApplicationType)"
    returnType: "org.springframework.core.env.ConfigurableEnvironment"
    parameters:
    - name: "webApplicationType"
      type: "org.springframework.boot.WebApplicationType"
    instructionFingerprint: "A20B370949E5DC07398640EBA49DF126"
  paths:
  - pathId: "path1"
    testPathName: "createEnvironmentWhenWebApplicationTypeNotEqualsWebApplicationTypeSERVLET"
    constructorSignature: "<init>() : void"
    modelFingerprint: "C3F84F5F25F5701145EE6DA029AC5F81"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "830F43FA9F3CF78152E96597C66C0CA7"
      valueUuid: "webApplicationType"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "07C617B6F1D348BCC0225644494DDADD"
      valueUuid: "configurableEnvironment"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
        parameters: []
      valueType: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
      uuid: "target"
    - sapientType: "ENUM"
      content: !<regular>
        value: "NONE"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "webApplicationType"
    - sapientType: "NULL"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "configurableEnvironment"
      fixed: true
    branches:
    - lineNumber: 42
      expression: "webApplicationType != WebApplicationType.SERVLET"
      range: "(42,11)-(42,58)"
      evaluatedAs: true
  - pathId: "path2"
    testPathName: "createEnvironmentWhenWebApplicationTypeEqualsWebApplicationTypeSERVLET"
    constructorSignature: "<init>() : void"
    modelFingerprint: "486136B190B520D3E69BD1F46DC1AE79"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "164831593CDD369484F37909C8EF7621"
      valueUuid: "webApplicationType"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "757CAAA31CB766EBEDFC7240A48322D0"
      valueUuid: "applicationServletEnvironment"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
        parameters: []
      valueType: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
      uuid: "target"
    - sapientType: "ENUM"
      content: !<regular>
        value: "SERVLET"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "webApplicationType"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.context.ApplicationServletEnvironment"
        parameters: []
      valueType: "org.springframework.boot.web.servlet.context.ApplicationServletEnvironment"
      uuid: "applicationServletEnvironment"
      fixed: true
    branches:
    - lineNumber: 42
      expression: "webApplicationType != WebApplicationType.SERVLET"
      range: "(42,11)-(42,58)"
      evaluatedAs: false
- method:
    name: "create"
    sourceCodeSignature: "ConfigurableApplicationContext create(WebApplicationType\
      \ webApplicationType)"
    returnType: "org.springframework.context.ConfigurableApplicationContext"
    parameters:
    - name: "webApplicationType"
      type: "org.springframework.boot.WebApplicationType"
    instructionFingerprint: "872AB29C5F1D1D4ADA7AA7B9C6D41109"
  paths:
  - pathId: "path1"
    testPathName: "createWhenWebApplicationTypeNotEqualsWebApplicationTypeSERVLET"
    constructorSignature: "<init>() : void"
    modelFingerprint: "E739A70AF38108D2AD1381791DFFE0DB"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "830F43FA9F3CF78152E96597C66C0CA7"
      valueUuid: "webApplicationType"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "659CCF3F56A72A794F669DD1D72B1498"
      valueUuid: "configurableApplicationContext"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
        parameters: []
      valueType: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
      uuid: "target"
    - sapientType: "ENUM"
      content: !<regular>
        value: "NONE"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "webApplicationType"
    - sapientType: "NULL"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "configurableApplicationContext"
      fixed: true
    branches:
    - lineNumber: 47
      expression: "webApplicationType != WebApplicationType.SERVLET"
      range: "(47,11)-(47,58)"
      evaluatedAs: true
  - pathId: "path2"
    testPathName: "createWhenAotDetectorNotUseGeneratedArtifacts"
    constructorSignature: "<init>() : void"
    modelFingerprint: "63159D4F65CAF3C6FC8E48461A648EF9"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "164831593CDD369484F37909C8EF7621"
      valueUuid: "webApplicationType"
    - type: "STATIC"
      name: "AotDetector.class.real"
      modelFingerprint: "A651F35C9CB1BB4329EA23C459C95680"
      valueUuid: "AotDetector.class.real"
      methodExercised:
        expression: "useGeneratedArtifacts():boolean1"
        staticAccess: true
    - type: "RESULT"
      name: "result"
      modelFingerprint: "6880384D304ED28F4F5B48DFE263BB30"
      valueUuid: "annotationConfigServletWebServerApplicationContext"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
        parameters: []
      valueType: "org.springframework.boot.web.servlet.context.ServletWebServerApplicationContextFactory"
      uuid: "target"
    - sapientType: "ENUM"
      content: !<regular>
        value: "SERVLET"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "webApplicationType"
    - sapientType: "REAL"
      valueType: "org.springframework.aot.AotDetector"
      uuid: "AotDetector.class.real"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "boolean1"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext"
        parameters: []
      valueType: "org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext"
      uuid: "annotationConfigServletWebServerApplicationContext"
      fixed: true
    branches:
    - lineNumber: 47
      expression: "webApplicationType != WebApplicationType.SERVLET"
      range: "(47,11)-(47,58)"
      evaluatedAs: false
    - lineNumber: 51
      expression: "!AotDetector.useGeneratedArtifacts()"
      range: "(51,7)-(51,42)"
      evaluatedAs: true
      internalMethodName: "createContext"
