---
modelFingerprint: "45BCC0EB55610DC7450DFE7A35E10852"
methods:
- method:
    name: "getHandler"
    returnType: "io.undertow.server.HttpHandler"
    signature: "getHandler(io.undertow.server.HttpHandler) : io.undertow.server.HttpHandler"
    instructionFingerprint: "A0E56DB66FC6132AEB3B782C046BB6B3"
    parametersTypes:
    - "io.undertow.server.HttpHandler"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getHandlerWhenNextIsNull"
    nameDefinedByUser: false
    constructorSignature: "<init>(io.undertow.servlet.api.DeploymentManager) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "89FF7B131C07C59BDE819E290EFC6A14"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "83E5319031FE84322EADCF36D6B65C32"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.web.embedded.undertow.DeploymentManagerHttpHandlerFactory"
          parameters:
          - name: "deploymentManager"
            value:
              sapientType: "MOCK"
              valueType: "io.undertow.servlet.api.DeploymentManager"
              uuid: "<init>_deploymentManager1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.web.embedded.undertow.DeploymentManagerHttpHandlerFactory"
          parameters:
          - name: "deploymentManager"
            value:
              sapientType: "UNKNOWN"
              valueType: "io.undertow.servlet.api.DeploymentManager"
              uuid: "<init>_deploymentManager1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.web.embedded.undertow.DeploymentManagerHttpHandlerFactory"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "next"
      modelFingerprint: "13B6F1840D7F6C30FA3012883B30F4B9"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "NULL"
        valueType: "io.undertow.server.HttpHandler"
        uuid: "getHandler_httpHandler1"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "64D85F553867EDE46BBBADDA38157F66"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "REAL"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "state"
        parameters:
        - name: "expression"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: true
            valueType: "boolean"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "DeploymentManagerHttpHandlerFactory must be first"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "state(boolean,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "getHandler_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "CE782DC959B6EC669D8415B0FAB5A206"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.web.embedded.undertow.DeploymentManagerHttpHandlerFactory$DeploymentManagerHandler"
          parameters:
          - name: "ex"
            value:
              sapientType: "MOCK"
              valueType: "io.undertow.servlet.api.DeploymentManager"
              uuid: "<init>_deploymentManager1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: true
        suggestedContent: !<new>
          target: "org.springframework.boot.web.embedded.undertow.DeploymentManagerHttpHandlerFactory$DeploymentManagerHandler"
          parameters:
          - name: "ex"
            value:
              sapientType: "UNKNOWN"
              valueType: "io.undertow.servlet.api.DeploymentManager"
              uuid: "<init>_deploymentManager1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: true
        valueType: "org.springframework.boot.web.embedded.undertow.DeploymentManagerHttpHandlerFactory$DeploymentManagerHandler"
        uuid: "getHandler_deploymentManagerHttpHandlerFactory.DeploymentManagerHandler1"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "12125328-09ad-3ad9-a3d7-194e6ef02de9"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path2"
    pathIdForUser: "path2"
    testPathName: "getHandlerWhenNextIsNotNull"
    nameDefinedByUser: false
    constructorSignature: "<init>(io.undertow.servlet.api.DeploymentManager) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "579AE3C9F9B34EA7E618EDB621A804BC"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "83E5319031FE84322EADCF36D6B65C32"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.web.embedded.undertow.DeploymentManagerHttpHandlerFactory"
          parameters:
          - name: "deploymentManager"
            value:
              sapientType: "MOCK"
              valueType: "io.undertow.servlet.api.DeploymentManager"
              uuid: "<init>_deploymentManager1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.web.embedded.undertow.DeploymentManagerHttpHandlerFactory"
          parameters:
          - name: "deploymentManager"
            value:
              sapientType: "UNKNOWN"
              valueType: "io.undertow.servlet.api.DeploymentManager"
              uuid: "<init>_deploymentManager1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.web.embedded.undertow.DeploymentManagerHttpHandlerFactory"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "next"
      modelFingerprint: "03A29F3089AF6BE5C3C38D533F8B8F9A"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "io.undertow.server.HttpHandler"
        uuid: "getHandler_httpHandler1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "DEC224E49008082C9FDEEED124587F28"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "state"
        parameters:
        - name: "expression"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: false
            valueType: "boolean"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "DeploymentManagerHttpHandlerFactory must be first"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "state(boolean,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "getHandler_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "CE782DC959B6EC669D8415B0FAB5A206"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.web.embedded.undertow.DeploymentManagerHttpHandlerFactory$DeploymentManagerHandler"
          parameters:
          - name: "ex"
            value:
              sapientType: "MOCK"
              valueType: "io.undertow.servlet.api.DeploymentManager"
              uuid: "<init>_deploymentManager1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: true
        suggestedContent: !<new>
          target: "org.springframework.boot.web.embedded.undertow.DeploymentManagerHttpHandlerFactory$DeploymentManagerHandler"
          parameters:
          - name: "ex"
            value:
              sapientType: "UNKNOWN"
              valueType: "io.undertow.servlet.api.DeploymentManager"
              uuid: "<init>_deploymentManager1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: true
        valueType: "org.springframework.boot.web.embedded.undertow.DeploymentManagerHttpHandlerFactory$DeploymentManagerHandler"
        uuid: "getHandler_deploymentManagerHttpHandlerFactory.DeploymentManagerHandler1"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "f54a3c50-c61c-392f-bc80-e45cb3f284ab"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "getDeploymentManager"
    returnType: "io.undertow.servlet.api.DeploymentManager"
    signature: "getDeploymentManager() : io.undertow.servlet.api.DeploymentManager"
    instructionFingerprint: "3502B5FDFE5E1EE7FB7E45005BCBA31E"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getDeploymentManagerTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(io.undertow.servlet.api.DeploymentManager) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "13F2697792F679F8E4D04BE8AEC82C68"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "71c8036d-eb9f-3dbf-9408-8d0a1be6f819"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
