---
modelFingerprint: "3AFFE5D442B94EEFC3142B2D62463E37"
methods:
- method:
    name: "createEnvironment"
    signature: "createEnvironment() : org.springframework.core.env.ConfigurableEnvironment"
    instructionFingerprint: "F465B788A11E71966B69DB17337B92D3"
  paths:
  - pathId: "path1"
    testPathName: "createEnvironmentTest"
    constructorSignature: "<init>(org.springframework.beans.factory.support.DefaultListableBeanFactory)\
      \ : void"
    filledByUser: false
    modelFingerprint: "9321572C63087A10446E1D6FB935EC86"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "F76105DA44E97FAEE985C76F5A1EAB38"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "ObjectUtils"
      modelFingerprint: "A1E30B97FAC8A3C35470453587802A1C"
      index: 2
      ignored: false
      valueUuid: "uuid1"
      methodExercised:
        target: "org.springframework.util.ObjectUtils"
        name: "identityToString"
        parameters:
        - name: "obj"
          valueUuid: "targetClassObject"
        signature: "identityToString(AbstractApplicationContext): String"
        returnValueUuid: "<init>_string1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "ObjectUtils"
      modelFingerprint: "A1E30B97FAC8A3C35470453587802A1C"
      index: 3
      ignored: false
      valueUuid: "uuid2"
      methodExercised:
        target: "org.springframework.util.ObjectUtils"
        name: "identityToString"
        parameters:
        - name: "obj"
          valueUuid: "targetClassObject"
        signature: "identityToString(AbstractApplicationContext): String"
        returnValueUuid: "<init>_string2"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "D507F26D7508EE01F46981E90D5D685A"
      index: 4
      ignored: false
      valueUuid: "uuid4"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_defaultListableBeanFactory1"
        - name: "message"
          valueUuid: "uuid3"
        signature: "notNull(DefaultListableBeanFactory,String): void"
        returnValueUuid: "<init>_void1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "796795679E3C0F2DD38DF229E1CC991B"
      index: 5
      ignored: false
      valueUuid: "createEnvironment_standardReactiveWebEnvironment1"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "710fd138-f016-39a0-9d47-0163cb889999"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebApplicationContext"
        parameters:
        - name: "beanFactory"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.beans.factory.support.DefaultListableBeanFactory"
            uuid: "<init>_defaultListableBeanFactory1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebApplicationContext"
        parameters:
        - name: "beanFactory"
          value:
            sapientType: "UNKNOWN"
            valueType: "org.springframework.beans.factory.support.DefaultListableBeanFactory"
            uuid: "<init>_defaultListableBeanFactory1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebApplicationContext"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "REAL"
      valueType: "org.springframework.util.ObjectUtils"
      uuid: "uuid1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: ""
      valueType: "java.lang.String"
      uuid: "<init>_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "THIS"
      valueType: "org.springframework.context.support.AbstractApplicationContext"
      uuid: "targetClassObject"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "REAL"
      valueType: "org.springframework.util.ObjectUtils"
      uuid: "uuid2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: ""
      valueType: "java.lang.String"
      uuid: "<init>_string2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "THIS"
      valueType: "org.springframework.context.support.AbstractApplicationContext"
      uuid: "targetClassObject"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid4"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.beans.factory.support.DefaultListableBeanFactory"
      uuid: "<init>_defaultListableBeanFactory1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "BeanFactory must not be null"
      valueType: "java.lang.String"
      uuid: "uuid3"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.StandardReactiveWebEnvironment"
        parameters: []
        privateConstructor: false
        createdByTargetCode: true
      suggestedContent: !<new>
        target: "org.springframework.boot.web.reactive.context.StandardReactiveWebEnvironment"
        parameters: []
        privateConstructor: false
        createdByTargetCode: true
      valueType: "org.springframework.boot.web.reactive.context.StandardReactiveWebEnvironment"
      uuid: "createEnvironment_standardReactiveWebEnvironment1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
- method:
    name: "getResourceByPath"
    signature: "getResourceByPath(java.lang.String) : org.springframework.core.io.Resource"
    instructionFingerprint: "7F61740FEEBA55500608466E9A028119"
  paths:
  - pathId: "path1"
    testPathName: "getResourceByPathTest"
    constructorSignature: "<init>(org.springframework.beans.factory.support.DefaultListableBeanFactory)\
      \ : void"
    filledByUser: false
    modelFingerprint: "A7866D2641484C724F7FB7192356FF77"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "F76105DA44E97FAEE985C76F5A1EAB38"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "path"
      modelFingerprint: "E5D8046366728D2A3FFE7D3C8E23C101"
      index: 2
      ignored: false
      valueUuid: "getResourceByPath_string1"
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "ObjectUtils"
      modelFingerprint: "A1E30B97FAC8A3C35470453587802A1C"
      index: 3
      ignored: false
      valueUuid: "uuid5"
      methodExercised:
        target: "org.springframework.util.ObjectUtils"
        name: "identityToString"
        parameters:
        - name: "obj"
          valueUuid: "targetClassObject"
        signature: "identityToString(AbstractApplicationContext): String"
        returnValueUuid: "<init>_string1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "ObjectUtils"
      modelFingerprint: "A1E30B97FAC8A3C35470453587802A1C"
      index: 4
      ignored: false
      valueUuid: "uuid6"
      methodExercised:
        target: "org.springframework.util.ObjectUtils"
        name: "identityToString"
        parameters:
        - name: "obj"
          valueUuid: "targetClassObject"
        signature: "identityToString(AbstractApplicationContext): String"
        returnValueUuid: "<init>_string2"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "D507F26D7508EE01F46981E90D5D685A"
      index: 5
      ignored: false
      valueUuid: "uuid8"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_defaultListableBeanFactory1"
        - name: "message"
          valueUuid: "uuid7"
        signature: "notNull(DefaultListableBeanFactory,String): void"
        returnValueUuid: "<init>_void1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "9F576C1346E9C1C0C51890045FD2050A"
      index: 6
      ignored: false
      valueUuid: "getResourceByPath_filteredReactiveWebContextResource1"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "46d033a6-8edb-31ce-997e-289f3c60e900"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebApplicationContext"
        parameters:
        - name: "beanFactory"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.beans.factory.support.DefaultListableBeanFactory"
            uuid: "<init>_defaultListableBeanFactory1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebApplicationContext"
        parameters:
        - name: "beanFactory"
          value:
            sapientType: "UNKNOWN"
            valueType: "org.springframework.beans.factory.support.DefaultListableBeanFactory"
            uuid: "<init>_defaultListableBeanFactory1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebApplicationContext"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "path1"
      valueType: "java.lang.String"
      uuid: "getResourceByPath_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "REAL"
      valueType: "org.springframework.util.ObjectUtils"
      uuid: "uuid5"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: ""
      valueType: "java.lang.String"
      uuid: "<init>_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "THIS"
      valueType: "org.springframework.context.support.AbstractApplicationContext"
      uuid: "targetClassObject"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "REAL"
      valueType: "org.springframework.util.ObjectUtils"
      uuid: "uuid6"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: ""
      valueType: "java.lang.String"
      uuid: "<init>_string2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "THIS"
      valueType: "org.springframework.context.support.AbstractApplicationContext"
      uuid: "targetClassObject"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid8"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.beans.factory.support.DefaultListableBeanFactory"
      uuid: "<init>_defaultListableBeanFactory1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "BeanFactory must not be null"
      valueType: "java.lang.String"
      uuid: "uuid7"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.FilteredReactiveWebContextResource"
        parameters:
        - name: "path"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "path1"
            valueType: "java.lang.String"
            uuid: "getResourceByPath_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: true
      suggestedContent: !<new>
        target: "org.springframework.boot.web.reactive.context.FilteredReactiveWebContextResource"
        parameters:
        - name: "path"
          value:
            sapientType: "BASIC"
            valueType: "java.lang.String"
            uuid: "getResourceByPath_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: true
      valueType: "org.springframework.boot.web.reactive.context.FilteredReactiveWebContextResource"
      uuid: "getResourceByPath_filteredReactiveWebContextResource1"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
