---
modelFingerprint: "6BD2972C6E6C864DBA3F83550CDFFA2A"
targetClass:
  fullClassName: "org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebApplicationContext"
methods:
- method:
    name: "createEnvironment"
    sourceCodeSignature: "ConfigurableEnvironment createEnvironment()"
    returnType: "org.springframework.core.env.ConfigurableEnvironment"
    instructionFingerprint: "F465B788A11E71966B69DB17337B92D3"
  paths:
  - pathId: "path1"
    testPathName: "createEnvironmentTest"
    constructorSignature: "<init>(org.springframework.beans.factory.support.DefaultListableBeanFactory)\
      \ : void"
    modelFingerprint: "989AFC92478D7FEAD74E4AA76C07C065"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "B0A90836C43A241A6B0C34A0C3428CCA"
      valueUuid: "target"
    - type: "STATIC"
      name: "ObjectUtils.class.real"
      modelFingerprint: "BC4AAEAC8A7791F702A9EF3850F9E072"
      valueUuid: "ObjectUtils.class.real"
      methodExercised:
        expression: "identityToString(obj:targetClassObject):string"
        staticAccess: true
    - type: "STATIC"
      name: "ObjectUtils.class.real"
      modelFingerprint: "BC4AAEAC8A7791F702A9EF3850F9E072"
      valueUuid: "ObjectUtils.class.real"
      methodExercised:
        expression: "identityToString(obj:targetClassObject):string2"
        staticAccess: true
    - type: "STATIC"
      name: "Assert.class"
      modelFingerprint: "9C8FB2E949BB34E406BE754D9450327D"
      valueUuid: "Assert.class"
      methodExercised:
        expression: "notNull(object:beanFactory,message:uniqueUuid1):void"
        staticAccess: true
    - type: "RESULT"
      name: "result"
      modelFingerprint: "FA0BE8E75AF070908BF8A236417E0478"
      valueUuid: "standardReactiveWebEnvironment"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebApplicationContext"
        parameters:
        - name: "beanFactory"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.beans.factory.support.DefaultListableBeanFactory"
            uuid: "beanFactory"
      valueType: "org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebApplicationContext"
      uuid: "target"
    - sapientType: "REAL"
      valueType: "org.springframework.util.ObjectUtils"
      uuid: "ObjectUtils.class.real"
    - sapientType: "BASIC"
      content: !<regular>
        value: ""
      valueType: "java.lang.String"
      uuid: "string"
    - sapientType: "THIS"
      valueType: "org.springframework.context.support.AbstractApplicationContext"
      uuid: "targetClassObject"
      fixed: true
    - sapientType: "REAL"
      valueType: "org.springframework.util.ObjectUtils"
      uuid: "ObjectUtils.class.real"
    - sapientType: "BASIC"
      content: !<regular>
        value: ""
      valueType: "java.lang.String"
      uuid: "string2"
    - sapientType: "THIS"
      valueType: "org.springframework.context.support.AbstractApplicationContext"
      uuid: "targetClassObject"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "Assert.class"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.beans.factory.support.DefaultListableBeanFactory"
      uuid: "beanFactory"
    - sapientType: "BASIC"
      content: !<regular>
        value: "BeanFactory must not be null"
      valueType: "java.lang.String"
      uuid: "uniqueUuid1"
      fixed: true
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.StandardReactiveWebEnvironment"
        parameters: []
      valueType: "org.springframework.boot.web.reactive.context.StandardReactiveWebEnvironment"
      uuid: "standardReactiveWebEnvironment"
      fixed: true
- method:
    name: "getResourceByPath"
    sourceCodeSignature: "Resource getResourceByPath(String path)"
    returnType: "org.springframework.core.io.Resource"
    parameters:
    - name: "path"
      type: "java.lang.String"
    instructionFingerprint: "7F61740FEEBA55500608466E9A028119"
  paths:
  - pathId: "path1"
    testPathName: "getResourceByPathTest"
    constructorSignature: "<init>(org.springframework.beans.factory.support.DefaultListableBeanFactory)\
      \ : void"
    modelFingerprint: "D39B4CAC25BEC80E616B06704157866F"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "B0A90836C43A241A6B0C34A0C3428CCA"
      valueUuid: "target"
    - type: "INPUT"
      name: "path"
      modelFingerprint: "CCCA5C8EB56E398E3BD20AA7A3D33AEC"
      valueUuid: "path"
    - type: "STATIC"
      name: "ObjectUtils.class.real"
      modelFingerprint: "BC4AAEAC8A7791F702A9EF3850F9E072"
      valueUuid: "ObjectUtils.class.real"
      methodExercised:
        expression: "identityToString(obj:targetClassObject):string"
        staticAccess: true
    - type: "STATIC"
      name: "ObjectUtils.class.real"
      modelFingerprint: "BC4AAEAC8A7791F702A9EF3850F9E072"
      valueUuid: "ObjectUtils.class.real"
      methodExercised:
        expression: "identityToString(obj:targetClassObject):string2"
        staticAccess: true
    - type: "STATIC"
      name: "Assert.class"
      modelFingerprint: "9C8FB2E949BB34E406BE754D9450327D"
      valueUuid: "Assert.class"
      methodExercised:
        expression: "notNull(object:beanFactory,message:uniqueUuid2):void"
        staticAccess: true
    - type: "RESULT"
      name: "result"
      modelFingerprint: "C73EE5697FD19C444FE4C2586F343123"
      valueUuid: "filteredReactiveWebContextResource"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebApplicationContext"
        parameters:
        - name: "beanFactory"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.beans.factory.support.DefaultListableBeanFactory"
            uuid: "beanFactory"
      valueType: "org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebApplicationContext"
      uuid: "target"
    - sapientType: "BASIC"
      content: !<regular>
        value: "path1"
      valueType: "java.lang.String"
      uuid: "path"
    - sapientType: "REAL"
      valueType: "org.springframework.util.ObjectUtils"
      uuid: "ObjectUtils.class.real"
    - sapientType: "BASIC"
      content: !<regular>
        value: ""
      valueType: "java.lang.String"
      uuid: "string"
    - sapientType: "THIS"
      valueType: "org.springframework.context.support.AbstractApplicationContext"
      uuid: "targetClassObject"
      fixed: true
    - sapientType: "REAL"
      valueType: "org.springframework.util.ObjectUtils"
      uuid: "ObjectUtils.class.real"
    - sapientType: "BASIC"
      content: !<regular>
        value: ""
      valueType: "java.lang.String"
      uuid: "string2"
    - sapientType: "THIS"
      valueType: "org.springframework.context.support.AbstractApplicationContext"
      uuid: "targetClassObject"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "Assert.class"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.beans.factory.support.DefaultListableBeanFactory"
      uuid: "beanFactory"
    - sapientType: "BASIC"
      content: !<regular>
        value: "BeanFactory must not be null"
      valueType: "java.lang.String"
      uuid: "uniqueUuid2"
      fixed: true
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.FilteredReactiveWebContextResource"
        parameters:
        - name: "path"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "path1"
            valueType: "java.lang.String"
            uuid: "path"
      valueType: "org.springframework.boot.web.reactive.context.FilteredReactiveWebContextResource"
      uuid: "filteredReactiveWebContextResource"
      fixed: true
