---
modelFingerprint: "F2CF88D9B99F6A27D7634211BD76EE8B"
methods:
- method:
    name: "doGetActiveProfilesProperty"
    signature: "doGetActiveProfilesProperty() : java.lang.String"
    sourceCodeSignature: "String doGetActiveProfilesProperty()"
    instructionFingerprint: "137D807D65466C377F71910631A85488"
  paths:
  - pathId: "path1"
    testPathName: "doGetActiveProfilesPropertyTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "C650CE5A78515B09055E6639299802C4"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "8EDA3F2AE365AC99A4FDAA03D44C0B66"
      index: 2
      valueUuid: "doGetActiveProfilesProperty_string1"
    uuid: "de774194-de49-370c-8c3d-0b1e904baef9"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.ApplicationReactiveWebEnvironment"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.web.reactive.context.ApplicationReactiveWebEnvironment"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "NULL"
      valueType: "java.lang.String"
      uuid: "doGetActiveProfilesProperty_string1"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
- method:
    name: "doGetDefaultProfilesProperty"
    signature: "doGetDefaultProfilesProperty() : java.lang.String"
    sourceCodeSignature: "String doGetDefaultProfilesProperty()"
    instructionFingerprint: "7FC870E71BD8CA32F80246D349D66538"
  paths:
  - pathId: "path1"
    testPathName: "doGetDefaultProfilesPropertyTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "C650CE5A78515B09055E6639299802C4"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "8EDA3F2AE365AC99A4FDAA03D44C0B66"
      index: 2
      valueUuid: "doGetDefaultProfilesProperty_string1"
    uuid: "8851a08f-f7e0-376c-a9da-76a0fc519c42"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.ApplicationReactiveWebEnvironment"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.web.reactive.context.ApplicationReactiveWebEnvironment"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "NULL"
      valueType: "java.lang.String"
      uuid: "doGetDefaultProfilesProperty_string1"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
- method:
    name: "createPropertyResolver"
    signature: "createPropertyResolver(org.springframework.core.env.MutablePropertySources)\
      \ : org.springframework.core.env.ConfigurablePropertyResolver"
    sourceCodeSignature: "ConfigurablePropertyResolver createPropertyResolver(MutablePropertySources\
      \ propertySources)"
    instructionFingerprint: "B00607FDC96C1479B907A109A8D6BBB0"
  paths:
  - pathId: "path1"
    testPathName: "createPropertyResolverTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "6F2780C82AAC68C01F27FB42D69507E5"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "propertySources"
      modelFingerprint: "ECC118C98697ECA905ACD56377FB455D"
      index: 2
      valueUuid: "createPropertyResolver_mutablePropertySources1"
    - type: "STATIC"
      name: "ConfigurationPropertySources"
      modelFingerprint: "4ACF67E0DFC0166B2A7A9E4A0BD27DE6"
      index: 3
      valueUuid: "uuid1"
      methodExercised:
        target: "org.springframework.boot.context.properties.source.ConfigurationPropertySources"
        name: "createPropertyResolver"
        parameters:
        - name: "propertySources"
          valueUuid: "createPropertyResolver_mutablePropertySources1"
        signature: "createPropertyResolver(MutablePropertySources): ConfigurablePropertyResolver"
        returnValueUuid: "createPropertyResolver_configurablePropertyResolver1"
        access: 9
    - type: "RESULT"
      name: "result"
      modelFingerprint: "4E89ED0894044493A5A3A2AFE5AB727E"
      index: 4
      valueUuid: "createPropertyResolver_configurablePropertyResolver1"
    uuid: "cd721531-c35e-340b-93ef-a0cc3cccaba6"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.ApplicationReactiveWebEnvironment"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.web.reactive.context.ApplicationReactiveWebEnvironment"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.MutablePropertySources"
      uuid: "createPropertyResolver_mutablePropertySources1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertySources"
      uuid: "uuid1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.ConfigurablePropertyResolver"
      uuid: "createPropertyResolver_configurablePropertyResolver1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.MutablePropertySources"
      uuid: "createPropertyResolver_mutablePropertySources1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.ConfigurablePropertyResolver"
      uuid: "createPropertyResolver_configurablePropertyResolver1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
