---
modelFingerprint: "C9B57D6B4ADBB12ED22992B752B0CF80"
methods:
- method:
    name: "createEnvironment"
    returnType: "org.springframework.core.env.ConfigurableEnvironment"
    signature: "createEnvironment() : org.springframework.core.env.ConfigurableEnvironment"
    instructionFingerprint: "F465B788A11E71966B69DB17337B92D3"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "createEnvironmentTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(org.springframework.beans.factory.support.DefaultListableBeanFactory)\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "E931F90A0922D736E7925AB21B0F6CCC"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "F76105DA44E97FAEE985C76F5A1EAB38"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.web.reactive.context.GenericReactiveWebApplicationContext"
          parameters:
          - name: "beanFactory"
            value:
              sapientType: "MOCK"
              valueType: "org.springframework.beans.factory.support.DefaultListableBeanFactory"
              uuid: "<init>_defaultListableBeanFactory1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.web.reactive.context.GenericReactiveWebApplicationContext"
          parameters:
          - name: "beanFactory"
            value:
              sapientType: "UNKNOWN"
              valueType: "org.springframework.beans.factory.support.DefaultListableBeanFactory"
              uuid: "<init>_defaultListableBeanFactory1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.web.reactive.context.GenericReactiveWebApplicationContext"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "ObjectUtils"
      modelFingerprint: "A1E30B97FAC8A3C35470453587802A1C"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "REAL"
        valueType: "org.springframework.util.ObjectUtils"
        uuid: "org.springframework.util.ObjectUtils"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.ObjectUtils"
        name: "identityToString"
        parameters:
        - name: "obj"
          value:
            sapientType: "THIS"
            valueType: "org.springframework.context.support.AbstractApplicationContext"
            uuid: "targetClassObject"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "identityToString(AbstractApplicationContext): String"
        returnValue:
          sapientType: "BASIC"
          content: !<regular>
            value: ""
          valueType: "java.lang.String"
          uuid: "<init>_string1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "ObjectUtils"
      modelFingerprint: "A1E30B97FAC8A3C35470453587802A1C"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "REAL"
        valueType: "org.springframework.util.ObjectUtils"
        uuid: "org.springframework.util.ObjectUtils"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.ObjectUtils"
        name: "identityToString"
        parameters:
        - name: "obj"
          value:
            sapientType: "THIS"
            valueType: "org.springframework.context.support.AbstractApplicationContext"
            uuid: "targetClassObject"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "identityToString(AbstractApplicationContext): String"
        returnValue:
          sapientType: "BASIC"
          content: !<regular>
            value: ""
          valueType: "java.lang.String"
          uuid: "<init>_string2"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "D507F26D7508EE01F46981E90D5D685A"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.beans.factory.support.DefaultListableBeanFactory"
            uuid: "<init>_defaultListableBeanFactory1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "BeanFactory must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(DefaultListableBeanFactory,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "<init>_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "796795679E3C0F2DD38DF229E1CC991B"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.web.reactive.context.StandardReactiveWebEnvironment"
          parameters: []
          privateConstructor: false
          createdByTargetCode: true
        suggestedContent: !<new>
          target: "org.springframework.boot.web.reactive.context.StandardReactiveWebEnvironment"
          parameters: []
          privateConstructor: false
          createdByTargetCode: true
        valueType: "org.springframework.boot.web.reactive.context.StandardReactiveWebEnvironment"
        uuid: "createEnvironment_standardReactiveWebEnvironment1"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "710fd138-f016-39a0-9d47-0163cb889999"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "getResourceByPath"
    returnType: "org.springframework.core.io.Resource"
    signature: "getResourceByPath(java.lang.String) : org.springframework.core.io.Resource"
    instructionFingerprint: "7F61740FEEBA55500608466E9A028119"
    parametersTypes:
    - "java.lang.String"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getResourceByPathTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(org.springframework.beans.factory.support.DefaultListableBeanFactory)\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "18DE7D063EB9A26B1AE0BCA3C1A96E3C"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "F76105DA44E97FAEE985C76F5A1EAB38"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.web.reactive.context.GenericReactiveWebApplicationContext"
          parameters:
          - name: "beanFactory"
            value:
              sapientType: "MOCK"
              valueType: "org.springframework.beans.factory.support.DefaultListableBeanFactory"
              uuid: "<init>_defaultListableBeanFactory1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.web.reactive.context.GenericReactiveWebApplicationContext"
          parameters:
          - name: "beanFactory"
            value:
              sapientType: "UNKNOWN"
              valueType: "org.springframework.beans.factory.support.DefaultListableBeanFactory"
              uuid: "<init>_defaultListableBeanFactory1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.web.reactive.context.GenericReactiveWebApplicationContext"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "path"
      modelFingerprint: "E5D8046366728D2A3FFE7D3C8E23C101"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "BASIC"
        content: !<regular>
          value: "path1"
        valueType: "java.lang.String"
        uuid: "getResourceByPath_string1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "ObjectUtils"
      modelFingerprint: "A1E30B97FAC8A3C35470453587802A1C"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "REAL"
        valueType: "org.springframework.util.ObjectUtils"
        uuid: "org.springframework.util.ObjectUtils"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.ObjectUtils"
        name: "identityToString"
        parameters:
        - name: "obj"
          value:
            sapientType: "THIS"
            valueType: "org.springframework.context.support.AbstractApplicationContext"
            uuid: "targetClassObject"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "identityToString(AbstractApplicationContext): String"
        returnValue:
          sapientType: "BASIC"
          content: !<regular>
            value: ""
          valueType: "java.lang.String"
          uuid: "<init>_string1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "ObjectUtils"
      modelFingerprint: "A1E30B97FAC8A3C35470453587802A1C"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "REAL"
        valueType: "org.springframework.util.ObjectUtils"
        uuid: "org.springframework.util.ObjectUtils"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.ObjectUtils"
        name: "identityToString"
        parameters:
        - name: "obj"
          value:
            sapientType: "THIS"
            valueType: "org.springframework.context.support.AbstractApplicationContext"
            uuid: "targetClassObject"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "identityToString(AbstractApplicationContext): String"
        returnValue:
          sapientType: "BASIC"
          content: !<regular>
            value: ""
          valueType: "java.lang.String"
          uuid: "<init>_string2"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "D507F26D7508EE01F46981E90D5D685A"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.beans.factory.support.DefaultListableBeanFactory"
            uuid: "<init>_defaultListableBeanFactory1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "BeanFactory must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(DefaultListableBeanFactory,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "<init>_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "9F576C1346E9C1C0C51890045FD2050A"
      index: 6
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.web.reactive.context.FilteredReactiveWebContextResource"
          parameters:
          - name: "path"
            value:
              sapientType: "BASIC"
              content: !<regular>
                value: "path1"
              valueType: "java.lang.String"
              uuid: "getResourceByPath_string1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: true
        suggestedContent: !<new>
          target: "org.springframework.boot.web.reactive.context.FilteredReactiveWebContextResource"
          parameters:
          - name: "path"
            value:
              sapientType: "BASIC"
              valueType: "java.lang.String"
              uuid: "getResourceByPath_string1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: true
        valueType: "org.springframework.boot.web.reactive.context.FilteredReactiveWebContextResource"
        uuid: "getResourceByPath_filteredReactiveWebContextResource1"
        fixed: true
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "46d033a6-8edb-31ce-997e-289f3c60e900"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
