---
modelFingerprint: "0A4331214B35B6D0CE2DBE04937BE45B"
targetClass:
  fullClassName: "org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContextFactory"
methods:
- method:
    name: "getEnvironmentType"
    sourceCodeSignature: "Class<? extends ConfigurableEnvironment> getEnvironmentType(WebApplicationType\
      \ webApplicationType)"
    returnType: "java.lang.Class"
    genericReturnType: "? extends org.springframework.core.env.ConfigurableEnvironment"
    parameters:
    - name: "webApplicationType"
      type: "org.springframework.boot.WebApplicationType"
    instructionFingerprint: "5D9A344C4D915EFE911E2ABF39D9BC37"
  paths:
  - pathId: "path1"
    testPathName: "getEnvironmentTypeWhenWebApplicationTypeNotEqualsWebApplicationTypeREACTIVE"
    constructorSignature: "<init>() : void"
    modelFingerprint: "55999EE60A42CAA222A658CA720F6A30"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "830F43FA9F3CF78152E96597C66C0CA7"
      valueUuid: "webApplicationType"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "6E032A22C09FD07D5F1F19718D09D592"
      valueUuid: "class"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContextFactory"
        parameters: []
      valueType: "org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContextFactory"
      uuid: "target"
    - sapientType: "ENUM"
      content: !<regular>
        value: "NONE"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "webApplicationType"
    - sapientType: "NULL"
      valueType: "java.lang.Class"
      genericValueType: "? extends org.springframework.core.env.ConfigurableEnvironment"
      uuid: "class"
      fixed: true
    branches:
    - lineNumber: 37
      expression: "webApplicationType != WebApplicationType.REACTIVE"
      range: "(37,11)-(37,59)"
      evaluatedAs: true
  - pathId: "path2"
    testPathName: "getEnvironmentTypeWhenWebApplicationTypeEqualsWebApplicationTypeREACTIVE"
    constructorSignature: "<init>() : void"
    modelFingerprint: "04C3689EAF423263E6C6CD326E92A776"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "39F8607E22C91A68F4B61AF803A2F157"
      valueUuid: "webApplicationType"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "B08B6D3BC06CC65D52978973F2541F8F"
      valueUuid: "expectedResult"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContextFactory"
        parameters: []
      valueType: "org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContextFactory"
      uuid: "target"
    - sapientType: "ENUM"
      content: !<regular>
        value: "REACTIVE"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "webApplicationType"
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.web.reactive.context.ApplicationReactiveWebEnvironment"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.web.reactive.context.ApplicationReactiveWebEnvironment"
      uuid: "expectedResult"
      fixed: true
    branches:
    - lineNumber: 37
      expression: "webApplicationType != WebApplicationType.REACTIVE"
      range: "(37,11)-(37,59)"
      evaluatedAs: false
- method:
    name: "createEnvironment"
    sourceCodeSignature: "ConfigurableEnvironment createEnvironment(WebApplicationType\
      \ webApplicationType)"
    returnType: "org.springframework.core.env.ConfigurableEnvironment"
    parameters:
    - name: "webApplicationType"
      type: "org.springframework.boot.WebApplicationType"
    instructionFingerprint: "2569ABE589B0C094313837F511916E12"
  paths:
  - pathId: "path1"
    testPathName: "createEnvironmentWhenWebApplicationTypeNotEqualsWebApplicationTypeREACTIVE"
    constructorSignature: "<init>() : void"
    modelFingerprint: "36B0FB5620E797571F0E18777C822C2A"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "830F43FA9F3CF78152E96597C66C0CA7"
      valueUuid: "webApplicationType"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "07C617B6F1D348BCC0225644494DDADD"
      valueUuid: "configurableEnvironment"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContextFactory"
        parameters: []
      valueType: "org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContextFactory"
      uuid: "target"
    - sapientType: "ENUM"
      content: !<regular>
        value: "NONE"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "webApplicationType"
    - sapientType: "NULL"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "configurableEnvironment"
      fixed: true
    branches:
    - lineNumber: 42
      expression: "webApplicationType != WebApplicationType.REACTIVE"
      range: "(42,11)-(42,59)"
      evaluatedAs: true
  - pathId: "path2"
    testPathName: "createEnvironmentWhenWebApplicationTypeEqualsWebApplicationTypeREACTIVE"
    constructorSignature: "<init>() : void"
    modelFingerprint: "C77F7A37118A96631661612D983DAA82"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "39F8607E22C91A68F4B61AF803A2F157"
      valueUuid: "webApplicationType"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "7AD17BA46461927E47A0305AFCDD2F42"
      valueUuid: "applicationReactiveWebEnvironment"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContextFactory"
        parameters: []
      valueType: "org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContextFactory"
      uuid: "target"
    - sapientType: "ENUM"
      content: !<regular>
        value: "REACTIVE"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "webApplicationType"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.ApplicationReactiveWebEnvironment"
        parameters: []
      valueType: "org.springframework.boot.web.reactive.context.ApplicationReactiveWebEnvironment"
      uuid: "applicationReactiveWebEnvironment"
      fixed: true
    branches:
    - lineNumber: 42
      expression: "webApplicationType != WebApplicationType.REACTIVE"
      range: "(42,11)-(42,59)"
      evaluatedAs: false
- method:
    name: "create"
    sourceCodeSignature: "ConfigurableApplicationContext create(WebApplicationType\
      \ webApplicationType)"
    returnType: "org.springframework.context.ConfigurableApplicationContext"
    parameters:
    - name: "webApplicationType"
      type: "org.springframework.boot.WebApplicationType"
    instructionFingerprint: "8CBA407B2F33E1AC1A7DF77CBB7E4C89"
  paths:
  - pathId: "path1"
    testPathName: "createWhenWebApplicationTypeNotEqualsWebApplicationTypeREACTIVE"
    constructorSignature: "<init>() : void"
    modelFingerprint: "6E69E2FB7D52AD33A01E1FA6712E45EC"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "830F43FA9F3CF78152E96597C66C0CA7"
      valueUuid: "webApplicationType"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "659CCF3F56A72A794F669DD1D72B1498"
      valueUuid: "configurableApplicationContext"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContextFactory"
        parameters: []
      valueType: "org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContextFactory"
      uuid: "target"
    - sapientType: "ENUM"
      content: !<regular>
        value: "NONE"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "webApplicationType"
    - sapientType: "NULL"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "configurableApplicationContext"
      fixed: true
    branches:
    - lineNumber: 47
      expression: "webApplicationType != WebApplicationType.REACTIVE"
      range: "(47,11)-(47,59)"
      evaluatedAs: true
  - pathId: "path2"
    testPathName: "createWhenAotDetectorNotUseGeneratedArtifacts"
    constructorSignature: "<init>() : void"
    modelFingerprint: "051D0EE786EB7A74D17521F3DFD65FD3"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "webApplicationType"
      modelFingerprint: "39F8607E22C91A68F4B61AF803A2F157"
      valueUuid: "webApplicationType"
    - type: "STATIC"
      name: "AotDetector.class.real"
      modelFingerprint: "A651F35C9CB1BB4329EA23C459C95680"
      valueUuid: "AotDetector.class.real"
      methodExercised:
        expression: "useGeneratedArtifacts():boolean1"
        staticAccess: true
    - type: "RESULT"
      name: "result"
      modelFingerprint: "37A2A5F4AACCC766CE58C700B4DB2BC0"
      valueUuid: "annotationConfigReactiveWebServerApplicationContext"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContextFactory"
        parameters: []
      valueType: "org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContextFactory"
      uuid: "target"
    - sapientType: "ENUM"
      content: !<regular>
        value: "REACTIVE"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "webApplicationType"
    - sapientType: "REAL"
      valueType: "org.springframework.aot.AotDetector"
      uuid: "AotDetector.class.real"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "boolean1"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebServerApplicationContext"
        parameters: []
      valueType: "org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebServerApplicationContext"
      uuid: "annotationConfigReactiveWebServerApplicationContext"
      fixed: true
    branches:
    - lineNumber: 47
      expression: "webApplicationType != WebApplicationType.REACTIVE"
      range: "(47,11)-(47,59)"
      evaluatedAs: false
    - lineNumber: 51
      expression: "!AotDetector.useGeneratedArtifacts()"
      range: "(51,7)-(51,42)"
      evaluatedAs: true
      internalMethodName: "createContext"
