---
modelFingerprint: "FA44963318AD930349B3DAAE8F341155"
targetClass:
  fullClassName: "org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration"
methods:
- method:
    name: "configure"
    sourceCodeSignature: "void configure(WebAppContext context)"
    returnType: "void"
    throwsExceptions:
    - "java.lang.Exception"
    parameters:
    - name: "context"
      type: "org.eclipse.jetty.ee10.webapp.WebAppContext"
    instructionFingerprint: "CDEAFFF41AABCEC269CBEE424A75C924"
  paths:
  - pathId: "path1"
    testPathName: "configureWhenThisInitializersIsNotEmpty"
    constructorSignature: "<init>(org.springframework.boot.web.servlet.ServletContextInitializer[])\
      \ : void"
    modelFingerprint: "8D61809B8EACCAFBD694E0A868216A28"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "98F8FE85C83FD2699CEB5CD613367519"
      valueUuid: "target"
    - type: "INPUT"
      name: "context"
      modelFingerprint: "72654B36C04778F619F8E4F2BF4C3EAB"
      valueUuid: "context"
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "2AF66F08D8A522264B1E672E5177CFCE"
      valueUuid: "classMatcher2"
      methodExercised:
        expression: "asImmutable():classMatcher3"
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "2AF66F08D8A522264B1E672E5177CFCE"
      valueUuid: "classMatcher5"
      methodExercised:
        expression: "asImmutable():classMatcher6"
    - type: "STATIC"
      name: "Assert.class"
      modelFingerprint: "5206EBD262ED88DCA98FD6DF42530AA8"
      valueUuid: "Assert.class"
      methodExercised:
        expression: "notNull(object:initializers,message:uniqueUuid1):void"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      name: "context"
      modelFingerprint: "57FEDCEF72CF499534D62D87520AE8B8"
      valueUuid: "context"
      methodExercised:
        expression: "getClassLoader():classLoader2"
    - type: "LOCAL_VARIABLE"
      name: "context"
      modelFingerprint: "EDFA760CB3A9CF7E7A0A4A99FCADD353"
      valueUuid: "context"
      methodExercised:
        expression: "getContext():servletContextHandler.ServletScopedContext"
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "6160A292451599DA39238BECE079CC06"
      valueUuid: "servletContextHandler.ServletScopedContext"
      methodExercised:
        expression: "setExtendedListenerTypes(b:uniqueUuid2):void3"
    - type: "LOCAL_VARIABLE"
      name: "context"
      modelFingerprint: "BEDA9E833E147F317F9B822A0BB359E3"
      valueUuid: "context"
      methodExercised:
        expression: "getServletContext():servletContext"
    - type: "LOCAL_VARIABLE"
      name: "initializer"
      modelFingerprint: "EAE1F525638F5F9223FF3314DF29CF93"
      valueUuid: "servletContextInitializer"
      methodExercised:
        expression: "onStartup(servletContext:servletContext):void4"
        throwsExceptions:
        - "jakarta.servlet.ServletException"
    - type: "LOCAL_VARIABLE"
      name: "context"
      modelFingerprint: "EDFA760CB3A9CF7E7A0A4A99FCADD353"
      valueUuid: "context"
      methodExercised:
        expression: "getContext():servletContextHandler.ServletScopedContext2"
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "1C2762377E9FED0D9DE64C70D33A1F6E"
      valueUuid: "servletContextHandler.ServletScopedContext2"
      methodExercised:
        expression: "setExtendedListenerTypes(b:uniqueUuid3):void5"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.util.List.copyOf(java.util.List) : java.util.List"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration"
        parameters:
        - name: "initializers"
          value:
            sapientType: "ARRAY"
            content: !<array>
              values:
                0:
                  sapientType: "MOCK"
                  valueType: "org.springframework.boot.web.servlet.ServletContextInitializer"
                  uuid: "servletContextInitializer"
            valueType: "org.springframework.boot.web.servlet.ServletContextInitializer[]"
            uuid: "initializers"
      valueType: "org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.eclipse.jetty.ee10.webapp.WebAppContext"
      uuid: "context"
    - sapientType: "COLLECTION"
      content: !<collection>
        collectionClass: "org.eclipse.jetty.ee10.webapp.ClassMatcher"
        parameters: []
        values: []
      valueType: "org.eclipse.jetty.ee10.webapp.ClassMatcher"
      uuid: "classMatcher2"
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "org.eclipse.jetty.ee10.webapp.ClassMatcher"
      uuid: "classMatcher3"
      collectionUuid: "classMatcher2"
    - sapientType: "COLLECTION"
      content: !<collection>
        collectionClass: "org.eclipse.jetty.ee10.webapp.ClassMatcher"
        parameters: []
        values: []
      valueType: "org.eclipse.jetty.ee10.webapp.ClassMatcher"
      uuid: "classMatcher5"
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "org.eclipse.jetty.ee10.webapp.ClassMatcher"
      uuid: "classMatcher6"
      collectionUuid: "classMatcher5"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "Assert.class"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "ARRAY"
      content: !<array>
        values:
          0:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.web.servlet.ServletContextInitializer"
            uuid: "servletContextInitializer"
      valueType: "org.springframework.boot.web.servlet.ServletContextInitializer[]"
      uuid: "initializers"
    - sapientType: "BASIC"
      content: !<regular>
        value: "Initializers must not be null"
      valueType: "java.lang.String"
      uuid: "uniqueUuid1"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.eclipse.jetty.ee10.webapp.WebAppContext"
      uuid: "context"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.lang.ClassLoader"
        method: "getPlatformClassLoader"
        methodParameters: []
      valueType: "java.lang.ClassLoader"
      uuid: "classLoader2"
    - sapientType: "MOCK"
      valueType: "org.eclipse.jetty.ee10.webapp.WebAppContext"
      uuid: "context"
    - sapientType: "MOCK"
      valueType: "org.eclipse.jetty.ee10.servlet.ServletContextHandler$ServletScopedContext"
      uuid: "servletContextHandler.ServletScopedContext"
    - sapientType: "MOCK"
      valueType: "org.eclipse.jetty.ee10.servlet.ServletContextHandler$ServletScopedContext"
      uuid: "servletContextHandler.ServletScopedContext"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void3"
      fixed: true
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "uniqueUuid2"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.eclipse.jetty.ee10.webapp.WebAppContext"
      uuid: "context"
    - sapientType: "MOCK"
      valueType: "jakarta.servlet.ServletContext"
      uuid: "servletContext"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.servlet.ServletContextInitializer"
      uuid: "servletContextInitializer"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void4"
      fixed: true
    - sapientType: "MOCK"
      valueType: "jakarta.servlet.ServletContext"
      uuid: "servletContext"
    - sapientType: "MOCK"
      valueType: "org.eclipse.jetty.ee10.webapp.WebAppContext"
      uuid: "context"
    - sapientType: "MOCK"
      valueType: "org.eclipse.jetty.ee10.servlet.ServletContextHandler$ServletScopedContext"
      uuid: "servletContextHandler.ServletScopedContext2"
    - sapientType: "MOCK"
      valueType: "org.eclipse.jetty.ee10.servlet.ServletContextHandler$ServletScopedContext"
      uuid: "servletContextHandler.ServletScopedContext2"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void5"
      fixed: true
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "uniqueUuid3"
      fixed: true
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
    branches:
    - lineNumber: 64
      expression: "for-each(this.initializers)"
      range: "(64,49)-(64,65)"
      evaluatedAs: true
      internalMethodName: "callInitializers"
