---
modelFingerprint: "599D3BEB87F077B17782B3D27D12DBD6"
methods:
- method:
    name: "configure"
    signature: "configure(org.eclipse.jetty.ee10.webapp.WebAppContext) : void"
    sourceCodeSignature: "void configure(WebAppContext context)"
    instructionFingerprint: "CDEAFFF41AABCEC269CBEE424A75C924"
  paths:
  - pathId: "path1"
    testPathName: "configureWhenThisInitializersIsNotEmpty"
    constructorSignature: "<init>(org.springframework.boot.web.servlet.ServletContextInitializer[])\
      \ : void"
    modelFingerprint: "5C4B83EC8DCA92D258EF120FD47C84CB"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "6CA0BCBC2FF4309DD37AD2E1A8C97C55"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "context"
      modelFingerprint: "486688BC645F524579C412478C6F3E15"
      index: 2
      valueUuid: "configure_webAppContext1"
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "C3E9D59719C4889A4B682D6BC2E577C8"
      index: 3
      valueUuid: "<init>_classMatcher2"
      methodExercised:
        target: "org.eclipse.jetty.ee10.webapp.ClassMatcher"
        name: "asImmutable"
        parameters: []
        signature: "asImmutable(): ClassMatcher"
        returnValueUuid: "<init>_classMatcher3"
        access: 1
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "E7C10C0FC5229311A30DE4F5E2A02018"
      index: 4
      valueUuid: "<init>_classMatcher5"
      methodExercised:
        target: "org.eclipse.jetty.ee10.webapp.ClassMatcher"
        name: "asImmutable"
        parameters: []
        signature: "asImmutable(): ClassMatcher"
        returnValueUuid: "<init>_classMatcher6"
        access: 1
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "5AA4C0D7424E31D096AD1D23A94D06FA"
      index: 5
      valueUuid: "uuid2"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_servletContextInitializer[]1"
        - name: "message"
          valueUuid: "uuid1"
        signature: "notNull(ServletContextInitializer[],String): void"
        returnValueUuid: "<init>_void1"
        access: 9
    - type: "LOCAL_VARIABLE"
      name: "context"
      modelFingerprint: "E52804293EAE8E7DFC4EAF72F4CEA32E"
      index: 6
      valueUuid: "configure_webAppContext1"
      methodExercised:
        target: "context"
        name: "getClassLoader"
        parameters: []
        signature: "getClassLoader(): ClassLoader"
        returnValueUuid: "configure_classLoader2"
        access: 1
    - type: "LOCAL_VARIABLE"
      name: "context"
      modelFingerprint: "B38AC332DB138A901CB3E2D751773182"
      index: 7
      valueUuid: "configure_webAppContext1"
      methodExercised:
        target: "context"
        name: "getContext"
        parameters: []
        signature: "getContext(): ServletContextHandler$ServletScopedContext"
        returnValueUuid: "callInitializers_servletContextHandler.ServletScopedContext1"
        access: 1
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "E9E15FFD3A5A594B870A39F5E80A1D09"
      index: 8
      valueUuid: "callInitializers_servletContextHandler.ServletScopedContext1"
      methodExercised:
        target: "org.eclipse.jetty.ee10.servlet.ServletContextHandler$ServletScopedContext"
        name: "setExtendedListenerTypes"
        parameters:
        - name: "b"
          valueUuid: "uuid3"
        signature: "setExtendedListenerTypes(boolean): void"
        returnValueUuid: "callInitializers_void1"
        access: 1
    - type: "LOCAL_VARIABLE"
      name: "context"
      modelFingerprint: "954E7F8F8E7D5243FC84026AB306C0CF"
      index: 9
      valueUuid: "configure_webAppContext1"
      methodExercised:
        target: "context"
        name: "getServletContext"
        parameters: []
        signature: "getServletContext(): ServletContext"
        returnValueUuid: "callInitializers_servletContext1"
        access: 1
    - type: "LOCAL_VARIABLE"
      name: "initializer"
      modelFingerprint: "CF8B88515278BFDB0213DE7DC9931D30"
      index: 10
      valueUuid: "uuid4"
      methodExercised:
        target: "initializer"
        name: "onStartup"
        parameters:
        - name: "servletContext"
          valueUuid: "callInitializers_servletContext1"
        throwsExceptions:
        - "jakarta.servlet.ServletException"
        signature: "onStartup(ServletContext): void throws jakarta.servlet.ServletException"
        returnValueUuid: "callInitializers_void2"
        access: 1025
    - type: "LOCAL_VARIABLE"
      name: "context"
      modelFingerprint: "D6814D3A9FA7BE9F6FA83F51AB488996"
      index: 11
      valueUuid: "configure_webAppContext1"
      methodExercised:
        target: "context"
        name: "getContext"
        parameters: []
        signature: "getContext(): ServletContextHandler$ServletScopedContext"
        returnValueUuid: "callInitializers_servletContextHandler.ServletScopedContext2"
        access: 1
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "641F0DDEF92BA7DA75FFCC528B761AFC"
      index: 12
      valueUuid: "callInitializers_servletContextHandler.ServletScopedContext2"
      methodExercised:
        target: "org.eclipse.jetty.ee10.servlet.ServletContextHandler$ServletScopedContext"
        name: "setExtendedListenerTypes"
        parameters:
        - name: "b"
          valueUuid: "uuid5"
        signature: "setExtendedListenerTypes(boolean): void"
        returnValueUuid: "callInitializers_void3"
        access: 1
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 13
      valueUuid: "uuid6"
    uuid: "7798c9e2-958c-3e38-abc1-6b273a0c51d7"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.util.List.copyOf(java.util.List) : java.util.List"
    prover: "LLM"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration"
        parameters:
        - name: "initializers"
          value:
            sapientType: "ARRAY"
            content: !<array>
              values:
                0:
                  sapientType: "MOCK"
                  valueType: "org.springframework.boot.web.servlet.ServletContextInitializer"
                  fixed: false
                  equalsMethodPresent: false
                  explicitCastNeeded: false
            valueType: "org.springframework.boot.web.servlet.ServletContextInitializer[]"
            uuid: "<init>_servletContextInitializer[]1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.eclipse.jetty.ee10.webapp.WebAppContext"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.eclipse.jetty.ee10.webapp.WebAppContext"
      uuid: "configure_webAppContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        collectionClass: "org.eclipse.jetty.ee10.webapp.ClassMatcher"
        parameters: []
        values: []
      valueType: "org.eclipse.jetty.ee10.webapp.ClassMatcher"
      uuid: "<init>_classMatcher2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "org.eclipse.jetty.ee10.webapp.ClassMatcher"
      uuid: "<init>_classMatcher3"
      fixed: false
      collectionUuid: "<init>_classMatcher2"
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        collectionClass: "org.eclipse.jetty.ee10.webapp.ClassMatcher"
        parameters:
        - name: "patterns"
          value:
            sapientType: "NULL"
            valueType: "org.eclipse.jetty.ee10.webapp.ClassMatcher"
            uuid: "<init>_classMatcher4"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        values: []
      valueType: "org.eclipse.jetty.ee10.webapp.ClassMatcher"
      uuid: "<init>_classMatcher5"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "org.eclipse.jetty.ee10.webapp.ClassMatcher"
      uuid: "<init>_classMatcher6"
      fixed: false
      collectionUuid: "<init>_classMatcher5"
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "ARRAY"
      content: !<array>
        values:
          0:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.web.servlet.ServletContextInitializer"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
      valueType: "org.springframework.boot.web.servlet.ServletContextInitializer[]"
      uuid: "<init>_servletContextInitializer[]1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Initializers must not be null"
      valueType: "java.lang.String"
      uuid: "uuid1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.eclipse.jetty.ee10.webapp.WebAppContext"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.eclipse.jetty.ee10.webapp.WebAppContext"
      uuid: "configure_webAppContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.lang.ClassLoader"
        method: "getPlatformClassLoader"
        methodParameters: []
      valueType: "java.lang.ClassLoader"
      uuid: "configure_classLoader2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.eclipse.jetty.ee10.webapp.WebAppContext"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.eclipse.jetty.ee10.webapp.WebAppContext"
      uuid: "configure_webAppContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<method_return_from_value>
        target: "org.eclipse.jetty.ee10.servlet.ServletContextHandler$ServletScopedContext"
        localVariableValue:
          sapientType: "OBJECT"
          content: !<new>
            target: "org.eclipse.jetty.ee10.webapp.WebAppContext"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          valueType: "org.eclipse.jetty.ee10.webapp.WebAppContext"
          uuid: "configure_webAppContext1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        methodParameters: []
        methodName: "getContext"
      valueType: "org.eclipse.jetty.ee10.servlet.ServletContextHandler$ServletScopedContext"
      uuid: "callInitializers_servletContextHandler.ServletScopedContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<method_return_from_value>
        target: "org.eclipse.jetty.ee10.servlet.ServletContextHandler$ServletScopedContext"
        localVariableValue:
          sapientType: "OBJECT"
          content: !<new>
            target: "org.eclipse.jetty.ee10.webapp.WebAppContext"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          valueType: "org.eclipse.jetty.ee10.webapp.WebAppContext"
          uuid: "configure_webAppContext1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        methodParameters: []
        methodName: "getContext"
      valueType: "org.eclipse.jetty.ee10.servlet.ServletContextHandler$ServletScopedContext"
      uuid: "callInitializers_servletContextHandler.ServletScopedContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "callInitializers_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "uuid3"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.eclipse.jetty.ee10.webapp.WebAppContext"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.eclipse.jetty.ee10.webapp.WebAppContext"
      uuid: "configure_webAppContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "jakarta.servlet.ServletContext"
      uuid: "callInitializers_servletContext1"
      fixed: false
      nameForMock: "ServletContext"
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.servlet.ServletContextInitializer"
      uuid: "uuid4"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "callInitializers_void2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "jakarta.servlet.ServletContext"
      uuid: "callInitializers_servletContext1"
      fixed: false
      nameForMock: "ServletContext"
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.eclipse.jetty.ee10.webapp.WebAppContext"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.eclipse.jetty.ee10.webapp.WebAppContext"
      uuid: "configure_webAppContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.eclipse.jetty.ee10.servlet.ServletContextHandler$ServletScopedContext"
      uuid: "callInitializers_servletContextHandler.ServletScopedContext2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.eclipse.jetty.ee10.servlet.ServletContextHandler$ServletScopedContext"
      uuid: "callInitializers_servletContextHandler.ServletScopedContext2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "callInitializers_void3"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "uuid5"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      uuid: "uuid6"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "configureWhenThisInitializersIsEmpty"
    constructorSignature: "<init>(org.springframework.boot.web.servlet.ServletContextInitializer[])\
      \ : void"
    modelFingerprint: "238FE99EE923244149E37E43FCBAF573"
    problemWasSolvedByProver: false
    truncated: true
    inputParameters: []
    uuid: "679247b6-33ed-32b5-b808-5a0639a57ea5"
    deleted: true
    disabled: false
    ignoredBySystem: true
    variablesCouldNotBeIsolated: "object of type Thread"
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.util.List.copyOf(java.util.List) : java.util.List"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
