---
modelFingerprint: "51F833302DE06D22C4E37B73B2EC7996"
methods:
- method:
    name: "getOrder"
    signature: "getOrder() : int"
    sourceCodeSignature: "int getOrder()"
    instructionFingerprint: "593341498C308100DD534F54AE3EF822"
  paths:
  - pathId: "path1"
    testPathName: "getOrderTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "1FD511DAFE842939289F70C77EBBC750"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "c0bb632e-c120-35d3-9fe3-7fc42c801bce"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "setApplicationContext"
    signature: "setApplicationContext(org.springframework.context.ApplicationContext)\
      \ : void"
    sourceCodeSignature: "void setApplicationContext(ApplicationContext context)"
    instructionFingerprint: "0A550294F67D005459A8CCA8712F79B0"
  paths:
  - pathId: "path1"
    testPathName: "setApplicationContextTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "FAE904F6F8F039F7551AFB7AB8E6E024"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "8965c77a-005e-3a50-b8bb-0a78bd407600"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "onApplicationEvent"
    signature: "onApplicationEvent(org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent)\
      \ : void"
    sourceCodeSignature: "void onApplicationEvent(ParentContextAvailableEvent event)"
    instructionFingerprint: "738AF4ED85A12FA3F4942DAAC9B26D71"
  paths:
  - pathId: "path1"
    testPathName: "onApplicationEventWhenChildEqualsThisContextThrowsNullPointerException"
    constructorSignature: "<init>() : void"
    modelFingerprint: "C7B886850F1FF3760EAC7C903E16195B"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "event"
      modelFingerprint: "37C15398EC4F123E6B52E557D885F366"
      index: 2
      valueUuid: "onApplicationEvent_parentContextApplicationContextInitializer.ParentContextAvailableEvent1"
    - type: "LOCAL_VARIABLE"
      name: "event"
      modelFingerprint: "6674537B5C6BDC8AD02BBAC140B62670"
      index: 3
      valueUuid: "onApplicationEvent_parentContextApplicationContextInitializer.ParentContextAvailableEvent1"
      methodExercised:
        target: "event"
        name: "getApplicationContext"
        parameters: []
        signature: "getApplicationContext(): ConfigurableApplicationContext"
        returnValueUuid: "applicationContext1"
        access: 1
    - type: "LOCAL_VARIABLE"
      name: "child"
      modelFingerprint: "26367D3DDD98D816AE711C2BC23A7DB0"
      index: 4
      valueUuid: "applicationContext1"
      methodExercised:
        target: "child"
        name: "getParent"
        parameters: []
        signature: "getParent(): ApplicationContext"
        returnValueUuid: "uuid3"
        access: 1025
    - type: "RESULT"
      name: "result"
      modelFingerprint: "1544C3243427A58A5AE91A88CC628F77"
      index: 5
      valueUuid: "uuid4"
    uuid: "81b9d7fb-6b85-3488-a42a-929763a95266"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
      uuid: "onApplicationEvent_parentContextApplicationContextInitializer.ParentContextAvailableEvent1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
      uuid: "onApplicationEvent_parentContextApplicationContextInitializer.ParentContextAvailableEvent1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "NULL"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "applicationContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "NULL"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "applicationContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "EXCEPTION"
      content: !<new>
        target: "java.lang.NullPointerException"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "java.lang.NullPointerException"
      uuid: "uuid3"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "EXCEPTION"
      content: !<new>
        target: "java.lang.NullPointerException"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "java.lang.NullPointerException"
      uuid: "uuid4"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "onApplicationEventWhenChildNotEqualsThisContext"
    constructorSignature: "<init>() : void"
    modelFingerprint: "D3ADC058EB5B402287963022E8D97864"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "event"
      modelFingerprint: "37C15398EC4F123E6B52E557D885F366"
      index: 2
      valueUuid: "onApplicationEvent_parentContextApplicationContextInitializer.ParentContextAvailableEvent1"
    - type: "LOCAL_VARIABLE"
      name: "event"
      modelFingerprint: "9060D824409628A1B5A871D1F5406650"
      index: 3
      valueUuid: "onApplicationEvent_parentContextApplicationContextInitializer.ParentContextAvailableEvent1"
      methodExercised:
        target: "event"
        name: "getApplicationContext"
        parameters: []
        signature: "getApplicationContext(): ConfigurableApplicationContext"
        returnValueUuid: "onApplicationEvent_configurableApplicationContext1"
        access: 1
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 4
      valueUuid: "uuid5"
    uuid: "b2ca3fc2-f033-3a47-b322-3a9b693e9772"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
      uuid: "onApplicationEvent_parentContextApplicationContextInitializer.ParentContextAvailableEvent1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
      uuid: "onApplicationEvent_parentContextApplicationContextInitializer.ParentContextAvailableEvent1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "onApplicationEvent_configurableApplicationContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      uuid: "uuid5"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
- method:
    name: "createContextCloserListener"
    signature: "createContextCloserListener(org.springframework.context.ConfigurableApplicationContext)\
      \ : org.springframework.boot.builder.ParentContextCloserApplicationListener$ContextCloserListener"
    sourceCodeSignature: "ContextCloserListener createContextCloserListener(ConfigurableApplicationContext\
      \ child)"
    instructionFingerprint: "B7A3A4D5B399276F9F0B4964F01D4C60"
  paths:
  - pathId: "path1"
    testPathName: "createContextCloserListenerTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "1AD12CD234E446E308FFD3B683A53843"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "child"
      modelFingerprint: "E014A9E9EA4F187B268B66F8B4D87B5D"
      index: 2
      valueUuid: "createContextCloserListener_configurableApplicationContext1"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "56F3E309DEF07FAF07712393625B057B"
      index: 3
      valueUuid: "createContextCloserListener_parentContextCloserApplicationListener.ContextCloserListener1"
    uuid: "1660a61c-fd9b-37f0-bc8c-abd860570587"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "createContextCloserListener_configurableApplicationContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.builder.ParentContextCloserApplicationListener$ContextCloserListener"
        parameters:
        - name: "childContext"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.context.ConfigurableApplicationContext"
            uuid: "createContextCloserListener_configurableApplicationContext1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: true
      valueType: "org.springframework.boot.builder.ParentContextCloserApplicationListener$ContextCloserListener"
      uuid: "createContextCloserListener_parentContextCloserApplicationListener.ContextCloserListener1"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
