---
modelFingerprint: "9794197AA78E669942510C9F5F9D7018"
targetClass:
  fullClassName: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
methods:
- method:
    name: "getOrder"
    sourceCodeSignature: "int getOrder()"
    returnType: "int"
    instructionFingerprint: "593341498C308100DD534F54AE3EF822"
  paths:
  - pathId: "path1"
    testPathName: "getOrderTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "5F67CB3BDB2A41A05DABA3827201DFA1"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
- method:
    name: "setApplicationContext"
    sourceCodeSignature: "void setApplicationContext(ApplicationContext context)"
    returnType: "void"
    throwsExceptions:
    - "org.springframework.beans.BeansException"
    parameters:
    - name: "context"
      type: "org.springframework.context.ApplicationContext"
    instructionFingerprint: "0A550294F67D005459A8CCA8712F79B0"
  paths:
  - pathId: "path1"
    testPathName: "setApplicationContextTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "1D6E1EC9D7A596FB7CA0929BAF07259B"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
- method:
    name: "onApplicationEvent"
    sourceCodeSignature: "void onApplicationEvent(ParentContextAvailableEvent event)"
    returnType: "void"
    parameters:
    - name: "event"
      type: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
    instructionFingerprint: "738AF4ED85A12FA3F4942DAAC9B26D71"
  paths:
  - pathId: "path1"
    testPathName: "onApplicationEventWhenChildEqualsThisContextThrowsNullPointerException"
    constructorSignature: "<init>() : void"
    modelFingerprint: "0F61F89FDFF901C4BF2E3FFB7E9CC5B2"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "event"
      modelFingerprint: "EC69B494A383CCEBEA88EAAC96CCCFFE"
      valueUuid: "event"
    - type: "LOCAL_VARIABLE"
      name: "event"
      modelFingerprint: "4B129835F9FCC6A9E6CB409512C57254"
      valueUuid: "event"
      methodExercised:
        expression: "getApplicationContext():fieldApplicationContext"
    - type: "LOCAL_VARIABLE"
      name: "child"
      modelFingerprint: "7195D7CC6A9B394B715FA4C4A913721E"
      valueUuid: "fieldApplicationContext"
      methodExercised:
        expression: "getParent():uniqueUuid1"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "085DC12750BAC37E63C370C4A90AE3FA"
      valueUuid: "expectedResult"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
        parameters: []
      valueType: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
      uuid: "event"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
      uuid: "event"
    - sapientType: "NULL"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "fieldApplicationContext"
    - sapientType: "NULL"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "fieldApplicationContext"
    - sapientType: "EXCEPTION"
      content: !<new>
        target: "java.lang.NullPointerException"
        parameters: []
      valueType: "java.lang.NullPointerException"
      uuid: "uniqueUuid1"
    - sapientType: "EXCEPTION"
      content: !<new>
        target: "java.lang.NullPointerException"
        parameters: []
      valueType: "java.lang.NullPointerException"
      uuid: "expectedResult"
    branches:
    - lineNumber: 63
      expression: "child == this.context"
      range: "(63,7)-(63,27)"
      evaluatedAs: true
      internalMethodName: "maybeInstallListenerInParent"
  - pathId: "path2"
    testPathName: "onApplicationEventWhenChildNotEqualsThisContext"
    constructorSignature: "<init>() : void"
    modelFingerprint: "7487EC960C960CA1A71B9D322D8595DC"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "event"
      modelFingerprint: "EC69B494A383CCEBEA88EAAC96CCCFFE"
      valueUuid: "event"
    - type: "LOCAL_VARIABLE"
      name: "event"
      modelFingerprint: "AFC9C64103B2C58408E0505976076AAD"
      valueUuid: "event"
      methodExercised:
        expression: "getApplicationContext():configurableApplicationContext"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
        parameters: []
      valueType: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
      uuid: "event"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
      uuid: "event"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "configurableApplicationContext"
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
    branches:
    - lineNumber: 63
      expression: "child == this.context"
      range: "(63,7)-(63,27)"
      evaluatedAs: false
      internalMethodName: "maybeInstallListenerInParent"
- method:
    name: "createContextCloserListener"
    sourceCodeSignature: "ContextCloserListener createContextCloserListener(ConfigurableApplicationContext\
      \ child)"
    returnType: "org.springframework.boot.builder.ParentContextCloserApplicationListener$ContextCloserListener"
    parameters:
    - name: "child"
      type: "org.springframework.context.ConfigurableApplicationContext"
    instructionFingerprint: "B7A3A4D5B399276F9F0B4964F01D4C60"
  paths:
  - pathId: "path1"
    testPathName: "createContextCloserListenerTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "E5C66D618042D1D866B624EA90AC8DC3"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "child"
      modelFingerprint: "F3C374EA4CCED18A0FF7FA933129DDFE"
      valueUuid: "child"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3782BA063F41364AD14774434D7C679"
      valueUuid: "parentContextCloserApplicationListener.ContextCloserListener"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
        parameters: []
      valueType: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "child"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.builder.ParentContextCloserApplicationListener$ContextCloserListener"
        parameters:
        - name: "childContext"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.context.ConfigurableApplicationContext"
            uuid: "child"
      valueType: "org.springframework.boot.builder.ParentContextCloserApplicationListener$ContextCloserListener"
      uuid: "parentContextCloserApplicationListener.ContextCloserListener"
      fixed: true
