---
modelFingerprint: "79486D4194ADFE134CA72A0720102A35"
methods:
- method:
    name: "setOrder"
    signature: "setOrder(int) : void"
    instructionFingerprint: "F88C98C2D7593841680C2CA0FECB4028"
  paths:
  - pathId: "path1"
    testPathName: "setOrderTest"
    constructorSignature: "<init>(org.springframework.context.ApplicationContext)\
      \ : void"
    filledByUser: false
    modelFingerprint: "4BB46D14D79A8C2F0460BAA8B45D89F6"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "27a24730-befc-337f-a149-f3be3dcb76b7"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "getOrder"
    signature: "getOrder() : int"
    instructionFingerprint: "342D4E4F854A43E567A525BCBCDEA20C"
  paths:
  - pathId: "path1"
    testPathName: "getOrderTest"
    constructorSignature: "<init>(org.springframework.context.ApplicationContext)\
      \ : void"
    filledByUser: false
    modelFingerprint: "701BCAA5C1A2B61E22DDE938220F04CA"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "c0bb632e-c120-35d3-9fe3-7fc42c801bce"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "initialize"
    signature: "initialize(org.springframework.context.ConfigurableApplicationContext)\
      \ : void"
    instructionFingerprint: "2F7CCD31C95B2BD0FD1B02AC03A228BD"
  paths:
  - pathId: "path1"
    testPathName: "initializeWhenApplicationContextNotEqualsThisParent"
    constructorSignature: "<init>(org.springframework.context.ApplicationContext)\
      \ : void"
    filledByUser: false
    modelFingerprint: "EB738F64C3F25F32640AF1452A5CD387"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "F1B904A2CD241FFA09F856AA0B2900DE"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "applicationContext"
      modelFingerprint: "FB985DDC095B471E312DB0BC04FFD32F"
      index: 2
      ignored: false
      valueUuid: "initialize_configurableApplicationContext1"
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "applicationContext"
      modelFingerprint: "BE631B832BD7044AAF28303EF6E9BAC7"
      index: 3
      ignored: false
      valueUuid: "initialize_configurableApplicationContext1"
      methodExercised:
        target: "applicationContext"
        name: "setParent"
        parameters:
        - name: "parent"
          valueUuid: "<init>_applicationContext1"
        signature: "setParent(ApplicationContext): void"
        returnValueUuid: "initialize_void1"
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "applicationContext"
      modelFingerprint: "27257A5020EC1F488414945F04C24CD6"
      index: 4
      ignored: false
      valueUuid: "initialize_configurableApplicationContext1"
      methodExercised:
        target: "applicationContext"
        name: "addApplicationListener"
        parameters:
        - name: "listener"
          valueUuid: "initialize_parentContextApplicationContextInitializer.EventPublisher1"
        signature: "addApplicationListener(ParentContextApplicationContextInitializer$EventPublisher):\
          \ void"
        returnValueUuid: "initialize_void2"
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 5
      ignored: false
      valueUuid: "uuid2"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "f1cdb3aa-75b4-3cdc-be5b-8865eaa45da8"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "PRIVATE_INNER_CLASS_COMMENT"
      details: "PRIVATE_INNER_CLASS_COMMENT"
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.builder.ParentContextApplicationContextInitializer"
        parameters:
        - name: "parent"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.context.ApplicationContext"
            uuid: "<init>_applicationContext1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.builder.ParentContextApplicationContextInitializer"
        parameters:
        - name: "parent"
          value:
            sapientType: "UNKNOWN"
            valueType: "org.springframework.context.ApplicationContext"
            uuid: "<init>_applicationContext1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "initialize_configurableApplicationContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "initialize_configurableApplicationContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "initialize_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ApplicationContext"
      uuid: "<init>_applicationContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "initialize_configurableApplicationContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "initialize_void2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$EventPublisher"
      uuid: "initialize_parentContextApplicationContextInitializer.EventPublisher1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      uuid: "uuid2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "initializeWhenApplicationContextEqualsThisParent"
    constructorSignature: "<init>(org.springframework.context.ApplicationContext)\
      \ : void"
    filledByUser: false
    modelFingerprint: "50C94C8783E7ED89C4DA41787997C69E"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "12569a48-6330-3c7c-8bf8-8c4c51ee0c09"
    deleted: true
    disabled: false
    ignoredBySystem: true
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
