---
modelFingerprint: "51F833302DE06D22C4E37B73B2EC7996"
methods:
- method:
    name: "getOrder"
    returnType: "int"
    signature: "getOrder() : int"
    instructionFingerprint: "593341498C308100DD534F54AE3EF822"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getOrderTest"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "1FD511DAFE842939289F70C77EBBC750"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "c0bb632e-c120-35d3-9fe3-7fc42c801bce"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "setApplicationContext"
    returnType: "void"
    signature: "setApplicationContext(org.springframework.context.ApplicationContext)\
      \ : void"
    throwsExceptions:
    - "org.springframework.beans.BeansException"
    instructionFingerprint: "0A550294F67D005459A8CCA8712F79B0"
    parametersTypes:
    - "org.springframework.context.ApplicationContext"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "setApplicationContextTest"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "FAE904F6F8F039F7551AFB7AB8E6E024"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "8965c77a-005e-3a50-b8bb-0a78bd407600"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "onApplicationEvent"
    returnType: "void"
    signature: "onApplicationEvent(org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent)\
      \ : void"
    instructionFingerprint: "738AF4ED85A12FA3F4942DAAC9B26D71"
    parametersTypes:
    - "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "onApplicationEventWhenChildEqualsThisContextThrowsNullPointerException"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "C7B886850F1FF3760EAC7C903E16195B"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "event"
      modelFingerprint: "37C15398EC4F123E6B52E557D885F366"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
        uuid: "onApplicationEvent_parentContextApplicationContextInitializer.ParentContextAvailableEvent1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "event"
      modelFingerprint: "6674537B5C6BDC8AD02BBAC140B62670"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
        uuid: "onApplicationEvent_parentContextApplicationContextInitializer.ParentContextAvailableEvent1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "event"
        name: "getApplicationContext"
        parameters: []
        signature: "getApplicationContext(): ConfigurableApplicationContext"
        returnValue:
          sapientType: "NULL"
          valueType: "org.springframework.context.ConfigurableApplicationContext"
          uuid: "applicationContext1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "child"
      modelFingerprint: "26367D3DDD98D816AE711C2BC23A7DB0"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "NULL"
        valueType: "org.springframework.context.ConfigurableApplicationContext"
        uuid: "applicationContext1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "child"
        name: "getParent"
        parameters: []
        signature: "getParent(): ApplicationContext"
        returnValue:
          sapientType: "EXCEPTION"
          content: !<new>
            target: "java.lang.NullPointerException"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          suggestedContent: !<new>
            target: "java.lang.NullPointerException"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          valueType: "java.lang.NullPointerException"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "1544C3243427A58A5AE91A88CC628F77"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "EXCEPTION"
        content: !<new>
          target: "java.lang.NullPointerException"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "java.lang.NullPointerException"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        valueType: "java.lang.NullPointerException"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "81b9d7fb-6b85-3488-a42a-929763a95266"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path2"
    pathIdForUser: "path2"
    testPathName: "onApplicationEventWhenChildNotEqualsThisContext"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "D3ADC058EB5B402287963022E8D97864"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "event"
      modelFingerprint: "37C15398EC4F123E6B52E557D885F366"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
        uuid: "onApplicationEvent_parentContextApplicationContextInitializer.ParentContextAvailableEvent1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "event"
      modelFingerprint: "9060D824409628A1B5A871D1F5406650"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent"
        uuid: "onApplicationEvent_parentContextApplicationContextInitializer.ParentContextAvailableEvent1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "event"
        name: "getApplicationContext"
        parameters: []
        signature: "getApplicationContext(): ConfigurableApplicationContext"
        returnValue:
          sapientType: "MOCK"
          valueType: "org.springframework.context.ConfigurableApplicationContext"
          uuid: "onApplicationEvent_configurableApplicationContext1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "VOID"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "b2ca3fc2-f033-3a47-b322-3a9b693e9772"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "createContextCloserListener"
    returnType: "org.springframework.boot.builder.ParentContextCloserApplicationListener$ContextCloserListener"
    signature: "createContextCloserListener(org.springframework.context.ConfigurableApplicationContext)\
      \ : org.springframework.boot.builder.ParentContextCloserApplicationListener$ContextCloserListener"
    instructionFingerprint: "B7A3A4D5B399276F9F0B4964F01D4C60"
    parametersTypes:
    - "org.springframework.context.ConfigurableApplicationContext"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "createContextCloserListenerTest"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "1AD12CD234E446E308FFD3B683A53843"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.builder.ParentContextCloserApplicationListener"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "child"
      modelFingerprint: "E014A9E9EA4F187B268B66F8B4D87B5D"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.context.ConfigurableApplicationContext"
        uuid: "createContextCloserListener_configurableApplicationContext1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "56F3E309DEF07FAF07712393625B057B"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.builder.ParentContextCloserApplicationListener$ContextCloserListener"
          parameters:
          - name: "childContext"
            value:
              sapientType: "MOCK"
              valueType: "org.springframework.context.ConfigurableApplicationContext"
              uuid: "createContextCloserListener_configurableApplicationContext1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: true
        suggestedContent: !<new>
          target: "org.springframework.boot.builder.ParentContextCloserApplicationListener$ContextCloserListener"
          parameters:
          - name: "childContext"
            value:
              sapientType: "UNKNOWN"
              valueType: "org.springframework.context.ConfigurableApplicationContext"
              uuid: "createContextCloserListener_configurableApplicationContext1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: true
        valueType: "org.springframework.boot.builder.ParentContextCloserApplicationListener$ContextCloserListener"
        uuid: "createContextCloserListener_parentContextCloserApplicationListener.ContextCloserListener1"
        fixed: true
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "1660a61c-fd9b-37f0-bc8c-abd860570587"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
