---
modelFingerprint: "02EF993907648733F2BD43CA6370654D"
methods:
- method:
    name: "setOrder"
    returnType: "void"
    signature: "setOrder(int) : void"
    instructionFingerprint: "F88C98C2D7593841680C2CA0FECB4028"
    parametersTypes:
    - "int"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "setOrderTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(org.springframework.context.ApplicationContext)\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "4BB46D14D79A8C2F0460BAA8B45D89F6"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "27a24730-befc-337f-a149-f3be3dcb76b7"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "getOrder"
    returnType: "int"
    signature: "getOrder() : int"
    instructionFingerprint: "342D4E4F854A43E567A525BCBCDEA20C"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getOrderTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(org.springframework.context.ApplicationContext)\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "701BCAA5C1A2B61E22DDE938220F04CA"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "c0bb632e-c120-35d3-9fe3-7fc42c801bce"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "initialize"
    returnType: "void"
    signature: "initialize(org.springframework.context.ConfigurableApplicationContext)\
      \ : void"
    instructionFingerprint: "1C99795B0116F0111BE694B73C925EF5"
    parametersTypes:
    - "org.springframework.context.ConfigurableApplicationContext"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "initializeWhenApplicationContextNotEqualsThisParent"
    nameDefinedByUser: false
    constructorSignature: "<init>(org.springframework.context.ApplicationContext)\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "15B33D2506F719E766E56013CC2FB90F"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "F1B904A2CD241FFA09F856AA0B2900DE"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.builder.ParentContextApplicationContextInitializer"
          parameters:
          - name: "parent"
            value:
              sapientType: "MOCK"
              valueType: "org.springframework.context.ApplicationContext"
              uuid: "<init>_applicationContext1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.builder.ParentContextApplicationContextInitializer"
          parameters:
          - name: "parent"
            value:
              sapientType: "UNKNOWN"
              valueType: "org.springframework.context.ApplicationContext"
              uuid: "<init>_applicationContext1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "applicationContext"
      modelFingerprint: "FB985DDC095B471E312DB0BC04FFD32F"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.context.ConfigurableApplicationContext"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.context.ConfigurableApplicationContext"
        uuid: "initialize_configurableApplicationContext1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "applicationContext"
      modelFingerprint: "4961D7E1269DBEA21A55716828067044"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.context.ConfigurableApplicationContext"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.context.ConfigurableApplicationContext"
        uuid: "initialize_configurableApplicationContext1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "applicationContext"
        name: "setParent"
        parameters:
        - name: "arg0"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.context.ApplicationContext"
            uuid: "<init>_applicationContext1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "setParent(ApplicationContext): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "initialize_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "applicationContext"
      modelFingerprint: "6CF821EDA3D7A9E6FB6F6A1E666BD9D0"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.context.ConfigurableApplicationContext"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.context.ConfigurableApplicationContext"
        uuid: "initialize_configurableApplicationContext1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "applicationContext"
        name: "addApplicationListener"
        parameters:
        - name: "arg0"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$EventPublisher"
            uuid: "initialize_parentContextApplicationContextInitializer.EventPublisher1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "addApplicationListener(ParentContextApplicationContextInitializer$EventPublisher):\
          \ void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "initialize_void2"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "VOID"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "f1cdb3aa-75b4-3cdc-be5b-8865eaa45da8"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "PRIVATE_INNER_CLASS_COMMENT"
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path2"
    pathIdForUser: "path2"
    testPathName: "initializeWhenApplicationContextEqualsThisParent"
    nameDefinedByUser: false
    constructorSignature: "<init>(org.springframework.context.ApplicationContext)\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "50C94C8783E7ED89C4DA41787997C69E"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "12569a48-6330-3c7c-8bf8-8c4c51ee0c09"
    deleted: true
    disabled: false
    ignoredBySystem: true
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
