---
modelFingerprint: "095D2A2145BC32AE8A4E7285582698F1"
targetClass:
  fullClassName: "org.springframework.boot.builder.ParentContextApplicationContextInitializer"
methods:
- method:
    name: "setOrder"
    sourceCodeSignature: "void setOrder(int order)"
    returnType: "void"
    parameters:
    - name: "order"
      type: "int"
    instructionFingerprint: "F88C98C2D7593841680C2CA0FECB4028"
  paths:
  - pathId: "path1"
    testPathName: "setOrderTest"
    constructorSignature: "<init>(org.springframework.context.ApplicationContext)\
      \ : void"
    modelFingerprint: "4843E9B8EB497197C85F8DC0EFAAACA6"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
- method:
    name: "getOrder"
    sourceCodeSignature: "int getOrder()"
    returnType: "int"
    instructionFingerprint: "342D4E4F854A43E567A525BCBCDEA20C"
  paths:
  - pathId: "path1"
    testPathName: "getOrderTest"
    constructorSignature: "<init>(org.springframework.context.ApplicationContext)\
      \ : void"
    modelFingerprint: "AA3250683E55C5FA2222D48D75F3FAC2"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
- method:
    name: "initialize"
    sourceCodeSignature: "void initialize(ConfigurableApplicationContext applicationContext)"
    returnType: "void"
    parameters:
    - name: "applicationContext"
      type: "org.springframework.context.ConfigurableApplicationContext"
    instructionFingerprint: "2F7CCD31C95B2BD0FD1B02AC03A228BD"
  paths:
  - pathId: "path1"
    testPathName: "initializeWhenApplicationContextNotEqualsThisParent"
    constructorSignature: "<init>(org.springframework.context.ApplicationContext)\
      \ : void"
    modelFingerprint: "29D2C3502C4E42C6F9FD76A85DE094A1"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "EFA6E8F7723ADEB4CF4CECB762D1759A"
      valueUuid: "target"
    - type: "INPUT"
      name: "applicationContext"
      modelFingerprint: "DF659A8AABEBC6871FFB4901FD8A4D44"
      valueUuid: "applicationContext"
    - type: "LOCAL_VARIABLE"
      name: "applicationContext"
      modelFingerprint: "BF6CC4E6EFD63785BD42D8ED3F7F0F25"
      valueUuid: "applicationContext"
      methodExercised:
        expression: "setParent(parent:parent):void"
    - type: "LOCAL_VARIABLE"
      name: "applicationContext"
      modelFingerprint: "E51BB919C74EA3EBF739C642676285B0"
      valueUuid: "applicationContext"
      methodExercised:
        expression: "addApplicationListener(listener:parentContextApplicationContextInitializer.EventPublisher):void2"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    failureReason:
      reason: "PRIVATE_INNER_CLASS_COMMENT"
      details: "PRIVATE_INNER_CLASS_COMMENT"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.builder.ParentContextApplicationContextInitializer"
        parameters:
        - name: "parent"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.context.ApplicationContext"
            uuid: "parent"
      valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "applicationContext"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "applicationContext"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ApplicationContext"
      uuid: "parent"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "applicationContext"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void2"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.builder.ParentContextApplicationContextInitializer$EventPublisher"
      uuid: "parentContextApplicationContextInitializer.EventPublisher"
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
    branches:
    - lineNumber: 57
      expression: "applicationContext != this.parent"
      range: "(57,7)-(57,39)"
      evaluatedAs: true
