---
modelFingerprint: "7EEBF2C0F7C40B4B25B9B11E121E1493"
methods:
- method:
    name: "getSource"
    returnType: "java.io.File"
    signature: "getSource() : java.io.File"
    instructionFingerprint: "9EB527E192D9AB2C1AE59601F438A7F9"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getSourceTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.Class<?>) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "3962513474A8B050AA86CADBF596FD28"
    problemWasSolvedByProver: false
    truncated: true
    inputParameters: []
    uuid: "b18e1b7c-5aa2-3b75-96ca-a0f74ce65f85"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.lang.Class.getProtectionDomain() : java.security.ProtectionDomain"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "getDir"
    returnType: "java.io.File"
    signature: "getDir() : java.io.File"
    instructionFingerprint: "C71520A34E0ED513F90A50C20DA9EFD8"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getDirTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.Class<?>) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "FD5D8251274D14D1773D5EAE60C4F891"
    problemWasSolvedByProver: false
    truncated: true
    inputParameters: []
    uuid: "35a51e63-0256-3f72-8da1-9326eb162c00"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.lang.Class.getProtectionDomain() : java.security.ProtectionDomain"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "toString"
    returnType: "java.lang.String"
    signature: "toString() : java.lang.String"
    instructionFingerprint: "50AE321752BE95A26E358763574019D4"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "toStringTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.Class<?>) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "2E59BCD2314C400A53FD283C3C2AD883"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "B7BD19130CFB0156FF079884BCD16842"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.system.ApplicationHome"
          parameters:
          - name: "sourceClass"
            value:
              sapientType: "CLASS"
              content: !<regular>
                value: "org.springframework.boot.SpringApplication"
              suggestedContent: !<regular>
                value: "org.springframework.boot.SpringApplication"
              valueType: "java.lang.Class"
              genericValueType: "?"
              uuid: "<init>_class1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.system.ApplicationHome"
          parameters:
          - name: "sourceClass"
            value:
              sapientType: "CLASS"
              content: !<regular>
                value: "org.springframework.boot.SpringApplication"
              suggestedContent: !<regular>
                value: "org.springframework.boot.SpringApplication"
              valueType: "java.lang.Class"
              genericValueType: "?"
              uuid: "<init>_class1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.system.ApplicationHome"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INTERNAL"
      name: "internalMethod"
      modelFingerprint: "902457FACD435F764D9EE3BBEEAA47F0"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      methodExercised:
        target: "target"
        name: "getDir"
        parameters: []
        signature: "getDir(): File"
        returnValue:
          sapientType: "MOCK"
          valueType: "java.io.File"
          uuid: "toString_file1"
          fixed: false
          nameForMock: "toString_file1"
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "2B48690B91A1322B4E481D6C0E30B838"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "BASIC"
        content: !<regular>
          value: "toString_file1"
        suggestedContent: !<regular>
          value: "toString_file1"
        valueType: "java.lang.String"
        uuid: "toString_string1"
        fixed: false
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "363d3698-f34c-39ad-914f-376a19498023"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "LLM"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
