---
modelFingerprint: "7EEBF2C0F7C40B4B25B9B11E121E1493"
methods:
- method:
    name: "getSource"
    signature: "getSource() : java.io.File"
    sourceCodeSignature: "File getSource()"
    instructionFingerprint: "9EB527E192D9AB2C1AE59601F438A7F9"
  paths:
  - pathId: "path1"
    testPathName: "getSourceTest"
    constructorSignature: "<init>(java.lang.Class<?>) : void"
    modelFingerprint: "3962513474A8B050AA86CADBF596FD28"
    problemWasSolvedByProver: false
    truncated: true
    inputParameters: []
    uuid: "b18e1b7c-5aa2-3b75-96ca-a0f74ce65f85"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.lang.Class.getProtectionDomain() : java.security.ProtectionDomain"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "getDir"
    signature: "getDir() : java.io.File"
    sourceCodeSignature: "File getDir()"
    instructionFingerprint: "C71520A34E0ED513F90A50C20DA9EFD8"
  paths:
  - pathId: "path1"
    testPathName: "getDirTest"
    constructorSignature: "<init>(java.lang.Class<?>) : void"
    modelFingerprint: "FD5D8251274D14D1773D5EAE60C4F891"
    problemWasSolvedByProver: false
    truncated: true
    inputParameters: []
    uuid: "35a51e63-0256-3f72-8da1-9326eb162c00"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.lang.Class.getProtectionDomain() : java.security.ProtectionDomain"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "toString"
    signature: "toString() : java.lang.String"
    sourceCodeSignature: "String toString()"
    instructionFingerprint: "50AE321752BE95A26E358763574019D4"
  paths:
  - pathId: "path1"
    testPathName: "toStringTest"
    constructorSignature: "<init>(java.lang.Class<?>) : void"
    modelFingerprint: "054829F60D9D3CD90823A8BA55325690"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "CEFCE4DD8B348001EB906DBFF248DEA6"
      index: 1
      valueUuid: "target"
    - type: "STATIC"
      name: "StringUtils"
      modelFingerprint: "0ADC91B76C5E1D2A8701BB911882A91E"
      index: 2
      valueUuid: "uuid1"
      methodExercised:
        target: "org.springframework.util.StringUtils"
        name: "hasLength"
        parameters:
        - name: "str"
          valueUuid: "findDefaultHomeDir_string1"
        signature: "hasLength(String): boolean"
        returnValueUuid: "findDefaultHomeDir_boolean1"
        access: 9
    - type: "INTERNAL"
      name: "internalMethod"
      modelFingerprint: "902457FACD435F764D9EE3BBEEAA47F0"
      index: 3
      methodExercised:
        target: "target"
        name: "getDir"
        parameters: []
        signature: "getDir(): File"
        returnValueUuid: "toString_file1"
        access: 1
    - type: "RESULT"
      name: "result"
      modelFingerprint: "2B48690B91A1322B4E481D6C0E30B838"
      index: 4
      valueUuid: "toString_string1"
    uuid: "363d3698-f34c-39ad-914f-376a19498023"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_CALL_INSTRUCTION_UNSOLVABLE"
      source: "String userDir = System.getProperty(\\\"user.dir\\\");"
      lineNumber: 147
      details: "Method java.lang.System::getProperty has a unrepeatable behavior"
    prover: "LLM"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.system.ApplicationHome"
        parameters:
        - name: "sourceClass"
          value:
            sapientType: "CLASS"
            content: !<regular>
              value: "java.lang.Object"
            valueType: "java.lang.Class"
            genericValueType: "?"
            uuid: "<init>_class1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.system.ApplicationHome"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "REAL"
      valueType: "org.springframework.util.StringUtils"
      uuid: "uuid1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "findDefaultHomeDir_boolean1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "findDefaultHomeDir_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "java.io.File"
      uuid: "toString_file1"
      fixed: false
      nameForMock: "toString_file1"
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "toString_file1"
      valueType: "java.lang.String"
      uuid: "toString_string1"
      fixed: false
      equalsMethodPresent: true
      explicitCastNeeded: false
