---
modelFingerprint: "397C4552B8F67730B3DCF6A670B5B10C"
methods:
- method:
    name: "getSource"
    returnType: "java.io.File"
    signature: "getSource() : java.io.File"
    instructionFingerprint: "9EB527E192D9AB2C1AE59601F438A7F9"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getSourceTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.Class<?>) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "5DA5BA46ECBCF56612B28A498594B851"
    problemWasSolvedByProver: false
    truncated: true
    inputParameters: []
    uuid: "b18e1b7c-5aa2-3b75-96ca-a0f74ce65f85"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "getDir"
    returnType: "java.io.File"
    signature: "getDir() : java.io.File"
    instructionFingerprint: "C71520A34E0ED513F90A50C20DA9EFD8"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getDirTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.Class<?>) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "335A7BAC16A92EAABCD7516202E6E242"
    problemWasSolvedByProver: false
    truncated: true
    inputParameters: []
    uuid: "35a51e63-0256-3f72-8da1-9326eb162c00"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "toString"
    returnType: "java.lang.String"
    signature: "toString() : java.lang.String"
    instructionFingerprint: "50AE321752BE95A26E358763574019D4"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "toStringTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.Class<?>) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "3300D7E5D08A9E0494949697DCC07C0B"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "9A9D8529FEA7ABC42EBE721AD4CBFB98"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.system.ApplicationHome"
          parameters:
          - name: "sourceClass"
            value:
              sapientType: "CLASS"
              content: !<regular>
                value: "java.lang.String"
              suggestedContent: !<regular>
                value: "java.lang.String"
              valueType: "java.lang.Class"
              genericValueType: "?"
              uuid: "<init>_class1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.system.ApplicationHome"
          parameters:
          - name: "sourceClass"
            value:
              sapientType: "CLASS"
              content: !<regular>
                value: "java.lang.String"
              suggestedContent: !<regular>
                value: "java.lang.String"
              valueType: "java.lang.Class"
              genericValueType: "?"
              uuid: "<init>_class1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.system.ApplicationHome"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "StringUtils"
      modelFingerprint: "0ADC91B76C5E1D2A8701BB911882A91E"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "REAL"
        valueType: "org.springframework.util.StringUtils"
        uuid: "org.springframework.util.StringUtils"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.StringUtils"
        name: "hasLength"
        parameters:
        - name: "str"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "A"
            suggestedContent: !<regular>
              value: "A"
            valueType: "java.lang.String"
            uuid: "findDefaultHomeDir_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "hasLength(String): boolean"
        returnValue:
          sapientType: "BASIC"
          content: !<regular>
            value: true
          suggestedContent: !<regular>
            value: true
          valueType: "boolean"
          uuid: "findDefaultHomeDir_boolean1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "INTERNAL"
      name: "internalMethod"
      modelFingerprint: "0B76346E0E1B0E02F63F5DB3437AFE5A"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      methodExercised:
        target: "target"
        name: "getDir"
        parameters: []
        signature: "getDir(): File"
        returnValue:
          sapientType: "OBJECT"
          content: !<new>
            target: "java.io.File"
            parameters:
            - name: "pathname"
              value:
                sapientType: "BASIC"
                content: !<regular>
                  value: "pathname1"
                valueType: "java.lang.String"
                uuid: "toString_file1-pathname"
                fixed: false
                equalsMethodPresent: false
                explicitCastNeeded: false
            privateConstructor: false
            createdByTargetCode: false
          suggestedContent: !<new>
            target: "java.io.File"
            parameters:
            - name: "pathname"
              value:
                sapientType: "BASIC"
                valueType: "java.lang.String"
                uuid: "toString_file1-pathname"
                fixed: false
                equalsMethodPresent: false
                explicitCastNeeded: false
            privateConstructor: false
            createdByTargetCode: false
          valueType: "java.io.File"
          uuid: "toString_file1"
          fixed: false
          nameForMock: "toString_file1"
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "2B48690B91A1322B4E481D6C0E30B838"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "BASIC"
        content: !<regular>
          value: "toString_file1"
        suggestedContent: !<regular>
          value: "toString_file1"
        valueType: "java.lang.String"
        uuid: "toString_string1"
        fixed: false
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "363d3698-f34c-39ad-914f-376a19498023"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_CALL_INSTRUCTION_UNSOLVABLE"
      source: "String userDir = System.getProperty(\\\"user.dir\\\");"
      lineNumber: 147
    prover: "LLM"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
