---
modelFingerprint: "FE6FACB4019DD85A14A0A6A2669696FF"
targetClass:
  fullClassName: "org.springframework.boot.system.ApplicationHome"
methods:
- method:
    name: "getSource"
    sourceCodeSignature: "File getSource()"
    returnType: "java.io.File"
    instructionFingerprint: "9EB527E192D9AB2C1AE59601F438A7F9"
  paths:
  - pathId: "path1"
    testPathName: "getSourceTest"
    constructorSignature: "<init>(java.lang.Class<?>) : void"
    modelFingerprint: "C2A68F81F4E16253A4C6F3394A85D88C"
    problemWasSolvedByProver: false
    inputParameters: []
    disabled: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.lang.Class.getProtectionDomain() : java.security.ProtectionDomain"
    allValues: []
- method:
    name: "getDir"
    sourceCodeSignature: "File getDir()"
    returnType: "java.io.File"
    instructionFingerprint: "C71520A34E0ED513F90A50C20DA9EFD8"
  paths:
  - pathId: "path1"
    testPathName: "getDirTest"
    constructorSignature: "<init>(java.lang.Class<?>) : void"
    modelFingerprint: "6F9B73A9E8B5CE95E0F968ED97343673"
    problemWasSolvedByProver: false
    inputParameters: []
    disabled: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.lang.Class.getProtectionDomain() : java.security.ProtectionDomain"
    allValues: []
- method:
    name: "toString"
    sourceCodeSignature: "String toString()"
    returnType: "java.lang.String"
    instructionFingerprint: "50AE321752BE95A26E358763574019D4"
  paths:
  - pathId: "path1"
    testPathName: "toStringTest"
    constructorSignature: "<init>(java.lang.Class<?>) : void"
    modelFingerprint: "E7EA4E46227B20D8DAE01F71F8B0C3E9"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "7839DC77F816172045015BB7AF691BC7"
      valueUuid: "target"
    - type: "INTERNAL"
      name: "internalMethod"
      modelFingerprint: "27FE9BA49D5360D6941B091D6C74984D"
      methodExercised:
        expression: "getDir():file5"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "5E62F42429FAA37B0B3F2C299EE0DE96"
      valueUuid: "string19"
    disabled: true
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.lang.Class.getProtectionDomain() : java.security.ProtectionDomain"
    disabledStatusUpdatedBy: "SYSTEM"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.system.ApplicationHome"
        parameters:
        - name: "sourceClass"
          value:
            sapientType: "CLASS"
            content: !<regular>
              value: "java.lang.Object"
            valueType: "java.lang.Class"
            genericValueType: "?"
            uuid: "sourceClass"
      valueType: "org.springframework.boot.system.ApplicationHome"
      uuid: "target"
    - sapientType: "OBJECT"
      content: !<new>
        target: "java.io.File"
        parameters:
        - name: "pathname"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "pathname1"
            valueType: "java.lang.String"
            uuid: "file5-pathname"
      valueType: "java.io.File"
      uuid: "file5"
      nameForMock: "file5"
    - sapientType: "BASIC"
      content: !<regular>
        value: "file5"
      valueType: "java.lang.String"
      uuid: "string19"
