---
modelFingerprint: "E773728E5BE02A1BA128DAFFD34E487B"
methods:
- method:
    name: "lookup"
    signature: "lookup(java.lang.String) : java.lang.String"
    sourceCodeSignature: "String lookup(String key)"
    instructionFingerprint: "764BA9347C1176D4257861A3C534CCD3"
  paths:
  - pathId: "path1"
    testPathName: "lookup1WhenThisEnvironmentIsNull"
    constructorSignature: "<init>() : void"
    modelFingerprint: "CC4D082238F7F2A745FBCA797106807F"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "key"
      modelFingerprint: "23A886133DA0141E522DC74D3398EA06"
      index: 2
      valueUuid: "lookup_string1"
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "F46FE07B236FD656CA45BC236173D2CA"
      index: 3
      valueUuid: "uuid3"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "state"
        parameters:
        - name: "expression"
          valueUuid: "uuid1"
        - name: "message"
          valueUuid: "uuid2"
        signature: "state(boolean,String): void"
        returnValueUuid: "lookup_void1"
        access: 9
    - type: "FIELD"
      name: "environment"
      modelFingerprint: "B0F83B7D1DC54159656244CC14D16631"
      index: 4
      valueUuid: "environment1"
      methodExercised:
        target: "this.environment"
        name: "getProperty"
        parameters:
        - name: "key"
          valueUuid: "lookup_string1"
        signature: "getProperty(String): String"
        returnValueUuid: "lookup_string2"
        access: 1025
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D1F433D4EB9F8805FF391E82DAB508AB"
      index: 5
      valueUuid: "lookup_string2"
    uuid: "a16791f1-0bc3-3c28-a5f5-c1c0840540e6"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "UNKNOWN_REASON"
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.logging.log4j2.SpringEnvironmentLookup"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
        propertiesMap:
          environment:
            sapientType: "MOCK"
            valueType: "org.springframework.core.env.Environment"
            uuid: "environment1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
      valueType: "org.springframework.boot.logging.log4j2.SpringEnvironmentLookup"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "key1"
      valueType: "java.lang.String"
      uuid: "lookup_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid3"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "lookup_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "uuid1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Unable to obtain Spring Environment from LoggerContext"
      valueType: "java.lang.String"
      uuid: "uuid2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.Environment"
      uuid: "environment1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "return_of_getProperty1"
      valueType: "java.lang.String"
      uuid: "lookup_string2"
      fixed: false
      equalsMethodPresent: true
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "key1"
      valueType: "java.lang.String"
      uuid: "lookup_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "return_of_getProperty1"
      valueType: "java.lang.String"
      uuid: "lookup_string2"
      fixed: false
      equalsMethodPresent: true
      explicitCastNeeded: false
- method:
    name: "setLoggerContext"
    signature: "setLoggerContext(org.apache.logging.log4j.core.LoggerContext) : void"
    sourceCodeSignature: "void setLoggerContext(LoggerContext loggerContext)"
    instructionFingerprint: "7B2B9A91FA9D17DBC0B9C4C91D735E8B"
  paths:
  - pathId: "path1"
    testPathName: "setLoggerContextTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "31901E853FAD30E3D73E56677908FCE1"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "loggerContext"
      modelFingerprint: "2998B5554F634D40BB4293DE2F216FE9"
      index: 2
      valueUuid: "setLoggerContext_loggerContext1"
    - type: "STATIC"
      name: "Log4J2LoggingSystem"
      modelFingerprint: "0D194E2259A0FA3BE9EE60A09A64F47D"
      index: 3
      valueUuid: "uuid4"
      methodExercised:
        target: "org.springframework.boot.logging.log4j2.Log4J2LoggingSystem"
        name: "getEnvironment"
        parameters:
        - name: "loggerContext"
          valueUuid: "setLoggerContext_loggerContext1"
        signature: "getEnvironment(LoggerContext): Environment"
        returnValueUuid: "setLoggerContext_environment1"
        access: 9
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 4
      valueUuid: "uuid5"
    uuid: "7a5846a5-15d9-38ce-8d4b-9b708230d1b3"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.logging.log4j2.SpringEnvironmentLookup"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.logging.log4j2.SpringEnvironmentLookup"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.apache.logging.log4j.core.LoggerContext"
        parameters:
        - name: "name"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "name1"
            valueType: "java.lang.String"
            uuid: "setLoggerContext_loggerContext1-name"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.apache.logging.log4j.core.LoggerContext"
      uuid: "setLoggerContext_loggerContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.logging.log4j2.Log4J2LoggingSystem"
      uuid: "uuid4"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.Environment"
      uuid: "setLoggerContext_environment1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.apache.logging.log4j.core.LoggerContext"
        parameters:
        - name: "name"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "name1"
            valueType: "java.lang.String"
            uuid: "setLoggerContext_loggerContext1-name"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.apache.logging.log4j.core.LoggerContext"
      uuid: "setLoggerContext_loggerContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      uuid: "uuid5"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
