---
modelFingerprint: "9B1967B50A97B7D36EA2E0B64463DBE7"
targetClass:
  fullClassName: "org.springframework.boot.logging.log4j2.SpringBootConfigurationFactory"
methods:
- method:
    name: "getSupportedTypes"
    sourceCodeSignature: "String[] getSupportedTypes()"
    returnType: "java.lang.String[]"
    instructionFingerprint: "C540C6B2459ECFF6303AACC6D7AEECCB"
  paths:
  - pathId: "path1"
    testPathName: "getSupportedTypesTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "DC6C3A66FD1FFA4B6958552C4E7D7482"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
- method:
    name: "getConfiguration"
    sourceCodeSignature: "Configuration getConfiguration(LoggerContext loggerContext,\
      \ ConfigurationSource source)"
    returnType: "org.apache.logging.log4j.core.config.Configuration"
    parameters:
    - name: "loggerContext"
      type: "org.apache.logging.log4j.core.LoggerContext"
    - name: "source"
      type: "org.apache.logging.log4j.core.config.ConfigurationSource"
    instructionFingerprint: "41B197B481202FE128EBA47FDD88CA5A"
  paths:
  - pathId: "path1"
    testPathName: "getConfigurationWhenSourceEqualsConfigurationSourceNULL_SOURCE"
    constructorSignature: "<init>() : void"
    modelFingerprint: "33F8890B7691F70B217FAD8D5B867482"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "loggerContext"
      modelFingerprint: "46326C20482BCD19743FDB69EBF25387"
      valueUuid: "loggerContext"
    - type: "INPUT"
      name: "source"
      modelFingerprint: "2BA3DF22E224E2424514FC56887CF41E"
      valueUuid: "configurationSource"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "8680EA37170F8A5A15192DDDDE16AC72"
      valueUuid: "configuration"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.logging.log4j2.SpringBootConfigurationFactory"
        parameters: []
      valueType: "org.springframework.boot.logging.log4j2.SpringBootConfigurationFactory"
      uuid: "target"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.apache.logging.log4j.core.LoggerContext"
        parameters:
        - name: "name"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "name1"
            valueType: "java.lang.String"
            uuid: "loggerContext-name"
      valueType: "org.apache.logging.log4j.core.LoggerContext"
      uuid: "loggerContext"
    - sapientType: "OBJECT"
      content: !<static_field_return>
        target: "org.apache.logging.log4j.core.config.ConfigurationSource"
        fieldName: "NULL_SOURCE"
      valueType: "org.apache.logging.log4j.core.config.ConfigurationSource"
      uuid: "configurationSource"
    - sapientType: "NULL"
      valueType: "org.apache.logging.log4j.core.config.Configuration"
      uuid: "configuration"
      fixed: true
    branches:
    - lineNumber: 56
      expression: "source == null"
      range: "(56,7)-(56,20)"
      evaluatedAs: false
    - lineNumber: 56
      expression: "source == ConfigurationSource.NULL_SOURCE"
      range: "(56,25)-(56,65)"
      evaluatedAs: true
  - pathId: "path2"
    testPathName: "getConfigurationWhenSourceNotEqualsConfigurationSourceNULL_SOURCE"
    constructorSignature: "<init>() : void"
    modelFingerprint: "75569EF9E39EE97465384990F2AC0A6A"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "loggerContext"
      modelFingerprint: "46326C20482BCD19743FDB69EBF25387"
      valueUuid: "loggerContext"
    - type: "INPUT"
      name: "source"
      modelFingerprint: "180F0BEDB17F9F6500A174669868994C"
      valueUuid: "source"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "9ADD36AB3325F80BC2AF95A9F5524C50"
      valueUuid: "defaultConfiguration"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.logging.log4j2.SpringBootConfigurationFactory"
        parameters: []
      valueType: "org.springframework.boot.logging.log4j2.SpringBootConfigurationFactory"
      uuid: "target"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.apache.logging.log4j.core.LoggerContext"
        parameters:
        - name: "name"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "name1"
            valueType: "java.lang.String"
            uuid: "loggerContext-name"
      valueType: "org.apache.logging.log4j.core.LoggerContext"
      uuid: "loggerContext"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.apache.logging.log4j.core.config.ConfigurationSource"
        parameters:
        - name: "stream"
          value:
            sapientType: "INPUT_STREAM"
            content: !<inputStream>
              values: []
            valueType: "java.io.InputStream"
            uuid: "source-stream"
        - name: "file"
          value:
            sapientType: "OBJECT"
            content: !<new>
              target: "java.io.File"
              parameters:
              - name: "pathname"
                value:
                  sapientType: "BASIC"
                  content: !<regular>
                    value: "pathname1"
                  valueType: "java.lang.String"
                  uuid: "source-file-pathname"
            valueType: "java.io.File"
            uuid: "source-file"
      valueType: "org.apache.logging.log4j.core.config.ConfigurationSource"
      uuid: "source"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.apache.logging.log4j.core.config.DefaultConfiguration"
        parameters: []
      valueType: "org.apache.logging.log4j.core.config.DefaultConfiguration"
      uuid: "defaultConfiguration"
      fixed: true
    branches:
    - lineNumber: 56
      expression: "source == null"
      range: "(56,7)-(56,20)"
      evaluatedAs: false
    - lineNumber: 56
      expression: "source == ConfigurationSource.NULL_SOURCE"
      range: "(56,25)-(56,65)"
      evaluatedAs: false
