---
modelFingerprint: "056B5CAF76EDE5D95D820BFC65D9ED22"
methods:
- method:
    name: "getSupportedTypes"
    signature: "getSupportedTypes() : java.lang.String[]"
    sourceCodeSignature: "String[] getSupportedTypes()"
    instructionFingerprint: "C540C6B2459ECFF6303AACC6D7AEECCB"
  paths:
  - pathId: "path1"
    testPathName: "getSupportedTypesTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "2ABDC9FFBAC5219513625F47B2F0AE39"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "3e294366-1d74-3819-9989-e14991f4b9b9"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "getConfiguration"
    signature: "getConfiguration(org.apache.logging.log4j.core.LoggerContext,org.apache.logging.log4j.core.config.ConfigurationSource)\
      \ : org.apache.logging.log4j.core.config.Configuration"
    sourceCodeSignature: "Configuration getConfiguration(LoggerContext loggerContext,\
      \ ConfigurationSource source)"
    instructionFingerprint: "41B197B481202FE128EBA47FDD88CA5A"
  paths:
  - pathId: "path3"
    testPathName: "getConfigurationWhenSourceIsNull"
    constructorSignature: "<init>() : void"
    modelFingerprint: "62B9225A06498E9452654B6B3E906F41"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "b125377e-dcb6-3615-ba4b-aee22691aeb4"
    deleted: true
    disabled: false
    ignoredBySystem: true
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
  - pathId: "path1"
    testPathName: "getConfigurationWhenSourceEqualsConfigurationSourceNULL_SOURCE"
    constructorSignature: "<init>() : void"
    modelFingerprint: "C889EC3D98812E48D154A850278D5A6F"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "loggerContext"
      modelFingerprint: "2998B5554F634D40BB4293DE2F216FE9"
      index: 2
      valueUuid: "getConfiguration_loggerContext1"
    - type: "INPUT"
      name: "source"
      modelFingerprint: "8838203671A50A379719880D16A21579"
      index: 3
      valueUuid: "getConfiguration_configurationSource2"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "F8A31053DE79FA0F2B75924A6BDBF854"
      index: 4
      valueUuid: "getConfiguration_configuration1"
    uuid: "73052bf0-4a32-37a1-b2f0-143ba6bfce23"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.logging.log4j2.SpringBootConfigurationFactory"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.logging.log4j2.SpringBootConfigurationFactory"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.apache.logging.log4j.core.LoggerContext"
        parameters:
        - name: "name"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "name1"
            valueType: "java.lang.String"
            uuid: "getConfiguration_loggerContext1-name"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.apache.logging.log4j.core.LoggerContext"
      uuid: "getConfiguration_loggerContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<static_field_return>
        target: "org.apache.logging.log4j.core.config.ConfigurationSource"
        fieldName: "NULL_SOURCE"
      valueType: "org.apache.logging.log4j.core.config.ConfigurationSource"
      uuid: "getConfiguration_configurationSource2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "NULL"
      valueType: "org.apache.logging.log4j.core.config.Configuration"
      uuid: "getConfiguration_configuration1"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "getConfigurationWhenSourceNotEqualsConfigurationSourceNULL_SOURCE"
    constructorSignature: "<init>() : void"
    modelFingerprint: "7A3E9AD738B0C9422A6E5494FAE4ADE4"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "loggerContext"
      modelFingerprint: "2998B5554F634D40BB4293DE2F216FE9"
      index: 2
      valueUuid: "getConfiguration_loggerContext1"
    - type: "INPUT"
      name: "source"
      modelFingerprint: "93978E2CC67582C3B3B2EE0C829FC515"
      index: 3
      valueUuid: "getConfiguration_configurationSource1"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "1F92AD124189D116DFB981C522F76CF2"
      index: 4
      valueUuid: "getConfiguration_defaultConfiguration1"
    uuid: "7af94ba2-bfc1-3a03-8017-404a37d735ad"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.logging.log4j2.SpringBootConfigurationFactory"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.logging.log4j2.SpringBootConfigurationFactory"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.apache.logging.log4j.core.LoggerContext"
        parameters:
        - name: "name"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "name1"
            valueType: "java.lang.String"
            uuid: "getConfiguration_loggerContext1-name"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.apache.logging.log4j.core.LoggerContext"
      uuid: "getConfiguration_loggerContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.apache.logging.log4j.core.config.ConfigurationSource"
        parameters:
        - name: "stream"
          value:
            sapientType: "INPUT_STREAM"
            content: !<inputStream>
              values: []
            valueType: "java.io.InputStream"
            uuid: "getConfiguration_configurationSource1-stream"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "file"
          value:
            sapientType: "OBJECT"
            content: !<new>
              target: "java.io.File"
              parameters:
              - name: "pathname"
                value:
                  sapientType: "BASIC"
                  content: !<regular>
                    value: "pathname1"
                  valueType: "java.lang.String"
                  uuid: "getConfiguration_configurationSource1-file-pathname"
                  fixed: false
                  equalsMethodPresent: false
                  explicitCastNeeded: false
              privateConstructor: false
              createdByTargetCode: false
            valueType: "java.io.File"
            uuid: "getConfiguration_configurationSource1-file"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.apache.logging.log4j.core.config.ConfigurationSource"
      uuid: "getConfiguration_configurationSource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.apache.logging.log4j.core.config.DefaultConfiguration"
        parameters: []
        privateConstructor: false
        createdByTargetCode: true
      valueType: "org.apache.logging.log4j.core.config.DefaultConfiguration"
      uuid: "getConfiguration_defaultConfiguration1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
