---
modelFingerprint: "D9991F975CD8F716D615E2329886E548"
methods:
- method:
    name: "getPriority"
    signature: "getPriority() : int"
    instructionFingerprint: "2FBDB3543CE71261301D6ADCCF1F7246"
  paths:
  - pathId: "path1"
    testPathName: "getPriorityTest"
    constructorSignature: "<init>(org.springframework.core.env.Environment) : void"
    filledByUser: false
    modelFingerprint: "0F5E2B802B6BDE03898ADC01376316AA"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "2662db8a-7513-3e23-abe0-a3f8c61b9e29"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "getProperty"
    signature: "getProperty(java.lang.String) : java.lang.String"
    instructionFingerprint: "6B67649ABEACBE03B97B35E99C0CEF91"
  paths:
  - pathId: "path1"
    testPathName: "getPropertyTest"
    constructorSignature: "<init>(org.springframework.core.env.Environment) : void"
    filledByUser: false
    modelFingerprint: "938CB04C7FA923E8C1C40A86F0BC2F3D"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "678A01727309E9EFD30DE56BC25CC979"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "key"
      modelFingerprint: "23A886133DA0141E522DC74D3398EA06"
      index: 2
      ignored: false
      valueUuid: "getProperty_string1"
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "24D0B207822049BB1C39F549CF08D362"
      index: 3
      ignored: false
      valueUuid: "uuid5"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_environment1"
        - name: "message"
          valueUuid: "uuid4"
        signature: "notNull(Environment,String): void"
        returnValueUuid: "<init>_void1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "FIELD"
      name: "environment"
      modelFingerprint: "B0F83B7D1DC54159656244CC14D16631"
      index: 4
      ignored: false
      valueUuid: "<init>_environment1"
      methodExercised:
        target: "this.environment"
        name: "getProperty"
        parameters:
        - name: "key"
          valueUuid: "getProperty_string1"
        signature: "getProperty(String): String"
        returnValueUuid: "getProperty_string2"
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D1F433D4EB9F8805FF391E82DAB508AB"
      index: 5
      ignored: false
      valueUuid: "getProperty_string2"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "ebf9d063-d15c-33a6-bbb2-427433abed69"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.logging.log4j2.SpringEnvironmentPropertySource"
        parameters:
        - name: "environment"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.core.env.Environment"
            uuid: "<init>_environment1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.logging.log4j2.SpringEnvironmentPropertySource"
        parameters:
        - name: "environment"
          value:
            sapientType: "UNKNOWN"
            suggestedContent: !<unknown_object>
              target: "org.springframework.core.env.Environment"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "org.springframework.core.env.Environment"
            uuid: "<init>_environment1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.logging.log4j2.SpringEnvironmentPropertySource"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "key1"
      valueType: "java.lang.String"
      uuid: "getProperty_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid5"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.Environment"
      uuid: "<init>_environment1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Environment must not be null"
      valueType: "java.lang.String"
      uuid: "uuid4"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.Environment"
      uuid: "<init>_environment1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "return_of_getProperty1"
      valueType: "java.lang.String"
      uuid: "getProperty_string2"
      fixed: false
      equalsMethodPresent: true
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "key1"
      valueType: "java.lang.String"
      uuid: "getProperty_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "return_of_getProperty1"
      valueType: "java.lang.String"
      uuid: "getProperty_string2"
      fixed: false
      equalsMethodPresent: true
      explicitCastNeeded: false
- method:
    name: "containsProperty"
    signature: "containsProperty(java.lang.String) : boolean"
    instructionFingerprint: "91933F0186E7671C46ADEDB6337C0F5B"
  paths:
  - pathId: "path1"
    testPathName: "containsPropertyWhenThisEnvironmentContainsPropertyKey"
    constructorSignature: "<init>(org.springframework.core.env.Environment) : void"
    filledByUser: false
    modelFingerprint: "7CF5EDE08550E6BE4DC495ADD982BBC4"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "678A01727309E9EFD30DE56BC25CC979"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "key"
      modelFingerprint: "23A886133DA0141E522DC74D3398EA06"
      index: 2
      ignored: false
      valueUuid: "containsProperty_string1"
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "24D0B207822049BB1C39F549CF08D362"
      index: 3
      ignored: false
      valueUuid: "uuid7"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_environment1"
        - name: "message"
          valueUuid: "uuid6"
        signature: "notNull(Environment,String): void"
        returnValueUuid: "<init>_void1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "FIELD"
      name: "environment"
      modelFingerprint: "A03D7420B4916723B6F2BB613DEE450D"
      index: 4
      ignored: false
      valueUuid: "<init>_environment1"
      methodExercised:
        target: "this.environment"
        name: "containsProperty"
        parameters:
        - name: "key"
          valueUuid: "containsProperty_string1"
        signature: "containsProperty(String): boolean"
        returnValueUuid: "containsProperty_boolean1"
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "753659628F1B3F179A2EF0629F555437"
      index: 5
      ignored: false
      valueUuid: "containsProperty_boolean1"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "5a23cf8e-7bfb-34f1-b4a9-69f056d700ca"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.logging.log4j2.SpringEnvironmentPropertySource"
        parameters:
        - name: "environment"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.core.env.Environment"
            uuid: "<init>_environment1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.logging.log4j2.SpringEnvironmentPropertySource"
        parameters:
        - name: "environment"
          value:
            sapientType: "UNKNOWN"
            suggestedContent: !<unknown_object>
              target: "org.springframework.core.env.Environment"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "org.springframework.core.env.Environment"
            uuid: "<init>_environment1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.logging.log4j2.SpringEnvironmentPropertySource"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "key1"
      valueType: "java.lang.String"
      uuid: "containsProperty_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid7"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.Environment"
      uuid: "<init>_environment1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Environment must not be null"
      valueType: "java.lang.String"
      uuid: "uuid6"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.Environment"
      uuid: "<init>_environment1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "containsProperty_boolean1"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "key1"
      valueType: "java.lang.String"
      uuid: "containsProperty_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "containsProperty_boolean1"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "containsPropertyWhenThisEnvironmentNotContainsPropertyKey"
    constructorSignature: "<init>(org.springframework.core.env.Environment) : void"
    filledByUser: false
    modelFingerprint: "1965D60B55C3CFD026B34249D17240B3"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "678A01727309E9EFD30DE56BC25CC979"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "key"
      modelFingerprint: "23A886133DA0141E522DC74D3398EA06"
      index: 2
      ignored: false
      valueUuid: "containsProperty_string1"
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "24D0B207822049BB1C39F549CF08D362"
      index: 3
      ignored: false
      valueUuid: "uuid9"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_environment1"
        - name: "message"
          valueUuid: "uuid8"
        signature: "notNull(Environment,String): void"
        returnValueUuid: "<init>_void1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "FIELD"
      name: "environment"
      modelFingerprint: "65D928EC006BCC671CC6B4C4528189AD"
      index: 4
      ignored: false
      valueUuid: "<init>_environment1"
      methodExercised:
        target: "this.environment"
        name: "containsProperty"
        parameters:
        - name: "key"
          valueUuid: "containsProperty_string1"
        signature: "containsProperty(String): boolean"
        returnValueUuid: "containsProperty_boolean1"
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "3A21543F56248AC92654D6E439128AED"
      index: 5
      ignored: false
      valueUuid: "containsProperty_boolean1"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "3651f12b-ad92-378b-9faf-e62ddd5dc74c"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.logging.log4j2.SpringEnvironmentPropertySource"
        parameters:
        - name: "environment"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.core.env.Environment"
            uuid: "<init>_environment1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.logging.log4j2.SpringEnvironmentPropertySource"
        parameters:
        - name: "environment"
          value:
            sapientType: "UNKNOWN"
            suggestedContent: !<unknown_object>
              target: "org.springframework.core.env.Environment"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "org.springframework.core.env.Environment"
            uuid: "<init>_environment1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.logging.log4j2.SpringEnvironmentPropertySource"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "key1"
      valueType: "java.lang.String"
      uuid: "containsProperty_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid9"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.Environment"
      uuid: "<init>_environment1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Environment must not be null"
      valueType: "java.lang.String"
      uuid: "uuid8"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.Environment"
      uuid: "<init>_environment1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "containsProperty_boolean1"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "key1"
      valueType: "java.lang.String"
      uuid: "containsProperty_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "containsProperty_boolean1"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
