---
modelFingerprint: "66DEB52E15916446DCD4D5462EBBDEBE"
methods:
- method:
    name: "lookup"
    returnType: "java.lang.String"
    signature: "lookup(java.lang.String) : java.lang.String"
    instructionFingerprint: "989F3A20300463DEFE4F99D7686C93BC"
    parametersTypes:
    - "java.lang.String"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "lookup1WhenThisEnvironmentIsNull"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "9D880B8D2F770947A565D687A152DE6E"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.logging.log4j2.SpringEnvironmentLookup"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
          propertiesMap:
            environment:
              sapientType: "MOCK"
              suggestedContent: !<unknown_object>
                target: "org.springframework.core.env.Environment"
                onlyPojoFunctions: false
                builderPattern: false
              valueType: "org.springframework.core.env.Environment"
              uuid: "environment1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
        suggestedContent: !<new>
          target: "org.springframework.boot.logging.log4j2.SpringEnvironmentLookup"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
          propertiesMap:
            environment:
              sapientType: "UNKNOWN"
              suggestedContent: !<unknown_object>
                target: "org.springframework.core.env.Environment"
                onlyPojoFunctions: false
                builderPattern: false
              valueType: "org.springframework.core.env.Environment"
              uuid: "environment1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
        valueType: "org.springframework.boot.logging.log4j2.SpringEnvironmentLookup"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "key"
      modelFingerprint: "23A886133DA0141E522DC74D3398EA06"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "BASIC"
        content: !<regular>
          value: "key1"
        valueType: "java.lang.String"
        uuid: "lookup_string1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "F46FE07B236FD656CA45BC236173D2CA"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "state"
        parameters:
        - name: "expression"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: false
            valueType: "boolean"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Unable to obtain Spring Environment from LoggerContext"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "state(boolean,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "lookup_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "FIELD"
      name: "environment"
      modelFingerprint: "48989B556CD38FD1A3CC1D340065E1A2"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "org.springframework.core.env.Environment"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "org.springframework.core.env.Environment"
        uuid: "environment1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "this.environment"
        name: "getProperty"
        parameters:
        - name: "arg0"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "key1"
            valueType: "java.lang.String"
            uuid: "lookup_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "getProperty(String): String"
        returnValue:
          sapientType: "BASIC"
          content: !<regular>
            value: "return_of_getProperty1"
          valueType: "java.lang.String"
          uuid: "lookup_string2"
          fixed: false
          equalsMethodPresent: true
          explicitCastNeeded: false
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D1F433D4EB9F8805FF391E82DAB508AB"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "BASIC"
        content: !<regular>
          value: "return_of_getProperty1"
        valueType: "java.lang.String"
        uuid: "lookup_string2"
        fixed: false
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "a16791f1-0bc3-3c28-a5f5-c1c0840540e6"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "UNKNOWN_REASON"
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
- method:
    name: "setLoggerContext"
    returnType: "void"
    signature: "setLoggerContext(org.apache.logging.log4j.core.LoggerContext) : void"
    instructionFingerprint: "7B2B9A91FA9D17DBC0B9C4C91D735E8B"
    parametersTypes:
    - "org.apache.logging.log4j.core.LoggerContext"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "setLoggerContextTest"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "31901E853FAD30E3D73E56677908FCE1"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.logging.log4j2.SpringEnvironmentLookup"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.logging.log4j2.SpringEnvironmentLookup"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.logging.log4j2.SpringEnvironmentLookup"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "loggerContext"
      modelFingerprint: "2998B5554F634D40BB4293DE2F216FE9"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.apache.logging.log4j.core.LoggerContext"
          parameters:
          - name: "name"
            value:
              sapientType: "BASIC"
              content: !<regular>
                value: "name1"
              valueType: "java.lang.String"
              uuid: "setLoggerContext_loggerContext1-name"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.apache.logging.log4j.core.LoggerContext"
          parameters:
          - name: "name"
            value:
              sapientType: "BASIC"
              valueType: "java.lang.String"
              uuid: "setLoggerContext_loggerContext1-name"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.apache.logging.log4j.core.LoggerContext"
        uuid: "setLoggerContext_loggerContext1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Log4J2LoggingSystem"
      modelFingerprint: "0D194E2259A0FA3BE9EE60A09A64F47D"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.boot.logging.log4j2.Log4J2LoggingSystem"
        uuid: "org.springframework.boot.logging.log4j2.Log4J2LoggingSystem"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.boot.logging.log4j2.Log4J2LoggingSystem"
        name: "getEnvironment"
        parameters:
        - name: "loggerContext"
          value:
            sapientType: "OBJECT"
            content: !<new>
              target: "org.apache.logging.log4j.core.LoggerContext"
              parameters:
              - name: "name"
                value:
                  sapientType: "BASIC"
                  content: !<regular>
                    value: "name1"
                  valueType: "java.lang.String"
                  uuid: "setLoggerContext_loggerContext1-name"
                  fixed: false
                  equalsMethodPresent: false
                  explicitCastNeeded: false
              privateConstructor: false
              createdByTargetCode: false
            suggestedContent: !<new>
              target: "org.apache.logging.log4j.core.LoggerContext"
              parameters:
              - name: "name"
                value:
                  sapientType: "BASIC"
                  valueType: "java.lang.String"
                  uuid: "setLoggerContext_loggerContext1-name"
                  fixed: false
                  equalsMethodPresent: false
                  explicitCastNeeded: false
              privateConstructor: false
              createdByTargetCode: false
            valueType: "org.apache.logging.log4j.core.LoggerContext"
            uuid: "setLoggerContext_loggerContext1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "getEnvironment(LoggerContext): Environment"
        returnValue:
          sapientType: "MOCK"
          valueType: "org.springframework.core.env.Environment"
          uuid: "setLoggerContext_environment1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "VOID"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "7a5846a5-15d9-38ce-8d4b-9b708230d1b3"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
