---
modelFingerprint: "0C8C70386ACC5662A69A46A735FCA237"
methods:
- method:
    name: "doFilterInternal"
    signature: "doFilterInternal(jakarta.servlet.http.HttpServletRequest,jakarta.servlet.http.HttpServletResponse,jakarta.servlet.FilterChain)\
      \ : void"
    instructionFingerprint: "3F0C713BED9DF3A74BA857096E295B6E"
  paths:
  - pathId: "path1"
    testPathName: "doFilterInternalTest"
    constructorSignature: "<init>(org.springframework.context.ApplicationContext)\
      \ : void"
    filledByUser: false
    modelFingerprint: "E821F4F9FCF78139428ACFCC8F667E6B"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "FBFCE379638023B65A1141944964AFC7"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "request"
      modelFingerprint: "A9E0A9B4360F59391DE5FE1E55396E86"
      index: 2
      ignored: false
      valueUuid: "doFilterInternal_httpServletRequest1"
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "response"
      modelFingerprint: "954D9FD69E4D5680E3B644B2FDEF4A9E"
      index: 3
      ignored: false
      valueUuid: "doFilterInternal_httpServletResponse1"
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "filterChain"
      modelFingerprint: "32E278812A46D29CBF3C5C8FBE26AA7C"
      index: 4
      ignored: false
      valueUuid: "doFilterInternal_filterChain1"
      staticReadMethodForField: false
      filledByUser: false
    - type: "FIELD"
      name: "applicationContext"
      modelFingerprint: "BEA2C9487060EE579BB9897679F536C1"
      index: 5
      ignored: false
      valueUuid: "<init>_applicationContext1"
      methodExercised:
        target: "this.applicationContext"
        name: "getId"
        parameters: []
        signature: "getId(): String"
        returnValueUuid: "doFilterInternal_string1"
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "response"
      modelFingerprint: "114EF6CD2EF48896B3A4D22AAB0EBBFD"
      index: 6
      ignored: false
      valueUuid: "doFilterInternal_httpServletResponse1"
      methodExercised:
        target: "response"
        name: "addHeader"
        parameters:
        - name: "arg0"
          valueUuid: "uuid1"
        - name: "arg1"
          valueUuid: "doFilterInternal_string1"
        signature: "addHeader(String,String): void"
        returnValueUuid: "doFilterInternal_void1"
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "filterChain"
      modelFingerprint: "480F9A855BE51F6A87DC83CB11A820F3"
      index: 7
      ignored: false
      valueUuid: "doFilterInternal_filterChain1"
      methodExercised:
        target: "filterChain"
        name: "doFilter"
        parameters:
        - name: "arg0"
          valueUuid: "doFilterInternal_httpServletRequest1"
        - name: "arg1"
          valueUuid: "doFilterInternal_httpServletResponse1"
        throwsExceptions:
        - "java.io.IOException"
        - "jakarta.servlet.ServletException"
        signature: "doFilter(HttpServletRequest,HttpServletResponse): void throws\
          \ java.io.IOException,jakarta.servlet.ServletException"
        returnValueUuid: "doFilterInternal_void2"
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 8
      ignored: false
      valueUuid: "uuid2"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "5722faad-00bb-3006-971f-ae8d2d1a8d80"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.filter.ApplicationContextHeaderFilter"
        parameters:
        - name: "context"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.context.ApplicationContext"
            uuid: "<init>_applicationContext1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.web.servlet.filter.ApplicationContextHeaderFilter"
        parameters:
        - name: "context"
          value:
            sapientType: "UNKNOWN"
            suggestedContent: !<unknown_object>
              target: "org.springframework.context.ApplicationContext"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "org.springframework.context.ApplicationContext"
            uuid: "<init>_applicationContext1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.web.servlet.filter.ApplicationContextHeaderFilter"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "jakarta.servlet.http.HttpServletRequest"
      uuid: "doFilterInternal_httpServletRequest1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "jakarta.servlet.http.HttpServletResponse"
      uuid: "doFilterInternal_httpServletResponse1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "jakarta.servlet.FilterChain"
      uuid: "doFilterInternal_filterChain1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ApplicationContext"
      uuid: "<init>_applicationContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "return_of_getId1"
      valueType: "java.lang.String"
      uuid: "doFilterInternal_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "jakarta.servlet.http.HttpServletResponse"
      uuid: "doFilterInternal_httpServletResponse1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "doFilterInternal_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "X-Application-Context"
      valueType: "java.lang.String"
      uuid: "uuid1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "return_of_getId1"
      valueType: "java.lang.String"
      uuid: "doFilterInternal_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "jakarta.servlet.FilterChain"
      uuid: "doFilterInternal_filterChain1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "doFilterInternal_void2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "jakarta.servlet.http.HttpServletRequest"
      uuid: "doFilterInternal_httpServletRequest1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "jakarta.servlet.http.HttpServletResponse"
      uuid: "doFilterInternal_httpServletResponse1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      uuid: "uuid2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
