---
modelFingerprint: "AB02321256C9A61A02E451525145EC35"
methods:
- method:
    name: "getProperty"
    returnType: "java.lang.String"
    signature: "getProperty() : java.lang.String"
    instructionFingerprint: "68856DEC5AFA68A1962112DFC474B281"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getPropertyTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.String) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "C07ECD920FF875EC547AA783F3C031D8"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "ebf9d063-d15c-33a6-bbb2-427433abed69"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "equals"
    returnType: "boolean"
    signature: "equals(java.lang.Object) : boolean"
    instructionFingerprint: "A4B5E4F52A5D5A68FEBE8068D8C1228E"
    parametersTypes:
    - "java.lang.Object"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "equalsWhenThisEqualsObj"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.String) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "B177884F02E7B1CECDDCE353D435F24F"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "d0712d51-f0f8-381e-af89-bd29c8516608"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path5"
    pathIdForUser: "path2"
    testPathName: "equalsWhenObjIsNull"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.String) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "AF382FE0970CDE7CDAB34AF01B527D93"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "42f03dea-2e61-3c4b-bbc0-1a97b94b4d90"
    deleted: true
    disabled: false
    ignoredBySystem: true
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path2"
    pathIdForUser: "path3"
    testPathName: "equalsWhenGetClassNotEqualsObjGetClass"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.String) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "30FB7DC31FB760446AA17795782B75CD"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "26ff6ba6-6f29-3ff2-bca0-b8c532e7a53b"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path3"
    pathIdForUser: "path4"
    testPathName: "equalsWhenObjectUtilsNullSafeEqualsThisPropertyOtherProperty"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.String) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "AE4918A24EC7C592171AAF2FD993C737"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "b8d9e4ac-fa06-3d79-b0e0-90585e14b822"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path4"
    pathIdForUser: "path5"
    testPathName: "equalsWhenObjectUtilsNotNullSafeEqualsThisPropertyOtherProperty"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.String) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "78DAFA55F3E682B59337F8072BB317DC"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "2f24eb49-bb30-301f-a774-faa9887326a6"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "toString"
    returnType: "java.lang.String"
    signature: "toString() : java.lang.String"
    instructionFingerprint: "8DEB13D9E193B32860B7C332082A66CD"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "toStringTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.String) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "F96E5C60EF847E4EF0248995A45BC1E5"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "2356BB48004A81A5B004535B46522E99"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.origin.SystemEnvironmentOrigin"
          parameters:
          - name: "property"
            value:
              sapientType: "BASIC"
              content: !<regular>
                value: "A"
              suggestedContent: !<regular>
                value: "A"
              valueType: "java.lang.String"
              uuid: "<init>_string1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.origin.SystemEnvironmentOrigin"
          parameters:
          - name: "property"
            value:
              sapientType: "BASIC"
              suggestedContent: !<regular>
                value: "A"
              valueType: "java.lang.String"
              uuid: "<init>_string1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.origin.SystemEnvironmentOrigin"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "FC64DC9FF322A93193138934A45720D3"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "A"
            suggestedContent: !<regular>
              value: "A"
            valueType: "java.lang.String"
            uuid: "<init>_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Property name must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(String,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "<init>_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "C8B42013C3A792F5CA3D6AE93E558755"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "hasText"
        parameters:
        - name: "text"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "A"
            suggestedContent: !<regular>
              value: "A"
            valueType: "java.lang.String"
            uuid: "<init>_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Property name must not be empty"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "hasText(String,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "<init>_void2"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "28999FCFAFAF6680EFD68E60106CF6DF"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "BASIC"
        content: !<regular>
          value: "System Environment Property \\\"A\\\""
        suggestedContent: !<regular>
          value: "System Environment Property \\\"A\\\""
        valueType: "java.lang.String"
        uuid: "toString_string1"
        fixed: false
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "363d3698-f34c-39ad-914f-376a19498023"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
