---
modelFingerprint: "BA86D6BDAEBA4E3872DB874F5EDB061E"
methods:
- method:
    name: "getProperty"
    signature: "getProperty() : java.lang.String"
    sourceCodeSignature: "String getProperty()"
    instructionFingerprint: "68856DEC5AFA68A1962112DFC474B281"
  paths:
  - pathId: "path1"
    testPathName: "getPropertyTest"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "C07ECD920FF875EC547AA783F3C031D8"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "ebf9d063-d15c-33a6-bbb2-427433abed69"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "equals"
    signature: "equals(java.lang.Object) : boolean"
    sourceCodeSignature: "boolean equals(Object obj)"
    instructionFingerprint: "A4B5E4F52A5D5A68FEBE8068D8C1228E"
  paths:
  - pathId: "path1"
    testPathName: "equalsWhenThisEqualsObj"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "BB2CF785582935CDE7E4F1FE1F96EDBF"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "d0712d51-f0f8-381e-af89-bd29c8516608"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
  - pathId: "path5"
    testPathName: "equalsWhenObjIsNull"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "AF382FE0970CDE7CDAB34AF01B527D93"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "42f03dea-2e61-3c4b-bbc0-1a97b94b4d90"
    deleted: true
    disabled: false
    ignoredBySystem: true
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
  - pathId: "path2"
    testPathName: "equalsWhenGetClassNotEqualsObjGetClass"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "30FB7DC31FB760446AA17795782B75CD"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "26ff6ba6-6f29-3ff2-bca0-b8c532e7a53b"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
  - pathId: "path3"
    testPathName: "equalsWhenObjectUtilsNullSafeEqualsThisPropertyOtherProperty"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "AE4918A24EC7C592171AAF2FD993C737"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "b8d9e4ac-fa06-3d79-b0e0-90585e14b822"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
  - pathId: "path4"
    testPathName: "equalsWhenObjectUtilsNotNullSafeEqualsThisPropertyOtherProperty"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "78DAFA55F3E682B59337F8072BB317DC"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "2f24eb49-bb30-301f-a774-faa9887326a6"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "toString"
    signature: "toString() : java.lang.String"
    sourceCodeSignature: "String toString()"
    instructionFingerprint: "8DEB13D9E193B32860B7C332082A66CD"
  paths:
  - pathId: "path1"
    testPathName: "toStringTest"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "F96E5C60EF847E4EF0248995A45BC1E5"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "2356BB48004A81A5B004535B46522E99"
      index: 1
      valueUuid: "target"
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "FC64DC9FF322A93193138934A45720D3"
      index: 2
      valueUuid: "uuid31"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_string1"
        - name: "message"
          valueUuid: "uuid30"
        signature: "notNull(String,String): void"
        returnValueUuid: "<init>_void1"
        access: 9
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "C8B42013C3A792F5CA3D6AE93E558755"
      index: 3
      valueUuid: "uuid33"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "hasText"
        parameters:
        - name: "text"
          valueUuid: "<init>_string1"
        - name: "message"
          valueUuid: "uuid32"
        signature: "hasText(String,String): void"
        returnValueUuid: "<init>_void2"
        access: 9
    - type: "RESULT"
      name: "result"
      modelFingerprint: "28999FCFAFAF6680EFD68E60106CF6DF"
      index: 4
      valueUuid: "toString_string1"
    uuid: "363d3698-f34c-39ad-914f-376a19498023"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.origin.SystemEnvironmentOrigin"
        parameters:
        - name: "property"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "A"
            valueType: "java.lang.String"
            uuid: "<init>_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.origin.SystemEnvironmentOrigin"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid31"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "<init>_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Property name must not be null"
      valueType: "java.lang.String"
      uuid: "uuid30"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid33"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "<init>_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Property name must not be empty"
      valueType: "java.lang.String"
      uuid: "uuid32"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "System Environment Property \\\"A\\\""
      valueType: "java.lang.String"
      uuid: "toString_string1"
      fixed: false
      equalsMethodPresent: true
      explicitCastNeeded: false
