---
modelFingerprint: "245512C21E6B92DF828AE3190F944F6E"
methods:
- method:
    name: "stream"
    signature: "stream() : java.util.stream.Stream<org.springframework.boot.context.properties.source.ConfigurationPropertyName>"
    instructionFingerprint: "874FCD71A0A981E2FFB5277947E0B482"
  paths:
  - pathId: "path1"
    testPathName: "streamTest"
    constructorSignature: "<init>(org.springframework.boot.context.properties.source.IterableConfigurationPropertySource,org.springframework.boot.context.properties.source.ConfigurationPropertyNameAliases)\
      \ : void"
    filledByUser: false
    modelFingerprint: "16881175CEC81517D592ACDFA082E5C9"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "CE09A2D36160389B05B7F39FFA8E4565"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "3BCF9F71C3464BC4B8DD432AD321B6D9"
      index: 2
      ignored: false
      valueUuid: "uuid2"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_iterableConfigurationPropertySource1"
        - name: "message"
          valueUuid: "uuid1"
        signature: "notNull(IterableConfigurationPropertySource,String): void"
        returnValueUuid: "<init>_void1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "200466189AD84BFA7EAA32C91B2F6C8A"
      index: 3
      ignored: false
      valueUuid: "uuid4"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_configurationPropertyNameAliases1"
        - name: "message"
          valueUuid: "uuid3"
        signature: "notNull(ConfigurationPropertyNameAliases,String): void"
        returnValueUuid: "<init>_void2"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "INTERNAL"
      name: "internalMethod"
      modelFingerprint: "ABD3BA9BDB07FBA37DB2E6C185F38490"
      index: 4
      ignored: false
      methodExercised:
        target: "target"
        name: "getSource"
        parameters: []
        signature: "getSource(): IterableConfigurationPropertySource"
        returnValueUuid: "stream_iterableConfigurationPropertySource1"
        access: 4
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "F6F308D2A4A43F315058DFB56F570F64"
      index: 5
      ignored: false
      valueUuid: "stream_iterableConfigurationPropertySource1"
      methodExercised:
        target: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
        name: "stream"
        parameters: []
        signature: "stream(): Stream"
        returnValueUuid: "stream_stream1"
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "C753BC527FB9F94CD92387C5F4B57BA4"
      index: 6
      ignored: false
      valueUuid: "stream_stream2"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "b4af2388-e781-3800-820a-b8ede09bd914"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.util.stream.Stream.flatMap(java.util.function.Function)\
        \ : java.util.stream.Stream<org.springframework.boot.context.properties.source.ConfigurationPropertyName>"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.AliasedIterableConfigurationPropertySource"
        parameters:
        - name: "source"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
            uuid: "<init>_iterableConfigurationPropertySource1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "aliases"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyNameAliases"
            uuid: "<init>_configurationPropertyNameAliases1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.context.properties.source.AliasedIterableConfigurationPropertySource"
        parameters:
        - name: "source"
          value:
            sapientType: "UNKNOWN"
            valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
            uuid: "<init>_iterableConfigurationPropertySource1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "aliases"
          value:
            sapientType: "UNKNOWN"
            valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyNameAliases"
            uuid: "<init>_configurationPropertyNameAliases1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.source.AliasedIterableConfigurationPropertySource"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
      uuid: "<init>_iterableConfigurationPropertySource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Source must not be null"
      valueType: "java.lang.String"
      uuid: "uuid1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid4"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyNameAliases"
      uuid: "<init>_configurationPropertyNameAliases1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Aliases must not be null"
      valueType: "java.lang.String"
      uuid: "uuid3"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
      uuid: "stream_iterableConfigurationPropertySource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
      uuid: "stream_iterableConfigurationPropertySource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.util.stream.Stream"
        method: "empty"
        methodParameters: []
      suggestedContent: !<static_method_return>
        target: "java.util.stream.Stream"
        method: "empty"
        methodParameters: []
      valueType: "java.util.stream.Stream"
      uuid: "stream_stream1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.util.stream.Stream"
        method: "empty"
        methodParameters: []
      suggestedContent: !<static_method_return>
        target: "java.util.stream.Stream"
        method: "empty"
        methodParameters: []
      valueType: "java.util.stream.Stream"
      uuid: "stream_stream2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
- method:
    name: "getSource"
    signature: "getSource() : org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
    instructionFingerprint: "3EC400BDAF5814B52DCD3AD800B2BE43"
  paths:
  - pathId: "path1"
    testPathName: "getSource1Test"
    constructorSignature: "<init>(org.springframework.boot.context.properties.source.IterableConfigurationPropertySource,org.springframework.boot.context.properties.source.ConfigurationPropertyNameAliases)\
      \ : void"
    filledByUser: false
    modelFingerprint: "A17C129C6912D4283650524DA9998126"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "CE09A2D36160389B05B7F39FFA8E4565"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "3BCF9F71C3464BC4B8DD432AD321B6D9"
      index: 2
      ignored: false
      valueUuid: "uuid6"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_iterableConfigurationPropertySource1"
        - name: "message"
          valueUuid: "uuid5"
        signature: "notNull(IterableConfigurationPropertySource,String): void"
        returnValueUuid: "<init>_void1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "200466189AD84BFA7EAA32C91B2F6C8A"
      index: 3
      ignored: false
      valueUuid: "uuid8"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_configurationPropertyNameAliases1"
        - name: "message"
          valueUuid: "uuid7"
        signature: "notNull(ConfigurationPropertyNameAliases,String): void"
        returnValueUuid: "<init>_void2"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "B858CC7ADF4138B2495DFF7300E5B929"
      index: 4
      ignored: false
      valueUuid: "<init>_iterableConfigurationPropertySource1"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "bfcb6725-5fb8-3080-8655-dc87e9921af1"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.AliasedIterableConfigurationPropertySource"
        parameters:
        - name: "source"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
            uuid: "<init>_iterableConfigurationPropertySource1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "aliases"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyNameAliases"
            uuid: "<init>_configurationPropertyNameAliases1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.context.properties.source.AliasedIterableConfigurationPropertySource"
        parameters:
        - name: "source"
          value:
            sapientType: "UNKNOWN"
            valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
            uuid: "<init>_iterableConfigurationPropertySource1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "aliases"
          value:
            sapientType: "UNKNOWN"
            valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyNameAliases"
            uuid: "<init>_configurationPropertyNameAliases1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.source.AliasedIterableConfigurationPropertySource"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid6"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
      uuid: "<init>_iterableConfigurationPropertySource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Source must not be null"
      valueType: "java.lang.String"
      uuid: "uuid5"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid8"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyNameAliases"
      uuid: "<init>_configurationPropertyNameAliases1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Aliases must not be null"
      valueType: "java.lang.String"
      uuid: "uuid7"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
      uuid: "<init>_iterableConfigurationPropertySource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
