---
modelFingerprint: "2217EB965349025C8AAC09253CB5A4B9"
methods:
- method:
    name: "search"
    signature: "search(java.lang.Iterable<java.lang.Object>,java.util.function.Predicate<java.lang.Object>)\
      \ : org.springframework.boot.context.properties.source.ConfigurationPropertyState"
    instructionFingerprint: "15BE33C472B9C4B7425E811BA42FE78F"
  paths:
  - pathId: "path3"
    testPathName: "searchWhenSourceIsEmpty"
    filledByUser: false
    modelFingerprint: "FCF12276E277B0A5500BC1AC1EA37FA1"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "f8f5b892-5b0c-34e2-9864-d998ead7c60e"
    deleted: true
    disabled: false
    ignoredBySystem: true
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
  - pathId: "path1"
    testPathName: "searchWhenPredicateTestItem"
    filledByUser: false
    modelFingerprint: "2D4CEC2B7ED3B73DEFC62779C691A1FF"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "INPUT"
      name: "source"
      modelFingerprint: "687BFBC3C83E03C43843D5FAEBB2C203"
      index: 1
      ignored: false
      valueUuid: "search_iterable1"
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "predicate"
      modelFingerprint: "63CA3418964693573E3DBF8FEE63F255"
      index: 2
      ignored: false
      valueUuid: "search_predicate1"
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "34439DF793BEAB00BB1D0A058DBBC052"
      index: 3
      ignored: false
      valueUuid: "uuid2"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "search_iterable1"
        - name: "message"
          valueUuid: "uuid1"
        signature: "notNull(Iterable,String): void"
        returnValueUuid: "search_void1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "2230B8E05A4EB052E39DF1B39F8DBAB4"
      index: 4
      ignored: false
      valueUuid: "uuid4"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "search_predicate1"
        - name: "message"
          valueUuid: "uuid3"
        signature: "notNull(Predicate,String): void"
        returnValueUuid: "search_void2"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "predicate"
      modelFingerprint: "F1035C4F95D99D158F8A46C457FFDD1F"
      index: 5
      ignored: false
      valueUuid: "search_predicate1"
      methodExercised:
        target: "predicate"
        name: "test"
        parameters:
        - name: "arg0"
          valueUuid: "search_iterable1-0"
        signature: "test(Object): boolean"
        returnValueUuid: "search_boolean2"
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "215C6D4AFC6B5001AC9D2FA01D518C77"
      index: 6
      ignored: false
      valueUuid: "Enum-org.springframework.boot.context.properties.source.ConfigurationPropertyState-PRESENT"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "06fff9e8-aab3-3323-9bf4-83f0394f49b3"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "LLM"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values:
        - sapientType: "OBJECT"
          content: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          suggestedContent: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          valueType: "java.lang.Object"
          uuid: "search_iterable1-0"
          fixed: false
          collectionUuid: "search_iterable1"
          equalsMethodPresent: false
          explicitCastNeeded: false
      suggestedContent: !<collection>
        parameters: []
        values:
        - sapientType: "OBJECT"
          content: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          suggestedContent: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          valueType: "java.lang.Object"
          uuid: "search_iterable1-0"
          fixed: false
          collectionUuid: "search_iterable1"
          equalsMethodPresent: false
          explicitCastNeeded: false
      valueType: "java.lang.Iterable"
      genericValueType: "java.lang.Object"
      uuid: "search_iterable1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "java.util.function.Predicate"
      uuid: "search_predicate1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "REAL"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "search_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values:
        - sapientType: "OBJECT"
          content: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          suggestedContent: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          valueType: "java.lang.Object"
          uuid: "search_iterable1-0"
          fixed: false
          collectionUuid: "search_iterable1"
          equalsMethodPresent: false
          explicitCastNeeded: false
      suggestedContent: !<collection>
        parameters: []
        values:
        - sapientType: "OBJECT"
          content: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          suggestedContent: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          valueType: "java.lang.Object"
          uuid: "search_iterable1-0"
          fixed: false
          collectionUuid: "search_iterable1"
          equalsMethodPresent: false
          explicitCastNeeded: false
      valueType: "java.lang.Iterable"
      genericValueType: "java.lang.Object"
      uuid: "search_iterable1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Source must not be null"
      valueType: "java.lang.String"
      uuid: "uuid1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid4"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "search_void2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "java.util.function.Predicate"
      uuid: "search_predicate1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Predicate must not be null"
      valueType: "java.lang.String"
      uuid: "uuid3"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "java.util.function.Predicate"
      uuid: "search_predicate1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      suggestedContent: !<regular>
        value: true
      valueType: "boolean"
      uuid: "search_boolean2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "java.lang.Object"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "java.lang.Object"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "java.lang.Object"
      uuid: "search_iterable1-0"
      fixed: false
      collectionUuid: "search_iterable1"
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "ENUM"
      content: !<regular>
        value: "PRESENT"
      valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyState"
      uuid: "Enum-org.springframework.boot.context.properties.source.ConfigurationPropertyState-PRESENT"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "searchWhenPredicateNotTestItem"
    filledByUser: false
    modelFingerprint: "2ECBA51EDAE9F3B9D7B1861E4A72F00E"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "INPUT"
      name: "source"
      modelFingerprint: "0CD37021AEE35B1550A53B993D54141C"
      index: 1
      ignored: false
      valueUuid: "search_iterable1"
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "predicate"
      modelFingerprint: "5AB160B1932BFCC24800D287A98C368D"
      index: 2
      ignored: false
      valueUuid: "search_predicate1"
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "0563147BCC556B37F040960B91FAAD22"
      index: 3
      ignored: false
      valueUuid: "uuid10"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "search_iterable1"
        - name: "message"
          valueUuid: "uuid9"
        signature: "notNull(Iterable,String): void"
        returnValueUuid: "search_void1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "55779EEE47C46E4306B2E65D8107E32A"
      index: 4
      ignored: false
      valueUuid: "uuid12"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "search_predicate1"
        - name: "message"
          valueUuid: "uuid11"
        signature: "notNull(Predicate,String): void"
        returnValueUuid: "search_void2"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "75431720ECDEA53E347CAC6A8C13518F"
      index: 5
      ignored: false
      valueUuid: "Enum-org.springframework.boot.context.properties.source.ConfigurationPropertyState-ABSENT"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "f328f7bb-da87-3b6f-9463-4aa7094b1003"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.util.function.Predicate.test(java.lang.Object)\
        \ : boolean"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values:
        - sapientType: "OBJECT"
          content: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          suggestedContent: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          valueType: "java.lang.Object"
          uuid: "search_object1"
          fixed: false
          collectionUuid: "search_iterable1"
          equalsMethodPresent: false
          explicitCastNeeded: false
      suggestedContent: !<collection>
        parameters: []
        values:
        - sapientType: "OBJECT"
          content: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          suggestedContent: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          valueType: "java.lang.Object"
          uuid: "search_object1"
          fixed: false
          collectionUuid: "search_iterable1"
          equalsMethodPresent: false
          explicitCastNeeded: false
      valueType: "java.lang.Iterable"
      genericValueType: "java.lang.Object"
      uuid: "search_iterable1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "java.util.function.Predicate"
      uuid: "search_predicate1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid10"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "search_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values:
        - sapientType: "OBJECT"
          content: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          suggestedContent: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          valueType: "java.lang.Object"
          uuid: "search_object1"
          fixed: false
          collectionUuid: "search_iterable1"
          equalsMethodPresent: false
          explicitCastNeeded: false
      suggestedContent: !<collection>
        parameters: []
        values:
        - sapientType: "OBJECT"
          content: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          suggestedContent: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          valueType: "java.lang.Object"
          uuid: "search_object1"
          fixed: false
          collectionUuid: "search_iterable1"
          equalsMethodPresent: false
          explicitCastNeeded: false
      valueType: "java.lang.Iterable"
      genericValueType: "java.lang.Object"
      uuid: "search_iterable1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Source must not be null"
      valueType: "java.lang.String"
      uuid: "uuid9"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid12"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "search_void2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "java.util.function.Predicate"
      uuid: "search_predicate1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Predicate must not be null"
      valueType: "java.lang.String"
      uuid: "uuid11"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "ENUM"
      content: !<regular>
        value: "ABSENT"
      valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyState"
      uuid: "Enum-org.springframework.boot.context.properties.source.ConfigurationPropertyState-ABSENT"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
