---
modelFingerprint: "1D8000A8BDAC46295E0500EEE4502629"
methods:
- method:
    name: "search"
    returnType: "org.springframework.boot.context.properties.source.ConfigurationPropertyState"
    signature: "search(java.lang.Iterable<java.lang.Object>,java.util.function.Predicate<java.lang.Object>)\
      \ : org.springframework.boot.context.properties.source.ConfigurationPropertyState"
    instructionFingerprint: "15BE33C472B9C4B7425E811BA42FE78F"
    parametersTypes:
    - "java.lang.Iterable"
    - "java.util.function.Predicate"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "searchWhenPredicateTestItem"
    nameDefinedByUser: false
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "5C57729E777A3E36D4039F6138B70626"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "INPUT"
      name: "source"
      modelFingerprint: "F543B4FC5A9B8FB5F402851D531FF1A2"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "NULL"
        suggestedContent: !<unknown_object>
          target: "java.lang.Iterable"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "java.lang.Iterable"
        uuid: "search_iterable1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "predicate"
      modelFingerprint: "AEDCF931C4A3A1BB4742E18EDDE82D3D"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "NULL"
        suggestedContent: !<unknown_object>
          target: "java.util.function.Predicate"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "java.util.function.Predicate"
        uuid: "search_predicate1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "D10B250EDA4A17F7E530BCC1306C03F4"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "NULL"
            suggestedContent: !<unknown_object>
              target: "java.lang.Iterable"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "java.lang.Iterable"
            uuid: "search_iterable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Source must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(Iterable,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "search_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "8B7F62189720970AD9017D1A3497BACB"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "NULL"
            suggestedContent: !<unknown_object>
              target: "java.util.function.Predicate"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "java.util.function.Predicate"
            uuid: "search_predicate1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Predicate must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(Predicate,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "search_void2"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "215C6D4AFC6B5001AC9D2FA01D518C77"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "ENUM"
        content: !<regular>
          value: "PRESENT"
        valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyState"
        uuid: "Enum-org.springframework.boot.context.properties.source.ConfigurationPropertyState-PRESENT"
        fixed: true
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "06fff9e8-aab3-3323-9bf4-83f0394f49b3"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
  - pathId: "path2"
    pathIdForUser: "path2"
    testPathName: "searchWhenPredicateNotTestItem"
    nameDefinedByUser: false
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "FBAEEDEAF40CEF56FDE17BC7CEE2E220"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "INPUT"
      name: "source"
      modelFingerprint: "F543B4FC5A9B8FB5F402851D531FF1A2"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "NULL"
        suggestedContent: !<unknown_object>
          target: "java.lang.Iterable"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "java.lang.Iterable"
        uuid: "search_iterable1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "predicate"
      modelFingerprint: "AEDCF931C4A3A1BB4742E18EDDE82D3D"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "NULL"
        suggestedContent: !<unknown_object>
          target: "java.util.function.Predicate"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "java.util.function.Predicate"
        uuid: "search_predicate1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "D10B250EDA4A17F7E530BCC1306C03F4"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "NULL"
            suggestedContent: !<unknown_object>
              target: "java.lang.Iterable"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "java.lang.Iterable"
            uuid: "search_iterable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Source must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(Iterable,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "search_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "8B7F62189720970AD9017D1A3497BACB"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "NULL"
            suggestedContent: !<unknown_object>
              target: "java.util.function.Predicate"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "java.util.function.Predicate"
            uuid: "search_predicate1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Predicate must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(Predicate,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "search_void2"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "75431720ECDEA53E347CAC6A8C13518F"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "ENUM"
        content: !<regular>
          value: "ABSENT"
        valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyState"
        uuid: "Enum-org.springframework.boot.context.properties.source.ConfigurationPropertyState-ABSENT"
        fixed: true
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "f328f7bb-da87-3b6f-9463-4aa7094b1003"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
