---
modelFingerprint: "1D8000A8BDAC46295E0500EEE4502629"
methods:
- method:
    name: "search"
    returnType: "org.springframework.boot.context.properties.source.ConfigurationPropertyState"
    signature: "search(java.lang.Iterable<java.lang.Object>,java.util.function.Predicate<java.lang.Object>)\
      \ : org.springframework.boot.context.properties.source.ConfigurationPropertyState"
    instructionFingerprint: "15BE33C472B9C4B7425E811BA42FE78F"
    parametersTypes:
    - "java.lang.Iterable"
    - "java.util.function.Predicate"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "searchWhenPredicateTestItem"
    nameDefinedByUser: false
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "CCCA4AF9657FC46B0B9EC6DE034A44CA"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "INPUT"
      name: "source"
      modelFingerprint: "5BD192AD9E556680D9C212DC6ED5E674"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "java.lang.Iterable"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "java.lang.Iterable"
        uuid: "search_iterable1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "predicate"
      modelFingerprint: "CB9118E16CD8F9D9186626D2757758C6"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "java.util.function.Predicate"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "java.util.function.Predicate"
        uuid: "search_predicate1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "0749C0EC0AD0CF0E7AEF7D122C49ABA4"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            suggestedContent: !<unknown_object>
              target: "java.lang.Iterable"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "java.lang.Iterable"
            uuid: "search_iterable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Source must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(Iterable,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "search_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "4CAD2A5D3BBF23A5997AAFCCAC4533AA"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            suggestedContent: !<unknown_object>
              target: "java.util.function.Predicate"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "java.util.function.Predicate"
            uuid: "search_predicate1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Predicate must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(Predicate,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "search_void2"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "source"
      modelFingerprint: "1CC44ABF32697483B6BA50A5C00B74D9"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "java.lang.Iterable"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "java.lang.Iterable"
        uuid: "search_iterable1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "source"
        name: "iterator"
        parameters: []
        signature: "iterator(): Iterator"
        returnValue:
          sapientType: "ITERATOR"
          content: !<iterator>
            collectionValue:
              sapientType: "COLLECTION"
              content: !<collection>
                parameters: []
                values: []
              valueType: "java.util.List"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          valueType: "java.util.Iterator"
          uuid: "search_iterator1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "predicate"
      modelFingerprint: "90928F958A11D0AD05973C10E3B8B26C"
      index: 6
      ignored: false
      nestedInLoop: true
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "java.util.function.Predicate"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "java.util.function.Predicate"
        uuid: "search_predicate1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "predicate"
        name: "test"
        parameters:
        - name: "arg0"
          value:
            sapientType: "OBJECT"
            content: !<new>
              target: "java.lang.Object"
              parameters: []
              privateConstructor: false
              createdByTargetCode: false
            suggestedContent: !<new>
              target: "java.lang.Object"
              parameters: []
              privateConstructor: false
              createdByTargetCode: false
            valueType: "java.lang.Object"
            uuid: "search_object1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "test(Object): boolean"
        returnValue:
          sapientType: "BASIC"
          content: !<regular>
            value: true
          suggestedContent: !<regular>
            value: true
          valueType: "boolean"
          uuid: "search_boolean2"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "215C6D4AFC6B5001AC9D2FA01D518C77"
      index: 7
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "ENUM"
        content: !<regular>
          value: "PRESENT"
        valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyState"
        uuid: "Enum-org.springframework.boot.context.properties.source.ConfigurationPropertyState-PRESENT"
        fixed: true
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "06fff9e8-aab3-3323-9bf4-83f0394f49b3"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.util.Iterator.hasNext() : boolean"
    prover: "LLM"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
  - pathId: "path2"
    pathIdForUser: "path2"
    testPathName: "searchWhenPredicateNotTestItem"
    nameDefinedByUser: false
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "E093AA52B01AE25211B9EB843567680E"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "INPUT"
      name: "source"
      modelFingerprint: "5BD192AD9E556680D9C212DC6ED5E674"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "java.lang.Iterable"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "java.lang.Iterable"
        uuid: "search_iterable1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "predicate"
      modelFingerprint: "CB9118E16CD8F9D9186626D2757758C6"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "java.util.function.Predicate"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "java.util.function.Predicate"
        uuid: "search_predicate1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "0749C0EC0AD0CF0E7AEF7D122C49ABA4"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            suggestedContent: !<unknown_object>
              target: "java.lang.Iterable"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "java.lang.Iterable"
            uuid: "search_iterable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Source must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(Iterable,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "search_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "4CAD2A5D3BBF23A5997AAFCCAC4533AA"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "MOCK"
            suggestedContent: !<unknown_object>
              target: "java.util.function.Predicate"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "java.util.function.Predicate"
            uuid: "search_predicate1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Predicate must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(Predicate,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "search_void2"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "source"
      modelFingerprint: "1CC44ABF32697483B6BA50A5C00B74D9"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "java.lang.Iterable"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "java.lang.Iterable"
        uuid: "search_iterable1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "source"
        name: "iterator"
        parameters: []
        signature: "iterator(): Iterator"
        returnValue:
          sapientType: "ITERATOR"
          content: !<iterator>
            collectionValue:
              sapientType: "COLLECTION"
              content: !<collection>
                parameters: []
                values: []
              valueType: "java.util.List"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          valueType: "java.util.Iterator"
          uuid: "search_iterator1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "predicate"
      modelFingerprint: "79712B93851F199BAF759D933CE2BC58"
      index: 6
      ignored: false
      nestedInLoop: true
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        suggestedContent: !<unknown_object>
          target: "java.util.function.Predicate"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "java.util.function.Predicate"
        uuid: "search_predicate1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "predicate"
        name: "test"
        parameters:
        - name: "arg0"
          value:
            sapientType: "OBJECT"
            content: !<new>
              target: "java.lang.Object"
              parameters: []
              privateConstructor: false
              createdByTargetCode: false
            suggestedContent: !<new>
              target: "java.lang.Object"
              parameters: []
              privateConstructor: false
              createdByTargetCode: false
            valueType: "java.lang.Object"
            uuid: "search_object1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "test(Object): boolean"
        returnValue:
          sapientType: "BASIC"
          content: !<regular>
            value: false
          suggestedContent: !<regular>
            value: false
          valueType: "boolean"
          uuid: "search_boolean2"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "75431720ECDEA53E347CAC6A8C13518F"
      index: 7
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "ENUM"
        content: !<regular>
          value: "ABSENT"
        valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyState"
        uuid: "Enum-org.springframework.boot.context.properties.source.ConfigurationPropertyState-ABSENT"
        fixed: true
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "f328f7bb-da87-3b6f-9463-4aa7094b1003"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.util.Iterator.hasNext() : boolean"
    prover: "LLM"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
