---
modelFingerprint: "E56B21896D2FBF3DAF0EE7A8C88D8C00"
methods:
- method:
    name: "getConfiguredNames"
    returnType: "java.util.Set"
    signature: "getConfiguredNames() : java.util.Set<java.lang.String>"
    instructionFingerprint: "9636592D2245BC35783E71C3B56B1F3F"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getConfiguredNamesTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.util.Collection<java.lang.String>,java.util.Collection<java.lang.String>)\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "AF26558B7D654A9592C30B238E4BAE47"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "588c8f58-d9c7-34b5-99d8-41da6094ea32"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "getMutuallyExclusiveNames"
    returnType: "java.util.Set"
    signature: "getMutuallyExclusiveNames() : java.util.Set<java.lang.String>"
    instructionFingerprint: "762E9231D321F12656B479F0C774F5D1"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getMutuallyExclusiveNamesTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.util.Collection<java.lang.String>,java.util.Collection<java.lang.String>)\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "AF26558B7D654A9592C30B238E4BAE47"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "72d31c61-0b35-33c7-89e0-9989fccb818b"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "throwIfMultipleNonNullValuesIn"
    returnType: "void"
    signature: "throwIfMultipleNonNullValuesIn(java.util.function.Consumer<java.util.Map<java.lang.String,java.lang.Object>>)\
      \ : void"
    instructionFingerprint: "0F048E3679B4F4C9677F469A36F65ADE"
    parametersTypes:
    - "java.util.function.Consumer"
  paths:
  - pathId: "path3"
    pathIdForUser: "path1"
    testPathName: "throwIfMultipleNonNullValuesInWhenConfiguredNamesSizeNotGreaterThan1"
    nameDefinedByUser: false
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "748968BEC8098CE0536B08FCF73F130C"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "INPUT"
      name: "entries"
      modelFingerprint: "F6C64DF9C7404535D4DAD9B188823317"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "NULL"
        valueType: "java.util.function.Consumer"
        uuid: "throwIfMultipleNonNullValuesIn_consumer1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "1A9C0B8A4B62A9A54759EDABADCA3EC1"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "EXCEPTION"
        content: !<new>
          target: "java.lang.NullPointerException"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "java.lang.NullPointerException"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        valueType: "java.lang.NullPointerException"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "3108182a-2878-331d-9fc8-447f5994d0fc"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path1"
    pathIdForUser: "path2"
    testPathName: "throwIfMultipleNonNullValuesInWhenCollectionIsNotNullThrowsMutuallyExclusiveConfigurationPropertiesException"
    nameDefinedByUser: false
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "748968BEC8098CE0536B08FCF73F130C"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "INPUT"
      name: "entries"
      modelFingerprint: "F6C64DF9C7404535D4DAD9B188823317"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "NULL"
        valueType: "java.util.function.Consumer"
        uuid: "throwIfMultipleNonNullValuesIn_consumer1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "1A9C0B8A4B62A9A54759EDABADCA3EC1"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "EXCEPTION"
        content: !<new>
          target: "java.lang.NullPointerException"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "java.lang.NullPointerException"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        valueType: "java.lang.NullPointerException"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "88052858-048f-33ac-8a82-ddf8cad9aead"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path2"
    pathIdForUser: "path3"
    testPathName: "throwIfMultipleNonNullValuesInWhenCollectionIsNullThrowsMutuallyExclusiveConfigurationPropertiesException"
    nameDefinedByUser: false
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "748968BEC8098CE0536B08FCF73F130C"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "INPUT"
      name: "entries"
      modelFingerprint: "F6C64DF9C7404535D4DAD9B188823317"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "NULL"
        valueType: "java.util.function.Consumer"
        uuid: "throwIfMultipleNonNullValuesIn_consumer1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "1A9C0B8A4B62A9A54759EDABADCA3EC1"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "EXCEPTION"
        content: !<new>
          target: "java.lang.NullPointerException"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "java.lang.NullPointerException"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        valueType: "java.lang.NullPointerException"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "3dd09632-79d9-3e4f-846b-f9cf2a2ec546"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
