---
modelFingerprint: "1CA3353628034305A1C929577D71A235"
targetClass:
  fullClassName: "org.springframework.boot.context.properties.source.PrefixedIterableConfigurationPropertySource"
methods:
- method:
    name: "stream"
    sourceCodeSignature: "Stream<ConfigurationPropertyName> stream()"
    returnType: "java.util.stream.Stream"
    genericReturnType: "org.springframework.boot.context.properties.source.ConfigurationPropertyName"
    instructionFingerprint: "FB311C88BDC2AB8B53E33CC9733149A0"
  paths:
  - pathId: "path1"
    testPathName: "streamTest"
    constructorSignature: "<init>(org.springframework.boot.context.properties.source.IterableConfigurationPropertySource,java.lang.String)\
      \ : void"
    modelFingerprint: "0CE25E542E5E0229F064CC364CF360EB"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "EB2DA101236B342EF9588964A91FA997"
      valueUuid: "target"
    - type: "STATIC"
      name: "Assert.class"
      modelFingerprint: "3CFD9DF697674DB699F51FEF46E0D6E5"
      valueUuid: "Assert.class"
      methodExercised:
        expression: "notNull(object:source,message:uniqueUuid1):void"
        staticAccess: true
    - type: "STATIC"
      name: "Assert.class"
      modelFingerprint: "003F91A7301D496434638BE2602D21AE"
      valueUuid: "Assert.class"
      methodExercised:
        expression: "hasText(text:prefix,message:uniqueUuid2):void2"
        staticAccess: true
    - type: "STATIC"
      name: "ConfigurationPropertyName.class"
      modelFingerprint: "50CB1B84008D5C104084FABD0375153B"
      valueUuid: "ConfigurationPropertyName.class"
      methodExercised:
        expression: "of(name:prefix):configurationPropertyName"
        staticAccess: true
    - type: "INTERNAL"
      name: "internalMethod"
      modelFingerprint: "73E6093B75BC00507D410B0D1E2A78C7"
      methodExercised:
        expression: "getSource():iterableConfigurationPropertySource"
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "5B4C2C628307A1C10229BB5BDB1F7C5E"
      valueUuid: "iterableConfigurationPropertySource"
      methodExercised:
        expression: "stream():stream"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "B55B1820CF1A5590EBC1A63BF03E1217"
      valueUuid: "stream2"
    disabled: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.util.stream.Stream.map(java.util.function.Function)\
        \ : java.util.stream.Stream<org.springframework.boot.context.properties.source.ConfigurationPropertyName>"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.PrefixedIterableConfigurationPropertySource"
        parameters:
        - name: "source"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
            uuid: "source"
        - name: "prefix"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "A"
            valueType: "java.lang.String"
            uuid: "prefix"
      valueType: "org.springframework.boot.context.properties.source.PrefixedIterableConfigurationPropertySource"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "Assert.class"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
      uuid: "source"
    - sapientType: "BASIC"
      content: !<regular>
        value: "Source must not be null"
      valueType: "java.lang.String"
      uuid: "uniqueUuid1"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "Assert.class"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void2"
      fixed: true
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "prefix"
    - sapientType: "BASIC"
      content: !<regular>
        value: "Prefix must not be empty"
      valueType: "java.lang.String"
      uuid: "uniqueUuid2"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyName"
      uuid: "ConfigurationPropertyName.class"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyName"
      uuid: "configurationPropertyName"
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "prefix"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
      uuid: "iterableConfigurationPropertySource"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
      uuid: "iterableConfigurationPropertySource"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.util.stream.Stream"
        method: "empty"
        methodParameters: []
      valueType: "java.util.stream.Stream"
      uuid: "stream"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.util.stream.Stream"
        method: "empty"
        methodParameters: []
      valueType: "java.util.stream.Stream"
      uuid: "stream2"
- method:
    name: "getSource"
    sourceCodeSignature: "IterableConfigurationPropertySource getSource()"
    returnType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
    instructionFingerprint: "7E1A37576E89AE13D068355C037A1310"
  paths:
  - pathId: "path1"
    testPathName: "getSource1Test"
    constructorSignature: "<init>(org.springframework.boot.context.properties.source.IterableConfigurationPropertySource,java.lang.String)\
      \ : void"
    modelFingerprint: "98ED9EF5D0FC1D795CCD72662A17C9CE"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "EB2DA101236B342EF9588964A91FA997"
      valueUuid: "target"
    - type: "STATIC"
      name: "Assert.class"
      modelFingerprint: "3CFD9DF697674DB699F51FEF46E0D6E5"
      valueUuid: "Assert.class"
      methodExercised:
        expression: "notNull(object:source,message:uniqueUuid3):void"
        staticAccess: true
    - type: "STATIC"
      name: "Assert.class"
      modelFingerprint: "003F91A7301D496434638BE2602D21AE"
      valueUuid: "Assert.class"
      methodExercised:
        expression: "hasText(text:prefix,message:uniqueUuid4):void2"
        staticAccess: true
    - type: "STATIC"
      name: "ConfigurationPropertyName.class"
      modelFingerprint: "50CB1B84008D5C104084FABD0375153B"
      valueUuid: "ConfigurationPropertyName.class"
      methodExercised:
        expression: "of(name:prefix):configurationPropertyName"
        staticAccess: true
    - type: "RESULT"
      name: "result"
      modelFingerprint: "1E9862F51E12F3DCF416FA740B143D04"
      valueUuid: "source"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.PrefixedIterableConfigurationPropertySource"
        parameters:
        - name: "source"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
            uuid: "source"
        - name: "prefix"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "A"
            valueType: "java.lang.String"
            uuid: "prefix"
      valueType: "org.springframework.boot.context.properties.source.PrefixedIterableConfigurationPropertySource"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "Assert.class"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
      uuid: "source"
    - sapientType: "BASIC"
      content: !<regular>
        value: "Source must not be null"
      valueType: "java.lang.String"
      uuid: "uniqueUuid3"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "Assert.class"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void2"
      fixed: true
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "prefix"
    - sapientType: "BASIC"
      content: !<regular>
        value: "Prefix must not be empty"
      valueType: "java.lang.String"
      uuid: "uniqueUuid4"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyName"
      uuid: "ConfigurationPropertyName.class"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyName"
      uuid: "configurationPropertyName"
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "prefix"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
      uuid: "source"
