---
modelFingerprint: "1FC81114F7A119B6B6116ADCBEE3537D"
methods:
- method:
    name: "stream"
    signature: "stream() : java.util.stream.Stream<org.springframework.boot.context.properties.source.ConfigurationPropertyName>"
    instructionFingerprint: "FB311C88BDC2AB8B53E33CC9733149A0"
  paths:
  - pathId: "path1"
    testPathName: "streamTest"
    constructorSignature: "<init>(org.springframework.boot.context.properties.source.IterableConfigurationPropertySource,java.lang.String)\
      \ : void"
    filledByUser: false
    modelFingerprint: "98DC8D07A58E63CF7DB2A337A068F2B3"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "29982610ECDE8B68E51CDD4C51D982F4"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "3BCF9F71C3464BC4B8DD432AD321B6D9"
      index: 2
      ignored: false
      valueUuid: "uuid2"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_iterableConfigurationPropertySource1"
        - name: "message"
          valueUuid: "uuid1"
        signature: "notNull(IterableConfigurationPropertySource,String): void"
        returnValueUuid: "<init>_void1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "D271E309A9846E36F0DEC0249A6856D7"
      index: 3
      ignored: false
      valueUuid: "uuid4"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "hasText"
        parameters:
        - name: "text"
          valueUuid: "<init>_string1"
        - name: "message"
          valueUuid: "uuid3"
        signature: "hasText(String,String): void"
        returnValueUuid: "<init>_void2"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "ConfigurationPropertyName"
      modelFingerprint: "98879CBF045593C4E8446C7D5E22BA62"
      index: 4
      ignored: false
      valueUuid: "uuid5"
      methodExercised:
        target: "org.springframework.boot.context.properties.source.ConfigurationPropertyName"
        name: "of"
        parameters:
        - name: "name"
          valueUuid: "<init>_string1"
        signature: "of(String): ConfigurationPropertyName"
        returnValueUuid: "<init>_configurationPropertyName1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "INTERNAL"
      name: "internalMethod"
      modelFingerprint: "ABD3BA9BDB07FBA37DB2E6C185F38490"
      index: 5
      ignored: false
      methodExercised:
        target: "target"
        name: "getSource"
        parameters: []
        signature: "getSource(): IterableConfigurationPropertySource"
        returnValueUuid: "stream_iterableConfigurationPropertySource1"
        access: 4
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "F6F308D2A4A43F315058DFB56F570F64"
      index: 6
      ignored: false
      valueUuid: "stream_iterableConfigurationPropertySource1"
      methodExercised:
        target: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
        name: "stream"
        parameters: []
        signature: "stream(): Stream"
        returnValueUuid: "stream_stream1"
        access: 1025
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "C753BC527FB9F94CD92387C5F4B57BA4"
      index: 7
      ignored: false
      valueUuid: "stream_stream2"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "b4af2388-e781-3800-820a-b8ede09bd914"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.util.stream.Stream.map(java.util.function.Function)\
        \ : java.util.stream.Stream<org.springframework.boot.context.properties.source.ConfigurationPropertyName>"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.PrefixedIterableConfigurationPropertySource"
        parameters:
        - name: "source"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
            uuid: "<init>_iterableConfigurationPropertySource1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "prefix"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "A"
            suggestedContent: !<regular>
              value: "A"
            valueType: "java.lang.String"
            uuid: "<init>_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.context.properties.source.PrefixedIterableConfigurationPropertySource"
        parameters:
        - name: "source"
          value:
            sapientType: "UNKNOWN"
            valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
            uuid: "<init>_iterableConfigurationPropertySource1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "prefix"
          value:
            sapientType: "BASIC"
            suggestedContent: !<regular>
              value: "A"
            valueType: "java.lang.String"
            uuid: "<init>_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.source.PrefixedIterableConfigurationPropertySource"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
      uuid: "<init>_iterableConfigurationPropertySource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Source must not be null"
      valueType: "java.lang.String"
      uuid: "uuid1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid4"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      suggestedContent: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "<init>_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Prefix must not be empty"
      valueType: "java.lang.String"
      uuid: "uuid3"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyName"
      uuid: "uuid5"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyName"
      uuid: "<init>_configurationPropertyName1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      suggestedContent: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "<init>_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
      uuid: "stream_iterableConfigurationPropertySource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
      uuid: "stream_iterableConfigurationPropertySource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.util.stream.Stream"
        method: "empty"
        methodParameters: []
      suggestedContent: !<static_method_return>
        target: "java.util.stream.Stream"
        method: "empty"
        methodParameters: []
      valueType: "java.util.stream.Stream"
      uuid: "stream_stream1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.util.stream.Stream"
        method: "empty"
        methodParameters: []
      suggestedContent: !<static_method_return>
        target: "java.util.stream.Stream"
        method: "empty"
        methodParameters: []
      valueType: "java.util.stream.Stream"
      uuid: "stream_stream2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
- method:
    name: "getSource"
    signature: "getSource() : org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
    instructionFingerprint: "7E1A37576E89AE13D068355C037A1310"
  paths:
  - pathId: "path1"
    testPathName: "getSource1Test"
    constructorSignature: "<init>(org.springframework.boot.context.properties.source.IterableConfigurationPropertySource,java.lang.String)\
      \ : void"
    filledByUser: false
    modelFingerprint: "BD75EFD2A4651245E4147041995194FD"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "29982610ECDE8B68E51CDD4C51D982F4"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "3BCF9F71C3464BC4B8DD432AD321B6D9"
      index: 2
      ignored: false
      valueUuid: "uuid7"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_iterableConfigurationPropertySource1"
        - name: "message"
          valueUuid: "uuid6"
        signature: "notNull(IterableConfigurationPropertySource,String): void"
        returnValueUuid: "<init>_void1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "D271E309A9846E36F0DEC0249A6856D7"
      index: 3
      ignored: false
      valueUuid: "uuid9"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "hasText"
        parameters:
        - name: "text"
          valueUuid: "<init>_string1"
        - name: "message"
          valueUuid: "uuid8"
        signature: "hasText(String,String): void"
        returnValueUuid: "<init>_void2"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "ConfigurationPropertyName"
      modelFingerprint: "98879CBF045593C4E8446C7D5E22BA62"
      index: 4
      ignored: false
      valueUuid: "uuid10"
      methodExercised:
        target: "org.springframework.boot.context.properties.source.ConfigurationPropertyName"
        name: "of"
        parameters:
        - name: "name"
          valueUuid: "<init>_string1"
        signature: "of(String): ConfigurationPropertyName"
        returnValueUuid: "<init>_configurationPropertyName1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "B858CC7ADF4138B2495DFF7300E5B929"
      index: 5
      ignored: false
      valueUuid: "<init>_iterableConfigurationPropertySource1"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "bfcb6725-5fb8-3080-8655-dc87e9921af1"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.PrefixedIterableConfigurationPropertySource"
        parameters:
        - name: "source"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
            uuid: "<init>_iterableConfigurationPropertySource1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "prefix"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "A"
            suggestedContent: !<regular>
              value: "A"
            valueType: "java.lang.String"
            uuid: "<init>_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.context.properties.source.PrefixedIterableConfigurationPropertySource"
        parameters:
        - name: "source"
          value:
            sapientType: "UNKNOWN"
            valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
            uuid: "<init>_iterableConfigurationPropertySource1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "prefix"
          value:
            sapientType: "BASIC"
            suggestedContent: !<regular>
              value: "A"
            valueType: "java.lang.String"
            uuid: "<init>_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.source.PrefixedIterableConfigurationPropertySource"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid7"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
      uuid: "<init>_iterableConfigurationPropertySource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Source must not be null"
      valueType: "java.lang.String"
      uuid: "uuid6"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid9"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      suggestedContent: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "<init>_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Prefix must not be empty"
      valueType: "java.lang.String"
      uuid: "uuid8"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyName"
      uuid: "uuid10"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertyName"
      uuid: "<init>_configurationPropertyName1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      suggestedContent: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "<init>_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.source.IterableConfigurationPropertySource"
      uuid: "<init>_iterableConfigurationPropertySource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
