---
modelFingerprint: "8E5122F38726ED5A77A44C2C58400207"
methods:
- method:
    name: "isUsingSources"
    signature: "isUsingSources(java.lang.Iterable<org.springframework.core.env.PropertySource<?>>)\
      \ : boolean"
    instructionFingerprint: "0561389946EDF54148C7B05BBB18A9DC"
  paths:
  - pathId: "path1"
    testPathName: "isUsingSourcesWhenThisSourcesEqualsSources"
    constructorSignature: "<init>(java.lang.Iterable<org.springframework.core.env.PropertySource<?>>)\
      \ : void"
    filledByUser: false
    modelFingerprint: "03DEACD20CBC7036366F194343D5B442"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "9FA82B3ED1BA5274C387EDAF3C4AF460"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "sources"
      modelFingerprint: "770CE34786EBABF6177CD944C89F4C31"
      index: 2
      ignored: false
      valueUuid: "<init>_iterable1"
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "6BF38DFD7CC4055157A460FCFA440061"
      index: 3
      ignored: false
      valueUuid: "uuid2"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_iterable1"
        - name: "message"
          valueUuid: "uuid1"
        signature: "notNull(Iterable,String): void"
        returnValueUuid: "<init>_void1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "753659628F1B3F179A2EF0629F555437"
      index: 4
      ignored: false
      valueUuid: "uuid3"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "4f7f2e04-5085-3c77-9c5c-510e42b3bd0f"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
        parameters:
        - name: "sources"
          value:
            sapientType: "COLLECTION"
            content: !<collection>
              parameters: []
              values: []
            suggestedContent: !<collection>
              parameters: []
              values: []
            valueType: "java.lang.Iterable"
            genericValueType: "org.springframework.core.env.PropertySource<?>"
            uuid: "<init>_iterable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
        parameters:
        - name: "sources"
          value:
            sapientType: "COLLECTION"
            valueType: "java.lang.Iterable"
            genericValueType: "org.springframework.core.env.PropertySource<?>"
            uuid: "<init>_iterable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      suggestedContent: !<collection>
        parameters: []
        values: []
      valueType: "java.lang.Iterable"
      genericValueType: "org.springframework.core.env.PropertySource<?>"
      uuid: "<init>_iterable1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      suggestedContent: !<collection>
        parameters: []
        values: []
      valueType: "java.lang.Iterable"
      genericValueType: "org.springframework.core.env.PropertySource<?>"
      uuid: "<init>_iterable1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Sources must not be null"
      valueType: "java.lang.String"
      uuid: "uuid1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "uuid3"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "isUsingSourcesWhenThisSourcesNotEqualsSources"
    constructorSignature: "<init>(java.lang.Iterable<org.springframework.core.env.PropertySource<?>>)\
      \ : void"
    filledByUser: false
    modelFingerprint: "71D626730F0ADB1CB9D19E28DD0BF11E"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "9FA82B3ED1BA5274C387EDAF3C4AF460"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "sources"
      modelFingerprint: "770CE34786EBABF6177CD944C89F4C31"
      index: 2
      ignored: false
      valueUuid: "isUsingSources_iterable1"
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "6BF38DFD7CC4055157A460FCFA440061"
      index: 3
      ignored: false
      valueUuid: "uuid5"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_iterable1"
        - name: "message"
          valueUuid: "uuid4"
        signature: "notNull(Iterable,String): void"
        returnValueUuid: "<init>_void1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "3A21543F56248AC92654D6E439128AED"
      index: 4
      ignored: false
      valueUuid: "uuid6"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "9cb242de-be1f-37eb-b291-8765c225da25"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
        parameters:
        - name: "sources"
          value:
            sapientType: "COLLECTION"
            content: !<collection>
              parameters: []
              values: []
            suggestedContent: !<collection>
              parameters: []
              values: []
            valueType: "java.lang.Iterable"
            genericValueType: "org.springframework.core.env.PropertySource<?>"
            uuid: "<init>_iterable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
        parameters:
        - name: "sources"
          value:
            sapientType: "COLLECTION"
            valueType: "java.lang.Iterable"
            genericValueType: "org.springframework.core.env.PropertySource<?>"
            uuid: "<init>_iterable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      suggestedContent: !<collection>
        parameters: []
        values: []
      valueType: "java.lang.Iterable"
      genericValueType: "org.springframework.core.env.PropertySource<?>"
      uuid: "isUsingSources_iterable1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid5"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      suggestedContent: !<collection>
        parameters: []
        values: []
      valueType: "java.lang.Iterable"
      genericValueType: "org.springframework.core.env.PropertySource<?>"
      uuid: "<init>_iterable1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Sources must not be null"
      valueType: "java.lang.String"
      uuid: "uuid4"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "uuid6"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
- method:
    name: "iterator"
    signature: "iterator() : java.util.Iterator<org.springframework.boot.context.properties.source.ConfigurationPropertySource>"
    instructionFingerprint: "CBF4850B6BCA87D3580BBF0DE20041F4"
  paths:
  - pathId: "path1"
    testPathName: "iteratorTest"
    constructorSignature: "<init>(java.lang.Iterable<org.springframework.core.env.PropertySource<?>>)\
      \ : void"
    filledByUser: false
    modelFingerprint: "5BFABACF617974AF62837E923BFEAEC3"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "1F7D1A2964251E91A760D16D19BFBBBA"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "E4A6DBEBD709EC4AA96BB5CAE73A8807"
      index: 2
      ignored: false
      valueUuid: "uuid2"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_iterable1"
        - name: "message"
          valueUuid: "uuid1"
        signature: "notNull(Iterable,String): void"
        returnValueUuid: "<init>_void1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3FDA91A1373CE77D4FEC0FC2FE3683E"
      index: 3
      ignored: false
      valueUuid: "iterator_springConfigurationPropertySources.SourcesIterator1"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "78c09fb6-edcf-3ce7-9932-6ef4ffc152b3"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
        parameters:
        - name: "sources"
          value:
            sapientType: "COLLECTION"
            content: !<collection>
              parameters: []
              values: []
            suggestedContent: !<collection>
              parameters: []
              values: []
            valueType: "java.lang.Iterable"
            genericValueType: "org.springframework.core.env.PropertySource<?>"
            uuid: "<init>_iterable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
        parameters:
        - name: "sources"
          value:
            sapientType: "COLLECTION"
            content: !<collection>
              parameters: []
              values: []
            suggestedContent: !<collection>
              parameters: []
              values: []
            valueType: "java.lang.Iterable"
            genericValueType: "org.springframework.core.env.PropertySource<?>"
            uuid: "<init>_iterable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.source.SpringConfigurationPropertySources"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "REAL"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      suggestedContent: !<collection>
        parameters: []
        values: []
      valueType: "java.lang.Iterable"
      genericValueType: "org.springframework.core.env.PropertySource<?>"
      uuid: "<init>_iterable1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Sources must not be null"
      valueType: "java.lang.String"
      uuid: "uuid1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "NOT_NULL"
      valueType: "java.util.Iterator"
      genericValueType: "org.springframework.boot.context.properties.source.ConfigurationPropertySource"
      uuid: "iterator_springConfigurationPropertySources.SourcesIterator1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
