---
modelFingerprint: "516A18B0C2819103DC06C58D11EA4678"
methods:
- method:
    name: "doGetActiveProfilesProperty"
    returnType: "java.lang.String"
    signature: "doGetActiveProfilesProperty() : java.lang.String"
    instructionFingerprint: "137D807D65466C377F71910631A85488"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "doGetActiveProfilesPropertyTest"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "85B28E1C41B471C5E114ED0220748B32"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.ApplicationEnvironment"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.ApplicationEnvironment"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.ApplicationEnvironment"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "8EDA3F2AE365AC99A4FDAA03D44C0B66"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "NULL"
        valueType: "java.lang.String"
        uuid: "doGetActiveProfilesProperty_string1"
        fixed: true
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "de774194-de49-370c-8c3d-0b1e904baef9"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "doGetDefaultProfilesProperty"
    returnType: "java.lang.String"
    signature: "doGetDefaultProfilesProperty() : java.lang.String"
    instructionFingerprint: "7FC870E71BD8CA32F80246D349D66538"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "doGetDefaultProfilesPropertyTest"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "85B28E1C41B471C5E114ED0220748B32"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.ApplicationEnvironment"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.ApplicationEnvironment"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.ApplicationEnvironment"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "8EDA3F2AE365AC99A4FDAA03D44C0B66"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "NULL"
        valueType: "java.lang.String"
        uuid: "doGetDefaultProfilesProperty_string1"
        fixed: true
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "8851a08f-f7e0-376c-a9da-76a0fc519c42"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "createPropertyResolver"
    returnType: "org.springframework.core.env.ConfigurablePropertyResolver"
    signature: "createPropertyResolver(org.springframework.core.env.MutablePropertySources)\
      \ : org.springframework.core.env.ConfigurablePropertyResolver"
    instructionFingerprint: "B00607FDC96C1479B907A109A8D6BBB0"
    parametersTypes:
    - "org.springframework.core.env.MutablePropertySources"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "createPropertyResolverTest"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "473192316B31C016C32E09E6EE5BF7FF"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.ApplicationEnvironment"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.ApplicationEnvironment"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.ApplicationEnvironment"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "propertySources"
      modelFingerprint: "ECC118C98697ECA905ACD56377FB455D"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.core.env.MutablePropertySources"
        uuid: "createPropertyResolver_mutablePropertySources1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "ConfigurationPropertySources"
      modelFingerprint: "4ACF67E0DFC0166B2A7A9E4A0BD27DE6"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.boot.context.properties.source.ConfigurationPropertySources"
        uuid: "org.springframework.boot.context.properties.source.ConfigurationPropertySources"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.boot.context.properties.source.ConfigurationPropertySources"
        name: "createPropertyResolver"
        parameters:
        - name: "propertySources"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.core.env.MutablePropertySources"
            uuid: "createPropertyResolver_mutablePropertySources1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "createPropertyResolver(MutablePropertySources): ConfigurablePropertyResolver"
        returnValue:
          sapientType: "MOCK"
          valueType: "org.springframework.core.env.ConfigurablePropertyResolver"
          uuid: "createPropertyResolver_configurablePropertyResolver1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "4E89ED0894044493A5A3A2AFE5AB727E"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.core.env.ConfigurablePropertyResolver"
        uuid: "createPropertyResolver_configurablePropertyResolver1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "cd721531-c35e-340b-93ef-a0cc3cccaba6"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
