---
modelFingerprint: "26D356248E23726F77A73B77A1A9A6D3"
methods:
- method:
    name: "onApplicationEvent"
    returnType: "void"
    signature: "onApplicationEvent(org.springframework.context.event.ContextRefreshedEvent)\
      \ : void"
    tryCatchBlocks:
    - idExternalInstruction: 0
      id: 1
      catchExceptions:
      - "java.lang.Exception"
    instructionFingerprint: "2519487278F32675CD167D6EF704990D"
    parametersTypes:
    - "org.springframework.context.event.ContextRefreshedEvent"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "onApplicationEventWhenClassLoaderIsNull"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "B8A09F655EE6931E4704C9BEF00734D2"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.ClearCachesApplicationListener"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.ClearCachesApplicationListener"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.ClearCachesApplicationListener"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "event"
      modelFingerprint: "2DB0AB309217B334BEA7C385F908CAB2"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.context.event.ContextRefreshedEvent"
        uuid: "onApplicationEvent_contextRefreshedEvent1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "ReflectionUtils"
      modelFingerprint: "3EB29F8ABA592AC87EBFC3EA9638B7A9"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "REAL"
        valueType: "org.springframework.util.ReflectionUtils"
        uuid: "org.springframework.util.ReflectionUtils"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.ReflectionUtils"
        name: "clearCache"
        parameters: []
        signature: "clearCache(): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "onApplicationEvent_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "VOID"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "814da7ab-4387-3217-a93e-c676136e52ad"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path2"
    pathIdForUser: "path2"
    testPathName: "onApplicationEventWhenClassLoaderIsNotNull"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "467FC47E69549978F72D5579F9766551"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.ClearCachesApplicationListener"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.ClearCachesApplicationListener"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.ClearCachesApplicationListener"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "event"
      modelFingerprint: "2DB0AB309217B334BEA7C385F908CAB2"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.context.event.ContextRefreshedEvent"
        uuid: "onApplicationEvent_contextRefreshedEvent1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "ReflectionUtils"
      modelFingerprint: "3EB29F8ABA592AC87EBFC3EA9638B7A9"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "REAL"
        valueType: "org.springframework.util.ReflectionUtils"
        uuid: "org.springframework.util.ReflectionUtils"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.ReflectionUtils"
        name: "clearCache"
        parameters: []
        signature: "clearCache(): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "onApplicationEvent_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "VOID"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "8c66ab1e-a98c-3008-85eb-f845e5d22d6c"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path3"
    pathIdForUser: "path3"
    testPathName: "onApplicationEventWhenCaughtException"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "7ACB518F2C285A8B77EDE5B3859B715C"
    problemWasSolvedByProver: false
    catchBlockExercised:
      idExternalInstruction: 8
      id: 1
      catchExceptions:
      - "java.lang.Exception"
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.ClearCachesApplicationListener"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.ClearCachesApplicationListener"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.ClearCachesApplicationListener"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "event"
      modelFingerprint: "2DB0AB309217B334BEA7C385F908CAB2"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.context.event.ContextRefreshedEvent"
        uuid: "onApplicationEvent_contextRefreshedEvent1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "ReflectionUtils"
      modelFingerprint: "3EB29F8ABA592AC87EBFC3EA9638B7A9"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "REAL"
        valueType: "org.springframework.util.ReflectionUtils"
        uuid: "org.springframework.util.ReflectionUtils"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.ReflectionUtils"
        name: "clearCache"
        parameters: []
        signature: "clearCache(): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "onApplicationEvent_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "85AE57FF28BC905F9C2FE29152163D34"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: true
      idsTryCatchBlockSurrounding:
      - 80001
      value:
        sapientType: "CLASS"
        content: !<regular>
          value: "com.intellij.util.lang.PathClassLoader"
        valueType: "java.lang.Class"
        genericValueType: "?"
        uuid: "clearClassLoaderCaches_class1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "java.lang.Class"
        name: "getDeclaredMethod"
        parameters:
        - name: "name"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "clearCache"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "parameterTypes"
          value:
            sapientType: "ARRAY"
            content: !<array>
              values: {}
            suggestedContent: !<array>
              values: {}
            valueType: "java.lang.Class[]"
            uuid: "clearClassLoaderCaches_class[]1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        throwsExceptions:
        - "java.lang.NoSuchMethodException"
        - "java.lang.SecurityException"
        signature: "getDeclaredMethod(String,Class[]): Method throws java.lang.NoSuchMethodException,java.lang.SecurityException"
        returnValue:
          sapientType: "NULL"
          suggestedContent: !<unknown_object>
            target: "java.lang.reflect.Method"
            onlyPojoFunctions: false
            builderPattern: false
          valueType: "java.lang.reflect.Method"
          uuid: "clearClassLoaderCaches_method1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 129
      staticReadMethodForField: false
      filledByUser: false
    - type: "LOCAL_VARIABLE"
      name: "clearCacheMethod"
      modelFingerprint: "8272D25402D0D932C831FB565AEBB3CC"
      index: 5
      ignored: false
      nestedInLoop: false
      nestedInRecursion: true
      idsTryCatchBlockSurrounding:
      - 80001
      value:
        sapientType: "NULL"
        suggestedContent: !<unknown_object>
          target: "java.lang.reflect.Method"
          onlyPojoFunctions: false
          builderPattern: false
        valueType: "java.lang.reflect.Method"
        uuid: "clearClassLoaderCaches_method1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "clearCacheMethod"
        name: "invoke"
        parameters:
        - name: "obj"
          value:
            sapientType: "OBJECT"
            content: !<method_return_from_value>
              target: "java.lang.ClassLoader"
              localVariableValue:
                sapientType: "OBJECT"
                content: !<static_method_return>
                  target: "java.lang.Thread"
                  method: "currentThread"
                  methodParameters: []
                suggestedContent: !<static_method_return>
                  target: "java.lang.Thread"
                  method: "currentThread"
                  methodParameters: []
                valueType: "java.lang.Thread"
                uuid: "onApplicationEvent_thread1"
                fixed: false
                equalsMethodPresent: false
                explicitCastNeeded: false
              methodParameters: []
              methodName: "getContextClassLoader"
            suggestedContent: !<method_return_from_value>
              target: "java.lang.ClassLoader"
              localVariableValue:
                sapientType: "OBJECT"
                suggestedContent: !<static_method_return>
                  target: "java.lang.Thread"
                  method: "currentThread"
                  methodParameters: []
                valueType: "java.lang.Thread"
                uuid: "onApplicationEvent_thread1"
                fixed: false
                equalsMethodPresent: false
                explicitCastNeeded: false
              methodParameters: []
              methodName: "getContextClassLoader"
            valueType: "java.lang.ClassLoader"
            uuid: "onApplicationEvent_classLoader1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "args"
          value:
            sapientType: "ARRAY"
            content: !<array>
              values: {}
            suggestedContent: !<array>
              values: {}
            valueType: "java.lang.Object[]"
            uuid: "clearClassLoaderCaches_object[]1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        throwsExceptions:
        - "java.lang.IllegalAccessException"
        - "java.lang.IllegalArgumentException"
        - "java.lang.reflect.InvocationTargetException"
        signature: "invoke(ClassLoader,Object[]): Object throws java.lang.IllegalAccessException,java.lang.IllegalArgumentException,java.lang.reflect.InvocationTargetException"
        returnValue:
          sapientType: "OBJECT"
          content: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          suggestedContent: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          valueType: "java.lang.Object"
          uuid: "clearClassLoaderCaches_object1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 129
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 6
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "VOID"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "3f8e2b63-ec55-30bd-9a25-8574216baedd"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
