---
modelFingerprint: "5F5FB905F6BBE1FECB6E0DB2C58959D0"
targetClass:
  fullClassName: "org.springframework.boot.ClearCachesApplicationListener"
methods:
- method:
    name: "onApplicationEvent"
    sourceCodeSignature: "void onApplicationEvent(ContextRefreshedEvent event)"
    returnType: "void"
    parameters:
    - name: "event"
      type: "org.springframework.context.event.ContextRefreshedEvent"
    tryCatchBlocks:
    - idExternalInstruction: 0
      id: 1
      catchExceptions:
      - "java.lang.Exception"
    instructionFingerprint: "2519487278F32675CD167D6EF704990D"
  paths:
  - pathId: "path1"
    testPathName: "onApplicationEventWhenClassLoaderIsNotNull"
    constructorSignature: "<init>() : void"
    modelFingerprint: "4F8ABD20AD1A8CF3D5B3569F87E42C5C"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "event"
      modelFingerprint: "662A7D29BE9C0C9C79C4DF7F6107C619"
      valueUuid: "event"
    - type: "STATIC"
      name: "ReflectionUtils.class.real"
      modelFingerprint: "F2EC7E261F3D3BCA0247F7513CD6B0B3"
      valueUuid: "ReflectionUtils.class.real"
      methodExercised:
        expression: "clearCache():void"
        staticAccess: true
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    failureReason:
      reason: "VARIABLE_THAT_COULD_NOT_BE_ISOLATED_MOCKED"
      source: "Method clearCacheMethod = classLoader.getClass().getDeclaredMethod(\\\
        \"clearCache\\\");"
      lineNumber: 43
      details: "A variable could not be isolated/mocked when calling a method - Variable\
        \ name: classLoader - Method: getClass"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.ClearCachesApplicationListener"
        parameters: []
      valueType: "org.springframework.boot.ClearCachesApplicationListener"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.event.ContextRefreshedEvent"
      uuid: "event"
    - sapientType: "REAL"
      valueType: "org.springframework.util.ReflectionUtils"
      uuid: "ReflectionUtils.class.real"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
    branches:
    - lineNumber: 39
      expression: "classLoader == null"
      range: "(39,7)-(39,25)"
      evaluatedAs: false
      internalMethodName: "clearClassLoaderCaches"
  - pathId: "path2"
    testPathName: "onApplicationEventWhenCaughtException"
    constructorSignature: "<init>() : void"
    modelFingerprint: "448C9DD36F786503A4070C764E55B7F5"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "event"
      modelFingerprint: "662A7D29BE9C0C9C79C4DF7F6107C619"
      valueUuid: "event"
    - type: "STATIC"
      name: "ReflectionUtils.class.real"
      modelFingerprint: "F2EC7E261F3D3BCA0247F7513CD6B0B3"
      valueUuid: "ReflectionUtils.class.real"
      methodExercised:
        expression: "clearCache():void"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "81FDEF28FD453BF829C4F83713D8E0D4"
      valueUuid: "class"
      methodExercised:
        expression: "getDeclaredMethod(name:uniqueUuid1,parameterTypes:classArray):method"
        throwsExceptions:
        - "java.lang.NoSuchMethodException"
        - "java.lang.SecurityException"
    - type: "LOCAL_VARIABLE"
      name: "clearCacheMethod"
      modelFingerprint: "C93C76570FCFC67A7A1310EA34A94E6E"
      valueUuid: "method"
      methodExercised:
        expression: "invoke(obj:classLoader,args:objectArray):object"
        throwsExceptions:
        - "java.lang.IllegalAccessException"
        - "java.lang.IllegalArgumentException"
        - "java.lang.reflect.InvocationTargetException"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    failureReason:
      reason: "VARIABLE_THAT_COULD_NOT_BE_ISOLATED_MOCKED"
      source: "Method clearCacheMethod = classLoader.getClass().getDeclaredMethod(\\\
        \"clearCache\\\");"
      lineNumber: 43
      details: "A variable could not be isolated/mocked when calling a method - Variable\
        \ name: classLoader - Method: getClass"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.ClearCachesApplicationListener"
        parameters: []
      valueType: "org.springframework.boot.ClearCachesApplicationListener"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.event.ContextRefreshedEvent"
      uuid: "event"
    - sapientType: "REAL"
      valueType: "org.springframework.util.ReflectionUtils"
      uuid: "ReflectionUtils.class.real"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "CLASS"
      content: !<regular>
        value: "java.lang.Object"
      valueType: "java.lang.Class"
      genericValueType: "?"
      uuid: "class"
    - sapientType: "MOCK"
      valueType: "java.lang.reflect.Method"
      uuid: "method"
    - sapientType: "BASIC"
      content: !<regular>
        value: "clearCache"
      valueType: "java.lang.String"
      uuid: "uniqueUuid1"
      fixed: true
    - sapientType: "ARRAY"
      content: !<array>
        values: {}
      valueType: "java.lang.Class[]"
      uuid: "classArray"
    - sapientType: "MOCK"
      valueType: "java.lang.reflect.Method"
      uuid: "method"
    - sapientType: "OBJECT"
      content: !<new>
        target: "java.lang.Object"
        parameters: []
      valueType: "java.lang.Object"
      uuid: "object"
    - sapientType: "OBJECT"
      content: !<method_return_from_value>
        target: "java.lang.ClassLoader"
        localVariableValue:
          sapientType: "OBJECT"
          content: !<static_method_return>
            target: "java.lang.Thread"
            method: "currentThread"
            methodParameters: []
          valueType: "java.lang.Thread"
          uuid: "thread"
        methodParameters: []
        methodName: "getContextClassLoader"
      valueType: "java.lang.ClassLoader"
      uuid: "classLoader"
    - sapientType: "ARRAY"
      content: !<array>
        values: {}
      valueType: "java.lang.Object[]"
      uuid: "objectArray"
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
    branches:
    - lineNumber: 39
      expression: "classLoader == null"
      range: "(39,7)-(39,25)"
      evaluatedAs: false
      internalMethodName: "clearClassLoaderCaches"
    - lineNumber: 46
      expression: "catch-exception (Exception)"
      range: "(46,3)-(46,21)"
      evaluatedAs: true
      internalMethodName: "clearClassLoaderCaches"
    catchBlockExercised:
      idExternalInstruction: 8
      id: 1
      catchExceptions:
      - "java.lang.Exception"
