---
modelFingerprint: "E8EBA7BA39B34F4F2D29FDD785F10D95"
targetClass:
  fullClassName: "org.springframework.boot.SpringApplicationShutdownHook"
methods:
- method:
    name: "getHandlers"
    sourceCodeSignature: "SpringApplicationShutdownHandlers getHandlers()"
    returnType: "org.springframework.boot.SpringApplicationShutdownHandlers"
    instructionFingerprint: "A2592609D7A6DAA20426F6A2655B517E"
  paths:
  - pathId: "path1"
    testPathName: "getHandlersTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "5F74D5F5AE4793430FBB94834668BB45"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "C3875B734E5AE9A705F1363AB9770DE9"
      valueUuid: "springApplicationShutdownHook.HandlersNotNull"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.SpringApplicationShutdownHook"
        parameters: []
      valueType: "org.springframework.boot.SpringApplicationShutdownHook"
      uuid: "target"
    - sapientType: "NOT_NULL"
      valueType: "org.springframework.boot.SpringApplicationShutdownHandlers"
      uuid: "springApplicationShutdownHook.HandlersNotNull"
      fixed: true
- method:
    name: "enableShutdownHookAddition"
    sourceCodeSignature: "void enableShutdownHookAddition()"
    returnType: "void"
    instructionFingerprint: "0D72CDACCFECF1DE93FFD26E956A1B6E"
  paths:
  - pathId: "path1"
    testPathName: "enableShutdownHookAdditionTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "0A1F9D2307F891B79A39BE18CAA3B45A"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.SpringApplicationShutdownHook"
        parameters: []
      valueType: "org.springframework.boot.SpringApplicationShutdownHook"
      uuid: "target"
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
- method:
    name: "registerApplicationContext"
    sourceCodeSignature: "void registerApplicationContext(ConfigurableApplicationContext\
      \ context)"
    returnType: "void"
    parameters:
    - name: "context"
      type: "org.springframework.context.ConfigurableApplicationContext"
    instructionFingerprint: "208509C3EE196096A98035BDA1EF3DFC"
  paths:
  - pathId: "path1"
    testPathName: "registerApplicationContextWhenSpringApplicationShutdownHook_thisNotInProgress"
    constructorSignature: "<init>() : void"
    modelFingerprint: "A05E26603B35F839C70B7E97C3A08F37"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "context"
      modelFingerprint: "22F7680E81C8A00E4B019BF90B716E88"
      valueUuid: "context"
    - type: "STATIC"
      name: "Assert.class.real"
      modelFingerprint: "F60194AF1DA40DBC0531E92BAFF9D83B"
      valueUuid: "Assert.class.real"
      methodExercised:
        expression: "state(expression:uniqueUuid1,message:uniqueUuid2):void"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      name: "context"
      modelFingerprint: "315D63CCF439A313F66F4B24D1D1496F"
      valueUuid: "context"
      methodExercised:
        expression: "addApplicationListener(listener:springApplicationShutdownHook.ApplicationContextClosedListener):void2"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    failureReason:
      reason: "PRIVATE_INNER_CLASS_COMMENT"
      details: "PRIVATE_INNER_CLASS_COMMENT"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.SpringApplicationShutdownHook"
        parameters: []
      valueType: "org.springframework.boot.SpringApplicationShutdownHook"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "context"
    - sapientType: "REAL"
      valueType: "org.springframework.util.Assert"
      uuid: "Assert.class.real"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "uniqueUuid1"
      fixed: true
    - sapientType: "BASIC"
      content: !<regular>
        value: "Shutdown in progress"
      valueType: "java.lang.String"
      uuid: "uniqueUuid2"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "context"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void2"
      fixed: true
    - sapientType: "ANY"
      valueType: "org.springframework.boot.SpringApplicationShutdownHook$ApplicationContextClosedListener"
      uuid: "springApplicationShutdownHook.ApplicationContextClosedListener"
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
    branches:
    - lineNumber: 87
      expression: "this.shutdownHookAdditionEnabled"
      range: "(87,7)-(87,38)"
      evaluatedAs: false
      internalMethodName: "addRuntimeShutdownHookIfNecessary"
    - lineNumber: 166
      expression: "!SpringApplicationShutdownHook.this.inProgress"
      range: "(166,16)-(166,61)"
      evaluatedAs: true
      internalMethodName: "assertNotInProgress"
- method:
    name: "addRuntimeShutdownHook"
    sourceCodeSignature: "void addRuntimeShutdownHook()"
    returnType: "void"
    instructionFingerprint: "E3B0C87DD352224AACE665443CA1DD92"
  paths:
  - pathId: "path1"
    testPathName: "addRuntimeShutdownHookTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "0A1F9D2307F891B79A39BE18CAA3B45A"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.SpringApplicationShutdownHook"
        parameters: []
      valueType: "org.springframework.boot.SpringApplicationShutdownHook"
      uuid: "target"
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
- method:
    name: "deregisterFailedApplicationContext"
    sourceCodeSignature: "void deregisterFailedApplicationContext(ConfigurableApplicationContext\
      \ applicationContext)"
    returnType: "void"
    parameters:
    - name: "applicationContext"
      type: "org.springframework.context.ConfigurableApplicationContext"
    instructionFingerprint: "25416A89B337024CB8460A81D8F955EA"
  paths:
  - pathId: "path1"
    testPathName: "deregisterFailedApplicationContextWhenApplicationContextNotIsActive"
    constructorSignature: "<init>() : void"
    modelFingerprint: "62DB73BBC0AC2103DDB9553784F5CC0B"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "applicationContext"
      modelFingerprint: "DF659A8AABEBC6871FFB4901FD8A4D44"
      valueUuid: "applicationContext"
    - type: "LOCAL_VARIABLE"
      name: "applicationContext"
      modelFingerprint: "7F6A4EF5E61107A3FD8127C6C0E812E3"
      valueUuid: "applicationContext"
      methodExercised:
        expression: "isActive():boolean1"
    - type: "STATIC"
      name: "Assert.class.real"
      modelFingerprint: "6C5C68828D83ABE4270A1211DFD6DB51"
      valueUuid: "Assert.class.real"
      methodExercised:
        expression: "state(expression:uniqueUuid3,message:uniqueUuid4):void"
        staticAccess: true
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.SpringApplicationShutdownHook"
        parameters: []
      valueType: "org.springframework.boot.SpringApplicationShutdownHook"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "applicationContext"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "applicationContext"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "boolean1"
    - sapientType: "REAL"
      valueType: "org.springframework.util.Assert"
      uuid: "Assert.class.real"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "uniqueUuid3"
      fixed: true
    - sapientType: "BASIC"
      content: !<regular>
        value: "Cannot unregister active application context"
      valueType: "java.lang.String"
      uuid: "uniqueUuid4"
      fixed: true
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
    branches:
    - lineNumber: 98
      expression: "!applicationContext.isActive()"
      range: "(98,17)-(98,46)"
      evaluatedAs: true
  - pathId: "path2"
    testPathName: "deregisterFailedApplicationContextWhenApplicationContextIsActive"
    constructorSignature: "<init>() : void"
    modelFingerprint: "2977775A69755EFB634FEAEAA329151B"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "applicationContext"
      modelFingerprint: "DF659A8AABEBC6871FFB4901FD8A4D44"
      valueUuid: "applicationContext"
    - type: "LOCAL_VARIABLE"
      name: "applicationContext"
      modelFingerprint: "584F21E7A1D2791A7B2CE8049FF47762"
      valueUuid: "applicationContext"
      methodExercised:
        expression: "isActive():boolean1"
    - type: "STATIC"
      name: "Assert.class"
      modelFingerprint: "E28840B38C23065A81152BBD11364DED"
      valueUuid: "Assert.class"
      methodExercised:
        expression: "state(expression:uniqueUuid5,message:uniqueUuid6):void"
        staticAccess: true
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.SpringApplicationShutdownHook"
        parameters: []
      valueType: "org.springframework.boot.SpringApplicationShutdownHook"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "applicationContext"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "applicationContext"
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "boolean1"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "Assert.class"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "uniqueUuid5"
      fixed: true
    - sapientType: "BASIC"
      content: !<regular>
        value: "Cannot unregister active application context"
      valueType: "java.lang.String"
      uuid: "uniqueUuid6"
      fixed: true
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
    branches:
    - lineNumber: 98
      expression: "!applicationContext.isActive()"
      range: "(98,17)-(98,46)"
      evaluatedAs: false
- method:
    name: "run"
    sourceCodeSignature: "void run()"
    returnType: "void"
    instructionFingerprint: "C6D817EFBD61721B3A131777EC1D21A6"
  paths:
  - pathId: "path1"
    testPathName: "runTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "0A1F9D2307F891B79A39BE18CAA3B45A"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    failureReason:
      reason: "VARIABLE_THAT_COULD_NOT_BE_ISOLATED_MOCKED"
      source: "actions = new LinkedHashSet<>(this.handlers.getActions());"
      lineNumber: 112
      details: "A variable could not be isolated/mocked when calling a method - Variable\
        \ name: handlers - Method: getActions"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.SpringApplicationShutdownHook"
        parameters: []
      valueType: "org.springframework.boot.SpringApplicationShutdownHook"
      uuid: "target"
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
- method:
    name: "isApplicationContextRegistered"
    sourceCodeSignature: "boolean isApplicationContextRegistered(ConfigurableApplicationContext\
      \ context)"
    returnType: "boolean"
    parameters:
    - name: "context"
      type: "org.springframework.context.ConfigurableApplicationContext"
    instructionFingerprint: "AD782BA563574D007E11A802005D8D8B"
  paths:
  - pathId: "path1"
    testPathName: "isApplicationContextRegisteredTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "FB3171AAE946A609AF67DB7DF613F0B9"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "context"
      modelFingerprint: "6DEF13B8BEABCF66180D86ACB2708D19"
      valueUuid: "context"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "52785AAEEFCEB874D7B8C5DB08D93CCC"
      valueUuid: "boolean1"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.SpringApplicationShutdownHook"
        parameters: []
      valueType: "org.springframework.boot.SpringApplicationShutdownHook"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "context"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "boolean1"
      collectionUuid: "linkedHashSet"
- method:
    name: "reset"
    sourceCodeSignature: "void reset()"
    returnType: "void"
    instructionFingerprint: "EB26B49116F218C223B984848BB66BEC"
  paths:
  - pathId: "path1"
    testPathName: "resetTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "0A1F9D2307F891B79A39BE18CAA3B45A"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    failureReason:
      reason: "VARIABLE_THAT_COULD_NOT_BE_ISOLATED_MOCKED"
      source: "this.handlers.getActions().clear();"
      lineNumber: 129
      details: "A variable could not be isolated/mocked when calling a method - Variable\
        \ name: handlers - Method: getActions"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.SpringApplicationShutdownHook"
        parameters: []
      valueType: "org.springframework.boot.SpringApplicationShutdownHook"
      uuid: "target"
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
