---
modelFingerprint: "EE7D564401B2B008166D234070594A58"
targetClass:
  fullClassName: "org.springframework.boot.SpringApplicationAotProcessor"
methods:
- method:
    name: "prepareApplicationContext"
    sourceCodeSignature: "GenericApplicationContext prepareApplicationContext(Class<?>\
      \ application)"
    returnType: "org.springframework.context.support.GenericApplicationContext"
    parameters:
    - name: "application"
      type: "java.lang.Class"
    instructionFingerprint: "565A0CBDBB4851E0EA4BCB8BE549C029"
  paths:
  - pathId: "path1"
    testPathName: "prepareApplicationContextTest"
    constructorSignature: "<init>(java.lang.Class<?>,org.springframework.context.aot.AbstractAotProcessor$Settings,java.lang.String[])\
      \ : void"
    modelFingerprint: "62690D557E2E7405286B48F2E3029716"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "FBA232734F75223701FD6A9A81F8D1BB"
      valueUuid: "target"
    - type: "INPUT"
      name: "application"
      modelFingerprint: "307FDD34438F47951FD66E3E5E9B29C7"
      valueUuid: "application"
    - type: "STATIC"
      name: "ReflectionUtils.class"
      modelFingerprint: "6D6E91BA9C484EF2B2016EB6E9939AD0"
      valueUuid: "ReflectionUtils.class"
      methodExercised:
        expression: "invokeMethod(method:method,target:uniqueUuid1,args:objectArray):object"
        staticAccess: true
    - type: "RESULT"
      name: "result"
      modelFingerprint: "734433FD94FF981382D037CEBCD35C24"
      valueUuid: "genericApplicationContext"
    disabled: true
    failureReason:
      reason: "METHOD_CALL_INSTRUCTION_CONSTRUCTION_UNFILLED_PARAMS"
    disabledStatusUpdatedBy: "SYSTEM"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.SpringApplicationAotProcessor"
        parameters:
        - name: "application"
          value:
            sapientType: "CLASS"
            content: !<regular>
              value: "java.lang.Object"
            valueType: "java.lang.Class"
            genericValueType: "?"
            uuid: "application2"
        - name: "settings"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.context.aot.AbstractAotProcessor$Settings"
            uuid: "settings"
        - name: "applicationArgs"
          value:
            sapientType: "ARRAY"
            content: !<array>
              values: {}
            valueType: "java.lang.String[]"
            uuid: "applicationArgs"
      valueType: "org.springframework.boot.SpringApplicationAotProcessor"
      uuid: "target"
    - sapientType: "CLASS"
      content: !<regular>
        value: "java.lang.Object"
      valueType: "java.lang.Class"
      genericValueType: "?"
      uuid: "application"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ReflectionUtils"
      uuid: "ReflectionUtils.class"
    - sapientType: "OBJECT"
      content: !<new>
        target: "java.lang.Object"
        parameters: []
      valueType: "java.lang.Object"
      uuid: "object"
    - sapientType: "MOCK"
      valueType: "java.lang.reflect.Method"
      uuid: "method"
    - sapientType: "NULL"
      uuid: "uniqueUuid1"
    - sapientType: "ARRAY"
      content: !<array>
        values:
          0:
            sapientType: "ARRAY"
            content: !<array>
              values: {}
            valueType: "java.lang.String[]"
            uuid: "applicationArgs"
      valueType: "java.lang.Object[]"
      uuid: "objectArray"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.support.GenericApplicationContext"
      uuid: "genericApplicationContext"
