---
modelFingerprint: "DF6190F757D082F3215FA4C118926953"
methods:
- method:
    name: "prepareApplicationContext"
    returnType: "org.springframework.context.support.GenericApplicationContext"
    signature: "prepareApplicationContext(java.lang.Class<?>) : org.springframework.context.support.GenericApplicationContext"
    instructionFingerprint: "E6589F80831234A0D367657D0F1C95D3"
    parametersTypes:
    - "java.lang.Class"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "prepareApplicationContextTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.Class<?>,org.springframework.context.aot.AbstractAotProcessor$Settings,java.lang.String[])\
      \ : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "8B192DB8B71463E64F2C0E2195C704AD"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "41778831D76E80417710A32E46C6A7EA"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.SpringApplicationAotProcessor"
          parameters:
          - name: "application"
            value:
              sapientType: "CLASS"
              content: !<regular>
                value: "java.lang.Object"
              valueType: "java.lang.Class"
              genericValueType: "?"
              uuid: "<init>_class1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          - name: "settings"
            value:
              sapientType: "MOCK"
              suggestedContent: !<unknown_object>
                target: "org.springframework.context.aot.AbstractAotProcessor$Settings"
                onlyPojoFunctions: false
                builderPattern: false
              valueType: "org.springframework.context.aot.AbstractAotProcessor$Settings"
              uuid: "<init>_abstractAotProcessor.Settings1"
              fixed: false
              nameForMock: "true"
              equalsMethodPresent: false
              explicitCastNeeded: false
          - name: "applicationArgs"
            value:
              sapientType: "ARRAY"
              content: !<array>
                values:
                  0:
                    sapientType: "BASIC"
                    content: !<regular>
                      value: "arg1"
                    suggestedContent: !<regular>
                      value: "arg1"
                    valueType: "java.lang.String"
                    fixed: false
                    equalsMethodPresent: false
                    explicitCastNeeded: false
                  1:
                    sapientType: "BASIC"
                    content: !<regular>
                      value: "arg2"
                    suggestedContent: !<regular>
                      value: "arg2"
                    valueType: "java.lang.String"
                    fixed: false
                    equalsMethodPresent: false
                    explicitCastNeeded: false
              suggestedContent: !<array>
                values:
                  0:
                    sapientType: "BASIC"
                    content: !<regular>
                      value: "arg1"
                    suggestedContent: !<regular>
                      value: "arg1"
                    valueType: "java.lang.String"
                    fixed: false
                    equalsMethodPresent: false
                    explicitCastNeeded: false
                  1:
                    sapientType: "BASIC"
                    content: !<regular>
                      value: "arg2"
                    suggestedContent: !<regular>
                      value: "arg2"
                    valueType: "java.lang.String"
                    fixed: false
                    equalsMethodPresent: false
                    explicitCastNeeded: false
              valueType: "java.lang.String[]"
              uuid: "<init>_string[]1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.SpringApplicationAotProcessor"
          parameters:
          - name: "application"
            value:
              sapientType: "CLASS"
              valueType: "java.lang.Class"
              genericValueType: "?"
              uuid: "<init>_class1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          - name: "settings"
            value:
              sapientType: "MOCK"
              suggestedContent: !<unknown_object>
                target: "org.springframework.context.aot.AbstractAotProcessor$Settings"
                onlyPojoFunctions: false
                builderPattern: false
              valueType: "org.springframework.context.aot.AbstractAotProcessor$Settings"
              uuid: "<init>_abstractAotProcessor.Settings1"
              fixed: false
              nameForMock: "true"
              equalsMethodPresent: false
              explicitCastNeeded: false
          - name: "applicationArgs"
            value:
              sapientType: "ARRAY"
              content: !<array>
                values:
                  0:
                    sapientType: "BASIC"
                    content: !<regular>
                      value: "arg1"
                    suggestedContent: !<regular>
                      value: "arg1"
                    valueType: "java.lang.String"
                    fixed: false
                    equalsMethodPresent: false
                    explicitCastNeeded: false
                  1:
                    sapientType: "BASIC"
                    content: !<regular>
                      value: "arg2"
                    suggestedContent: !<regular>
                      value: "arg2"
                    valueType: "java.lang.String"
                    fixed: false
                    equalsMethodPresent: false
                    explicitCastNeeded: false
              suggestedContent: !<array>
                values:
                  0:
                    sapientType: "BASIC"
                    content: !<regular>
                      value: "arg1"
                    suggestedContent: !<regular>
                      value: "arg1"
                    valueType: "java.lang.String"
                    fixed: false
                    equalsMethodPresent: false
                    explicitCastNeeded: false
                  1:
                    sapientType: "BASIC"
                    content: !<regular>
                      value: "arg2"
                    suggestedContent: !<regular>
                      value: "arg2"
                    valueType: "java.lang.String"
                    fixed: false
                    equalsMethodPresent: false
                    explicitCastNeeded: false
              valueType: "java.lang.String[]"
              uuid: "<init>_string[]1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.SpringApplicationAotProcessor"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "INPUT"
      name: "application"
      modelFingerprint: "99FCDD1EAF0C8138C357FC45FFE21FE2"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "CLASS"
        content: !<regular>
          value: "java.lang.Object"
        valueType: "java.lang.Class"
        genericValueType: "?"
        uuid: "prepareApplicationContext_class1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "ReflectionUtils"
      modelFingerprint: "2431FBFDDD24815283C87EFF0247F69D"
      index: 3
      ignored: false
      nestedInLoop: true
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.ReflectionUtils"
        uuid: "org.springframework.util.ReflectionUtils"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.ReflectionUtils"
        name: "invokeMethod"
        parameters:
        - name: "ex"
          value:
            sapientType: "MOCK"
            suggestedContent: !<unknown_object>
              target: "java.lang.reflect.Method"
              onlyPojoFunctions: false
              builderPattern: false
            valueType: "java.lang.reflect.Method"
            uuid: "lambda$prepareApplicationContext$0_method1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "method"
          value:
            sapientType: "NULL"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "target"
          value:
            sapientType: "ARRAY"
            content: !<array>
              values:
                0:
                  sapientType: "ARRAY"
                  content: !<array>
                    values:
                      0:
                        sapientType: "BASIC"
                        content: !<regular>
                          value: "arg1"
                        suggestedContent: !<regular>
                          value: "arg1"
                        valueType: "java.lang.String"
                        fixed: false
                        equalsMethodPresent: false
                        explicitCastNeeded: false
                      1:
                        sapientType: "BASIC"
                        content: !<regular>
                          value: "arg2"
                        suggestedContent: !<regular>
                          value: "arg2"
                        valueType: "java.lang.String"
                        fixed: false
                        equalsMethodPresent: false
                        explicitCastNeeded: false
                  suggestedContent: !<array>
                    values:
                      0:
                        sapientType: "BASIC"
                        content: !<regular>
                          value: "arg1"
                        suggestedContent: !<regular>
                          value: "arg1"
                        valueType: "java.lang.String"
                        fixed: false
                        equalsMethodPresent: false
                        explicitCastNeeded: false
                      1:
                        sapientType: "BASIC"
                        content: !<regular>
                          value: "arg2"
                        suggestedContent: !<regular>
                          value: "arg2"
                        valueType: "java.lang.String"
                        fixed: false
                        equalsMethodPresent: false
                        explicitCastNeeded: false
                  valueType: "java.lang.String[]"
                  uuid: "<init>_string[]1"
                  fixed: false
                  equalsMethodPresent: false
                  explicitCastNeeded: false
            suggestedContent: !<array>
              values:
                0:
                  sapientType: "ARRAY"
                  content: !<array>
                    values:
                      0:
                        sapientType: "BASIC"
                        content: !<regular>
                          value: "arg1"
                        suggestedContent: !<regular>
                          value: "arg1"
                        valueType: "java.lang.String"
                        fixed: false
                        equalsMethodPresent: false
                        explicitCastNeeded: false
                      1:
                        sapientType: "BASIC"
                        content: !<regular>
                          value: "arg2"
                        suggestedContent: !<regular>
                          value: "arg2"
                        valueType: "java.lang.String"
                        fixed: false
                        equalsMethodPresent: false
                        explicitCastNeeded: false
                  suggestedContent: !<array>
                    values:
                      0:
                        sapientType: "BASIC"
                        content: !<regular>
                          value: "arg1"
                        suggestedContent: !<regular>
                          value: "arg1"
                        valueType: "java.lang.String"
                        fixed: false
                        equalsMethodPresent: false
                        explicitCastNeeded: false
                      1:
                        sapientType: "BASIC"
                        content: !<regular>
                          value: "arg2"
                        suggestedContent: !<regular>
                          value: "arg2"
                        valueType: "java.lang.String"
                        fixed: false
                        equalsMethodPresent: false
                        explicitCastNeeded: false
                  valueType: "java.lang.String[]"
                  uuid: "<init>_string[]1"
                  fixed: false
                  equalsMethodPresent: false
                  explicitCastNeeded: false
            valueType: "java.lang.Object[]"
            uuid: "lambda$prepareApplicationContext$0_object[]1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "invokeMethod(Method,not-detected,Object[]): Object"
        returnValue:
          sapientType: "OBJECT"
          content: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          suggestedContent: !<new>
            target: "java.lang.Object"
            parameters: []
            privateConstructor: false
            createdByTargetCode: false
          valueType: "java.lang.Object"
          uuid: "lambda$prepareApplicationContext$0_object1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 137
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "069C03BD4931E13F76F43EDF3AC46FEA"
      index: 4
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.context.support.GenericApplicationContext"
        uuid: "prepareApplicationContext_genericApplicationContext1"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "2e5860ff-9b97-3d7a-a37a-361ee5355e86"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_CALL_INSTRUCTION_CONSTRUCTION_UNFILLED_PARAMS"
    prover: "LLM"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
