---
modelFingerprint: "B12639A20AC1F253CAC61EBED746967B"
targetClass:
  fullClassName: "org.springframework.boot.WebApplicationType"
methods:
- method:
    name: "deduceFromClasspath"
    sourceCodeSignature: "WebApplicationType deduceFromClasspath()"
    returnType: "org.springframework.boot.WebApplicationType"
    instructionFingerprint: "AC19D19E712093ADC7338C1B31B2F828"
  paths:
  - pathId: "path1"
    testPathName: "deduceFromClasspathWhenClassUtilsNotIsPresentJERSEY_INDICATOR_CLASSNull"
    modelFingerprint: "96FF6C6086F05567ADC19E5CB28D0692"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "STATIC"
      name: "ClassUtils.class"
      modelFingerprint: "69D0AA742AA7C00AF2F2910D781662B3"
      valueUuid: "ClassUtils.class"
      methodExercised:
        expression: "isPresent(className:uniqueUuid1,classLoader:uniqueUuid2):boolean1"
        staticAccess: true
    - type: "STATIC"
      name: "ClassUtils.class"
      modelFingerprint: "9D101A7F15D0008600182C9C5BFC5985"
      valueUuid: "ClassUtils.class"
      methodExercised:
        expression: "isPresent(className:uniqueUuid3,classLoader:uniqueUuid4):boolean2"
        staticAccess: true
    - type: "STATIC"
      name: "ClassUtils.class"
      modelFingerprint: "A00714390CC376CE0E11611AD0CFF5B3"
      valueUuid: "ClassUtils.class"
      methodExercised:
        expression: "isPresent(className:uniqueUuid5,classLoader:uniqueUuid6):boolean3"
        staticAccess: true
    - type: "RESULT"
      name: "result"
      modelFingerprint: "69890BE0239E9574FA2A584458F31119"
      valueUuid: "Enum-org.springframework.boot.WebApplicationType-REACTIVE"
    disabled: false
    allValues:
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ClassUtils"
      uuid: "ClassUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "boolean1"
    - sapientType: "BASIC"
      content: !<regular>
        value: "org.springframework.web.reactive.DispatcherHandler"
      valueType: "java.lang.String"
      uuid: "uniqueUuid1"
      fixed: true
    - sapientType: "NULL"
      uuid: "uniqueUuid2"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ClassUtils"
      uuid: "ClassUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "boolean2"
    - sapientType: "BASIC"
      content: !<regular>
        value: "org.springframework.web.servlet.DispatcherServlet"
      valueType: "java.lang.String"
      uuid: "uniqueUuid3"
      fixed: true
    - sapientType: "NULL"
      uuid: "uniqueUuid4"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ClassUtils"
      uuid: "ClassUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "boolean3"
    - sapientType: "BASIC"
      content: !<regular>
        value: "org.glassfish.jersey.servlet.ServletContainer"
      valueType: "java.lang.String"
      uuid: "uniqueUuid5"
      fixed: true
    - sapientType: "NULL"
      uuid: "uniqueUuid6"
    - sapientType: "ENUM"
      content: !<regular>
        value: "REACTIVE"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "Enum-org.springframework.boot.WebApplicationType-REACTIVE"
      fixed: true
    branches:
    - lineNumber: 61
      expression: "ClassUtils.isPresent(WEBFLUX_INDICATOR_CLASS, null)"
      range: "(61,7)-(61,57)"
      evaluatedAs: true
    - lineNumber: 61
      expression: "!ClassUtils.isPresent(WEBMVC_INDICATOR_CLASS, null)"
      range: "(61,62)-(61,112)"
      evaluatedAs: true
    - lineNumber: 62
      expression: "!ClassUtils.isPresent(JERSEY_INDICATOR_CLASS, null)"
      range: "(62,8)-(62,58)"
      evaluatedAs: true
  - pathId: "path2"
    testPathName: "deduceFromClasspathWhenClassUtilsIsPresentJERSEY_INDICATOR_CLASSNullAndSERVLET_INDICATOR_CLASSESIsNotEmptyAndClassUtils"
    modelFingerprint: "D6FD7F8CC82BD7A8730A19B826DF00B5"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "STATIC"
      name: "ClassUtils.class"
      modelFingerprint: "69D0AA742AA7C00AF2F2910D781662B3"
      valueUuid: "ClassUtils.class"
      methodExercised:
        expression: "isPresent(className:uniqueUuid7,classLoader:uniqueUuid8):boolean1"
        staticAccess: true
    - type: "STATIC"
      name: "ClassUtils.class"
      modelFingerprint: "9D101A7F15D0008600182C9C5BFC5985"
      valueUuid: "ClassUtils.class"
      methodExercised:
        expression: "isPresent(className:uniqueUuid9,classLoader:uniqueUuid10):boolean2"
        staticAccess: true
    - type: "STATIC"
      name: "ClassUtils.class"
      modelFingerprint: "431DEDF1E6BA190CD050D1824977404F"
      valueUuid: "ClassUtils.class"
      methodExercised:
        expression: "isPresent(className:uniqueUuid11,classLoader:uniqueUuid12):boolean3"
        staticAccess: true
    - type: "STATIC"
      name: "ClassUtils.class"
      modelFingerprint: "9E19E2CCEB3C149D7736AA32A93F476B"
      valueUuid: "ClassUtils.class"
      methodExercised:
        expression: "isPresent(className:string2,classLoader:uniqueUuid13):boolean4"
        staticAccess: true
    - type: "RESULT"
      name: "result"
      modelFingerprint: "62E62D157B1772A86A54792446F0D9EF"
      valueUuid: "Enum-org.springframework.boot.WebApplicationType-NONE"
    disabled: false
    allValues:
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ClassUtils"
      uuid: "ClassUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "boolean1"
    - sapientType: "BASIC"
      content: !<regular>
        value: "org.springframework.web.reactive.DispatcherHandler"
      valueType: "java.lang.String"
      uuid: "uniqueUuid7"
      fixed: true
    - sapientType: "NULL"
      uuid: "uniqueUuid8"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ClassUtils"
      uuid: "ClassUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "boolean2"
    - sapientType: "BASIC"
      content: !<regular>
        value: "org.springframework.web.servlet.DispatcherServlet"
      valueType: "java.lang.String"
      uuid: "uniqueUuid9"
      fixed: true
    - sapientType: "NULL"
      uuid: "uniqueUuid10"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ClassUtils"
      uuid: "ClassUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "boolean3"
    - sapientType: "BASIC"
      content: !<regular>
        value: "org.glassfish.jersey.servlet.ServletContainer"
      valueType: "java.lang.String"
      uuid: "uniqueUuid11"
      fixed: true
    - sapientType: "NULL"
      uuid: "uniqueUuid12"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ClassUtils"
      uuid: "ClassUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "boolean4"
    - sapientType: "BASIC"
      content: !<regular>
        value: "jakarta.servlet.Servlet"
      valueType: "java.lang.String"
      uuid: "string2"
    - sapientType: "NULL"
      uuid: "uniqueUuid13"
    - sapientType: "ENUM"
      content: !<regular>
        value: "NONE"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "Enum-org.springframework.boot.WebApplicationType-NONE"
      fixed: true
    branches:
    - lineNumber: 61
      expression: "ClassUtils.isPresent(WEBFLUX_INDICATOR_CLASS, null)"
      range: "(61,7)-(61,57)"
      evaluatedAs: true
    - lineNumber: 61
      expression: "!ClassUtils.isPresent(WEBMVC_INDICATOR_CLASS, null)"
      range: "(61,62)-(61,112)"
      evaluatedAs: true
    - lineNumber: 62
      expression: "!ClassUtils.isPresent(JERSEY_INDICATOR_CLASS, null)"
      range: "(62,8)-(62,58)"
      evaluatedAs: false
    - lineNumber: 65
      expression: "for-each(SERVLET_INDICATOR_CLASSES)"
      range: "(65,27)-(65,51)"
      evaluatedAs: true
    - lineNumber: 66
      expression: "!ClassUtils.isPresent(className, null)"
      range: "(66,8)-(66,45)"
      evaluatedAs: true
  - pathId: "path3"
    testPathName: "deduceFromClasspathWhenSERVLET_INDICATOR_CLASSESIsNotEmptyAndClassUtilsIsPresentClassNameNull2"
    modelFingerprint: "0ECDF054501849F4D96A813B7537D805"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "STATIC"
      name: "ClassUtils.class"
      modelFingerprint: "69D0AA742AA7C00AF2F2910D781662B3"
      valueUuid: "ClassUtils.class"
      methodExercised:
        expression: "isPresent(className:uniqueUuid14,classLoader:uniqueUuid15):boolean1"
        staticAccess: true
    - type: "STATIC"
      name: "ClassUtils.class"
      modelFingerprint: "9D101A7F15D0008600182C9C5BFC5985"
      valueUuid: "ClassUtils.class"
      methodExercised:
        expression: "isPresent(className:uniqueUuid16,classLoader:uniqueUuid17):boolean2"
        staticAccess: true
    - type: "STATIC"
      name: "ClassUtils.class"
      modelFingerprint: "431DEDF1E6BA190CD050D1824977404F"
      valueUuid: "ClassUtils.class"
      methodExercised:
        expression: "isPresent(className:uniqueUuid18,classLoader:uniqueUuid19):boolean3"
        staticAccess: true
    - type: "STATIC"
      name: "ClassUtils.class"
      modelFingerprint: "A7BB31AA8B4B3D568A822E6CA631ACB4"
      valueUuid: "ClassUtils.class"
      methodExercised:
        expression: "isPresent(className:string2,classLoader:uniqueUuid20):boolean4"
        staticAccess: true
    - type: "STATIC"
      name: "ClassUtils.class"
      modelFingerprint: "9DB399AF98570939162349A8BFE215E6"
      valueUuid: "ClassUtils.class"
      methodExercised:
        expression: "isPresent(className:string4,classLoader:uniqueUuid21):boolean5"
        staticAccess: true
    - type: "RESULT"
      name: "result"
      modelFingerprint: "AE42E418BA8C3A4BA095ED5087C30160"
      valueUuid: "Enum-org.springframework.boot.WebApplicationType-SERVLET"
    disabled: false
    allValues:
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ClassUtils"
      uuid: "ClassUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "boolean1"
    - sapientType: "BASIC"
      content: !<regular>
        value: "org.springframework.web.reactive.DispatcherHandler"
      valueType: "java.lang.String"
      uuid: "uniqueUuid14"
      fixed: true
    - sapientType: "NULL"
      uuid: "uniqueUuid15"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ClassUtils"
      uuid: "ClassUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "boolean2"
    - sapientType: "BASIC"
      content: !<regular>
        value: "org.springframework.web.servlet.DispatcherServlet"
      valueType: "java.lang.String"
      uuid: "uniqueUuid16"
      fixed: true
    - sapientType: "NULL"
      uuid: "uniqueUuid17"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ClassUtils"
      uuid: "ClassUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "boolean3"
    - sapientType: "BASIC"
      content: !<regular>
        value: "org.glassfish.jersey.servlet.ServletContainer"
      valueType: "java.lang.String"
      uuid: "uniqueUuid18"
      fixed: true
    - sapientType: "NULL"
      uuid: "uniqueUuid19"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ClassUtils"
      uuid: "ClassUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "boolean4"
    - sapientType: "BASIC"
      content: !<regular>
        value: "jakarta.servlet.Servlet"
      valueType: "java.lang.String"
      uuid: "string2"
    - sapientType: "NULL"
      uuid: "uniqueUuid20"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ClassUtils"
      uuid: "ClassUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "boolean5"
    - sapientType: "BASIC"
      content: !<regular>
        value: "org.springframework.web.context.ConfigurableWebApplicationContext"
      valueType: "java.lang.String"
      uuid: "string4"
    - sapientType: "NULL"
      uuid: "uniqueUuid21"
    - sapientType: "ENUM"
      content: !<regular>
        value: "SERVLET"
      valueType: "org.springframework.boot.WebApplicationType"
      uuid: "Enum-org.springframework.boot.WebApplicationType-SERVLET"
      fixed: true
    branches:
    - lineNumber: 61
      expression: "ClassUtils.isPresent(WEBFLUX_INDICATOR_CLASS, null)"
      range: "(61,7)-(61,57)"
      evaluatedAs: true
    - lineNumber: 61
      expression: "!ClassUtils.isPresent(WEBMVC_INDICATOR_CLASS, null)"
      range: "(61,62)-(61,112)"
      evaluatedAs: true
    - lineNumber: 62
      expression: "!ClassUtils.isPresent(JERSEY_INDICATOR_CLASS, null)"
      range: "(62,8)-(62,58)"
      evaluatedAs: false
    - lineNumber: 65
      expression: "for-each(SERVLET_INDICATOR_CLASSES)"
      range: "(65,27)-(65,51)"
      evaluatedAs: true
    - lineNumber: 66
      expression: "!ClassUtils.isPresent(className, null)"
      range: "(66,8)-(66,45)"
      evaluatedAs: false
