---
modelFingerprint: "488BD42762902C5135B2F50425F6CF99"
targetClass:
  fullClassName: "org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer"
methods:
- method:
    name: "initialize"
    sourceCodeSignature: "void initialize(ConfigurableApplicationContext context)"
    returnType: "void"
    parameters:
    - name: "context"
      type: "org.springframework.context.ConfigurableApplicationContext"
    instructionFingerprint: "6A068C45CEA4AF35B96D781B283C9D34"
  paths:
  - pathId: "path1"
    testPathName: "initializeTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "264FBE57C982DC7B76AD46E988AE9B1D"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "context"
      modelFingerprint: "22F7680E81C8A00E4B019BF90B716E88"
      valueUuid: "context"
    - type: "INTERNAL"
      name: "internalMethod"
      modelFingerprint: "43C4A3D02EE9EC9C27B285FFFAE38F66"
      methodExercised:
        expression: "getChecks():configurationWarningsApplicationContextInitializer.CheckArray"
    - type: "LOCAL_VARIABLE"
      name: "context"
      modelFingerprint: "EABEB522606127615AB30A56153AAEE9"
      valueUuid: "context"
      methodExercised:
        expression: "addBeanFactoryPostProcessor(postProcessor:configurationWarningsApplicationContextInitializer.ConfigurationWarningsPostProcessor):void"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer"
        parameters: []
      valueType: "org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "context"
    - sapientType: "ARRAY"
      content: !<array>
        values: {}
      valueType: "org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer$Check[]"
      uuid: "configurationWarningsApplicationContextInitializer.CheckArray"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "context"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "ANY"
      valueType: "org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer$ConfigurationWarningsPostProcessor"
      uuid: "configurationWarningsApplicationContextInitializer.ConfigurationWarningsPostProcessor"
      fixed: true
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
- method:
    name: "getChecks"
    sourceCodeSignature: "Check[] getChecks()"
    returnType: "org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer$Check[]"
    instructionFingerprint: "FE5F4E2A516B16DFA24656DE327A093F"
  paths:
  - pathId: "path1"
    testPathName: "getChecksTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "B12E4115E38774BE88EC04BD702A2F4D"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "69F7824FFFB74F0628FF2D427CB95ACF"
      valueUuid: "configurationWarningsApplicationContextInitializer.CheckArray"
    disabled: true
    failureReason:
      reason: "UNKNOWN_REASON"
    disabledStatusUpdatedBy: "SYSTEM"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer"
        parameters: []
      valueType: "org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer"
      uuid: "target"
    - sapientType: "ARRAY"
      content: !<array>
        values:
          0:
            sapientType: "OBJECT"
            content: !<new>
              target: "org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer$ComponentScanPackageCheck"
              parameters: []
            valueType: "org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer$ComponentScanPackageCheck"
            uuid: "configurationWarningsApplicationContextInitializer.ComponentScanPackageCheck"
            fixed: true
      valueType: "org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer$Check[]"
      uuid: "configurationWarningsApplicationContextInitializer.CheckArray"
