---
modelFingerprint: "FC11F62CE03E2096FD8D65966BCACD49"
methods:
- method:
    name: "registerBeanDefinitions"
    signature: "registerBeanDefinitions(org.springframework.core.type.AnnotationMetadata,org.springframework.beans.factory.support.BeanDefinitionRegistry)\
      \ : void"
    sourceCodeSignature: "void registerBeanDefinitions(AnnotationMetadata importingClassMetadata,\
      \ BeanDefinitionRegistry registry)"
    instructionFingerprint: "9D8B9673EDC4B0D75324BB226698C335"
  paths:
  - pathId: "path1"
    testPathName: "registerBeanDefinitionsWhenRegistryNotContainsBeanDefinitionName"
    constructorSignature: "<init>() : void"
    modelFingerprint: "CEEB8C4AEF74A5185FDD060ADD3520F3"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "importingClassMetadata"
      modelFingerprint: "C7469A8CA7AF21A17555B3A3A335DB1E"
      index: 2
      valueUuid: "registerBeanDefinitions_annotationMetadata1"
    - type: "INPUT"
      name: "registry"
      modelFingerprint: "AC26ED6AF7BCA1FA06F082E15D2C363A"
      index: 3
      valueUuid: "registerBeanDefinitions_beanDefinitionRegistry1"
    - type: "LOCAL_VARIABLE"
      name: "registry"
      modelFingerprint: "930AE089B5C1C85283E0172731001106"
      index: 4
      valueUuid: "registerBeanDefinitions_beanDefinitionRegistry1"
      methodExercised:
        target: "registry"
        name: "containsBeanDefinition"
        parameters:
        - name: "beanName"
          valueUuid: "registerBeanDefinitions_string1"
        signature: "containsBeanDefinition(String): boolean"
        returnValueUuid: "registerBeanDefinitions_boolean1"
        access: 1025
    - type: "STATIC"
      name: "BeanDefinitionBuilder"
      modelFingerprint: "B8DE3774097A9AD02D39FCEB2799504C"
      index: 5
      valueUuid: "uuid2"
      methodExercised:
        target: "org.springframework.beans.factory.support.BeanDefinitionBuilder"
        name: "rootBeanDefinition"
        parameters:
        - name: "beanClass"
          valueUuid: "uuid1"
        signature: "rootBeanDefinition(Class): BeanDefinitionBuilder"
        returnValueUuid: "registerBeanDefinitions_beanDefinitionBuilder1"
        access: 9
    - type: "LOCAL_VARIABLE"
      name: "builder"
      modelFingerprint: "2EC472569B18DC223D237DFC7448255E"
      index: 6
      valueUuid: "registerBeanDefinitions_beanDefinitionBuilder1"
      methodExercised:
        target: "builder"
        name: "getBeanDefinition"
        parameters: []
        signature: "getBeanDefinition(): AbstractBeanDefinition"
        returnValueUuid: "registerBeanDefinitions_abstractBeanDefinition1"
        access: 1
    - type: "LOCAL_VARIABLE"
      name: "registry"
      modelFingerprint: "A015C05B2749579405943E01F7DB58B9"
      index: 7
      valueUuid: "registerBeanDefinitions_beanDefinitionRegistry1"
      methodExercised:
        target: "registry"
        name: "registerBeanDefinition"
        parameters:
        - name: "beanName"
          valueUuid: "registerBeanDefinitions_string1"
        - name: "beanDefinition"
          valueUuid: "registerBeanDefinitions_abstractBeanDefinition1"
        throwsExceptions:
        - "org.springframework.beans.factory.BeanDefinitionStoreException"
        signature: "registerBeanDefinition(String,AbstractBeanDefinition): void throws\
          \ org.springframework.beans.factory.BeanDefinitionStoreException"
        returnValueUuid: "registerBeanDefinitions_void1"
        access: 1025
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 8
      valueUuid: "uuid3"
    uuid: "ce40fea0-b825-3359-9140-d98e9640683a"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.type.AnnotationMetadata"
      uuid: "registerBeanDefinitions_annotationMetadata1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.beans.factory.support.BeanDefinitionRegistry"
      uuid: "registerBeanDefinitions_beanDefinitionRegistry1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.beans.factory.support.BeanDefinitionRegistry"
      uuid: "registerBeanDefinitions_beanDefinitionRegistry1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "registerBeanDefinitions_boolean1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor"
      valueType: "java.lang.String"
      uuid: "registerBeanDefinitions_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "REAL"
      valueType: "org.springframework.beans.factory.support.BeanDefinitionBuilder"
      uuid: "uuid2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "org.springframework.beans.factory.support.BeanDefinitionBuilder"
        method: "rootBeanDefinition"
        methodParameters:
        - value:
            sapientType: "CLASS"
            content: !<regular>
              value: "org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor"
            valueType: "java.lang.Class"
            genericValueType: "org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
      valueType: "org.springframework.beans.factory.support.BeanDefinitionBuilder"
      uuid: "registerBeanDefinitions_beanDefinitionBuilder1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor"
      uuid: "uuid1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "org.springframework.beans.factory.support.BeanDefinitionBuilder"
        method: "rootBeanDefinition"
        methodParameters:
        - value:
            sapientType: "CLASS"
            content: !<regular>
              value: "org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor"
            valueType: "java.lang.Class"
            genericValueType: "org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
      valueType: "org.springframework.beans.factory.support.BeanDefinitionBuilder"
      uuid: "registerBeanDefinitions_beanDefinitionBuilder1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<method_return_from_value>
        target: "org.springframework.beans.factory.support.AbstractBeanDefinition"
        localVariableValue:
          sapientType: "OBJECT"
          content: !<static_method_return>
            target: "org.springframework.beans.factory.support.BeanDefinitionBuilder"
            method: "rootBeanDefinition"
            methodParameters:
            - value:
                sapientType: "CLASS"
                content: !<regular>
                  value: "org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor"
                valueType: "java.lang.Class"
                genericValueType: "org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor"
                fixed: true
                equalsMethodPresent: false
                explicitCastNeeded: false
          valueType: "org.springframework.beans.factory.support.BeanDefinitionBuilder"
          uuid: "registerBeanDefinitions_beanDefinitionBuilder1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        methodParameters: []
        methodName: "getBeanDefinition"
      valueType: "org.springframework.beans.factory.support.AbstractBeanDefinition"
      uuid: "registerBeanDefinitions_abstractBeanDefinition1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.beans.factory.support.BeanDefinitionRegistry"
      uuid: "registerBeanDefinitions_beanDefinitionRegistry1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "registerBeanDefinitions_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor"
      valueType: "java.lang.String"
      uuid: "registerBeanDefinitions_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<method_return_from_value>
        target: "org.springframework.beans.factory.support.AbstractBeanDefinition"
        localVariableValue:
          sapientType: "OBJECT"
          content: !<static_method_return>
            target: "org.springframework.beans.factory.support.BeanDefinitionBuilder"
            method: "rootBeanDefinition"
            methodParameters:
            - value:
                sapientType: "CLASS"
                content: !<regular>
                  value: "org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor"
                valueType: "java.lang.Class"
                genericValueType: "org.springframework.boot.sql.init.dependency.DatabaseInitializationDependencyConfigurer$DependsOnDatabaseInitializationPostProcessor"
                fixed: true
                equalsMethodPresent: false
                explicitCastNeeded: false
          valueType: "org.springframework.beans.factory.support.BeanDefinitionBuilder"
          uuid: "registerBeanDefinitions_beanDefinitionBuilder1"
          fixed: false
          equalsMethodPresent: false
          explicitCastNeeded: false
        methodParameters: []
        methodName: "getBeanDefinition"
      valueType: "org.springframework.beans.factory.support.AbstractBeanDefinition"
      uuid: "registerBeanDefinitions_abstractBeanDefinition1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      uuid: "uuid3"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "registerBeanDefinitionsWhenRegistryContainsBeanDefinitionName"
    constructorSignature: "<init>() : void"
    modelFingerprint: "89817B49C8152E31104A52C1B04B2C09"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "e42a2a9d-7782-3ec1-9358-86451601eb57"
    deleted: true
    disabled: false
    ignoredBySystem: true
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
