---
modelFingerprint: "4514FB90E0CF37E6DB094B710619B5AC"
targetClass:
  fullClassName: "org.springframework.boot.reactor.ReactorEnvironmentPostProcessor"
methods:
- method:
    name: "postProcessEnvironment"
    sourceCodeSignature: "void postProcessEnvironment(ConfigurableEnvironment environment,\
      \ SpringApplication application)"
    returnType: "void"
    parameters:
    - name: "environment"
      type: "org.springframework.core.env.ConfigurableEnvironment"
    - name: "application"
      type: "org.springframework.boot.SpringApplication"
    tryCatchBlocks:
    - idExternalInstruction: 0
      id: 1
      catchExceptions:
      - "java.lang.Exception"
    instructionFingerprint: "C83E21FDBC2ECFEA6C631CF21C12CEB6"
  paths:
  - pathId: "path7"
    testPathName: "postProcessEnvironmentWhenCaughtExceptionThrowsRuntimeException"
    constructorSignature: "<init>() : void"
    modelFingerprint: "32510DC8F807B1BF96FC9AC653FEE73B"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "environment"
      modelFingerprint: "2AB40C7309B23844284816875A86BEFD"
      valueUuid: "environment"
    - type: "INPUT"
      name: "application"
      modelFingerprint: "86BFF8B99831ED759F640847C7C0F409"
      valueUuid: "application"
    - type: "STATIC"
      name: "ClassUtils.class"
      modelFingerprint: "973D6B82BB4187A79AD60D4094B5E6E7"
      valueUuid: "ClassUtils.class"
      methodExercised:
        expression: "isPresent(className:uniqueUuid1,classLoader:uniqueUuid2):boolean1"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      name: "environment"
      modelFingerprint: "1E13A20A3BAF38121F57F0950899E3D4"
      valueUuid: "environment"
      methodExercised:
        expression: "getProperty(key:uniqueUuid3,targetType:uniqueUuid4):object"
    - type: "STATIC"
      name: "Class.class"
      modelFingerprint: "74D0148739EF65F9654645733913537E"
      valueUuid: "Class.class"
      methodExercised:
        expression: "forName(className:uniqueUuid5):class"
        throwsExceptions:
        - "java.lang.ClassNotFoundException"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      name: "debugAgent"
      modelFingerprint: "830E19138586BC6C5D10EDA469C3FF02"
      valueUuid: "class"
      methodExercised:
        expression: "getMethod(name:uniqueUuid6,parameterTypes:classArray):method"
        throwsExceptions:
        - "java.lang.NoSuchMethodException"
        - "java.lang.SecurityException"
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "84C46B879D0B45EAE017C49BDEA902B2"
      valueUuid: "method"
      methodExercised:
        expression: "invoke(obj:uniqueUuid8,args:objectArray):object2"
        throwsExceptions:
        - "java.lang.IllegalAccessException"
        - "java.lang.IllegalArgumentException"
        - "java.lang.reflect.InvocationTargetException"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "1885BB17DA5CF051BD73EE3B223E98EA"
      valueUuid: "runtimeException"
    disabled: true
    failureReason:
      reason: "VARIABLE_THAT_COULD_NOT_BE_ISOLATED_MOCKED"
      source: "debugAgent.getMethod(\\\"init\\\").invoke(null);"
      lineNumber: 52
      details: "A variable could not be isolated/mocked when calling a method - Variable\
        \ name: object of type Method - Method: invoke"
    disabledStatusUpdatedBy: "SYSTEM"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.reactor.ReactorEnvironmentPostProcessor"
        parameters: []
      valueType: "org.springframework.boot.reactor.ReactorEnvironmentPostProcessor"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "environment"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.SpringApplication"
      uuid: "application"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ClassUtils"
      uuid: "ClassUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "boolean1"
    - sapientType: "BASIC"
      content: !<regular>
        value: "reactor.tools.agent.ReactorDebugAgent"
      valueType: "java.lang.String"
      uuid: "uniqueUuid1"
      fixed: true
    - sapientType: "NULL"
      uuid: "uniqueUuid2"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "environment"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "java.lang.Boolean"
      uuid: "object"
      explicitCastNeeded: true
    - sapientType: "BASIC"
      content: !<regular>
        value: "spring.reactor.debug-agent.enabled"
      valueType: "java.lang.String"
      uuid: "uniqueUuid3"
      fixed: true
    - sapientType: "CLASS"
      content: !<regular>
        value: "java.lang.Boolean"
      valueType: "java.lang.Class"
      genericValueType: "java.lang.Boolean"
      uuid: "uniqueUuid4"
      fixed: true
    - sapientType: "MOCK"
      valueType: "java.lang.Class"
      uuid: "Class.class"
    - sapientType: "CLASS"
      content: !<regular>
        value: "reactor.tools.agent.ReactorDebugAgent"
      valueType: "java.lang.Class"
      uuid: "class"
    - sapientType: "BASIC"
      content: !<regular>
        value: "reactor.tools.agent.ReactorDebugAgent"
      valueType: "java.lang.String"
      uuid: "uniqueUuid5"
      fixed: true
    - sapientType: "CLASS"
      content: !<regular>
        value: "reactor.tools.agent.ReactorDebugAgent"
      valueType: "java.lang.Class"
      uuid: "class"
    - sapientType: "OBJECT"
      content: !<method_return_from_value>
        target: "java.lang.reflect.Method"
        localVariableValue:
          sapientType: "CLASS"
          content: !<regular>
            value: "reactor.tools.agent.ReactorDebugAgent"
          valueType: "java.lang.Class"
          uuid: "class"
        methodParameters:
        - value:
            sapientType: "BASIC"
            content: !<regular>
              value: "init"
            valueType: "java.lang.String"
            uuid: "uniqueUuid9"
            fixed: true
        - value:
            sapientType: "ARRAY"
            content: !<array>
              values: {}
            valueType: "java.lang.Class[]"
            uuid: "classArray"
        methodName: "getMethod"
      valueType: "java.lang.reflect.Method"
      uuid: "method"
    - sapientType: "BASIC"
      content: !<regular>
        value: "init"
      valueType: "java.lang.String"
      uuid: "uniqueUuid6"
      fixed: true
    - sapientType: "ARRAY"
      content: !<array>
        values: {}
      valueType: "java.lang.Class[]"
      uuid: "classArray"
    - sapientType: "OBJECT"
      content: !<method_return_from_value>
        target: "java.lang.reflect.Method"
        localVariableValue:
          sapientType: "CLASS"
          content: !<regular>
            value: "reactor.tools.agent.ReactorDebugAgent"
          valueType: "java.lang.Class"
          uuid: "class"
        methodParameters:
        - value:
            sapientType: "BASIC"
            content: !<regular>
              value: "init"
            valueType: "java.lang.String"
            uuid: "uniqueUuid9"
            fixed: true
        - value:
            sapientType: "ARRAY"
            content: !<array>
              values: {}
            valueType: "java.lang.Class[]"
            uuid: "classArray"
        methodName: "getMethod"
      valueType: "java.lang.reflect.Method"
      uuid: "method"
    - sapientType: "OBJECT"
      content: !<new>
        target: "java.lang.Object"
        parameters: []
      valueType: "java.lang.Object"
      uuid: "object2"
    - sapientType: "NULL"
      uuid: "uniqueUuid8"
    - sapientType: "ARRAY"
      content: !<array>
        values: {}
      valueType: "java.lang.Object[]"
      uuid: "objectArray"
    - sapientType: "EXCEPTION"
      content: !<new>
        target: "java.lang.RuntimeException"
        parameters:
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Failed to init Reactor's debug agent"
            valueType: "java.lang.String"
            uuid: "uniqueUuid10"
            fixed: true
        - name: "cause"
          value:
            sapientType: "OBJECT"
            content: !<new>
              target: "java.lang.Exception"
              parameters: []
            valueType: "java.lang.Exception"
            uuid: "exception"
      valueType: "java.lang.RuntimeException"
      uuid: "runtimeException"
      fixed: true
    branches:
    - lineNumber: 47
      expression: "ClassUtils.isPresent(REACTOR_DEBUGAGENT_CLASS, null)"
      range: "(47,7)-(47,58)"
      evaluatedAs: true
    - lineNumber: 49
      expression: "agentEnabled != Boolean.FALSE"
      range: "(49,8)-(49,36)"
      evaluatedAs: true
    - lineNumber: 54
      expression: "catch-exception (Exception)"
      range: "(54,5)-(54,23)"
      evaluatedAs: true
    catchBlockExercised:
      idExternalInstruction: 0
      id: 1
      catchExceptions:
      - "java.lang.Exception"
  - pathId: "path1"
    testPathName: "postProcessEnvironmentWhenEnvironmentGetPropertySpring_threads_virtual_enabledBooleanFalseAndJavaVersionGetJavaVersionN"
    constructorSignature: "<init>() : void"
    modelFingerprint: "B61361F04343F7ED6E312777AC542A49"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "environment"
      modelFingerprint: "2AB40C7309B23844284816875A86BEFD"
      valueUuid: "environment"
    - type: "INPUT"
      name: "application"
      modelFingerprint: "86BFF8B99831ED759F640847C7C0F409"
      valueUuid: "application"
    - type: "STATIC"
      name: "ClassUtils.class"
      modelFingerprint: "973D6B82BB4187A79AD60D4094B5E6E7"
      valueUuid: "ClassUtils.class"
      methodExercised:
        expression: "isPresent(className:uniqueUuid11,classLoader:uniqueUuid12):boolean1"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      name: "environment"
      modelFingerprint: "1E13A20A3BAF38121F57F0950899E3D4"
      valueUuid: "environment"
      methodExercised:
        expression: "getProperty(key:uniqueUuid13,targetType:uniqueUuid14):object"
    - type: "LOCAL_VARIABLE"
      name: "environment"
      modelFingerprint: "C9E03A78F01A1CE740B208717AEF4FF0"
      valueUuid: "environment"
      methodExercised:
        expression: "getProperty(key:uniqueUuid15,targetType:class2,defaultValue:boolean3):object3"
    - type: "STATIC"
      name: "JavaVersion.class.real"
      modelFingerprint: "C99A71E088AC3B7A726A7AC05256EF18"
      valueUuid: "JavaVersion.class.real"
      methodExercised:
        expression: "getJavaVersion():javaVersion"
        staticAccess: true
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    failureReason:
      reason: "VARIABLE_THAT_COULD_NOT_BE_ISOLATED_MOCKED"
      source: "debugAgent.getMethod(\\\"init\\\").invoke(null);"
      lineNumber: 52
      details: "A variable could not be isolated/mocked when calling a method - Variable\
        \ name: object of type Method - Method: invoke"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.reactor.ReactorEnvironmentPostProcessor"
        parameters: []
      valueType: "org.springframework.boot.reactor.ReactorEnvironmentPostProcessor"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "environment"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.SpringApplication"
      uuid: "application"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ClassUtils"
      uuid: "ClassUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "boolean1"
    - sapientType: "BASIC"
      content: !<regular>
        value: "reactor.tools.agent.ReactorDebugAgent"
      valueType: "java.lang.String"
      uuid: "uniqueUuid11"
      fixed: true
    - sapientType: "NULL"
      uuid: "uniqueUuid12"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "environment"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "java.lang.Boolean"
      uuid: "object"
      explicitCastNeeded: true
    - sapientType: "BASIC"
      content: !<regular>
        value: "spring.reactor.debug-agent.enabled"
      valueType: "java.lang.String"
      uuid: "uniqueUuid13"
      fixed: true
    - sapientType: "CLASS"
      content: !<regular>
        value: "java.lang.Boolean"
      valueType: "java.lang.Class"
      genericValueType: "java.lang.Boolean"
      uuid: "uniqueUuid14"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "environment"
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "java.lang.Boolean"
      uuid: "object3"
      explicitCastNeeded: true
    - sapientType: "BASIC"
      content: !<regular>
        value: "spring.threads.virtual.enabled"
      valueType: "java.lang.String"
      uuid: "uniqueUuid15"
      fixed: true
    - sapientType: "CLASS"
      content: !<regular>
        value: "boolean"
      valueType: "java.lang.Class"
      uuid: "class2"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "java.lang.Boolean"
      uuid: "boolean3"
    - sapientType: "REAL"
      valueType: "org.springframework.boot.system.JavaVersion"
      uuid: "JavaVersion.class.real"
    - sapientType: "ENUM"
      content: !<regular>
        value: "SEVENTEEN"
      valueType: "org.springframework.boot.system.JavaVersion"
      uuid: "javaVersion"
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
    branches:
    - lineNumber: 47
      expression: "ClassUtils.isPresent(REACTOR_DEBUGAGENT_CLASS, null)"
      range: "(47,7)-(47,58)"
      evaluatedAs: true
    - lineNumber: 49
      expression: "agentEnabled != Boolean.FALSE"
      range: "(49,8)-(49,36)"
      evaluatedAs: true
    - lineNumber: 59
      expression: "environment.getProperty(\\\"spring.threads.virtual.enabled\\\"\
        , boolean.class, false)"
      range: "(59,7)-(59,85)"
      evaluatedAs: true
    - lineNumber: 60
      expression: "JavaVersion.getJavaVersion().isEqualOrNewerThan(JavaVersion.TWENTY_ONE)"
      range: "(60,8)-(60,78)"
      evaluatedAs: false
- method:
    name: "getOrder"
    sourceCodeSignature: "int getOrder()"
    returnType: "int"
    instructionFingerprint: "B3FE1F447F1436B3B1DD16C4601C95C8"
  paths:
  - pathId: "path1"
    testPathName: "getOrderTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "408D0DD0148C1F235863C7884C307A16"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
