---
modelFingerprint: "80E7CD37ED1EDA42423DE76B4A4C83C9"
targetClass:
  fullClassName: "org.springframework.boot.context.properties.ConfigurationPropertiesBindException"
methods:
- method:
    name: "getBeanType"
    sourceCodeSignature: "Class<?> getBeanType()"
    returnType: "java.lang.Class"
    genericReturnType: "?"
    instructionFingerprint: "0621A159C26129041E912F099C89B605"
  paths:
  - pathId: "path1"
    testPathName: "getBeanTypeTest"
    constructorSignature: "<init>(org.springframework.boot.context.properties.ConfigurationPropertiesBean,java.lang.Exception)\
      \ : void"
    modelFingerprint: "65F793B63079A638A08FFBB3F7517EA1"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "C1D90502D0A449F35A51F92CAAB4BFDD"
      valueUuid: "target"
    - type: "LOCAL_VARIABLE"
      name: "bean"
      modelFingerprint: "0E782D69707814C859C17B6E56271351"
      valueUuid: "bean"
      methodExercised:
        expression: "getName():name"
    - type: "LOCAL_VARIABLE"
      name: "bean"
      modelFingerprint: "B2CEC8BB098D480AEFB43BA3AF5D36E0"
      valueUuid: "bean"
      methodExercised:
        expression: "getAnnotation():configurationProperties"
    - type: "LOCAL_VARIABLE"
      name: "bean"
      modelFingerprint: "8A1B5FFA67ACD9A8F91AAA2C9C6092A4"
      valueUuid: "bean"
      methodExercised:
        expression: "getType():class"
    - type: "STATIC"
      name: "ClassUtils.class"
      modelFingerprint: "53B93477574AD2DD89AFC34DEDDD03C0"
      valueUuid: "ClassUtils.class"
      methodExercised:
        expression: "getShortName(clazz:class):string2"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      name: "annotation"
      modelFingerprint: "A64ACF1091962E51379C44288A665528"
      valueUuid: "configurationProperties"
      methodExercised:
        expression: "prefix():string3"
    - type: "LOCAL_VARIABLE"
      name: "annotation"
      modelFingerprint: "7FE4D5EFF832B93F15E35F05A552A36B"
      valueUuid: "configurationProperties"
      methodExercised:
        expression: "ignoreInvalidFields():boolean1"
    - type: "LOCAL_VARIABLE"
      name: "annotation"
      modelFingerprint: "4E1BBBDF25C6DD1D68E47E2F00B636DC"
      valueUuid: "configurationProperties"
      methodExercised:
        expression: "ignoreUnknownFields():boolean2"
    - type: "FIELD"
      name: "bean"
      modelFingerprint: "E2F5257FE9A84EF11DB7522A949F41F5"
      valueUuid: "bean"
      methodExercised:
        expression: "getType():class2"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "CB6AD079E1AE17612A32D52978FCD12B"
      valueUuid: "class2"
    disabled: false
    failureReason:
      reason: "METHOD_CALL_INSTRUCTION_INTERNAL_METHOD_FAILURE"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.ConfigurationPropertiesBindException"
        parameters:
        - name: "bean"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.ConfigurationPropertiesBean"
            uuid: "bean"
        - name: "cause"
          value:
            sapientType: "OBJECT"
            content: !<new>
              target: "java.lang.Exception"
              parameters: []
            valueType: "java.lang.Exception"
            uuid: "cause"
      valueType: "org.springframework.boot.context.properties.ConfigurationPropertiesBindException"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationPropertiesBean"
      uuid: "bean"
    - sapientType: "BASIC"
      content: !<regular>
        value: "C"
      valueType: "java.lang.String"
      uuid: "name"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationPropertiesBean"
      uuid: "bean"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationProperties"
      uuid: "configurationProperties"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationPropertiesBean"
      uuid: "bean"
    - sapientType: "CLASS"
      content: !<regular>
        value: "java.lang.Object"
      valueType: "java.lang.Class"
      genericValueType: "?"
      uuid: "class"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ClassUtils"
      uuid: "ClassUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "string2"
    - sapientType: "CLASS"
      content: !<regular>
        value: "java.lang.Object"
      valueType: "java.lang.Class"
      genericValueType: "?"
      uuid: "class"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationProperties"
      uuid: "configurationProperties"
    - sapientType: "BASIC"
      content: !<regular>
        value: "B"
      valueType: "java.lang.String"
      uuid: "string3"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationProperties"
      uuid: "configurationProperties"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "boolean1"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationProperties"
      uuid: "configurationProperties"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "boolean2"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationPropertiesBean"
      uuid: "bean"
    - sapientType: "CLASS"
      content: !<regular>
        value: "java.lang.Object"
      valueType: "java.lang.Class"
      genericValueType: "?"
      uuid: "class2"
    - sapientType: "CLASS"
      content: !<regular>
        value: "java.lang.Object"
      valueType: "java.lang.Class"
      genericValueType: "?"
      uuid: "class2"
    calledSomeStaticInternalMethod: true
- method:
    name: "getAnnotation"
    sourceCodeSignature: "ConfigurationProperties getAnnotation()"
    returnType: "org.springframework.boot.context.properties.ConfigurationProperties"
    instructionFingerprint: "1F15587850139EA1EB259A27700A3D40"
  paths:
  - pathId: "path1"
    testPathName: "getAnnotationTest"
    constructorSignature: "<init>(org.springframework.boot.context.properties.ConfigurationPropertiesBean,java.lang.Exception)\
      \ : void"
    modelFingerprint: "3E2CE1E430C35FAEC8B66D04D43C48FF"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "C1D90502D0A449F35A51F92CAAB4BFDD"
      valueUuid: "target"
    - type: "LOCAL_VARIABLE"
      name: "bean"
      modelFingerprint: "0E782D69707814C859C17B6E56271351"
      valueUuid: "bean"
      methodExercised:
        expression: "getName():name"
    - type: "LOCAL_VARIABLE"
      name: "bean"
      modelFingerprint: "B2CEC8BB098D480AEFB43BA3AF5D36E0"
      valueUuid: "bean"
      methodExercised:
        expression: "getAnnotation():configurationProperties"
    - type: "LOCAL_VARIABLE"
      name: "bean"
      modelFingerprint: "8A1B5FFA67ACD9A8F91AAA2C9C6092A4"
      valueUuid: "bean"
      methodExercised:
        expression: "getType():class"
    - type: "STATIC"
      name: "ClassUtils.class"
      modelFingerprint: "53B93477574AD2DD89AFC34DEDDD03C0"
      valueUuid: "ClassUtils.class"
      methodExercised:
        expression: "getShortName(clazz:class):string2"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      name: "annotation"
      modelFingerprint: "A64ACF1091962E51379C44288A665528"
      valueUuid: "configurationProperties"
      methodExercised:
        expression: "prefix():string3"
    - type: "LOCAL_VARIABLE"
      name: "annotation"
      modelFingerprint: "7FE4D5EFF832B93F15E35F05A552A36B"
      valueUuid: "configurationProperties"
      methodExercised:
        expression: "ignoreInvalidFields():boolean1"
    - type: "LOCAL_VARIABLE"
      name: "annotation"
      modelFingerprint: "4E1BBBDF25C6DD1D68E47E2F00B636DC"
      valueUuid: "configurationProperties"
      methodExercised:
        expression: "ignoreUnknownFields():boolean2"
    - type: "FIELD"
      name: "bean"
      modelFingerprint: "83A2C4FA38E563666077B1307898BF8F"
      valueUuid: "bean"
      methodExercised:
        expression: "getAnnotation():configurationProperties2"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "56BBAFD8BC48A8B2C7AC211628E486D1"
      valueUuid: "configurationProperties2"
    disabled: true
    failureReason:
      reason: "METHOD_CALL_INSTRUCTION_INTERNAL_METHOD_FAILURE"
    disabledStatusUpdatedBy: "SYSTEM"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.ConfigurationPropertiesBindException"
        parameters:
        - name: "bean"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.properties.ConfigurationPropertiesBean"
            uuid: "bean"
        - name: "cause"
          value:
            sapientType: "OBJECT"
            content: !<new>
              target: "java.lang.Exception"
              parameters: []
            valueType: "java.lang.Exception"
            uuid: "cause"
      valueType: "org.springframework.boot.context.properties.ConfigurationPropertiesBindException"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationPropertiesBean"
      uuid: "bean"
    - sapientType: "BASIC"
      content: !<regular>
        value: "C"
      valueType: "java.lang.String"
      uuid: "name"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationPropertiesBean"
      uuid: "bean"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationProperties"
      uuid: "configurationProperties"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationPropertiesBean"
      uuid: "bean"
    - sapientType: "CLASS"
      content: !<regular>
        value: "java.lang.Object"
      valueType: "java.lang.Class"
      genericValueType: "?"
      uuid: "class"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.ClassUtils"
      uuid: "ClassUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "string2"
    - sapientType: "CLASS"
      content: !<regular>
        value: "java.lang.Object"
      valueType: "java.lang.Class"
      genericValueType: "?"
      uuid: "class"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationProperties"
      uuid: "configurationProperties"
    - sapientType: "BASIC"
      content: !<regular>
        value: "B"
      valueType: "java.lang.String"
      uuid: "string3"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationProperties"
      uuid: "configurationProperties"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "boolean1"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationProperties"
      uuid: "configurationProperties"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "boolean2"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationPropertiesBean"
      uuid: "bean"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationProperties"
      uuid: "configurationProperties2"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.ConfigurationProperties"
      uuid: "configurationProperties2"
    calledSomeStaticInternalMethod: true
