---
modelFingerprint: "F0EE6C0CA1FD8B70BBC59FE410E784AF"
methods:
- method:
    name: "getIncompatibleKeys"
    signature: "getIncompatibleKeys() : java.util.Collection<java.lang.String>"
    sourceCodeSignature: "Collection<String> getIncompatibleKeys()"
    instructionFingerprint: "93FB793E1B2725A546A0A199F79F678F"
  paths:
  - pathId: "path1"
    testPathName: "getIncompatibleKeysTest"
    constructorSignature: "<init>(java.lang.String[]) : void"
    modelFingerprint: "A6A04173479CB9B662F2A0234097345B"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "B4549FD0F44BA024D614871E9D3E4109"
      index: 1
      valueUuid: "target"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "5C52255E4C5718FA6A53B2C5AB9393AF"
      index: 2
      valueUuid: "<init>_list1"
    uuid: "47639a94-7d23-372b-b1db-c80b039f9206"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.properties.IncompatibleConfigurationException"
        parameters:
        - name: "incompatibleKeys"
          value:
            sapientType: "ARRAY"
            content: !<array>
              values: {}
            valueType: "java.lang.String[]"
            uuid: "<init>_string[]1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.properties.IncompatibleConfigurationException"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.List"
      genericValueType: "java.lang.String"
      uuid: "<init>_list1"
      fixed: false
      equalsMethodPresent: true
      explicitCastNeeded: false
