---
modelFingerprint: "00947102DC09A83FB9504F86277B2049"
targetClass:
  fullClassName: "org.springframework.boot.web.context.ServerPortInfoApplicationContextInitializer"
methods:
- method:
    name: "initialize"
    sourceCodeSignature: "void initialize(ConfigurableApplicationContext applicationContext)"
    returnType: "void"
    parameters:
    - name: "applicationContext"
      type: "org.springframework.context.ConfigurableApplicationContext"
    instructionFingerprint: "116A5DA1E71285E9C64704C3DBB33C9A"
  paths:
  - pathId: "path1"
    testPathName: "initializeTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "53D7AC1FDF53B951524B16B6779E6B5E"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "applicationContext"
      modelFingerprint: "DF659A8AABEBC6871FFB4901FD8A4D44"
      valueUuid: "applicationContext"
    - type: "LOCAL_VARIABLE"
      name: "applicationContext"
      modelFingerprint: "A4D12748FE3659115BB9423F12EC5B35"
      valueUuid: "applicationContext"
      methodExercised:
        expression: "addApplicationListener(listener:targetClassObject):void"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.context.ServerPortInfoApplicationContextInitializer"
        parameters: []
      valueType: "org.springframework.boot.web.context.ServerPortInfoApplicationContextInitializer"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "applicationContext"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ConfigurableApplicationContext"
      uuid: "applicationContext"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "THIS"
      valueType: "org.springframework.boot.web.context.ServerPortInfoApplicationContextInitializer"
      uuid: "targetClassObject"
      fixed: true
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
- method:
    name: "onApplicationEvent"
    sourceCodeSignature: "void onApplicationEvent(WebServerInitializedEvent event)"
    returnType: "void"
    parameters:
    - name: "event"
      type: "org.springframework.boot.web.context.WebServerInitializedEvent"
    instructionFingerprint: "A35A483525B044679606133AA6D0A51F"
  paths:
  - pathId: "path1"
    testPathName: "onApplicationEventWhenContextGetParentIsNotNull"
    constructorSignature: "<init>() : void"
    modelFingerprint: "8654A3554883A27A34CC4C437D540620"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "event"
      modelFingerprint: "DBE276975429758C808C2C597F9C4E06"
      valueUuid: "event"
    - type: "LOCAL_VARIABLE"
      name: "event"
      modelFingerprint: "EFBD6D6526665700746E741FE18F5D9F"
      valueUuid: "event"
      methodExercised:
        expression: "getApplicationContext():webServerApplicationContext"
    - type: "LOCAL_VARIABLE"
      name: "context"
      modelFingerprint: "59FE87855BFB45ADDA38D2A0ED452EF3"
      valueUuid: "webServerApplicationContext"
      methodExercised:
        expression: "getServerNamespace():string"
    - type: "STATIC"
      name: "StringUtils.class.real"
      modelFingerprint: "A91647CB447119BB97CB86EA51675C61"
      valueUuid: "StringUtils.class.real"
      methodExercised:
        expression: "hasText(str:string):boolean1"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      name: "event"
      modelFingerprint: "EFBD6D6526665700746E741FE18F5D9F"
      valueUuid: "event"
      methodExercised:
        expression: "getApplicationContext():webServerApplicationContext2"
    - type: "LOCAL_VARIABLE"
      name: "event"
      modelFingerprint: "CEC4B9692D383BDEDED11B7ACA90C121"
      valueUuid: "event"
      methodExercised:
        expression: "getWebServer():webServer"
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "6803A62129679EDF27A45BC74EA8814A"
      valueUuid: "webServer"
      methodExercised:
        expression: "getPort():int1"
    - type: "LOCAL_VARIABLE"
      name: "context"
      modelFingerprint: "D78B0466EB1484C31CED26905ED35676"
      valueUuid: "webServerApplicationContext2"
      methodExercised:
        expression: "getParent():applicationContext"
    - type: "LOCAL_VARIABLE"
      name: "context"
      modelFingerprint: "D78B0466EB1484C31CED26905ED35676"
      valueUuid: "webServerApplicationContext2"
      methodExercised:
        expression: "getParent():applicationContext2"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    failureReason:
      reason: "METHOD_CALL_INSTRUCTION_INTERNAL_METHOD_RECURSIVE_CALL"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.context.ServerPortInfoApplicationContextInitializer"
        parameters: []
      valueType: "org.springframework.boot.web.context.ServerPortInfoApplicationContextInitializer"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerInitializedEvent"
      uuid: "event"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerInitializedEvent"
      uuid: "event"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerApplicationContext"
      uuid: "webServerApplicationContext"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerApplicationContext"
      uuid: "webServerApplicationContext"
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "string"
    - sapientType: "REAL"
      valueType: "org.springframework.util.StringUtils"
      uuid: "StringUtils.class.real"
    - sapientType: "BASIC"
      content: !<regular>
        value: true
      valueType: "boolean"
      uuid: "boolean1"
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "string"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerInitializedEvent"
      uuid: "event"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerApplicationContext"
      uuid: "webServerApplicationContext2"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerInitializedEvent"
      uuid: "event"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.server.WebServer"
      uuid: "webServer"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.server.WebServer"
      uuid: "webServer"
    - sapientType: "BASIC"
      content: !<regular>
        value: 0
      valueType: "int"
      uuid: "int1"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerApplicationContext"
      uuid: "webServerApplicationContext2"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ApplicationContext"
      uuid: "applicationContext"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerApplicationContext"
      uuid: "webServerApplicationContext2"
    - sapientType: "MOCK"
      valueType: "org.springframework.context.ApplicationContext"
      uuid: "applicationContext2"
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
    branches:
    - lineNumber: 70
      expression: "StringUtils.hasText(name)"
      range: "(70,10)-(70,34)"
      evaluatedAs: true
      internalMethodName: "getName"
    - lineNumber: 74
      expression: "context instanceof ConfigurableApplicationContext configurableContext"
      range: "(74,7)-(74,75)"
      evaluatedAs: false
      internalMethodName: "setPortProperty"
    - lineNumber: 77
      expression: "context.getParent() != null"
      range: "(77,7)-(77,33)"
      evaluatedAs: true
      internalMethodName: "setPortProperty"
  - pathId: "path3"
    testPathName: "onApplicationEventWhenContextNotInstanceOfConfigurableApplicationContextAndContextGetParentIsNull"
    constructorSignature: "<init>() : void"
    modelFingerprint: "6DC4BF6014D0756969D3781A0BDCC53F"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "event"
      modelFingerprint: "DBE276975429758C808C2C597F9C4E06"
      valueUuid: "event"
    - type: "LOCAL_VARIABLE"
      name: "event"
      modelFingerprint: "EFBD6D6526665700746E741FE18F5D9F"
      valueUuid: "event"
      methodExercised:
        expression: "getApplicationContext():webServerApplicationContext"
    - type: "LOCAL_VARIABLE"
      name: "context"
      modelFingerprint: "59FE87855BFB45ADDA38D2A0ED452EF3"
      valueUuid: "webServerApplicationContext"
      methodExercised:
        expression: "getServerNamespace():string"
    - type: "STATIC"
      name: "StringUtils.class"
      modelFingerprint: "54487C1342835B70D21156D482BFAC73"
      valueUuid: "StringUtils.class"
      methodExercised:
        expression: "hasText(str:string):boolean1"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      name: "event"
      modelFingerprint: "EFBD6D6526665700746E741FE18F5D9F"
      valueUuid: "event"
      methodExercised:
        expression: "getApplicationContext():webServerApplicationContext2"
    - type: "LOCAL_VARIABLE"
      name: "event"
      modelFingerprint: "CEC4B9692D383BDEDED11B7ACA90C121"
      valueUuid: "event"
      methodExercised:
        expression: "getWebServer():webServer"
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "6803A62129679EDF27A45BC74EA8814A"
      valueUuid: "webServer"
      methodExercised:
        expression: "getPort():int1"
    - type: "LOCAL_VARIABLE"
      name: "context"
      modelFingerprint: "B88A332A542977E9543FB77ED1CC4067"
      valueUuid: "webServerApplicationContext2"
      methodExercised:
        expression: "getParent():applicationContext"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.context.ServerPortInfoApplicationContextInitializer"
        parameters: []
      valueType: "org.springframework.boot.web.context.ServerPortInfoApplicationContextInitializer"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerInitializedEvent"
      uuid: "event"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerInitializedEvent"
      uuid: "event"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerApplicationContext"
      uuid: "webServerApplicationContext"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerApplicationContext"
      uuid: "webServerApplicationContext"
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "string"
    - sapientType: "MOCK"
      valueType: "org.springframework.util.StringUtils"
      uuid: "StringUtils.class"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "boolean1"
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "string"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerInitializedEvent"
      uuid: "event"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerApplicationContext"
      uuid: "webServerApplicationContext2"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerInitializedEvent"
      uuid: "event"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.server.WebServer"
      uuid: "webServer"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.server.WebServer"
      uuid: "webServer"
    - sapientType: "BASIC"
      content: !<regular>
        value: 0
      valueType: "int"
      uuid: "int1"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.web.context.WebServerApplicationContext"
      uuid: "webServerApplicationContext2"
    - sapientType: "NULL"
      valueType: "org.springframework.context.ApplicationContext"
      uuid: "applicationContext"
      fixed: true
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
    branches:
    - lineNumber: 70
      expression: "StringUtils.hasText(name)"
      range: "(70,10)-(70,34)"
      evaluatedAs: false
      internalMethodName: "getName"
    - lineNumber: 74
      expression: "context instanceof ConfigurableApplicationContext configurableContext"
      range: "(74,7)-(74,75)"
      evaluatedAs: false
      internalMethodName: "setPortProperty"
    - lineNumber: 77
      expression: "context.getParent() != null"
      range: "(77,7)-(77,33)"
      evaluatedAs: false
      internalMethodName: "setPortProperty"
