---
modelFingerprint: "DBDA660A82466387D71DDBBB2EDE06F6"
methods:
- method:
    name: "onApplicationEvent"
    signature: "onApplicationEvent(org.springframework.boot.context.event.ApplicationEnvironmentPreparedEvent)\
      \ : void"
    sourceCodeSignature: "void onApplicationEvent(ApplicationEnvironmentPreparedEvent\
      \ event)"
    instructionFingerprint: "7DE71F3D7360565863E50BC43A9E2131"
  paths:
  - pathId: "path1"
    testPathName: "onApplicationEventTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "4CD6FB9FF706DD447439EBD45AD56C2E"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "event"
      modelFingerprint: "1D35C3C0931222FAB0303A9775E0FF76"
      index: 2
      valueUuid: "onApplicationEvent_applicationEnvironmentPreparedEvent1"
    - type: "LOCAL_VARIABLE"
      name: "event"
      modelFingerprint: "7733F028206E15905051EB3FEE8D500C"
      index: 3
      valueUuid: "onApplicationEvent_applicationEnvironmentPreparedEvent1"
      methodExercised:
        target: "event"
        name: "getEnvironment"
        parameters: []
        signature: "getEnvironment(): ConfigurableEnvironment"
        returnValueUuid: "onApplicationEvent_configurableEnvironment1"
        access: 1
    - type: "STATIC"
      name: "Binder"
      modelFingerprint: "043221FB9C28A02BC77E6C5F39E43BCE"
      index: 4
      valueUuid: "uuid1"
      methodExercised:
        target: "org.springframework.boot.context.properties.bind.Binder"
        name: "get"
        parameters:
        - name: "environment"
          valueUuid: "onApplicationEvent_configurableEnvironment1"
        signature: "get(ConfigurableEnvironment): Binder"
        returnValueUuid: "onApplicationEvent_binder1"
        access: 9
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "A69EF5826107047BC36293AB1875E8D3"
      index: 5
      valueUuid: "onApplicationEvent_binder1"
      methodExercised:
        target: "org.springframework.boot.context.properties.bind.Binder"
        name: "bind"
        parameters:
        - name: "name"
          valueUuid: "uuid2"
        - name: "target"
          valueUuid: "uuid3"
        signature: "bind(String,Class): BindResult"
        returnValueUuid: "onApplicationEvent_bindResult1"
        access: 1
    - type: "STATIC"
      name: "AnsiOutput"
      modelFingerprint: "37A2298ACE8D7A85F4A60437A978B753"
      index: 6
      valueUuid: "uuid4"
      methodExercised:
        target: "org.springframework.boot.ansi.AnsiOutput"
        name: "setEnabled"
        parameters:
        - valueUuid: "onApplicationEvent_ansiOutput.Enabled1"
        signature: "setEnabled(AnsiOutput$Enabled): void"
        returnValueUuid: "onApplicationEvent_void2"
        access: 9
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "B1EE9589E9F52247B3F01B368BED1CA8"
      index: 7
      valueUuid: "onApplicationEvent_bindResult1"
      methodExercised:
        target: "org.springframework.boot.context.properties.bind.BindResult"
        name: "ifBound"
        parameters:
        - name: "consumer"
          valueUuid: "uuid5"
        signature: "ifBound(Consumer): void"
        returnValueUuid: "onApplicationEvent_void1"
        access: 1
    - type: "LOCAL_VARIABLE"
      name: "environment"
      modelFingerprint: "D0643D4D620DDAFA5CDD6D279E9A3815"
      index: 8
      valueUuid: "onApplicationEvent_configurableEnvironment1"
      methodExercised:
        target: "environment"
        name: "getProperty"
        parameters:
        - name: "key"
          valueUuid: "uuid6"
        - name: "targetType"
          valueUuid: "uuid7"
        signature: "getProperty(String,Class): Object"
        returnValueUuid: "onApplicationEvent_object1"
        access: 1025
    - type: "STATIC"
      name: "AnsiOutput"
      modelFingerprint: "1B7A92F5A939CA0F79F8670695116E33"
      index: 9
      valueUuid: "uuid8"
      methodExercised:
        target: "org.springframework.boot.ansi.AnsiOutput"
        name: "setConsoleAvailable"
        parameters:
        - name: "consoleAvailable"
          valueUuid: "onApplicationEvent_object1"
        signature: "setConsoleAvailable(Boolean): void"
        returnValueUuid: "onApplicationEvent_void3"
        access: 9
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 10
      valueUuid: "uuid9"
    uuid: "472c146e-fdf0-3ffc-9db9-d5a3f9028e9d"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "UNKNOWN_REASON"
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.AnsiOutputApplicationListener"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.config.AnsiOutputApplicationListener"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.event.ApplicationEnvironmentPreparedEvent"
        parameters:
        - name: "bootstrapContext"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.ConfigurableBootstrapContext"
            uuid: "onApplicationEvent_applicationEnvironmentPreparedEvent1-bootstrapContext"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "application"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.SpringApplication"
            uuid: "onApplicationEvent_applicationEnvironmentPreparedEvent1-application"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "args"
          value:
            sapientType: "ARRAY"
            content: !<array>
              values: {}
            valueType: "java.lang.String[]"
            uuid: "onApplicationEvent_applicationEnvironmentPreparedEvent1-args"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "environment"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.core.env.ConfigurableEnvironment"
            uuid: "onApplicationEvent_configurableEnvironment1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.event.ApplicationEnvironmentPreparedEvent"
      uuid: "onApplicationEvent_applicationEnvironmentPreparedEvent1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.event.ApplicationEnvironmentPreparedEvent"
        parameters:
        - name: "bootstrapContext"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.ConfigurableBootstrapContext"
            uuid: "onApplicationEvent_applicationEnvironmentPreparedEvent1-bootstrapContext"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "application"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.SpringApplication"
            uuid: "onApplicationEvent_applicationEnvironmentPreparedEvent1-application"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "args"
          value:
            sapientType: "ARRAY"
            content: !<array>
              values: {}
            valueType: "java.lang.String[]"
            uuid: "onApplicationEvent_applicationEnvironmentPreparedEvent1-args"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "environment"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.core.env.ConfigurableEnvironment"
            uuid: "onApplicationEvent_configurableEnvironment1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.event.ApplicationEnvironmentPreparedEvent"
      uuid: "onApplicationEvent_applicationEnvironmentPreparedEvent1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "onApplicationEvent_configurableEnvironment1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.bind.Binder"
      uuid: "uuid1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.bind.Binder"
      uuid: "onApplicationEvent_binder1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "onApplicationEvent_configurableEnvironment1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.bind.Binder"
      uuid: "onApplicationEvent_binder1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.bind.BindResult"
      uuid: "onApplicationEvent_bindResult1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "spring.output.ansi.enabled"
      valueType: "java.lang.String"
      uuid: "uuid2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.ansi.AnsiOutput$Enabled"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.ansi.AnsiOutput$Enabled"
      uuid: "uuid3"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.ansi.AnsiOutput"
      uuid: "uuid4"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "onApplicationEvent_void2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "ENUM"
      content: !<regular>
        value: "NEVER"
      valueType: "org.springframework.boot.ansi.AnsiOutput$Enabled"
      uuid: "onApplicationEvent_ansiOutput.Enabled1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.bind.BindResult"
      uuid: "onApplicationEvent_bindResult1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "onApplicationEvent_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "PRIVATE_INNER_CLASS_OR_LAMBDA"
      valueType: "java.util.function.Consumer"
      uuid: "uuid5"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.ConfigurableEnvironment"
      uuid: "onApplicationEvent_configurableEnvironment1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "java.lang.Boolean"
      uuid: "onApplicationEvent_object1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: true
    - sapientType: "BASIC"
      content: !<regular>
        value: "spring.output.ansi.console-available"
      valueType: "java.lang.String"
      uuid: "uuid6"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "CLASS"
      content: !<regular>
        value: "java.lang.Boolean"
      valueType: "java.lang.Class"
      genericValueType: "java.lang.Boolean"
      uuid: "uuid7"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.ansi.AnsiOutput"
      uuid: "uuid8"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "onApplicationEvent_void3"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "java.lang.Boolean"
      uuid: "onApplicationEvent_object1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: true
    - sapientType: "VOID"
      uuid: "uuid9"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
- method:
    name: "getOrder"
    signature: "getOrder() : int"
    sourceCodeSignature: "int getOrder()"
    instructionFingerprint: "95CF55ABF81D9F2AD97C4B845549B578"
  paths:
  - pathId: "path1"
    testPathName: "getOrderTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "78C74A2B4027C98A6F6D029815F43B2B"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "62ACDF8F5454EC79FE782A40BE51B358"
      index: 2
      valueUuid: "uuid10"
    uuid: "c0bb632e-c120-35d3-9fe3-7fc42c801bce"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.AnsiOutputApplicationListener"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.config.AnsiOutputApplicationListener"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: -2147483637
      valueType: "int"
      uuid: "uuid10"
      fixed: true
      equalsMethodPresent: true
      explicitCastNeeded: false
