---
modelFingerprint: "6858B34BD7A56D7CCC39E97E30C60ED9"
targetClass:
  fullClassName: "org.springframework.boot.context.config.ConfigDataEnvironmentContributorPlaceholdersResolver"
methods:
- method:
    name: "resolvePlaceholders"
    sourceCodeSignature: "Object resolvePlaceholders(Object value)"
    returnType: "java.lang.Object"
    parameters:
    - name: "value"
      type: "java.lang.Object"
    instructionFingerprint: "3592E9ED98C6900040A82AACF60D19CC"
  paths:
  - pathId: "path1"
    testPathName: "resolvePlaceholdersWhenValueInstanceOfString"
    constructorSignature: "<init>(java.lang.Iterable<org.springframework.boot.context.config.ConfigDataEnvironmentContributor>,org.springframework.boot.context.config.ConfigDataActivationContext,org.springframework.boot.context.config.ConfigDataEnvironmentContributor,boolean)\
      \ : void"
    modelFingerprint: "8A4EF19A540C1D9E729591E5AE3F3B76"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "6B8180B0F5B96522894D164FF15FC91E"
      valueUuid: "target"
    - type: "INPUT"
      name: "value"
      modelFingerprint: "771DC1EEA9260D80AEE9A3ECE44C7DDE"
      valueUuid: "value"
    - type: "FIELD"
      name: "helper"
      modelFingerprint: "BA84305E87CDCC05608B6067DE369C06"
      valueUuid: "propertyPlaceholderHelper"
      methodExercised:
        expression: "replacePlaceholders(value:value,placeholderResolver:uniqueUuid1):string"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D446A609419428DDEAA49A58091F3986"
      valueUuid: "string"
    disabled: true
    failureReason:
      reason: "VARIABLE_THAT_COULD_NOT_BE_ISOLATED_MOCKED"
      source: "return this.helper.replacePlaceholders(string, this::resolvePlaceholder);"
      lineNumber: 60
      details: "A variable could not be isolated/mocked when calling a method - Variable\
        \ name: helper - Method: replacePlaceholders"
    disabledStatusUpdatedBy: "SYSTEM"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataEnvironmentContributorPlaceholdersResolver"
        parameters:
        - name: "contributors"
          value:
            sapientType: "COLLECTION"
            content: !<collection>
              parameters: []
              values: []
            valueType: "java.lang.Iterable"
            genericValueType: "org.springframework.boot.context.config.ConfigDataEnvironmentContributor"
            uuid: "contributors"
        - name: "activationContext"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.config.ConfigDataActivationContext"
            uuid: "activationContext"
        - name: "activeContributor"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.config.ConfigDataEnvironmentContributor"
            uuid: "activeContributor"
        - name: "failOnResolveFromInactiveContributor"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: false
            valueType: "boolean"
            uuid: "failOnResolveFromInactiveContributor"
      valueType: "org.springframework.boot.context.config.ConfigDataEnvironmentContributorPlaceholdersResolver"
      uuid: "target"
    - sapientType: "BASIC"
      content: !<regular>
        value: "value1"
      valueType: "java.lang.String"
      uuid: "value"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.util.PropertyPlaceholderHelper"
        parameters:
        - name: "placeholderPrefix"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "${"
            valueType: "java.lang.String"
            uuid: "uniqueUuid2"
            fixed: true
        - name: "placeholderSuffix"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "}"
            valueType: "java.lang.String"
            uuid: "uniqueUuid3"
            fixed: true
        - name: "valueSeparator"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: ":"
            valueType: "java.lang.String"
            uuid: "uniqueUuid4"
            fixed: true
        - name: "ignoreUnresolvablePlaceholders"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: true
            valueType: "boolean"
            uuid: "uniqueUuid5"
            fixed: true
      valueType: "org.springframework.util.PropertyPlaceholderHelper"
      uuid: "propertyPlaceholderHelper"
      fixed: true
    - sapientType: "BASIC"
      content: !<regular>
        value: "return_of_replacePlaceholders1"
      valueType: "java.lang.String"
      uuid: "string"
    - sapientType: "BASIC"
      content: !<regular>
        value: "value1"
      valueType: "java.lang.String"
      uuid: "value"
    - sapientType: "ANY"
      valueType: "org.springframework.util.PropertyPlaceholderHelper$PlaceholderResolver"
      uuid: "uniqueUuid1"
    - sapientType: "BASIC"
      content: !<regular>
        value: "return_of_replacePlaceholders1"
      valueType: "java.lang.String"
      uuid: "string"
    branches:
    - lineNumber: 59
      expression: "value instanceof String string"
      range: "(59,7)-(59,36)"
      evaluatedAs: true
  - pathId: "path2"
    testPathName: "resolvePlaceholdersWhenValueNotInstanceOfString"
    constructorSignature: "<init>(java.lang.Iterable<org.springframework.boot.context.config.ConfigDataEnvironmentContributor>,org.springframework.boot.context.config.ConfigDataActivationContext,org.springframework.boot.context.config.ConfigDataEnvironmentContributor,boolean)\
      \ : void"
    modelFingerprint: "584C237A478C60FD612E333946BA5C7C"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "6B8180B0F5B96522894D164FF15FC91E"
      valueUuid: "target"
    - type: "INPUT"
      name: "value"
      modelFingerprint: "EB88C1798DFE893966CC3D4502A52694"
      valueUuid: "value"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "7D8E87CB1B63A9579EC7584A697ED33D"
      valueUuid: "value"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataEnvironmentContributorPlaceholdersResolver"
        parameters:
        - name: "contributors"
          value:
            sapientType: "COLLECTION"
            content: !<collection>
              parameters: []
              values: []
            valueType: "java.lang.Iterable"
            genericValueType: "org.springframework.boot.context.config.ConfigDataEnvironmentContributor"
            uuid: "contributors"
        - name: "activationContext"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.config.ConfigDataActivationContext"
            uuid: "activationContext"
        - name: "activeContributor"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.config.ConfigDataEnvironmentContributor"
            uuid: "activeContributor"
        - name: "failOnResolveFromInactiveContributor"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: false
            valueType: "boolean"
            uuid: "failOnResolveFromInactiveContributor"
      valueType: "org.springframework.boot.context.config.ConfigDataEnvironmentContributorPlaceholdersResolver"
      uuid: "target"
    - sapientType: "OBJECT"
      content: !<new>
        target: "java.lang.Object"
        parameters: []
      valueType: "java.lang.Object"
      uuid: "value"
    - sapientType: "OBJECT"
      content: !<new>
        target: "java.lang.Object"
        parameters: []
      valueType: "java.lang.Object"
      uuid: "value"
    branches:
    - lineNumber: 59
      expression: "value instanceof String string"
      range: "(59,7)-(59,36)"
      evaluatedAs: false
