---
modelFingerprint: "294CAC41BAC406C44A26680D397F5A93"
methods:
- method:
    name: "getPath"
    signature: "getPath() : java.nio.file.Path"
    sourceCodeSignature: "Path getPath()"
    instructionFingerprint: "28B39D9A186260040038580F8A81C210"
  paths:
  - pathId: "path1"
    testPathName: "getPathTest"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "CC233906D0CD3046B1D863FF9B08183D"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "a8f6c4be-0895-3a4f-9a2a-c43eb253ed13"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "equals"
    signature: "equals(java.lang.Object) : boolean"
    sourceCodeSignature: "boolean equals(Object obj)"
    instructionFingerprint: "371E6F678CC03DC2B369E0BD3502C867"
  paths:
  - pathId: "path1"
    testPathName: "equalsWhenThisEqualsObj"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "CF0E57E25700EA4E82CEB42659FB1CE6"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "d0712d51-f0f8-381e-af89-bd29c8516608"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
  - pathId: "path5"
    testPathName: "equalsWhenObjIsNull"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "CD744B3DF49272425F76276A04615E0A"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "42f03dea-2e61-3c4b-bbc0-1a97b94b4d90"
    deleted: true
    disabled: false
    ignoredBySystem: true
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
  - pathId: "path2"
    testPathName: "equalsWhenGetClassNotEqualsObjGetClass"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "0C32B4776DBA2C225121D174DA10D409"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "26ff6ba6-6f29-3ff2-bca0-b8c532e7a53b"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
  - pathId: "path3"
    testPathName: "equalsWhenObjectsEqualsThisPathOtherPath"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "63892D524CF70BBA816F39CF3FAC5CE6"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "99005416-0d04-3a2b-a722-ec83efe2e866"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
  - pathId: "path4"
    testPathName: "equalsWhenObjectsNotEqualsThisPathOtherPath"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "B3B7F3D30B0882AF933C0524510A2CBA"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "ee0e48e4-37b5-3ea7-aa6e-3aa1b978d3b2"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "toString"
    signature: "toString() : java.lang.String"
    sourceCodeSignature: "String toString()"
    instructionFingerprint: "7511E8642DC32E52DA30EF94A2C6D752"
  paths:
  - pathId: "path1"
    testPathName: "toStringTest"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "EF635FFFDD6E2B1C93FC0C854BCC7BEB"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "5EB66ED8A9342B390E46E6290581C737"
      index: 1
      valueUuid: "target"
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "8F65BA100D896AA9661BEBDAFF5DB075"
      index: 2
      valueUuid: "uuid2"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_string1"
        - name: "message"
          valueUuid: "uuid1"
        signature: "notNull(String,String): void"
        returnValueUuid: "<init>_void1"
        access: 9
    - type: "RESULT"
      name: "result"
      modelFingerprint: "C43FC0385E8B0466F8D218E8F9709DED"
      index: 3
      valueUuid: "toString_string1"
    uuid: "363d3698-f34c-39ad-914f-376a19498023"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "UNKNOWN_REASON"
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigTreeConfigDataResource"
        parameters:
        - name: "path"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "A"
            valueType: "java.lang.String"
            uuid: "<init>_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.config.ConfigTreeConfigDataResource"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "REAL"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "<init>_string1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Path must not be null"
      valueType: "java.lang.String"
      uuid: "uuid1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "config tree [/A]"
      valueType: "java.lang.String"
      uuid: "toString_string1"
      fixed: false
      equalsMethodPresent: true
      explicitCastNeeded: false
