---
modelFingerprint: "81CAE786662FAB2995DECBCDD16B4CEB"
methods:
- method:
    name: "load"
    signature: "load(org.springframework.boot.context.config.ConfigDataLoaderContext,org.springframework.boot.context.config.ConfigTreeConfigDataResource)\
      \ : org.springframework.boot.context.config.ConfigData"
    sourceCodeSignature: "ConfigData load(ConfigDataLoaderContext context, ConfigTreeConfigDataResource\
      \ resource)"
    instructionFingerprint: "F5BEF8FCE3F0BDF00ADE8F8E5BBB5286"
  paths:
  - pathId: "path1"
    testPathName: "loadTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "510F247B7BB0EC8CBF62A46434AFF673"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "context"
      modelFingerprint: "A77FA42C1218B17B3106286D9F01EEA7"
      index: 2
      valueUuid: "load_configDataLoaderContext1"
    - type: "INPUT"
      name: "resource"
      modelFingerprint: "C252926492BA85DC62DBCCEB6DBB1A90"
      index: 3
      valueUuid: "load_configTreeConfigDataResource1"
    - type: "LOCAL_VARIABLE"
      name: "resource"
      modelFingerprint: "1F580CCE3749E82EA132EEC00FFB7076"
      index: 4
      valueUuid: "load_configTreeConfigDataResource1"
      methodExercised:
        target: "resource"
        name: "getPath"
        parameters: []
        signature: "getPath(): Path"
        returnValueUuid: "load_path1"
        access: 0
    - type: "STATIC"
      name: "ConfigDataResourceNotFoundException"
      modelFingerprint: "98B87600C45E4217A02A93C565CA097D"
      index: 5
      valueUuid: "uuid1"
      methodExercised:
        target: "org.springframework.boot.context.config.ConfigDataResourceNotFoundException"
        name: "throwIfDoesNotExist"
        parameters:
        - name: "resource"
          valueUuid: "load_configTreeConfigDataResource1"
        - name: "pathToCheck"
          valueUuid: "load_path1"
        signature: "throwIfDoesNotExist(ConfigTreeConfigDataResource,Path): void"
        returnValueUuid: "load_void1"
        access: 9
    - type: "RESULT"
      name: "result"
      modelFingerprint: "7279F1C557DAAD5BC15EBC8981E107B3"
      index: 6
      valueUuid: "load_configData1"
    uuid: "ff42effe-8e08-33e3-9690-b409079214e3"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "CLASS_TYPE_COULD_NOT_BE_MOCKED_AND_NEEDS_TO_STRING"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigTreeConfigDataLoader"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.config.ConfigTreeConfigDataLoader"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigDataLoaderContext"
      uuid: "load_configDataLoaderContext1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigTreeConfigDataResource"
      uuid: "load_configTreeConfigDataResource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigTreeConfigDataResource"
      uuid: "load_configTreeConfigDataResource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "java.nio.file.Path"
      uuid: "load_path1"
      fixed: false
      nameForMock: "load_path1"
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigDataResourceNotFoundException"
      uuid: "uuid1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "load_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigTreeConfigDataResource"
      uuid: "load_configTreeConfigDataResource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "java.nio.file.Path"
      uuid: "load_path1"
      fixed: false
      nameForMock: "load_path1"
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigData"
        parameters:
        - name: "propertySources"
          value:
            sapientType: "COLLECTION"
            content: !<collection>
              parameters: []
              values:
              - sapientType: "OBJECT"
                content: !<new>
                  target: "org.springframework.boot.env.ConfigTreePropertySource"
                  parameters:
                  - name: "name"
                    value:
                      sapientType: "BASIC"
                      content: !<regular>
                        value: "Config tree 'load_path1'"
                      valueType: "java.lang.String"
                      uuid: "load_string1"
                      fixed: false
                      equalsMethodPresent: false
                      explicitCastNeeded: false
                  - name: "sourceDirectory"
                    value:
                      sapientType: "MOCK"
                      valueType: "java.nio.file.Path"
                      uuid: "load_path1"
                      fixed: false
                      nameForMock: "load_path1"
                      equalsMethodPresent: false
                      explicitCastNeeded: false
                  - name: "options"
                    value:
                      sapientType: "ARRAY"
                      content: !<array>
                        values:
                          0:
                            sapientType: "ENUM"
                            content: !<regular>
                              value: "AUTO_TRIM_TRAILING_NEW_LINE"
                            valueType: "org.springframework.boot.env.ConfigTreePropertySource$Option"
                            uuid: "Enum-org.springframework.boot.env.ConfigTreePropertySource$Option-AUTO_TRIM_TRAILING_NEW_LINE"
                            fixed: true
                            equalsMethodPresent: false
                            explicitCastNeeded: false
                      valueType: "org.springframework.boot.env.ConfigTreePropertySource$Option[]"
                      uuid: "load_configTreePropertySource.Option[]1"
                      fixed: false
                      equalsMethodPresent: false
                      explicitCastNeeded: false
                  privateConstructor: false
                  createdByTargetCode: true
                valueType: "org.springframework.boot.env.ConfigTreePropertySource"
                uuid: "load_configTreePropertySource1"
                fixed: true
                equalsMethodPresent: false
                explicitCastNeeded: false
            valueType: "java.util.List"
            genericValueType: "org.springframework.boot.env.ConfigTreePropertySource"
            uuid: "load_list1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "options"
          value:
            sapientType: "ARRAY"
            content: !<array>
              values: {}
            valueType: "org.springframework.boot.context.config.ConfigData$Option[]"
            uuid: "load_configData.Option[]1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: true
      valueType: "org.springframework.boot.context.config.ConfigData"
      uuid: "load_configData1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
