---
modelFingerprint: "039995CCEE905B18B7B4E1C20E4841D5"
targetClass:
  fullClassName: "org.springframework.boot.context.config.ConfigDataPropertiesRuntimeHints"
methods:
- method:
    name: "registerHints"
    sourceCodeSignature: "void registerHints(RuntimeHints hints, ClassLoader classLoader)"
    returnType: "void"
    parameters:
    - name: "hints"
      type: "org.springframework.aot.hint.RuntimeHints"
    - name: "classLoader"
      type: "java.lang.ClassLoader"
    instructionFingerprint: "E220058433C211F375CBA5AF7F701D97"
  paths:
  - pathId: "path1"
    testPathName: "registerHintsTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "1F1C14A64F987CB4788BA12CA9E8D7B2"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "hints"
      modelFingerprint: "4ED55336421B23543566FDFA4FA3D8EE"
      valueUuid: "hints"
    - type: "INPUT"
      name: "classLoader"
      modelFingerprint: "C286DE215DE7563ED1CD0033A63BD833"
      valueUuid: "classLoader"
    - type: "STATIC"
      name: "BindableRuntimeHintsRegistrar.class"
      modelFingerprint: "A8666CF007E73993AA9A644297004D7C"
      valueUuid: "BindableRuntimeHintsRegistrar.class"
      methodExercised:
        expression: "forTypes(types:classArray):bindableRuntimeHintsRegistrar"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "B27B7D07B561008C206004EAE97D3A01"
      valueUuid: "bindableRuntimeHintsRegistrar"
      methodExercised:
        expression: "registerHints(hints:hints):void"
    - type: "LOCAL_VARIABLE"
      name: "hints"
      modelFingerprint: "4CB4DF9F79CB3A7EB548A6DBF86FE8B8"
      valueUuid: "hints"
      methodExercised:
        expression: "reflection():reflectionHints"
    - type: "STATIC"
      name: "ReflectionUtils.class.real"
      modelFingerprint: "EEE045DAC712A64644D9B1C66D9D96D2"
      valueUuid: "ReflectionUtils.class.real"
      methodExercised:
        expression: "findMethod(clazz:uniqueUuid2,name:uniqueUuid3,paramTypes:classArray2):method"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "D01638ABA71109C110A27981CA8CD566"
      valueUuid: "reflectionHints"
      methodExercised:
        expression: "registerMethod(method:method,mode:Enum-org.springframework.aot.hint.ExecutableMode-INVOKE):reflectionHints2"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataPropertiesRuntimeHints"
        parameters: []
      valueType: "org.springframework.boot.context.config.ConfigDataPropertiesRuntimeHints"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.RuntimeHints"
      uuid: "hints"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.lang.ClassLoader"
        method: "getPlatformClassLoader"
        methodParameters: []
      valueType: "java.lang.ClassLoader"
      uuid: "classLoader"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar"
      uuid: "BindableRuntimeHintsRegistrar.class"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar"
      uuid: "bindableRuntimeHintsRegistrar"
    - sapientType: "ARRAY"
      content: !<array>
        values:
          0:
            sapientType: "CLASS"
            content: !<regular>
              value: "org.springframework.boot.context.config.ConfigDataProperties"
            valueType: "java.lang.Class"
            genericValueType: "org.springframework.boot.context.config.ConfigDataProperties"
            uuid: "uniqueUuid1"
            fixed: true
      valueType: "java.lang.Class[]"
      genericValueType: "org.springframework.boot.context.config.ConfigDataProperties"
      uuid: "classArray"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar"
      uuid: "bindableRuntimeHintsRegistrar"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.RuntimeHints"
      uuid: "hints"
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.RuntimeHints"
      uuid: "hints"
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.ReflectionHints"
      uuid: "reflectionHints"
    - sapientType: "REAL"
      valueType: "org.springframework.util.ReflectionUtils"
      uuid: "ReflectionUtils.class.real"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "org.springframework.util.ReflectionUtils"
        method: "findMethod"
        methodParameters:
        - value:
            sapientType: "CLASS"
            content: !<regular>
              value: "org.springframework.boot.context.config.ConfigDataLocation"
            valueType: "java.lang.Class"
            genericValueType: "org.springframework.boot.context.config.ConfigDataLocation"
            uuid: "uniqueUuid5"
            fixed: true
        - value:
            sapientType: "BASIC"
            content: !<regular>
              value: "of"
            valueType: "java.lang.String"
            uuid: "uniqueUuid6"
            fixed: true
        - value:
            sapientType: "ARRAY"
            content: !<array>
              values:
                0:
                  sapientType: "CLASS"
                  content: !<regular>
                    value: "java.lang.String"
                  valueType: "java.lang.Class"
                  genericValueType: "java.lang.String"
                  fixed: true
            valueType: "java.lang.Class[]"
            genericValueType: "java.lang.String"
            uuid: "classArray2"
      valueType: "java.lang.reflect.Method"
      uuid: "method"
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.context.config.ConfigDataLocation"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.context.config.ConfigDataLocation"
      uuid: "uniqueUuid2"
      fixed: true
    - sapientType: "BASIC"
      content: !<regular>
        value: "of"
      valueType: "java.lang.String"
      uuid: "uniqueUuid3"
      fixed: true
    - sapientType: "ARRAY"
      content: !<array>
        values:
          0:
            sapientType: "CLASS"
            content: !<regular>
              value: "java.lang.String"
            valueType: "java.lang.Class"
            genericValueType: "java.lang.String"
            uuid: "uniqueUuid4"
            fixed: true
      valueType: "java.lang.Class[]"
      genericValueType: "java.lang.String"
      uuid: "classArray2"
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.ReflectionHints"
      uuid: "reflectionHints"
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.ReflectionHints"
      uuid: "reflectionHints2"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "org.springframework.util.ReflectionUtils"
        method: "findMethod"
        methodParameters:
        - value:
            sapientType: "CLASS"
            content: !<regular>
              value: "org.springframework.boot.context.config.ConfigDataLocation"
            valueType: "java.lang.Class"
            genericValueType: "org.springframework.boot.context.config.ConfigDataLocation"
            uuid: "uniqueUuid7"
            fixed: true
        - value:
            sapientType: "BASIC"
            content: !<regular>
              value: "of"
            valueType: "java.lang.String"
            uuid: "uniqueUuid8"
            fixed: true
        - value:
            sapientType: "ARRAY"
            content: !<array>
              values:
                0:
                  sapientType: "CLASS"
                  content: !<regular>
                    value: "java.lang.String"
                  valueType: "java.lang.Class"
                  genericValueType: "java.lang.String"
                  fixed: true
            valueType: "java.lang.Class[]"
            genericValueType: "java.lang.String"
            uuid: "classArray2"
      valueType: "java.lang.reflect.Method"
      uuid: "method"
    - sapientType: "ENUM"
      content: !<regular>
        value: "INVOKE"
      valueType: "org.springframework.aot.hint.ExecutableMode"
      uuid: "Enum-org.springframework.aot.hint.ExecutableMode-INVOKE"
      fixed: true
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
