---
modelFingerprint: "5232542B7D1603979FEFD37434340781"
methods:
- method:
    name: "getLocation"
    signature: "getLocation() : org.springframework.boot.context.config.ConfigDataLocation"
    instructionFingerprint: "EDAAE51B769561EB9940BA79DA30CE9E"
  paths:
  - pathId: "path1"
    testPathName: "getLocationTest"
    constructorSignature: "<init>(org.springframework.boot.context.config.ConfigDataLocation,java.lang.String,java.lang.Throwable)\
      \ : void"
    filledByUser: false
    modelFingerprint: "E1D47491519AB981AAA7702671D0893E"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "ee6cb6cd-2929-3c2a-8c18-cd662e8fb11b"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "getOrigin"
    signature: "getOrigin() : org.springframework.boot.origin.Origin"
    instructionFingerprint: "190C3C140F95851B2D0034BBEFF17D2A"
  paths:
  - pathId: "path1"
    testPathName: "getOriginTest"
    constructorSignature: "<init>(org.springframework.boot.context.config.ConfigDataLocation,java.lang.String,java.lang.Throwable)\
      \ : void"
    filledByUser: false
    modelFingerprint: "B4DAA467EF4463D8773722D7DC967CF4"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "EE7EB18B1F0AD03378031D10BB280A3B"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "8DAA0ACF6E9FD16A035385420479491B"
      index: 2
      ignored: false
      valueUuid: "uuid4"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_configDataLocation1"
        - name: "message"
          valueUuid: "uuid3"
        signature: "notNull(ConfigDataLocation,String): void"
        returnValueUuid: "<init>_void1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Origin"
      modelFingerprint: "1E61C3D49E018B1D27BD993DCE011428"
      index: 3
      ignored: false
      valueUuid: "uuid5"
      methodExercised:
        target: "org.springframework.boot.origin.Origin"
        name: "from"
        parameters:
        - name: "source"
          valueUuid: "<init>_configDataLocation1"
        signature: "from(ConfigDataLocation): Origin"
        returnValueUuid: "getOrigin_origin1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "5F7FDFDDEDFBC96EDDAA057511F38A3C"
      index: 4
      ignored: false
      valueUuid: "getOrigin_origin1"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "7470ee36-9b2f-3d61-ac6f-ede146cc5169"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataLocationNotFoundException"
        parameters:
        - name: "location"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.config.ConfigDataLocation"
            uuid: "<init>_configDataLocation1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "message1"
            valueType: "java.lang.String"
            uuid: "<init>_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "cause"
          value:
            sapientType: "OBJECT"
            content: !<new>
              target: "java.lang.Throwable"
              parameters: []
              privateConstructor: false
              createdByTargetCode: false
            suggestedContent: !<new>
              target: "java.lang.Throwable"
              parameters: []
              privateConstructor: false
              createdByTargetCode: false
            valueType: "java.lang.Throwable"
            uuid: "<init>_throwable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.context.config.ConfigDataLocationNotFoundException"
        parameters:
        - name: "location"
          value:
            sapientType: "UNKNOWN"
            valueType: "org.springframework.boot.context.config.ConfigDataLocation"
            uuid: "<init>_configDataLocation1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            valueType: "java.lang.String"
            uuid: "<init>_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "cause"
          value:
            sapientType: "UNKNOWN"
            suggestedContent: !<new>
              target: "java.lang.Throwable"
              parameters: []
              privateConstructor: false
              createdByTargetCode: false
            valueType: "java.lang.Throwable"
            uuid: "<init>_throwable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.config.ConfigDataLocationNotFoundException"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid4"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigDataLocation"
      uuid: "<init>_configDataLocation1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Location must not be null"
      valueType: "java.lang.String"
      uuid: "uuid3"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.origin.Origin"
      uuid: "uuid5"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.origin.Origin"
      uuid: "getOrigin_origin1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigDataLocation"
      uuid: "<init>_configDataLocation1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.origin.Origin"
      uuid: "getOrigin_origin1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
- method:
    name: "getReferenceDescription"
    signature: "getReferenceDescription() : java.lang.String"
    instructionFingerprint: "DAF88A1FBC403B9EE10A029746D3B05E"
  paths:
  - pathId: "path1"
    testPathName: "getReferenceDescriptionTest"
    constructorSignature: "<init>(org.springframework.boot.context.config.ConfigDataLocation,java.lang.String,java.lang.Throwable)\
      \ : void"
    filledByUser: false
    modelFingerprint: "C09F8411F3195626286BA2F79828FDB0"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "EE7EB18B1F0AD03378031D10BB280A3B"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "8DAA0ACF6E9FD16A035385420479491B"
      index: 2
      ignored: false
      valueUuid: "uuid7"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_configDataLocation1"
        - name: "message"
          valueUuid: "uuid6"
        signature: "notNull(ConfigDataLocation,String): void"
        returnValueUuid: "<init>_void1"
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D1F433D4EB9F8805FF391E82DAB508AB"
      index: 3
      ignored: false
      valueUuid: "getReferenceDescription_string1"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "ce5624c4-d029-3185-9cec-77e45be74ad0"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "UNKNOWN_REASON"
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataLocationNotFoundException"
        parameters:
        - name: "location"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.config.ConfigDataLocation"
            uuid: "<init>_configDataLocation1"
            fixed: false
            nameForMock: "<init>_configDataLocation1"
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "message1"
            valueType: "java.lang.String"
            uuid: "<init>_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "cause"
          value:
            sapientType: "OBJECT"
            content: !<new>
              target: "java.lang.Throwable"
              parameters: []
              privateConstructor: false
              createdByTargetCode: false
            suggestedContent: !<new>
              target: "java.lang.Throwable"
              parameters: []
              privateConstructor: false
              createdByTargetCode: false
            valueType: "java.lang.Throwable"
            uuid: "<init>_throwable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      suggestedContent: !<new>
        target: "org.springframework.boot.context.config.ConfigDataLocationNotFoundException"
        parameters:
        - name: "location"
          value:
            sapientType: "UNKNOWN"
            valueType: "org.springframework.boot.context.config.ConfigDataLocation"
            uuid: "<init>_configDataLocation1"
            fixed: false
            nameForMock: "<init>_configDataLocation1"
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            valueType: "java.lang.String"
            uuid: "<init>_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "cause"
          value:
            sapientType: "UNKNOWN"
            suggestedContent: !<new>
              target: "java.lang.Throwable"
              parameters: []
              privateConstructor: false
              createdByTargetCode: false
            valueType: "java.lang.Throwable"
            uuid: "<init>_throwable1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.config.ConfigDataLocationNotFoundException"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid7"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigDataLocation"
      uuid: "<init>_configDataLocation1"
      fixed: false
      nameForMock: "<init>_configDataLocation1"
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "Location must not be null"
      valueType: "java.lang.String"
      uuid: "uuid6"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "result1"
      valueType: "java.lang.String"
      uuid: "getReferenceDescription_string1"
      fixed: false
      equalsMethodPresent: true
      explicitCastNeeded: false
