---
modelFingerprint: "D4DE13B47A41C9D29F4316CC9ABDF0EF"
targetClass:
  fullClassName: "org.springframework.boot.context.config.ConfigTreeConfigDataResource"
methods:
- method:
    name: "getPath"
    sourceCodeSignature: "Path getPath()"
    returnType: "java.nio.file.Path"
    instructionFingerprint: "28B39D9A186260040038580F8A81C210"
  paths:
  - pathId: "path1"
    testPathName: "getPathTest"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "DF918E43163E98DE5543305E4EEB7570"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
- method:
    name: "equals"
    sourceCodeSignature: "boolean equals(Object obj)"
    returnType: "boolean"
    parameters:
    - name: "obj"
      type: "java.lang.Object"
    instructionFingerprint: "371E6F678CC03DC2B369E0BD3502C867"
  paths:
  - pathId: "path1"
    testPathName: "equalsWhenThisEqualsObj"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "0C65D61A9C4D341E55E9DDCB77CA6770"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
    branches:
    - lineNumber: 54
      expression: "this == obj"
      range: "(54,7)-(54,17)"
      evaluatedAs: true
  - pathId: "path2"
    testPathName: "equalsWhenGetClassNotEqualsObjGetClass"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "DCC29C34537FCDA115BB795ECD97F0DF"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
    branches:
    - lineNumber: 54
      expression: "this == obj"
      range: "(54,7)-(54,17)"
      evaluatedAs: false
    - lineNumber: 57
      expression: "obj == null"
      range: "(57,7)-(57,17)"
      evaluatedAs: false
    - lineNumber: 57
      expression: "getClass() != obj.getClass()"
      range: "(57,22)-(57,49)"
      evaluatedAs: true
  - pathId: "path3"
    testPathName: "equalsWhenObjectsEqualsThisPathOtherPath"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "20F12C414EAF18FDA2A27B2011572A51"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
    branches:
    - lineNumber: 54
      expression: "this == obj"
      range: "(54,7)-(54,17)"
      evaluatedAs: false
    - lineNumber: 57
      expression: "obj == null"
      range: "(57,7)-(57,17)"
      evaluatedAs: false
    - lineNumber: 57
      expression: "getClass() != obj.getClass()"
      range: "(57,22)-(57,49)"
      evaluatedAs: false
    - lineNumber: 61
      expression: "Objects.equals(this.path, other.path)"
      range: "(61,10)-(61,46)"
      evaluatedAs: true
  - pathId: "path4"
    testPathName: "equalsWhenObjectsNotEqualsThisPathOtherPath"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "BBBF261BDC2DBBD94A42A50001B85586"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
    branches:
    - lineNumber: 54
      expression: "this == obj"
      range: "(54,7)-(54,17)"
      evaluatedAs: false
    - lineNumber: 57
      expression: "obj == null"
      range: "(57,7)-(57,17)"
      evaluatedAs: false
    - lineNumber: 57
      expression: "getClass() != obj.getClass()"
      range: "(57,22)-(57,49)"
      evaluatedAs: false
    - lineNumber: 61
      expression: "Objects.equals(this.path, other.path)"
      range: "(61,10)-(61,46)"
      evaluatedAs: false
- method:
    name: "toString"
    sourceCodeSignature: "String toString()"
    returnType: "java.lang.String"
    instructionFingerprint: "7511E8642DC32E52DA30EF94A2C6D752"
  paths:
  - pathId: "path1"
    testPathName: "toStringTest"
    constructorSignature: "<init>(java.lang.String) : void"
    modelFingerprint: "CC337FEB5640C268C39D4094304176E9"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "5C79C6A87F488FC1728C53EBF9CF38B7"
      valueUuid: "target"
    - type: "STATIC"
      name: "Assert.class.real"
      modelFingerprint: "E3C7160918F12F0CB94267EE2D0A5E6A"
      valueUuid: "Assert.class.real"
      methodExercised:
        expression: "notNull(object:path,message:uniqueUuid1):void"
        staticAccess: true
    - type: "RESULT"
      name: "result"
      modelFingerprint: "091B75976C9D293D99B1CC9191883BE7"
      valueUuid: "string"
    disabled: true
    failureReason:
      reason: "UNKNOWN_REASON"
    disabledStatusUpdatedBy: "SYSTEM"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigTreeConfigDataResource"
        parameters:
        - name: "path"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "A"
            valueType: "java.lang.String"
            uuid: "path"
      valueType: "org.springframework.boot.context.config.ConfigTreeConfigDataResource"
      uuid: "target"
    - sapientType: "REAL"
      valueType: "org.springframework.util.Assert"
      uuid: "Assert.class.real"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void"
      fixed: true
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "path"
    - sapientType: "BASIC"
      content: !<regular>
        value: "Path must not be null"
      valueType: "java.lang.String"
      uuid: "uniqueUuid1"
      fixed: true
    - sapientType: "BASIC"
      content: !<regular>
        value: "config tree [/A]"
      valueType: "java.lang.String"
      uuid: "string"
