---
modelFingerprint: "F8F90C4B0862C165E585E0674E3CF4EF"
targetClass:
  fullClassName: "org.springframework.boot.context.config.ConfigDataActivationContext"
methods:
- method:
    name: "withProfiles"
    sourceCodeSignature: "ConfigDataActivationContext withProfiles(Profiles profiles)"
    returnType: "org.springframework.boot.context.config.ConfigDataActivationContext"
    parameters:
    - name: "profiles"
      type: "org.springframework.boot.context.config.Profiles"
    instructionFingerprint: "15BA650F6D38082DF59181E3AE71BE28"
  paths:
  - pathId: "path1"
    testPathName: "withProfilesTest"
    constructorSignature: "<init>(org.springframework.boot.cloud.CloudPlatform,org.springframework.boot.context.config.Profiles)\
      \ : void"
    modelFingerprint: "CA6EBB89C21C170448827514978290AA"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "66E88232337CD5B2E4AE638A07CB24F0"
      valueUuid: "target"
    - type: "INPUT"
      name: "profiles"
      modelFingerprint: "94DB7841E4063FBE5D7010645BC08A04"
      valueUuid: "profiles"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "C30E4B8206DAE3CF43326C757018F8BF"
      valueUuid: "configDataActivationContext2"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataActivationContext"
        parameters:
        - name: "cloudPlatform"
          value:
            sapientType: "ENUM"
            content: !<regular>
              value: "NONE"
            valueType: "org.springframework.boot.cloud.CloudPlatform"
            uuid: "cloudPlatform"
        - name: "profiles"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.config.Profiles"
            uuid: "profiles2"
      valueType: "org.springframework.boot.context.config.ConfigDataActivationContext"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.Profiles"
      uuid: "profiles"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataActivationContext"
        parameters:
        - name: "cloudPlatform"
          value:
            sapientType: "ENUM"
            content: !<regular>
              value: "NONE"
            valueType: "org.springframework.boot.cloud.CloudPlatform"
            uuid: "cloudPlatform"
        - name: "profiles"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.config.Profiles"
            uuid: "profiles"
      valueType: "org.springframework.boot.context.config.ConfigDataActivationContext"
      uuid: "configDataActivationContext2"
      fixed: true
- method:
    name: "getCloudPlatform"
    sourceCodeSignature: "CloudPlatform getCloudPlatform()"
    returnType: "org.springframework.boot.cloud.CloudPlatform"
    instructionFingerprint: "A4275D56235D7EC6E7EF3FBC19632A5F"
  paths:
  - pathId: "path1"
    testPathName: "getCloudPlatformTest"
    constructorSignature: "<init>(org.springframework.boot.cloud.CloudPlatform,org.springframework.boot.context.config.Profiles)\
      \ : void"
    modelFingerprint: "D7D672F2CE94B9FDCAA2E867ADD16838"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
- method:
    name: "getProfiles"
    sourceCodeSignature: "Profiles getProfiles()"
    returnType: "org.springframework.boot.context.config.Profiles"
    instructionFingerprint: "88B3518F0423D2CB4792CCF5E9657D8D"
  paths:
  - pathId: "path1"
    testPathName: "getProfilesTest"
    constructorSignature: "<init>(org.springframework.boot.cloud.CloudPlatform,org.springframework.boot.context.config.Profiles)\
      \ : void"
    modelFingerprint: "646AAE565A7F3581D58AAA906B480B13"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
- method:
    name: "toString"
    sourceCodeSignature: "String toString()"
    returnType: "java.lang.String"
    instructionFingerprint: "53B48C0CF62D32947C878916D0D3AD58"
  paths:
  - pathId: "path1"
    testPathName: "toStringTest"
    constructorSignature: "<init>(org.springframework.boot.cloud.CloudPlatform,org.springframework.boot.context.config.Profiles)\
      \ : void"
    modelFingerprint: "2983A1F7871936D73D688B8F0A080EC1"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "66E88232337CD5B2E4AE638A07CB24F0"
      valueUuid: "target"
    - type: "LOCAL_VARIABLE"
      name: "creator"
      modelFingerprint: "F7439A9D7009C69AF2B96C801D4496FB"
      valueUuid: "toStringCreator"
      methodExercised:
        expression: "append(fieldName:uniqueUuid1,value:cloudPlatform):toStringCreator2"
    - type: "LOCAL_VARIABLE"
      name: "creator"
      modelFingerprint: "A18E4FBAD1B4EED195D8F10140D76650"
      valueUuid: "toStringCreator"
      methodExercised:
        expression: "append(fieldName:uniqueUuid3,value:profiles):toStringCreator3"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D446A609419428DDEAA49A58091F3986"
      valueUuid: "string"
    disabled: true
    failureReason:
      reason: "VARIABLE_THAT_COULD_NOT_BE_ISOLATED_MOCKED"
      source: "creator.append(\\\"cloudPlatform\\\", this.cloudPlatform);"
      lineNumber: 95
      details: "A variable could not be isolated/mocked when calling a method - Variable\
        \ name: creator - Method: append"
    disabledStatusUpdatedBy: "SYSTEM"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataActivationContext"
        parameters:
        - name: "cloudPlatform"
          value:
            sapientType: "ENUM"
            content: !<regular>
              value: "NONE"
            valueType: "org.springframework.boot.cloud.CloudPlatform"
            uuid: "cloudPlatform"
        - name: "profiles"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.config.Profiles"
            uuid: "profiles"
      valueType: "org.springframework.boot.context.config.ConfigDataActivationContext"
      uuid: "target"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.core.style.ToStringCreator"
        parameters:
        - name: "obj"
          value:
            sapientType: "THIS"
            valueType: "org.springframework.boot.context.config.ConfigDataActivationContext"
            uuid: "targetClassObject"
            fixed: true
      valueType: "org.springframework.core.style.ToStringCreator"
      uuid: "toStringCreator"
      fixed: true
    - sapientType: "OBJECT"
      content: !<method_return_from_value>
        target: "org.springframework.core.style.ToStringCreator"
        localVariableValue:
          sapientType: "OBJECT"
          content: !<new>
            target: "org.springframework.core.style.ToStringCreator"
            parameters:
            - name: "obj"
              value:
                sapientType: "THIS"
                valueType: "org.springframework.boot.context.config.ConfigDataActivationContext"
                uuid: "targetClassObject"
                fixed: true
          valueType: "org.springframework.core.style.ToStringCreator"
          uuid: "toStringCreator"
          fixed: true
        methodParameters:
        - name: "fieldName"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "cloudPlatform"
            valueType: "java.lang.String"
            uuid: "uniqueUuid2"
            fixed: true
        - name: "value"
          value:
            sapientType: "ENUM"
            content: !<regular>
              value: "NONE"
            valueType: "org.springframework.boot.cloud.CloudPlatform"
            uuid: "cloudPlatform"
        methodName: "append"
      valueType: "org.springframework.core.style.ToStringCreator"
      uuid: "toStringCreator2"
    - sapientType: "BASIC"
      content: !<regular>
        value: "cloudPlatform"
      valueType: "java.lang.String"
      uuid: "uniqueUuid1"
      fixed: true
    - sapientType: "ENUM"
      content: !<regular>
        value: "NONE"
      valueType: "org.springframework.boot.cloud.CloudPlatform"
      uuid: "cloudPlatform"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.core.style.ToStringCreator"
        parameters:
        - name: "obj"
          value:
            sapientType: "THIS"
            valueType: "org.springframework.boot.context.config.ConfigDataActivationContext"
            uuid: "targetClassObject"
            fixed: true
      valueType: "org.springframework.core.style.ToStringCreator"
      uuid: "toStringCreator"
      fixed: true
    - sapientType: "OBJECT"
      content: !<method_return_from_value>
        target: "org.springframework.core.style.ToStringCreator"
        localVariableValue:
          sapientType: "OBJECT"
          content: !<new>
            target: "org.springframework.core.style.ToStringCreator"
            parameters:
            - name: "obj"
              value:
                sapientType: "THIS"
                valueType: "org.springframework.boot.context.config.ConfigDataActivationContext"
                uuid: "targetClassObject"
                fixed: true
          valueType: "org.springframework.core.style.ToStringCreator"
          uuid: "toStringCreator"
          fixed: true
        methodParameters:
        - name: "fieldName"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "profiles"
            valueType: "java.lang.String"
            uuid: "uniqueUuid4"
            fixed: true
        - name: "value"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.config.Profiles"
            uuid: "profiles"
        methodName: "append"
      valueType: "org.springframework.core.style.ToStringCreator"
      uuid: "toStringCreator3"
    - sapientType: "BASIC"
      content: !<regular>
        value: "profiles"
      valueType: "java.lang.String"
      uuid: "uniqueUuid3"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.Profiles"
      uuid: "profiles"
    - sapientType: "BASIC"
      content: !<regular>
        value: "result1"
      valueType: "java.lang.String"
      uuid: "string"
