---
modelFingerprint: "A9CBC68E7A77BA21E37255FF50CAC2FE"
methods:
- method:
    name: "getPropertySources"
    signature: "getPropertySources() : java.util.List<org.springframework.core.env.PropertySource<?>>"
    sourceCodeSignature: "List<PropertySource<?>> getPropertySources()"
    instructionFingerprint: "7CB24862E95CA88AA30FB1F986F2609C"
  paths:
  - pathId: "path1"
    testPathName: "getPropertySourcesTest"
    constructorSignature: "<init>(java.util.Collection<? extends org.springframework.core.env.PropertySource<?>>,org.springframework.boot.context.config.ConfigData$PropertySourceOptions)\
      \ : void"
    modelFingerprint: "4C5267494456E5B5886DA2BB444D1CE7"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "d1ed9975-a055-3ae2-ae07-91a9afad825b"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "getOptions"
    signature: "getOptions(org.springframework.core.env.PropertySource<?>) : org.springframework.boot.context.config.ConfigData$Options"
    sourceCodeSignature: "Options getOptions(PropertySource<?> propertySource)"
    instructionFingerprint: "FD730EB043BCA01AE25478FF9E0E5AB2"
  paths:
  - pathId: "path1"
    testPathName: "getOptionsWhenOptionsIsNotNull"
    constructorSignature: "<init>(java.util.Collection<? extends org.springframework.core.env.PropertySource<?>>,org.springframework.boot.context.config.ConfigData$PropertySourceOptions)\
      \ : void"
    modelFingerprint: "73EF5E209974981335B48C36B5297105"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4713ECB6C023C56E82E4E8CACE456D95"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "propertySource"
      modelFingerprint: "1507B1A06C175A4ED7FF5042921FAA7D"
      index: 2
      valueUuid: "getOptions_propertySource1"
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "FE55F40C19F6BD2B54D817D88E2F4225"
      index: 3
      valueUuid: "uuid6"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_collection1"
        - name: "message"
          valueUuid: "uuid5"
        signature: "notNull(Collection,String): void"
        returnValueUuid: "<init>_void3"
        access: 9
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "5C5EEDBE65D4ED46FB79FE67686FA1CB"
      index: 4
      valueUuid: "uuid8"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_configData.PropertySourceOptions2"
        - name: "message"
          valueUuid: "uuid7"
        signature: "notNull(ConfigData$PropertySourceOptions,String): void"
        returnValueUuid: "<init>_void4"
        access: 9
    - type: "FIELD"
      name: "propertySourceOptions"
      modelFingerprint: "86DEA6D25B9F5729C6FF163FE7A35222"
      index: 5
      valueUuid: "<init>_configData.PropertySourceOptions2"
      methodExercised:
        target: "this.propertySourceOptions"
        name: "get"
        parameters:
        - name: "propertySource"
          valueUuid: "getOptions_propertySource1"
        signature: "get(PropertySource): ConfigData$Options"
        returnValueUuid: "getOptions_configData.Options1"
        access: 1025
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D729A98C0FCA5691EE895C7CAB977F3C"
      index: 6
      valueUuid: "getOptions_configData.Options1"
    uuid: "35c45523-e5c7-34f7-8d6d-4e96598349f7"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "UNKNOWN_REASON"
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigData"
        parameters:
        - name: "propertySources"
          value:
            sapientType: "COLLECTION"
            content: !<collection>
              parameters: []
              values: []
            valueType: "java.util.Collection"
            genericValueType: "? extends org.springframework.core.env.PropertySource<?>"
            uuid: "<init>_collection1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "propertySourceOptions"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.config.ConfigData$PropertySourceOptions"
            uuid: "<init>_configData.PropertySourceOptions2"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.config.ConfigData"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.PropertySource"
      genericValueType: "?"
      uuid: "getOptions_propertySource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid6"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void3"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.Collection"
      genericValueType: "? extends org.springframework.core.env.PropertySource<?>"
      uuid: "<init>_collection1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "PropertySources must not be null"
      valueType: "java.lang.String"
      uuid: "uuid5"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid8"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void4"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigData$PropertySourceOptions"
      uuid: "<init>_configData.PropertySourceOptions2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "PropertySourceOptions must not be null"
      valueType: "java.lang.String"
      uuid: "uuid7"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigData$PropertySourceOptions"
      uuid: "<init>_configData.PropertySourceOptions2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigData$Options"
      uuid: "getOptions_configData.Options1"
      fixed: false
      equalsMethodPresent: true
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.PropertySource"
      genericValueType: "?"
      uuid: "getOptions_propertySource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigData$Options"
      uuid: "getOptions_configData.Options1"
      fixed: false
      equalsMethodPresent: true
      explicitCastNeeded: false
  - pathId: "path2"
    testPathName: "getOptionsWhenOptionsIsNull"
    constructorSignature: "<init>(java.util.Collection<? extends org.springframework.core.env.PropertySource<?>>,org.springframework.boot.context.config.ConfigData$PropertySourceOptions)\
      \ : void"
    modelFingerprint: "72408234804943AB8ED3347D4053CFCF"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4713ECB6C023C56E82E4E8CACE456D95"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "propertySource"
      modelFingerprint: "1507B1A06C175A4ED7FF5042921FAA7D"
      index: 2
      valueUuid: "getOptions_propertySource1"
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "FE55F40C19F6BD2B54D817D88E2F4225"
      index: 3
      valueUuid: "uuid10"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_collection1"
        - name: "message"
          valueUuid: "uuid9"
        signature: "notNull(Collection,String): void"
        returnValueUuid: "<init>_void3"
        access: 9
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "5C5EEDBE65D4ED46FB79FE67686FA1CB"
      index: 4
      valueUuid: "uuid12"
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          valueUuid: "<init>_configData.PropertySourceOptions2"
        - name: "message"
          valueUuid: "uuid11"
        signature: "notNull(ConfigData$PropertySourceOptions,String): void"
        returnValueUuid: "<init>_void4"
        access: 9
    - type: "FIELD"
      name: "propertySourceOptions"
      modelFingerprint: "B50BCC40B641E5F27EBF51336D60ADD2"
      index: 5
      valueUuid: "<init>_configData.PropertySourceOptions2"
      methodExercised:
        target: "this.propertySourceOptions"
        name: "get"
        parameters:
        - name: "propertySource"
          valueUuid: "getOptions_propertySource1"
        signature: "get(PropertySource): ConfigData$Options"
        returnValueUuid: "getOptions_configData.Options1"
        access: 1025
    - type: "RESULT"
      name: "result"
      modelFingerprint: "8562AB18C970D1FF90E0A0DA5096D017"
      index: 6
      valueUuid: "getOptions_configData.Options2"
    uuid: "50b37f37-bd4b-33ea-95ca-e144f7ee5a35"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigData"
        parameters:
        - name: "propertySources"
          value:
            sapientType: "COLLECTION"
            content: !<collection>
              parameters: []
              values: []
            valueType: "java.util.Collection"
            genericValueType: "? extends org.springframework.core.env.PropertySource<?>"
            uuid: "<init>_collection1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "propertySourceOptions"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.config.ConfigData$PropertySourceOptions"
            uuid: "<init>_configData.PropertySourceOptions2"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.config.ConfigData"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.PropertySource"
      genericValueType: "?"
      uuid: "getOptions_propertySource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid10"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void3"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.Collection"
      genericValueType: "? extends org.springframework.core.env.PropertySource<?>"
      uuid: "<init>_collection1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "PropertySources must not be null"
      valueType: "java.lang.String"
      uuid: "uuid9"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.util.Assert"
      uuid: "uuid12"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "<init>_void4"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigData$PropertySourceOptions"
      uuid: "<init>_configData.PropertySourceOptions2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "PropertySourceOptions must not be null"
      valueType: "java.lang.String"
      uuid: "uuid11"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigData$PropertySourceOptions"
      uuid: "<init>_configData.PropertySourceOptions2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "NULL"
      valueType: "org.springframework.boot.context.config.ConfigData$Options"
      uuid: "getOptions_configData.Options1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.core.env.PropertySource"
      genericValueType: "?"
      uuid: "getOptions_propertySource1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<static_field_return>
        target: "org.springframework.boot.context.config.ConfigData$Options"
        fieldName: "NONE"
      valueType: "org.springframework.boot.context.config.ConfigData$Options"
      uuid: "getOptions_configData.Options2"
      fixed: false
      equalsMethodPresent: true
      explicitCastNeeded: false
