---
modelFingerprint: "B167083AC7091A9193C0B3FD3D9ED020"
methods:
- method:
    name: "registerHints"
    signature: "registerHints(org.springframework.aot.hint.RuntimeHints,java.lang.ClassLoader)\
      \ : void"
    sourceCodeSignature: "void registerHints(RuntimeHints hints, ClassLoader classLoader)"
    instructionFingerprint: "E220058433C211F375CBA5AF7F701D97"
  paths:
  - pathId: "path1"
    testPathName: "registerHintsTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "66C346DEFB51BC314E9AEF7FAAF66D59"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      valueUuid: "target"
    - type: "INPUT"
      name: "hints"
      modelFingerprint: "7FF56B1861637B3DDB635C56C3562869"
      index: 2
      valueUuid: "registerHints_runtimeHints1"
    - type: "INPUT"
      name: "classLoader"
      modelFingerprint: "EE299BDC26205B7BAC15A9BAB1622CBF"
      index: 3
      valueUuid: "registerHints_classLoader1"
    - type: "STATIC"
      name: "BindableRuntimeHintsRegistrar"
      modelFingerprint: "7A3EA5DAF2FF52A2B57A91C963CB88E0"
      index: 4
      valueUuid: "uuid1"
      methodExercised:
        target: "org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar"
        name: "forTypes"
        parameters:
        - name: "types"
          valueUuid: "registerHints_class[]1"
        signature: "forTypes(Class[]): BindableRuntimeHintsRegistrar"
        returnValueUuid: "registerHints_bindableRuntimeHintsRegistrar1"
        access: 137
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "8E3074620232B54C8290E154B791C9F3"
      index: 5
      valueUuid: "registerHints_bindableRuntimeHintsRegistrar1"
      methodExercised:
        target: "org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar"
        name: "registerHints"
        parameters:
        - name: "hints"
          valueUuid: "registerHints_runtimeHints1"
        signature: "registerHints(RuntimeHints): void"
        returnValueUuid: "registerHints_void1"
        access: 1
    - type: "LOCAL_VARIABLE"
      name: "hints"
      modelFingerprint: "AB7FE28238F4E840CA7ADB36324CDC13"
      index: 6
      valueUuid: "registerHints_runtimeHints1"
      methodExercised:
        target: "hints"
        name: "reflection"
        parameters: []
        signature: "reflection(): ReflectionHints"
        returnValueUuid: "registerHints_reflectionHints1"
        access: 1
    - type: "STATIC"
      name: "ReflectionUtils"
      modelFingerprint: "54E44EBF731B4A46BE79413FFAAE6348"
      index: 7
      valueUuid: "uuid4"
      methodExercised:
        target: "org.springframework.util.ReflectionUtils"
        name: "findMethod"
        parameters:
        - name: "clazz"
          valueUuid: "uuid2"
        - name: "name"
          valueUuid: "uuid3"
        - name: "paramTypes"
          valueUuid: "registerHints_class[]2"
        signature: "findMethod(Class,String,Class[]): Method"
        returnValueUuid: "registerHints_method1"
        access: 137
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "9A9D7935123B5DD29D2F99894AC58EC7"
      index: 8
      valueUuid: "registerHints_reflectionHints1"
      methodExercised:
        target: "org.springframework.aot.hint.ReflectionHints"
        name: "registerMethod"
        parameters:
        - name: "method"
          valueUuid: "registerHints_method1"
        - name: "mode"
          valueUuid: "Enum-org.springframework.aot.hint.ExecutableMode-INVOKE"
        signature: "registerMethod(Method,ExecutableMode): ReflectionHints"
        returnValueUuid: "registerHints_reflectionHints2"
        access: 1
    - type: "RESULT"
      name: "result"
      modelFingerprint: "68041019986276EDF5D420282D883A57"
      index: 9
      valueUuid: "uuid5"
    uuid: "b1fc7be3-9a56-3b28-acf9-0d8d8fa91d7d"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataPropertiesRuntimeHints"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
      valueType: "org.springframework.boot.context.config.ConfigDataPropertiesRuntimeHints"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.RuntimeHints"
      uuid: "registerHints_runtimeHints1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.lang.ClassLoader"
        method: "getPlatformClassLoader"
        methodParameters: []
      valueType: "java.lang.ClassLoader"
      uuid: "registerHints_classLoader1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar"
      uuid: "uuid1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar"
      uuid: "registerHints_bindableRuntimeHintsRegistrar1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "ARRAY"
      content: !<array>
        values:
          0:
            sapientType: "CLASS"
            content: !<regular>
              value: "org.springframework.boot.context.config.ConfigDataProperties"
            valueType: "java.lang.Class"
            genericValueType: "org.springframework.boot.context.config.ConfigDataProperties"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
      valueType: "java.lang.Class[]"
      genericValueType: "org.springframework.boot.context.config.ConfigDataProperties"
      uuid: "registerHints_class[]1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar"
      uuid: "registerHints_bindableRuntimeHintsRegistrar1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      valueType: "void"
      uuid: "registerHints_void1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.RuntimeHints"
      uuid: "registerHints_runtimeHints1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.RuntimeHints"
      uuid: "registerHints_runtimeHints1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.ReflectionHints"
      uuid: "registerHints_reflectionHints1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "REAL"
      valueType: "org.springframework.util.ReflectionUtils"
      uuid: "uuid4"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "org.springframework.util.ReflectionUtils"
        method: "findMethod"
        methodParameters:
        - value:
            sapientType: "CLASS"
            content: !<regular>
              value: "org.springframework.boot.context.config.ConfigDataLocation"
            valueType: "java.lang.Class"
            genericValueType: "org.springframework.boot.context.config.ConfigDataLocation"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - value:
            sapientType: "BASIC"
            content: !<regular>
              value: "of"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - value:
            sapientType: "ARRAY"
            content: !<array>
              values:
                0:
                  sapientType: "CLASS"
                  content: !<regular>
                    value: "java.lang.String"
                  valueType: "java.lang.Class"
                  genericValueType: "java.lang.String"
                  fixed: true
                  equalsMethodPresent: false
                  explicitCastNeeded: false
            valueType: "java.lang.Class[]"
            genericValueType: "java.lang.String"
            uuid: "registerHints_class[]2"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
      valueType: "java.lang.reflect.Method"
      uuid: "registerHints_method1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.context.config.ConfigDataLocation"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.context.config.ConfigDataLocation"
      uuid: "uuid2"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "BASIC"
      content: !<regular>
        value: "of"
      valueType: "java.lang.String"
      uuid: "uuid3"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "ARRAY"
      content: !<array>
        values:
          0:
            sapientType: "CLASS"
            content: !<regular>
              value: "java.lang.String"
            valueType: "java.lang.Class"
            genericValueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
      valueType: "java.lang.Class[]"
      genericValueType: "java.lang.String"
      uuid: "registerHints_class[]2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.ReflectionHints"
      uuid: "registerHints_reflectionHints1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.ReflectionHints"
      uuid: "registerHints_reflectionHints2"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "org.springframework.util.ReflectionUtils"
        method: "findMethod"
        methodParameters:
        - value:
            sapientType: "CLASS"
            content: !<regular>
              value: "org.springframework.boot.context.config.ConfigDataLocation"
            valueType: "java.lang.Class"
            genericValueType: "org.springframework.boot.context.config.ConfigDataLocation"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - value:
            sapientType: "BASIC"
            content: !<regular>
              value: "of"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - value:
            sapientType: "ARRAY"
            content: !<array>
              values:
                0:
                  sapientType: "CLASS"
                  content: !<regular>
                    value: "java.lang.String"
                  valueType: "java.lang.Class"
                  genericValueType: "java.lang.String"
                  fixed: true
                  equalsMethodPresent: false
                  explicitCastNeeded: false
            valueType: "java.lang.Class[]"
            genericValueType: "java.lang.String"
            uuid: "registerHints_class[]2"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
      valueType: "java.lang.reflect.Method"
      uuid: "registerHints_method1"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "ENUM"
      content: !<regular>
        value: "INVOKE"
      valueType: "org.springframework.aot.hint.ExecutableMode"
      uuid: "Enum-org.springframework.aot.hint.ExecutableMode-INVOKE"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "VOID"
      uuid: "uuid5"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
