---
modelFingerprint: "83A082F927614F17ECF7D667B476F372"
targetClass:
  fullClassName: "org.springframework.boot.context.config.ConfigDataNotFoundFailureAnalyzer"
methods:
- method:
    name: "analyze"
    sourceCodeSignature: "FailureAnalysis analyze(Throwable rootFailure, ConfigDataNotFoundException\
      \ cause)"
    returnType: "org.springframework.boot.diagnostics.FailureAnalysis"
    parameters:
    - name: "rootFailure"
      type: "java.lang.Throwable"
    - name: "cause"
      type: "org.springframework.boot.context.config.ConfigDataNotFoundException"
    instructionFingerprint: "29325B1C2ABBCF123CFEAAA6256B257B"
  paths:
  - pathId: "path1"
    testPathName: "analyze2WhenLocationNotIsOptional"
    constructorSignature: "<init>() : void"
    modelFingerprint: "0AB8DFF5AACB5AC434E304B7D6AB9D3D"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "rootFailure"
      modelFingerprint: "342BEFE484C53ADA99B8405F2B8802F3"
      valueUuid: "rootFailure"
    - type: "INPUT"
      name: "cause"
      modelFingerprint: "EEF498BE30466A719ADD16B5678A3CE1"
      valueUuid: "cause"
    - type: "LOCAL_VARIABLE"
      name: "locationNotFoundException"
      modelFingerprint: "0714AE792962B78AD33FE1F9C3F6AC99"
      valueUuid: "cause"
      methodExercised:
        expression: "getLocation():location"
    - type: "STATIC"
      name: "Origin.class"
      modelFingerprint: "37A7E568A7A9FEF7B30F46B62306B84C"
      valueUuid: "Origin.class"
      methodExercised:
        expression: "from(source:location):origin"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      name: "cause"
      modelFingerprint: "9D35B226F1A1BE0FD6AB12494C42390C"
      valueUuid: "cause"
      methodExercised:
        expression: "getReferenceDescription():string"
    - type: "LOCAL_VARIABLE"
      name: "location"
      modelFingerprint: "CF8FD1065B97926517C295038E555085"
      valueUuid: "location"
      methodExercised:
        expression: "isOptional():optional"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "E7B73ACB951CC264094CB84FC6A29949"
      valueUuid: "failureAnalysis"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataNotFoundFailureAnalyzer"
        parameters: []
      valueType: "org.springframework.boot.context.config.ConfigDataNotFoundFailureAnalyzer"
      uuid: "target"
    - sapientType: "OBJECT"
      content: !<new>
        target: "java.lang.Throwable"
        parameters: []
      valueType: "java.lang.Throwable"
      uuid: "rootFailure"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigDataLocationNotFoundException"
      uuid: "cause"
      explicitCastForOverloadedMethods: "org.springframework.boot.context.config.ConfigDataNotFoundException"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigDataLocationNotFoundException"
      uuid: "cause"
      explicitCastForOverloadedMethods: "org.springframework.boot.context.config.ConfigDataNotFoundException"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigDataLocation"
      uuid: "location"
      nameForMock: "location"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.origin.Origin"
      uuid: "Origin.class"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.origin.Origin"
      uuid: "origin"
      nameForMock: "origin"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigDataLocation"
      uuid: "location"
      nameForMock: "location"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigDataLocationNotFoundException"
      uuid: "cause"
      explicitCastForOverloadedMethods: "org.springframework.boot.context.config.ConfigDataNotFoundException"
    - sapientType: "BASIC"
      content: !<regular>
        value: ""
      valueType: "java.lang.String"
      uuid: "string"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigDataLocation"
      uuid: "location"
      nameForMock: "location"
    - sapientType: "BASIC"
      content: !<regular>
        value: false
      valueType: "boolean"
      uuid: "optional"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.diagnostics.FailureAnalysis"
        parameters:
        - name: "description"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Config data  does not exist"
            valueType: "java.lang.String"
            uuid: "string2"
        - name: "action"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Check that the value 'null' at null is correct, or prefix it\
                \ with 'optional:'"
            valueType: "java.lang.String"
            uuid: "string6"
        - name: "cause"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.config.ConfigDataLocationNotFoundException"
            uuid: "cause"
      valueType: "org.springframework.boot.diagnostics.FailureAnalysis"
      uuid: "failureAnalysis"
      fixed: true
    branches:
    - lineNumber: 52
      expression: "cause instanceof ConfigDataLocationNotFoundException locationNotFoundException"
      range: "(52,7)-(52,84)"
      evaluatedAs: true
      internalMethodName: "getLocation"
    - lineNumber: 38
      expression: "location != null"
      range: "(38,7)-(38,22)"
      evaluatedAs: true
    - lineNumber: 41
      expression: "origin != null"
      range: "(41,7)-(41,20)"
      evaluatedAs: true
    - lineNumber: 45
      expression: "location != null"
      range: "(45,7)-(45,22)"
      evaluatedAs: true
    - lineNumber: 45
      expression: "!location.isOptional()"
      range: "(45,27)-(45,48)"
      evaluatedAs: true
  - pathId: "path7"
    testPathName: "analyze2WhenLocationIsNullAndOriginIsNullAndLocationIsNull"
    constructorSignature: "<init>() : void"
    modelFingerprint: "83019B46EB8EFEBECC348ED50E475A9A"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "rootFailure"
      modelFingerprint: "342BEFE484C53ADA99B8405F2B8802F3"
      valueUuid: "rootFailure"
    - type: "INPUT"
      name: "cause"
      modelFingerprint: "5F47AF69D0548C0C2130DD6F7C598872"
      valueUuid: "cause"
    - type: "LOCAL_VARIABLE"
      name: "resourceNotFoundException"
      modelFingerprint: "90E77EE2DE77EB429B214A8C316A3033"
      valueUuid: "cause"
      methodExercised:
        expression: "getLocation():location"
    - type: "STATIC"
      name: "Origin.class"
      modelFingerprint: "5EDCC795CCA6B44E1198AD91AFFC18B8"
      valueUuid: "Origin.class"
      methodExercised:
        expression: "from(source:location):origin"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      name: "cause"
      modelFingerprint: "EB2B19D92AFCB10EA5CB153FF1A6741B"
      valueUuid: "cause"
      methodExercised:
        expression: "getReferenceDescription():string"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "CB38D5233DB783E22051D23EBAA27E89"
      valueUuid: "failureAnalysis"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataNotFoundFailureAnalyzer"
        parameters: []
      valueType: "org.springframework.boot.context.config.ConfigDataNotFoundFailureAnalyzer"
      uuid: "target"
    - sapientType: "OBJECT"
      content: !<new>
        target: "java.lang.Throwable"
        parameters: []
      valueType: "java.lang.Throwable"
      uuid: "rootFailure"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigDataResourceNotFoundException"
      uuid: "cause"
      explicitCastForOverloadedMethods: "org.springframework.boot.context.config.ConfigDataNotFoundException"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigDataResourceNotFoundException"
      uuid: "cause"
      explicitCastForOverloadedMethods: "org.springframework.boot.context.config.ConfigDataNotFoundException"
    - sapientType: "NULL"
      valueType: "org.springframework.boot.context.config.ConfigDataLocation"
      uuid: "location"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.origin.Origin"
      uuid: "Origin.class"
    - sapientType: "NULL"
      valueType: "org.springframework.boot.origin.Origin"
      uuid: "origin"
      fixed: true
    - sapientType: "NULL"
      valueType: "org.springframework.boot.context.config.ConfigDataLocation"
      uuid: "location"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigDataResourceNotFoundException"
      uuid: "cause"
      explicitCastForOverloadedMethods: "org.springframework.boot.context.config.ConfigDataNotFoundException"
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "string"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.diagnostics.FailureAnalysis"
        parameters:
        - name: "description"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Config data A does not exist"
            valueType: "java.lang.String"
            uuid: "string2"
        - name: "action"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Check that the value is correct"
            valueType: "java.lang.String"
            uuid: "string3"
        - name: "cause"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.config.ConfigDataResourceNotFoundException"
            uuid: "cause"
      valueType: "org.springframework.boot.diagnostics.FailureAnalysis"
      uuid: "failureAnalysis"
      fixed: true
    branches:
    - lineNumber: 52
      expression: "cause instanceof ConfigDataLocationNotFoundException locationNotFoundException"
      range: "(52,7)-(52,84)"
      evaluatedAs: false
      internalMethodName: "getLocation"
    - lineNumber: 55
      expression: "cause instanceof ConfigDataResourceNotFoundException resourceNotFoundException"
      range: "(55,7)-(55,84)"
      evaluatedAs: true
      internalMethodName: "getLocation"
    - lineNumber: 38
      expression: "location != null"
      range: "(38,7)-(38,22)"
      evaluatedAs: false
    - lineNumber: 41
      expression: "origin != null"
      range: "(41,7)-(41,20)"
      evaluatedAs: false
    - lineNumber: 45
      expression: "location != null"
      range: "(45,7)-(45,22)"
      evaluatedAs: false
  - pathId: "path8"
    testPathName: "analyze2WhenCauseNotInstanceOfConfigDataResourceNotFoundExceptionAndLocationIsNullAndOriginIsNullAndLocationIsNull"
    constructorSignature: "<init>() : void"
    modelFingerprint: "1C98E7C2E63C5219BD50708804351101"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "rootFailure"
      modelFingerprint: "342BEFE484C53ADA99B8405F2B8802F3"
      valueUuid: "rootFailure"
    - type: "INPUT"
      name: "cause"
      modelFingerprint: "61F88DDD27E05A5F5B5C9EA98145FAF2"
      valueUuid: "cause"
    - type: "STATIC"
      name: "Origin.class"
      modelFingerprint: "280738D4626EA98F6F526C593CA42CAD"
      valueUuid: "Origin.class"
      methodExercised:
        expression: "from(source:configDataLocation):origin"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      name: "cause"
      modelFingerprint: "3B64D366E94876AC472AE03DE0C0E7F1"
      valueUuid: "cause"
      methodExercised:
        expression: "getReferenceDescription():string"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "3252FE8C4BBDDE5D5AECD315AEC91E95"
      valueUuid: "failureAnalysis"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataNotFoundFailureAnalyzer"
        parameters: []
      valueType: "org.springframework.boot.context.config.ConfigDataNotFoundFailureAnalyzer"
      uuid: "target"
    - sapientType: "OBJECT"
      content: !<new>
        target: "java.lang.Throwable"
        parameters: []
      valueType: "java.lang.Throwable"
      uuid: "rootFailure"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigDataNotFoundException"
      uuid: "cause"
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.origin.Origin"
      uuid: "Origin.class"
    - sapientType: "NULL"
      valueType: "org.springframework.boot.origin.Origin"
      uuid: "origin"
      fixed: true
    - sapientType: "NULL"
      valueType: "org.springframework.boot.context.config.ConfigDataLocation"
      uuid: "configDataLocation"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.context.config.ConfigDataNotFoundException"
      uuid: "cause"
    - sapientType: "BASIC"
      content: !<regular>
        value: "A"
      valueType: "java.lang.String"
      uuid: "string"
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.diagnostics.FailureAnalysis"
        parameters:
        - name: "description"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Config data A does not exist"
            valueType: "java.lang.String"
            uuid: "string2"
        - name: "action"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Check that the value is correct"
            valueType: "java.lang.String"
            uuid: "string3"
        - name: "cause"
          value:
            sapientType: "MOCK"
            valueType: "org.springframework.boot.context.config.ConfigDataNotFoundException"
            uuid: "cause"
      valueType: "org.springframework.boot.diagnostics.FailureAnalysis"
      uuid: "failureAnalysis"
      fixed: true
    branches:
    - lineNumber: 52
      expression: "cause instanceof ConfigDataLocationNotFoundException locationNotFoundException"
      range: "(52,7)-(52,84)"
      evaluatedAs: false
      internalMethodName: "getLocation"
    - lineNumber: 55
      expression: "cause instanceof ConfigDataResourceNotFoundException resourceNotFoundException"
      range: "(55,7)-(55,84)"
      evaluatedAs: false
      internalMethodName: "getLocation"
    - lineNumber: 38
      expression: "location != null"
      range: "(38,7)-(38,22)"
      evaluatedAs: false
    - lineNumber: 41
      expression: "origin != null"
      range: "(41,7)-(41,20)"
      evaluatedAs: false
    - lineNumber: 45
      expression: "location != null"
      range: "(45,7)-(45,22)"
      evaluatedAs: false
