---
modelFingerprint: "D21D5A3883632D4ABEB06B55CE5C2511"
targetClass:
  fullClassName: "org.springframework.boot.context.config.ConfigDataLocationRuntimeHints"
methods:
- method:
    name: "registerHints"
    sourceCodeSignature: "void registerHints(RuntimeHints hints, ClassLoader classLoader)"
    returnType: "void"
    parameters:
    - name: "hints"
      type: "org.springframework.aot.hint.RuntimeHints"
    - name: "classLoader"
      type: "java.lang.ClassLoader"
    instructionFingerprint: "346774AFF20ACA0E27E3C7E8FC62CDB8"
  paths:
  - pathId: "path1"
    testPathName: "registerHintsWhenLoggerIsDebugEnabled"
    constructorSignature: "<init>() : void"
    modelFingerprint: "25742AE9F5D2F6A9252DE261E9255E04"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "hints"
      modelFingerprint: "4ED55336421B23543566FDFA4FA3D8EE"
      valueUuid: "hints"
    - type: "INPUT"
      name: "classLoader"
      modelFingerprint: "C286DE215DE7563ED1CD0033A63BD833"
      valueUuid: "classLoader"
    - type: "INTERNAL"
      name: "internalMethod"
      modelFingerprint: "17521A2A53588220852982BFAE1FF37F"
      methodExercised:
        expression: "getLocations(classLoader:classLoader):list2"
    - type: "INTERNAL"
      name: "internalMethod"
      modelFingerprint: "961F762DA9D43EF1553DB01CF681EB0B"
      methodExercised:
        expression: "getExtensions(classLoader:classLoader):list3"
    - type: "STATIC"
      name: "FilePatternResourceHintsRegistrar.class"
      modelFingerprint: "AB6B4E41A8F594AAF84A6622DEE97BA4"
      valueUuid: "FilePatternResourceHintsRegistrar.class"
      methodExercised:
        expression: "forClassPathLocations(classpathLocations:list2):filePatternResourceHintsRegistrar.Builder"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "6BBF12F8A9E11CB5EF08280A398CCAE5"
      valueUuid: "filePatternResourceHintsRegistrar.Builder"
      methodExercised:
        expression: "withFilePrefixes(filePrefixes:list):filePatternResourceHintsRegistrar.Builder2"
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "10F2D0B22657EA19B81EDFBF4919977F"
      valueUuid: "filePatternResourceHintsRegistrar.Builder2"
      methodExercised:
        expression: "withFileExtensions(fileExtensions:list3):filePatternResourceHintsRegistrar.Builder3"
    - type: "LOCAL_VARIABLE"
      name: "hints"
      modelFingerprint: "F20B333C682E361E8CAF6F8D23EADC4B"
      valueUuid: "hints"
      methodExercised:
        expression: "resources():resourceHints"
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "2BAE550A5CCC70C33EDE07EBDA52A5D3"
      valueUuid: "filePatternResourceHintsRegistrar.Builder3"
      methodExercised:
        expression: "registerHints(hints:resourceHints,classLoader:classLoader):void2"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "D3C52B3FA506EC339365BC9568CBF6B9"
      valueUuid: "expectedResult"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataLocationRuntimeHints"
        parameters: []
      valueType: "org.springframework.boot.context.config.ConfigDataLocationRuntimeHints"
      uuid: "target"
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.RuntimeHints"
      uuid: "hints"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.lang.ClassLoader"
        method: "getPlatformClassLoader"
        methodParameters: []
      valueType: "java.lang.ClassLoader"
      uuid: "classLoader"
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.List"
      genericValueType: "java.lang.String"
      uuid: "list2"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.lang.ClassLoader"
        method: "getPlatformClassLoader"
        methodParameters: []
      valueType: "java.lang.ClassLoader"
      uuid: "classLoader"
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.List"
      genericValueType: "java.lang.String"
      uuid: "list3"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.lang.ClassLoader"
        method: "getPlatformClassLoader"
        methodParameters: []
      valueType: "java.lang.ClassLoader"
      uuid: "classLoader"
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.support.FilePatternResourceHintsRegistrar"
      uuid: "FilePatternResourceHintsRegistrar.class"
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.support.FilePatternResourceHintsRegistrar$Builder"
      uuid: "filePatternResourceHintsRegistrar.Builder"
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.List"
      genericValueType: "java.lang.String"
      uuid: "list2"
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.support.FilePatternResourceHintsRegistrar$Builder"
      uuid: "filePatternResourceHintsRegistrar.Builder"
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.support.FilePatternResourceHintsRegistrar$Builder"
      uuid: "filePatternResourceHintsRegistrar.Builder2"
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values:
        - sapientType: "BASIC"
          content: !<regular>
            value: "application"
          valueType: "java.lang.String"
          uuid: "uniqueUuid1"
          fixed: true
      valueType: "java.util.List"
      genericValueType: "java.lang.String"
      uuid: "list"
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.support.FilePatternResourceHintsRegistrar$Builder"
      uuid: "filePatternResourceHintsRegistrar.Builder2"
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.support.FilePatternResourceHintsRegistrar$Builder"
      uuid: "filePatternResourceHintsRegistrar.Builder3"
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values: []
      valueType: "java.util.List"
      genericValueType: "java.lang.String"
      uuid: "list3"
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.RuntimeHints"
      uuid: "hints"
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.ResourceHints"
      uuid: "resourceHints"
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.support.FilePatternResourceHintsRegistrar$Builder"
      uuid: "filePatternResourceHintsRegistrar.Builder3"
    - sapientType: "VOID"
      valueType: "void"
      uuid: "void2"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.aot.hint.ResourceHints"
      uuid: "resourceHints"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.lang.ClassLoader"
        method: "getPlatformClassLoader"
        methodParameters: []
      valueType: "java.lang.ClassLoader"
      uuid: "classLoader"
    - sapientType: "VOID"
      uuid: "expectedResult"
      fixed: true
    branches:
    - lineNumber: 48
      expression: "logger.isDebugEnabled()"
      range: "(48,7)-(48,29)"
      evaluatedAs: true
- method:
    name: "getFileNames"
    sourceCodeSignature: "List<String> getFileNames(ClassLoader classLoader)"
    returnType: "java.util.List"
    genericReturnType: "java.lang.String"
    parameters:
    - name: "classLoader"
      type: "java.lang.ClassLoader"
    instructionFingerprint: "231948FF62FEAC3BCDE52D9BC62638D9"
  paths:
  - pathId: "path1"
    testPathName: "getFileNamesTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "7ABBCE26377E4E17A40A05615BF5E580"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "classLoader"
      modelFingerprint: "C286DE215DE7563ED1CD0033A63BD833"
      valueUuid: "classLoader"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "1E32AFC4EFDFDDC33825AAF07149BAB3"
      valueUuid: "list"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataLocationRuntimeHints"
        parameters: []
      valueType: "org.springframework.boot.context.config.ConfigDataLocationRuntimeHints"
      uuid: "target"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.lang.ClassLoader"
        method: "getPlatformClassLoader"
        methodParameters: []
      valueType: "java.lang.ClassLoader"
      uuid: "classLoader"
    - sapientType: "COLLECTION"
      content: !<collection>
        parameters: []
        values:
        - sapientType: "BASIC"
          content: !<regular>
            value: "application"
          valueType: "java.lang.String"
          uuid: "uniqueUuid2"
          fixed: true
      valueType: "java.util.List"
      genericValueType: "java.lang.String"
      uuid: "list"
- method:
    name: "getLocations"
    sourceCodeSignature: "List<String> getLocations(ClassLoader classLoader)"
    returnType: "java.util.List"
    genericReturnType: "java.lang.String"
    parameters:
    - name: "classLoader"
      type: "java.lang.ClassLoader"
    instructionFingerprint: "51846580C95AB05DD4246C0214DBE260"
  paths:
  - pathId: "path1"
    testPathName: "getLocationsWhenConfigDataEnvironmentDEFAULT_SEARCH_LOCATIONSIsEmpty"
    constructorSignature: "<init>() : void"
    modelFingerprint: "CDFDD278D5ED14487A12E6288966BD22"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "classLoader"
      modelFingerprint: "C286DE215DE7563ED1CD0033A63BD833"
      valueUuid: "classLoader"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "B989BDA75F5BDC9D2C041885867BFEF4"
      valueUuid: "arrayList"
    disabled: true
    failureReason:
      reason: "UNKNOWN_REASON"
    disabledStatusUpdatedBy: "SYSTEM"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataLocationRuntimeHints"
        parameters: []
      valueType: "org.springframework.boot.context.config.ConfigDataLocationRuntimeHints"
      uuid: "target"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.lang.ClassLoader"
        method: "getPlatformClassLoader"
        methodParameters: []
      valueType: "java.lang.ClassLoader"
      uuid: "classLoader"
    - sapientType: "COLLECTION"
      content: !<collection>
        collectionClass: "java.util.ArrayList"
        parameters: []
        values: []
      valueType: "java.util.List"
      genericValueType: "java.lang.String"
      uuid: "arrayList"
    branches:
    - lineNumber: 75
      expression: "for-each(ConfigDataEnvironment.DEFAULT_SEARCH_LOCATIONS)"
      range: "(75,39)-(75,84)"
      evaluatedAs: false
- method:
    name: "getExtensions"
    sourceCodeSignature: "List<String> getExtensions(ClassLoader classLoader)"
    returnType: "java.util.List"
    genericReturnType: "java.lang.String"
    parameters:
    - name: "classLoader"
      type: "java.lang.ClassLoader"
    instructionFingerprint: "D0446BEC4F3E8AE6A6228495706A8DE7"
  paths:
  - pathId: "path1"
    testPathName: "getExtensionsWhenExtensionsNotContainsCandidate"
    constructorSignature: "<init>() : void"
    modelFingerprint: "80060D28568DED5C543B00A441E759FE"
    problemWasSolvedByProver: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "classLoader"
      modelFingerprint: "C286DE215DE7563ED1CD0033A63BD833"
      valueUuid: "classLoader"
    - type: "STATIC"
      name: "SpringFactoriesLoader.class"
      modelFingerprint: "19A37BD44A53C26E3548241BC080A192"
      valueUuid: "SpringFactoriesLoader.class"
      methodExercised:
        expression: "forDefaultResourceLocation(classLoader:classLoader):springFactoriesLoader"
        staticAccess: true
    - type: "LOCAL_VARIABLE"
      modelFingerprint: "8D50141F6467AC1FD77EC865EFA6D90B"
      valueUuid: "springFactoriesLoader"
      methodExercised:
        expression: "load(factoryType:uniqueUuid3):list"
    - type: "LOCAL_VARIABLE"
      name: "propertySourceLoader"
      modelFingerprint: "6AEE05F271BC0E30E089E035D806D4BC"
      valueUuid: "object"
      methodExercised:
        expression: "getFileExtensions():stringArray"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "BE2D7264BC2BB4FA44CB8BDCA1C8ACB8"
      valueUuid: "arrayList"
    disabled: false
    failureReason:
      reason: "ERROR_RECALCULATING_SUGGESTED_VALUES"
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataLocationRuntimeHints"
        parameters: []
      valueType: "org.springframework.boot.context.config.ConfigDataLocationRuntimeHints"
      uuid: "target"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.lang.ClassLoader"
        method: "getPlatformClassLoader"
        methodParameters: []
      valueType: "java.lang.ClassLoader"
      uuid: "classLoader"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader"
      uuid: "SpringFactoriesLoader.class"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader"
      uuid: "springFactoriesLoader"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.lang.ClassLoader"
        method: "getPlatformClassLoader"
        methodParameters: []
      valueType: "java.lang.ClassLoader"
      uuid: "classLoader"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader"
      uuid: "springFactoriesLoader"
    - sapientType: "COLLECTION"
      content: !<collection>
        collectionClass: "java.util.ArrayList"
        parameters: []
        values:
        - sapientType: "MOCK"
          valueType: "org.springframework.boot.env.PropertySourceLoader"
          uuid: "object"
          collectionUuid: "list"
      valueType: "java.util.List"
      genericValueType: "org.springframework.boot.env.PropertySourceLoader"
      uuid: "list"
    - sapientType: "CLASS"
      content: !<regular>
        value: "org.springframework.boot.env.PropertySourceLoader"
      valueType: "java.lang.Class"
      genericValueType: "org.springframework.boot.env.PropertySourceLoader"
      uuid: "uniqueUuid3"
      fixed: true
    - sapientType: "MOCK"
      valueType: "org.springframework.boot.env.PropertySourceLoader"
      uuid: "object"
      collectionUuid: "list"
    - sapientType: "ARRAY"
      content: !<array>
        values:
          0:
            sapientType: "BASIC"
            content: !<regular>
              value: "A"
            valueType: "java.lang.String"
            uuid: "string"
      valueType: "java.lang.String[]"
      uuid: "stringArray"
    - sapientType: "COLLECTION"
      content: !<collection>
        collectionClass: "java.util.ArrayList"
        parameters: []
        values:
        - sapientType: "BASIC"
          content: !<regular>
            value: ".A"
          valueType: "java.lang.String"
          uuid: "string2"
      valueType: "java.util.List"
      genericValueType: "java.lang.String"
      uuid: "arrayList"
    branches:
    - lineNumber: 96
      expression: "for-each(propertySourceLoaders)"
      range: "(96,52)-(96,72)"
      evaluatedAs: true
    - lineNumber: 97
      expression: "for-each(propertySourceLoader.getFileExtensions())"
      range: "(97,32)-(97,71)"
      evaluatedAs: true
    - lineNumber: 99
      expression: "!extensions.contains(candidate)"
      range: "(99,9)-(99,39)"
      evaluatedAs: true
- method:
    name: "getSpringFactoriesLoader"
    sourceCodeSignature: "SpringFactoriesLoader getSpringFactoriesLoader(ClassLoader\
      \ classLoader)"
    returnType: "org.springframework.core.io.support.SpringFactoriesLoader"
    parameters:
    - name: "classLoader"
      type: "java.lang.ClassLoader"
    instructionFingerprint: "354396FFF575510B18F943E8B7D8F6A4"
  paths:
  - pathId: "path1"
    testPathName: "getSpringFactoriesLoaderTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "E1E15EBEC434270A17127E3E0E1F3FF0"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "INPUT"
      name: "classLoader"
      modelFingerprint: "C286DE215DE7563ED1CD0033A63BD833"
      valueUuid: "classLoader"
    - type: "STATIC"
      name: "SpringFactoriesLoader.class"
      modelFingerprint: "4BD8F0AAEA9434AA9CFA541178CE86A1"
      valueUuid: "SpringFactoriesLoader.class"
      methodExercised:
        expression: "forDefaultResourceLocation(classLoader:classLoader):springFactoriesLoader"
        staticAccess: true
    - type: "RESULT"
      name: "result"
      modelFingerprint: "3F71606328C76DAAD18D757CBA0112E8"
      valueUuid: "springFactoriesLoader"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.context.config.ConfigDataLocationRuntimeHints"
        parameters: []
      valueType: "org.springframework.boot.context.config.ConfigDataLocationRuntimeHints"
      uuid: "target"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.lang.ClassLoader"
        method: "getPlatformClassLoader"
        methodParameters: []
      valueType: "java.lang.ClassLoader"
      uuid: "classLoader"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader"
      uuid: "SpringFactoriesLoader.class"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader"
      uuid: "springFactoriesLoader"
    - sapientType: "OBJECT"
      content: !<static_method_return>
        target: "java.lang.ClassLoader"
        method: "getPlatformClassLoader"
        methodParameters: []
      valueType: "java.lang.ClassLoader"
      uuid: "classLoader"
    - sapientType: "MOCK"
      valueType: "org.springframework.core.io.support.SpringFactoriesLoader"
      uuid: "springFactoriesLoader"
