---
modelFingerprint: "5100AA7CEEFE90CAFFE6E368DBB218DA"
methods:
- method:
    name: "getPath"
    returnType: "java.nio.file.Path"
    signature: "getPath() : java.nio.file.Path"
    instructionFingerprint: "28B39D9A186260040038580F8A81C210"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "getPathTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.String) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "30A10A2007F6E07BB4BCA0518709B0C5"
    problemWasSolvedByProver: false
    truncated: true
    inputParameters: []
    uuid: "a8f6c4be-0895-3a4f-9a2a-c43eb253ed13"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.nio.file.Paths.get(java.lang.String,java.lang.String[])\
        \ : java.nio.file.Path"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "equals"
    returnType: "boolean"
    signature: "equals(java.lang.Object) : boolean"
    instructionFingerprint: "371E6F678CC03DC2B369E0BD3502C867"
    parametersTypes:
    - "java.lang.Object"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "equalsWhenThisEqualsObj"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.String) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "2A5C063EDE686C0D5F1132193D79D730"
    problemWasSolvedByProver: false
    truncated: true
    inputParameters: []
    uuid: "d0712d51-f0f8-381e-af89-bd29c8516608"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.nio.file.Paths.get(java.lang.String,java.lang.String[])\
        \ : java.nio.file.Path"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path5"
    pathIdForUser: "path2"
    testPathName: "equalsWhenObjIsNull"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.String) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "FB090FE4A7D2504FADEF740DCFF9DE56"
    problemWasSolvedByProver: false
    truncated: true
    inputParameters: []
    uuid: "42f03dea-2e61-3c4b-bbc0-1a97b94b4d90"
    deleted: true
    disabled: false
    ignoredBySystem: true
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.nio.file.Paths.get(java.lang.String,java.lang.String[])\
        \ : java.nio.file.Path"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path2"
    pathIdForUser: "path3"
    testPathName: "equalsWhenGetClassNotEqualsObjGetClass"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.String) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "70EC0B3D040BE108F8EC902755C0DEC2"
    problemWasSolvedByProver: false
    truncated: true
    inputParameters: []
    uuid: "26ff6ba6-6f29-3ff2-bca0-b8c532e7a53b"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.nio.file.Paths.get(java.lang.String,java.lang.String[])\
        \ : java.nio.file.Path"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path3"
    pathIdForUser: "path4"
    testPathName: "equalsWhenObjectsEqualsThisPathOtherPath"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.String) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "14CD26DB96596E16FF91633C9AE6D67D"
    problemWasSolvedByProver: false
    truncated: true
    inputParameters: []
    uuid: "99005416-0d04-3a2b-a722-ec83efe2e866"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.nio.file.Paths.get(java.lang.String,java.lang.String[])\
        \ : java.nio.file.Path"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
  - pathId: "path4"
    pathIdForUser: "path5"
    testPathName: "equalsWhenObjectsNotEqualsThisPathOtherPath"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.String) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "A2711081D83C9D98F5731CBE367ABF6B"
    problemWasSolvedByProver: false
    truncated: true
    inputParameters: []
    uuid: "ee0e48e4-37b5-3ea7-aa6e-3aa1b978d3b2"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.nio.file.Paths.get(java.lang.String,java.lang.String[])\
        \ : java.nio.file.Path"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "toString"
    returnType: "java.lang.String"
    signature: "toString() : java.lang.String"
    instructionFingerprint: "7511E8642DC32E52DA30EF94A2C6D752"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "toStringTest"
    nameDefinedByUser: false
    constructorSignature: "<init>(java.lang.String) : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "9B627B71BF613C947629B7C66D7BFFEF"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "A1E8BBA83228E6DBCC979685EFEC59C6"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.context.config.ConfigTreeConfigDataResource"
          parameters:
          - name: "path"
            value:
              sapientType: "BASIC"
              content: !<regular>
                value: "<value>"
              suggestedContent: !<regular>
                value: "<value>"
              valueType: "java.lang.String"
              uuid: "<init>_string1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        suggestedContent: !<new>
          target: "org.springframework.boot.context.config.ConfigTreeConfigDataResource"
          parameters:
          - name: "path"
            value:
              sapientType: "BASIC"
              content: !<regular>
                value: "<value>"
              suggestedContent: !<regular>
                value: "<value>"
              valueType: "java.lang.String"
              uuid: "<init>_string1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: false
        valueType: "org.springframework.boot.context.config.ConfigTreeConfigDataResource"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "STATIC"
      name: "Assert"
      modelFingerprint: "972E86AFD65F12EE7D4D745B4C4A24B5"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "MOCK"
        valueType: "org.springframework.util.Assert"
        uuid: "org.springframework.util.Assert"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      methodExercised:
        target: "org.springframework.util.Assert"
        name: "notNull"
        parameters:
        - name: "object"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "<value>"
            suggestedContent: !<regular>
              value: "<value>"
            valueType: "java.lang.String"
            uuid: "<init>_string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "message"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "Path must not be null"
            valueType: "java.lang.String"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        signature: "notNull(String,String): void"
        returnValue:
          sapientType: "VOID"
          valueType: "void"
          uuid: "<init>_void1"
          fixed: true
          equalsMethodPresent: false
          explicitCastNeeded: false
        access: 9
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "CAA6462F2E7A25EE9307F52270BCD612"
      index: 3
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "BASIC"
        content: !<regular>
          value: "config tree [<init>_path2]"
        suggestedContent: !<regular>
          value: "config tree [<init>_path2]"
        valueType: "java.lang.String"
        uuid: "toString_string1"
        fixed: false
        equalsMethodPresent: true
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "363d3698-f34c-39ad-914f-376a19498023"
    deleted: false
    disabled: false
    ignoredBySystem: false
    failureReason:
      reason: "METHOD_WITHOUT_EXPRESSION_SUPPORT"
      details: "Expression missing: java.nio.file.Paths.get(java.lang.String,java.lang.String[])\
        \ : java.nio.file.Path"
    prover: "LLM"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
