---
modelFingerprint: "13F9E7650E0B1E70FA714D9F6E9B2F0E"
methods:
- method:
    name: "setLocation"
    returnType: "void"
    signature: "setLocation(java.lang.String) : void"
    instructionFingerprint: "58D74E026D819E27A9780739FD19BD32"
    parametersTypes:
    - "java.lang.String"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "setLocationTest"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "9BAB731A43D9BA020CB7099281064314"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "10429219-944a-3b02-9737-f50a88747ae7"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "setMaxFileSize"
    returnType: "void"
    signature: "setMaxFileSize(org.springframework.util.unit.DataSize) : void"
    instructionFingerprint: "5A6EA0B42288F59D2EF1CD3942F8CBA6"
    parametersTypes:
    - "org.springframework.util.unit.DataSize"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "setMaxFileSizeTest"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "880EF806C213AC500272BB1EBE9F060D"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "666c9b51-a0ec-3625-bba6-be12b31faa3f"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "setMaxRequestSize"
    returnType: "void"
    signature: "setMaxRequestSize(org.springframework.util.unit.DataSize) : void"
    instructionFingerprint: "6FB4E6DC946654BF98B86322AB6C908D"
    parametersTypes:
    - "org.springframework.util.unit.DataSize"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "setMaxRequestSizeTest"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "987EF1C24DF058CBD8D08EFBA188AB39"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "deb3a9fa-419d-3ffe-b39a-32c02a069dfa"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "setFileSizeThreshold"
    returnType: "void"
    signature: "setFileSizeThreshold(org.springframework.util.unit.DataSize) : void"
    instructionFingerprint: "574857945193B6B0085EE0E2B6934A67"
    parametersTypes:
    - "org.springframework.util.unit.DataSize"
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "setFileSizeThresholdTest"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "6DFA66E8F6D061F14B232916E4700E69"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "3c58e727-9ada-3102-b58a-d19ad3085883"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
- method:
    name: "createMultipartConfig"
    returnType: "jakarta.servlet.MultipartConfigElement"
    signature: "createMultipartConfig() : jakarta.servlet.MultipartConfigElement"
    instructionFingerprint: "590798701BC34A90E51DCD3BFFDB4BA8"
    parametersTypes: []
  paths:
  - pathId: "path1"
    pathIdForUser: "path1"
    testPathName: "createMultipartConfigWhenSizeIsNull"
    nameDefinedByUser: false
    constructorSignature: "<init>() : void"
    priorityDefinedByUser: false
    filledByUser: false
    priority: "LOW"
    modelFingerprint: "CD2F9782FBD6A17DAE5B12D628C76715"
    problemWasSolvedByProver: false
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "org.springframework.boot.web.servlet.MultipartConfigFactory"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
          propertiesMap:
            location:
              sapientType: "BASIC"
              content: !<regular>
                value: "location1"
              valueType: "java.lang.String"
              uuid: "string1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
        suggestedContent: !<new>
          target: "org.springframework.boot.web.servlet.MultipartConfigFactory"
          parameters: []
          privateConstructor: false
          createdByTargetCode: false
          propertiesMap:
            location:
              sapientType: "BASIC"
              valueType: "java.lang.String"
              uuid: "string1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
        valueType: "org.springframework.boot.web.servlet.MultipartConfigFactory"
        uuid: "target"
        fixed: false
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "DFC6F09FD4DDDA943BAA22AB59294C85"
      index: 2
      ignored: false
      nestedInLoop: false
      nestedInRecursion: false
      value:
        sapientType: "OBJECT"
        content: !<new>
          target: "jakarta.servlet.MultipartConfigElement"
          parameters:
          - name: "location"
            value:
              sapientType: "BASIC"
              content: !<regular>
                value: "location1"
              valueType: "java.lang.String"
              uuid: "string1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          - name: "maxFileSize"
            value:
              sapientType: "BASIC"
              content: !<regular>
                value: -1
              valueType: "long"
              originalValueType: "int"
              uuid: "createMultipartConfig_long1"
              fixed: true
              equalsMethodPresent: false
              explicitCastNeeded: false
          - name: "arg2"
            value:
              sapientType: "BASIC"
              content: !<regular>
                value: -1
              valueType: "long"
              originalValueType: "int"
              uuid: "createMultipartConfig_long2"
              fixed: true
              equalsMethodPresent: false
              explicitCastNeeded: false
          - name: "maxRequestSize"
            value:
              sapientType: "BASIC"
              content: !<regular>
                value: 0
              valueType: "int"
              originalValueType: "long"
              fixed: true
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: true
        suggestedContent: !<new>
          target: "jakarta.servlet.MultipartConfigElement"
          parameters:
          - name: "location"
            value:
              sapientType: "BASIC"
              valueType: "java.lang.String"
              uuid: "string1"
              fixed: false
              equalsMethodPresent: false
              explicitCastNeeded: false
          - name: "maxFileSize"
            value:
              sapientType: "BASIC"
              content: !<regular>
                value: -1
              valueType: "long"
              originalValueType: "int"
              uuid: "createMultipartConfig_long1"
              fixed: true
              equalsMethodPresent: false
              explicitCastNeeded: false
          - name: "arg2"
            value:
              sapientType: "BASIC"
              content: !<regular>
                value: -1
              valueType: "long"
              originalValueType: "int"
              uuid: "createMultipartConfig_long2"
              fixed: true
              equalsMethodPresent: false
              explicitCastNeeded: false
          - name: "maxRequestSize"
            value:
              sapientType: "BASIC"
              content: !<regular>
                value: 0
              valueType: "int"
              originalValueType: "long"
              fixed: true
              equalsMethodPresent: false
              explicitCastNeeded: false
          privateConstructor: false
          createdByTargetCode: true
        valueType: "jakarta.servlet.MultipartConfigElement"
        uuid: "createMultipartConfig_multipartConfigElement1"
        fixed: true
        equalsMethodPresent: false
        explicitCastNeeded: false
      staticReadMethodForField: false
      filledByUser: false
    uuid: "0cb85a2a-a8bc-3dfb-b101-36cdfdc10d22"
    deleted: false
    disabled: true
    ignoredBySystem: false
    failureReason:
      reason: "EQUALS_METHOD_TODO_COMMENT"
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: true
