---
modelFingerprint: "5F2BBF745FF63328F2432A7F168D5F9D"
methods:
- method:
    name: "setLocation"
    signature: "setLocation(java.lang.String) : void"
    instructionFingerprint: "58D74E026D819E27A9780739FD19BD32"
  paths:
  - pathId: "path1"
    testPathName: "setLocationTest"
    constructorSignature: "<init>() : void"
    filledByUser: false
    modelFingerprint: "9BAB731A43D9BA020CB7099281064314"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "10429219-944a-3b02-9737-f50a88747ae7"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "setMaxFileSize"
    signature: "setMaxFileSize(org.springframework.util.unit.DataSize) : void"
    instructionFingerprint: "5A6EA0B42288F59D2EF1CD3942F8CBA6"
  paths:
  - pathId: "path1"
    testPathName: "setMaxFileSizeTest"
    constructorSignature: "<init>() : void"
    filledByUser: false
    modelFingerprint: "880EF806C213AC500272BB1EBE9F060D"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "666c9b51-a0ec-3625-bba6-be12b31faa3f"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "setMaxRequestSize"
    signature: "setMaxRequestSize(org.springframework.util.unit.DataSize) : void"
    instructionFingerprint: "6FB4E6DC946654BF98B86322AB6C908D"
  paths:
  - pathId: "path1"
    testPathName: "setMaxRequestSizeTest"
    constructorSignature: "<init>() : void"
    filledByUser: false
    modelFingerprint: "987EF1C24DF058CBD8D08EFBA188AB39"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "deb3a9fa-419d-3ffe-b39a-32c02a069dfa"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "setFileSizeThreshold"
    signature: "setFileSizeThreshold(org.springframework.util.unit.DataSize) : void"
    instructionFingerprint: "574857945193B6B0085EE0E2B6934A67"
  paths:
  - pathId: "path1"
    testPathName: "setFileSizeThresholdTest"
    constructorSignature: "<init>() : void"
    filledByUser: false
    modelFingerprint: "6DFA66E8F6D061F14B232916E4700E69"
    problemWasSolvedByProver: true
    truncated: true
    inputParameters: []
    uuid: "3c58e727-9ada-3102-b58a-d19ad3085883"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues: []
- method:
    name: "createMultipartConfig"
    signature: "createMultipartConfig() : jakarta.servlet.MultipartConfigElement"
    instructionFingerprint: "E09BF42EDC80D4B414C393A8C3943FB9"
  paths:
  - pathId: "path1"
    testPathName: "createMultipartConfigWhenSizeIsNull"
    constructorSignature: "<init>() : void"
    filledByUser: false
    modelFingerprint: "00A89769B0830342B73DBD564DBEBD77"
    problemWasSolvedByProver: true
    truncated: false
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      index: 1
      ignored: false
      valueUuid: "target"
      staticReadMethodForField: false
      filledByUser: false
    - type: "RESULT"
      name: "result"
      modelFingerprint: "38F76D0A574D643F592E49D47B184538"
      index: 2
      ignored: false
      valueUuid: "createMultipartConfig_multipartConfigElement1"
      staticReadMethodForField: false
      filledByUser: false
    uuid: "0cb85a2a-a8bc-3dfb-b101-36cdfdc10d22"
    deleted: false
    disabled: false
    ignoredBySystem: false
    prover: "DEFAULT"
    disabledStatusUpdatedByUser: false
    disabledStatusUpdatedBySystem: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.MultipartConfigFactory"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
        propertiesMap:
          location:
            sapientType: "BASIC"
            content: !<regular>
              value: "location1"
            valueType: "java.lang.String"
            uuid: "string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
      suggestedContent: !<new>
        target: "org.springframework.boot.web.servlet.MultipartConfigFactory"
        parameters: []
        privateConstructor: false
        createdByTargetCode: false
        propertiesMap:
          location:
            sapientType: "BASIC"
            valueType: "java.lang.String"
            uuid: "string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
      valueType: "org.springframework.boot.web.servlet.MultipartConfigFactory"
      uuid: "target"
      fixed: false
      equalsMethodPresent: false
      explicitCastNeeded: false
    - sapientType: "OBJECT"
      content: !<new>
        target: "jakarta.servlet.MultipartConfigElement"
        parameters:
        - name: "location"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "location1"
            valueType: "java.lang.String"
            uuid: "string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "maxFileSize"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: -1
            valueType: "long"
            originalValueType: "int"
            uuid: "createMultipartConfig_long1"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "maxRequestSize"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: -1
            valueType: "long"
            originalValueType: "int"
            uuid: "createMultipartConfig_long2"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "fileSizeThreshold"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: 0
            valueType: "int"
            originalValueType: "long"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: true
      suggestedContent: !<new>
        target: "jakarta.servlet.MultipartConfigElement"
        parameters:
        - name: "location"
          value:
            sapientType: "BASIC"
            valueType: "java.lang.String"
            uuid: "string1"
            fixed: false
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "maxFileSize"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: -1
            valueType: "long"
            originalValueType: "int"
            uuid: "createMultipartConfig_long1"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "maxRequestSize"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: -1
            valueType: "long"
            originalValueType: "int"
            uuid: "createMultipartConfig_long2"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        - name: "fileSizeThreshold"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: 0
            valueType: "int"
            originalValueType: "long"
            fixed: true
            equalsMethodPresent: false
            explicitCastNeeded: false
        privateConstructor: false
        createdByTargetCode: true
      valueType: "jakarta.servlet.MultipartConfigElement"
      uuid: "createMultipartConfig_multipartConfigElement1"
      fixed: true
      equalsMethodPresent: false
      explicitCastNeeded: false
