---
modelFingerprint: "B96B3CCE6AF790623817812033068F70"
targetClass:
  fullClassName: "org.springframework.boot.web.servlet.MultipartConfigFactory"
methods:
- method:
    name: "setLocation"
    sourceCodeSignature: "void setLocation(String location)"
    returnType: "void"
    parameters:
    - name: "location"
      type: "java.lang.String"
    instructionFingerprint: "58D74E026D819E27A9780739FD19BD32"
  paths:
  - pathId: "path1"
    testPathName: "setLocationTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "7EE818D932C913176BB417E1BC8FC638"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
- method:
    name: "setMaxFileSize"
    sourceCodeSignature: "void setMaxFileSize(DataSize maxFileSize)"
    returnType: "void"
    parameters:
    - name: "maxFileSize"
      type: "org.springframework.util.unit.DataSize"
    instructionFingerprint: "5A6EA0B42288F59D2EF1CD3942F8CBA6"
  paths:
  - pathId: "path1"
    testPathName: "setMaxFileSizeTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "CDDB09BA9A9C92A79A142AE9AAF81E83"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
- method:
    name: "setMaxRequestSize"
    sourceCodeSignature: "void setMaxRequestSize(DataSize maxRequestSize)"
    returnType: "void"
    parameters:
    - name: "maxRequestSize"
      type: "org.springframework.util.unit.DataSize"
    instructionFingerprint: "6FB4E6DC946654BF98B86322AB6C908D"
  paths:
  - pathId: "path1"
    testPathName: "setMaxRequestSizeTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "025AAC738C11B220358CB2C2B76AD776"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
- method:
    name: "setFileSizeThreshold"
    sourceCodeSignature: "void setFileSizeThreshold(DataSize fileSizeThreshold)"
    returnType: "void"
    parameters:
    - name: "fileSizeThreshold"
      type: "org.springframework.util.unit.DataSize"
    instructionFingerprint: "574857945193B6B0085EE0E2B6934A67"
  paths:
  - pathId: "path1"
    testPathName: "setFileSizeThresholdTest"
    constructorSignature: "<init>() : void"
    modelFingerprint: "FDD371AB337DA64DE95CEBA84D6A9C77"
    problemWasSolvedByProver: true
    inputParameters: []
    disabled: false
    allValues: []
- method:
    name: "createMultipartConfig"
    sourceCodeSignature: "MultipartConfigElement createMultipartConfig()"
    returnType: "jakarta.servlet.MultipartConfigElement"
    instructionFingerprint: "E09BF42EDC80D4B414C393A8C3943FB9"
  paths:
  - pathId: "path1"
    testPathName: "createMultipartConfigWhenSizeIsNull"
    constructorSignature: "<init>() : void"
    modelFingerprint: "63903F2A1761AB4829961B27C79A3E9C"
    problemWasSolvedByProver: true
    inputParameters:
    - type: "CONSTRUCTOR"
      modelFingerprint: "4DB0F57EEFC6BBF1691C61D6F11B96D4"
      valueUuid: "target"
    - type: "RESULT"
      name: "result"
      modelFingerprint: "98B94E0044AC6FEA592771BF2FC7F976"
      valueUuid: "multipartConfigElement"
    disabled: false
    allValues:
    - sapientType: "OBJECT"
      content: !<new>
        target: "org.springframework.boot.web.servlet.MultipartConfigFactory"
        parameters: []
        propertiesMap:
          location:
            sapientType: "BASIC"
            content: !<regular>
              value: "location1"
            valueType: "java.lang.String"
            uuid: "fieldString"
      valueType: "org.springframework.boot.web.servlet.MultipartConfigFactory"
      uuid: "target"
    - sapientType: "OBJECT"
      content: !<new>
        target: "jakarta.servlet.MultipartConfigElement"
        parameters:
        - name: "location"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: "location1"
            valueType: "java.lang.String"
            uuid: "fieldString"
        - name: "maxFileSize"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: -1
            valueType: "long"
            originalValueType: "int"
            uuid: "long2"
            fixed: true
        - name: "maxRequestSize"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: -1
            valueType: "long"
            originalValueType: "int"
            uuid: "long4"
            fixed: true
        - name: "fileSizeThreshold"
          value:
            sapientType: "BASIC"
            content: !<regular>
              value: 0
            valueType: "int"
            originalValueType: "long"
            uuid: "uniqueUuid1"
            fixed: true
      valueType: "jakarta.servlet.MultipartConfigElement"
      uuid: "multipartConfigElement"
      fixed: true
    branches:
    - lineNumber: 91
      expression: "size != null"
      range: "(91,7)-(91,18)"
      evaluatedAs: false
      internalMethodName: "convertToBytes"
